import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> dapaRawData = [
  ExcelRowData(
    permitDate: "2006.03.15.",
    name: "한국방위산업진흥회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2009.11.03.",
    name: "한국국방획득혁신학회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2009.12.07.",
    name: "한국화생방방어학회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2009.12.30.",
    name: "국방창업기술진흥원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2011.03.14.",
    name: "한국시스템엔지니어링협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2011.03.14.",
    name: "한국모의훈련체계협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2011.12.29.",
    name: "PMI 한국챕터",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2013.03.05.",
    name: "한국방위사업연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2013.06.03.",
    name: "방위산업전략포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2015.04.28.",
    name: "방우회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2017.01.18.",
    name: "국방과학연구소연우회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2018.01.29.",
    name: "평화전략연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2018.06.01.",
    name: "한국무기체계안전협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2020.04.09.",
    name: "국방무기체계분석연구소",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2020.06.02.",
    name: "한국방위사업정보원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2020.06.08.",
    name: "방산중소벤처기업협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2021.06.11.",
    name: "방위산업공제조합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2023.08.11.",
    name: "한국방위산업협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
  ExcelRowData(
    permitDate: "2023.09.22.",
    name: "한국비행시험협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "방위사업청",
  ),
];
