import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> kfsawData = [
  ExcelRowData(
    permitDate: "-",
    name: "한국양묘협회",
    purpose: "회원의 협동적 자치정신을 구현하여 국가 치산정책에 호응 협조하고 양묘사업의 건전한 발전을 기함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국합판보드협회",
    purpose: "합판, 목재가공업 및 해외조림의 건전한 육성발전",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국조경수협회",
    purpose: "조경식물생산 및 조경건설업의 발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국포플러·속성수위원회",
    purpose: "FAO 국제포플러 위원회에 우리나라 대표로 가입하여 그 연락업무를 하는 동시에 국내의 개량포플러 증식과 활용 등에 관한 기본적 문제를 연구․검토하여 개량포플러 증식재배 관리 및 기술 훈련",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림정책연구회",
    purpose: "임업연구와 합리적인 산림정책방안 추구 및 회원화합",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림경영인협회",
    purpose: "임업에 관한 새로운 정보 기술보급, 효율적인 산림경영을 도모하고 회원 권익보호에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국임산물연료협회",
    purpose: "목탄생산 및 이를 판매하는 자의 협동단결과 기술제휴, 공동이익을 도모",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국목재칩연합회",
    purpose: "목재칩의 효율적 이용관리",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대한민국자생란협회",
    purpose: "자생란의 우수성 홍보 및 자연애호사상 고취, 자생종자 보호 육성",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국숲사랑청소년단",
    purpose: "숲사랑소년단 등을 선발 육성하여 산림에 대한 올바른 이해와 산림사랑 정신을 함양",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국분재조합",
    purpose: "분재산업의 진흥과 조합원의 경제적 , 사회적 지위 향상",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국수목보호협회",
    purpose: "수목의 생리적, 생물적, 인위적, 기상적 재해 및 기타 피해에 대한 원인 조사 연구로 건강한 산림유지에 기여함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국자생식물협회",
    purpose: "자생식물의 연구개발과 보급 및 자연환경보호, 자생식물의 자원화로 농가 소득 작목 개발로 국가경제 발전에 기여, 우리꽃 사랑에 대한 의식향상에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림보호원",
    purpose: "자연이 물려준 우리의 산림을 푸르게 가꾸고 맑고 푸른 산수를 잘 보전하여 후손에게 물려주며, 산림을 보호.발전하는데 있음",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국임산버섯생산자단체연합회",
    purpose: "임산버섯 산업의 건전한 발전도모",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산지환경연구회",
    purpose: "산림환경보전과 과학적인 산림자원관리에 필요한 객관적 정보를 제공·임업발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국임업후계자협회",
    purpose: "임업발전을 위하여 산림경영 기술보급과 회원 상호간 정보교환, 친목도모, 권익보호에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국목조건축협회",
    purpose: "목조건축의 활성화를 위한 기술의 연구개발과 목조건축업의 건전한 발전을 도모",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림보호협회",
    purpose: "산림의 보호.육성, 산림자원증식, 공익기능증진을 도모하고 국토보전 등을 위한 산림보호 운동을 전개",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "자생식물단체연합회",
    purpose: "식물자원의 보존, 증식, 이용에 관한 사업을 수행하고 국제 관련기구와의 정보교류와 협력을 통하여 자연환경 보존 및 보호에 적극 기여하며 이를 새로운 농림업인의 소득원 및 수출 자원으로 개발하여 국가경제발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국임업기계화협회",
    purpose: "우리나라 지역 설정에 맞는 임업기계 장비 및 작업시스템 개발",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림자원육성운동협회",
    purpose: "산림자원의 증식․보호․육성, 임업생산업의 향상, 산림의 공익기능 증진은 물론 적극적 육림사업으로 산림사랑 운동을 전개하고 산림자원의 묘목을 보급․지도․홍보하는데 기여함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "생명의숲",
    purpose: "숲을 가꿈으로써 국토보전 및 산림자원조성에 기여하고, 산림을 사랑하는 국민정신을 함양하여 국가발전을 위한 국민적 역량을 결집",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국자생식물보존회",
    purpose: "자생식물의 생태와 현황을 탐사 및 식물자원의 중요성을 홍보, 연구기관 및 관련기관에 자연환경보전을 위한 기초자료로 제공하여 국민의 쾌적한 삶을 누리는데 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국임산탄화물협회",
    purpose: "임산탄화물의 품질향상과 유통체계를 개선",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림유기자원협회",
    purpose: "산림작업에서 생산되는 부산물을 수집․활용하여 산주의 소득증대 및 임업과 환경농업, 환경축산과 상호 연계하여 산림의 공익적 기능을 극대화하고 국민보건과 환경보전에 기여함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "산지약용식물협회",
    purpose: "한국고유의 산지식물 자원의 보호 및 유통활성화를 도모",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화의숲",
    purpose: "국제협력과 국내외 시민의 참여를 통해 북한 등 동북아지역의 훼손된 산림을 복구함으로써, 농업생산력 회복과 환경보존에 기여하고 식량․식수․에너지 극복을 도모함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "나라꽃무궁화운동중앙회",
    purpose: "한민족 정신적 상징으로 삼아온 무궁화를 보급․보존․선양함을 기본으로 하고, 무궁화의 5대 정신을 바탕으로 하여 한민족 전통문화 계승발전에 새로운 가치관 정립과 정신질서를 통한 애국심을 길러 국가발전에 기여함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국숲해설가협회",
    purpose: "국민들에게 숲의 가치와 중요성을 알리고, 숲과 자연생태에 관한 소양과 지식 제공",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "동북아산림포럼",
    purpose: "동북아 국가의 산림을 환경적으로 건전하고 지속가능하게 보전하기 위해 국제공조 및 민간주도의 국제협력사업 도모",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국목구조기술인협회",
    purpose: "목구조기술자의 권익을 보호하며 목구조 건축 발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "생태산촌",
    purpose: "- 자연과 조화되고 지속가능한 생산기반을 갖춘 생태적인 산촌조성 - 국토의 균형적인 발전을 통한 생태마을의 육성과 산촌활성화에 기여 - 공동체적 가치관 회복과 생태적 문화의 창출",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "광릉숲보존협회",
    purpose: "광릉숲의 다양한 생물종의 보전과 복원을 위해 연구·조사·교육·홍보, 보전·감시, 협력 등의 활동을 통해 광릉숲을 지켜나가고 나아가 우리 나라의 생태계를 보전",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국식물원수목원협회",
    purpose: "관련 국제 기구와의 정보교류와 협력을 통하여 식물원, 수목원의 발전을 도모하고 건전한 식물원, 수목원 문화 창달로 국민복지향상과 공익에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "새천년생명운동",
    purpose: "남북, 해외 동포를 결집하여 북한의 산림복구와 식량난 해결을 위한 농업 및 산림협력",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국꽃누르미협회",
    purpose: "꽃과 식물을 누르미라는 특수기술을 통해 꽃예술문화 사업으로 육성",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국아트플라워협회",
    purpose: "아트플라워라는 방법으로 우리나라의 자생식물을 꽃으로 재현 및 상품화함 경쟁력 있는 꽃 예술문화사업으로 육성",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국닥나무협회",
    purpose: "닥나무의 재배기술 개발 보급과 생산품의 가공판매 촉진으로 닥나무 관련 사업 발전에 기여함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국밤재배자협회",
    purpose: "밤나무 재배환경 조사 연구 등 밤산업활성화 도모",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국수액협회",
    purpose: "무분별한 수액채취로 인한 수목 및 환경피해 방지 및 수액의 위생적인 유통체계 확립",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국보호수보존연구회",
    purpose: "보호수에 대한 보존사업과 이를 위한 각종 연구사어을 실시하여 우리 나라의 산림문화자원 및 우량 산림자원의 보존",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대한산악스키협회",
    purpose: "산악스키와 관련된 조사 연구, 교육, 홍보 및 산림환경의 보전, 청소년 선도사업 등의 장려",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국목재보존협회",
    purpose: "회원상호간의 정보교류와 협력을 통하여 목재 보존산업의 건전한 육성발전",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국옻나무협회",
    purpose: "옻나무를 보존 개발하여 한국의 전통 옻칠공예 산업을 개발 육성하고 옻나무 재배단지를 육성하여 옻나무관련 산업발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림과학기술단체연합회",
    purpose: "산림관련 학술 및 산업의 정보수집과 조사연구 수행, 기술지도 및 보급 등 산림과학기술 발전 도모",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국표고생산·유통협회",
    purpose: "표고버섯의 생산, 유통, 가공, 기술개발 및 정보교류 등",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림공학회",
    purpose: "사방,임도,산림훼손지 복원 등에 관한 연구 및 기술개발",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국사유림발전연구회",
    purpose: "사유림발전에 관한 연구 및 회원상호간의 유기적인 침목도모하여 사유린경영발전 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림휴양복지학회",
    purpose: "산림환경을 보존 보호하여 산림의 휴양적 가치 및 산림치유가치를 제고시키고, 국민의 산림휴양 및 산림치유 요구에 부응함과 동시에 산지 산촌 지역의 활성화를 위하여 학제간의 연구 유대를 강화함으로써 산림휴양, 산림치유, 산림교육(유아숲체험), 숲해설, 숲길, 산촌, 숲, 자연공원, 도시숲, 생태숲, 그린 투어리즘 및 환경 경관 계획 분야 등의 연구 및 기술 향상에 기여함을 목적으로 함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림복합경영인협회",
    purpose: "생산기술개발을 통한 경영합리회 및 효율적인 유통체계 확립",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산악문화협회",
    purpose: "산악문화의 건전한 육성과 환경친화적이고 지속적인 발전추구로 국가사회의 발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림과학회(구 한국임학회)",
    purpose: "임학전반에 관한 연구와 회원 상호간의 유기적인 화합을 도모하여 임학 및 임업발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국나무병원협회",
    purpose: "수목보호진단, 치료에 관한 기술정보 교환 및 수목치료 신기술의 개발보급으로 수목치료 기술발전에 기여함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국새우란협회",
    purpose: "우수품종 개발 번식 새우란 자생지 복원",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국식물세밀화협회",
    purpose: "식물세밀화의 필요성과 중요성을 알리고, 사라져가는 식물뿐아니라 우리나라 식물들의 학술적, 예술적 가치를 지니는 그림으로 기록, 보전하고 알리는 것을 도모",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "숲생태지도자협회",
    purpose: "청소년들에게 숲생태․체험환경교육을 통하여 산림문화에 대한 이해와 자연환경보호의식을 고취",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "숲과문화연구회",
    purpose: "나무와 숲, 인간의 상호관계를 문화적․생태적 시각에서 그 가치와 중요성을 규명하여 임업과 임학을 발전",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산악승마협회",
    purpose: "산악승마인들의 친목도모 및 산악승마와 관련된 조사, 연구, 교육 등 산림문화 진흥 목적",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산삼학회",
    purpose: "국내자생 산삼원종의 보존증식 및 자생지 복원, 산양삼 품질향상을 위한 연구활동으로 산업육성에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국등산연합회",
    purpose: "산악단체(산악회)에 등산활동을 효율적으로 지도·지원하여 선진등산문화를 보급·정착",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국표고버섯생산자협회",
    purpose: "표고버섯 생산기술개발, 경영합리화 및 효율적인 유통체계확립, 회원상호간 정보교류로 표고산업육성",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림경제학회",
    purpose: "산림자원의 이용과 보전에 관한 연구 및 회원화합",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "산림문화콘텐츠연구소",
    purpose: "전통속에 빛나는 산림문화의 지식정보와 문화콘텐츠들을 연구․보존․개발하여 21세기 새로운 숲 문명의 창달에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림사업법인협회",
    purpose: "회원의 품위유지와 상호협격강화, 권익증진,산림사업법인 제도개선 및 산림사업기술향상으로 건전한 산림사업법인 육성",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "유명산숲학교",
    purpose: "산림을 활용하여 인간생활의 윤택화 방안을 연구․교육하여 산림사랑과 산림문화 고양에 이르도록 하는 「산림문화운동」을 전개",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "자연휴양림협회",
    purpose: "산림휴양자원의 보전과 효율적인 자연휴양림 경영을 통한 산림의 공익적 기능 증진을 도모하고 회원의 권익보호에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국해안림연구회",
    purpose: "해풍의 영향 범위에 있는 자연의 안정, 조화와 지속을 도모하고자 해안림의 조성,육성,관리,보전 등의 기술 발전을 위한 연구,개발 등",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "노거수회",
    purpose: "산림환경전반에 관한 조사.연구와 향토순례를 통하여 노거수, 희귀수목의 보호 및 보전가치가 높은 숲에 대한 보호운동을 전개하고 출판 및 홍보를 함으로써 산림환경보전과 향토사랑의 실천운동을 국민속에 뿌리내리게 함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "백두대간연구소",
    purpose: "백두대간의 체계와 이에 수반하는 인문과학, 자연과학 등의 분야에 대한 연구 및 활동",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "백두대간진흥회",
    purpose: "백두대간 보호와 관련된 사업, 남북 및 국제교류협력, 대국민 교육,홍보 등을 통한 백두대간 보호 및 학술문화 발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림치유포럼",
    purpose: "산림이 지닌 보건 의학적 치유기능을 통한 국민의 건강유지와 질병예방을 도모하고 관련산림자원의 육성",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "숲길",
    purpose: "새로운 산림자원의 가치를 지속적으로 보전·활용하기 위하여 산촌마을을 포함해 숲과 숲길을 연구·조사하고 조성",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "전국산림기능인협회",
    purpose: "전국의 산림기능인들의  친목을 도모하고, 상호간에 정보교류를 통하여 그 능력과 자질을 높임으로서 전국의 산림을 푸르고 울창하게 가꾸는데 기여함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "숲사랑",
    purpose: "숲과 자연을 사랑하고 보전 육성하는 운동을 범국민적 생명평화운동으로 개선발전",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "전국호두생산자협회",
    purpose: "생산성향샹을 위한 공동노력, 회원 소득증대 및 호두산업활성화 를 도모 경쟁력 있는 산업으로 육성",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국DIY가구공방협회",
    purpose: "DIY문화의 건전한 보급을 통한 국민의 삶의 질을 높이고, DIY산업의 종합적인 발전도모에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "수목장실천회",
    purpose: "수목장에 대한 대국민홍보와 연구·개발, 건전한 장묘문화 정챡·발전",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국시설양묘연구회",
    purpose: "시설양묘 연구 및 발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산악회",
    purpose: "산악에 관한 조사연구와 교육훈련을 통하여 건전한 산악운동을 보급·장려하고 자연보호정신을 함양하여 국가와 사회발전에 이바지",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "미래숲",
    purpose: "사막화․황사방지 및 북한 산림녹화 지원사업 추진",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국잔디협회",
    purpose: "잔디품종 생산기술 개발, 유통체계 개선 및 수요확대를 위한 체계적 개선으로 잔디문화 창달과 산업발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "숲연구소",
    purpose: "지구생태계의 근간이 되는 숲을 중심으로 생태를 체계적으로 연구하여 보전방법을 수립하고 그 내용을 각계각층의 시민들에게 널리 교육하고 홍보",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대한목재협회",
    purpose: "목재산업의 발전과 유통질서의 확립 그리고 목제품 품질 향상을 도모함으로서 국민경제 발전에 공헌하고 회원사들의 권익보호를 도모",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국목재공학회",
    purpose: "임산물 관련 학계, 산업계, 연구기관 및 정부간의 상호협력을 통한 학문연구 및 기술발전 도모",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "무궁화문화포럼",
    purpose: "무궁화와 우리 것을 국내외에 널리 알리고 선양하는 문화운동 협의체로서 국가브랜드를 높이고 민족화합과 민족번영에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림문학회",
    purpose: "회원 상호간의 친목을 도모하고 산림문학의 향상 발전과 산림문화 창달",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국밀원수조림육성협회",
    purpose: "밀원수 조림,육성,개발과 양봉산물에 관한 생산가공, 유통산업의 정보수집과 조사연구 등",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림기술사협회",
    purpose: "신 산림기술개발 보급으로 지속가능한 산림경영과 저탄소녹색성장의 기반 조성에 선도적 역활, 산림을 경제, 환경, 사회적으로 가치 있는 중요한 자원으로 육성 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국수목보호기술자협회",
    purpose: "회원의 상호협력을 통하여 수목치료 기술 향상 및 수목치료를 통하여 건강한 수목보호에 기여함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "산림바이오매스에너지협회",
    purpose: "목재펠릿 관련기술의 연구개발과 보급 및 펠릿연료 관련 제도개선을 통한 통한 펠릿산업의 건전한 육성과 발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "태극무궁화협회",
    purpose: "부안군을 국화인 무궁화를 심어 주민의 애국정신을 고취",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산양삼협회",
    purpose: "산양삼재배기술, 품질기술 및 공동유통망을 구축하여 회원 상호간의 권익보호와 산양삼 수출증대 등 산양삼 세계화에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국목공교육협회",
    purpose: "목공교육 프로그램을 개발․보급하고 어린이와 청소년들에게 목공교육 기회를 제공",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대한산악구조협회",
    purpose: "산악사고시 지상 구조활동 및 산림항공구조대와의 연계활동 전개, 일반 등산인을 위한 산악 안전교육 실시",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국대학산악연맹",
    purpose: "각 대학 산악회를 통한 건전한 산악운동과 등산문화 보급",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "곤충다양성연구회",
    purpose: "한반도 및 인접 국가들에 대한 산림곤충의 분류, 생태 및 자원화에 관련된 학술적 연구와 학문적 교류를 활성화시켜 관련 곤충학문 및 정책발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산악마라톤연맹",
    purpose: "산악마라톤을 통한 국민건강 증진 이바지",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "백두대간보전회",
    purpose: "백두대간보호, 생태체험·교육,생태계 증식 및 보전 등에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국숲유치원협회",
    purpose: "숲유치원 프로그램 등을 통해 유아의 건강증진 및 산림교육 강화",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국임우회",
    purpose: "회원 상호간의 친목을 도모하고 상부상조하여 회원의 복리증진 및 산림시책에 관한 홍보·자문 등을 통하여 임업발전에 이바지",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국잔디학회",
    purpose: "잔디류 및 지피식물 전반에 관한 학술연구와 기술개발 및 정보를 상호교환하고, 그 지식을 널리 보급하며 나아가 우리나라 국토개발 및 녹화에 따른 사업의 발전에 기여함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림유전·생리학회",
    purpose: "산림유전·수목생리와 관련된 연구 및 지원사업",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "무궁화사랑",
    purpose: "우리나라 국화인 무궁화의 중요성을 새로이 일깨우고 무궁화 우수 품종 증식과 보급 및 재배를 적극 추진함과 동시에 나라사랑과 애국정신을 함양하는데 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "백두대간 숲연구소",
    purpose: "백두대간 정맥 보호 및 산림생태계 보전·이용 복원에 대한 연구 등에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "목재산업단체총연합회",
    purpose: "목재산업 발전 및 목재문화 진흥을 위하여 공동으로 노력하고 저탄소 녹색성장을 위한 기반 구축에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국목재합판유통협회",
    purpose: "제재목, 보드류 기타 가공 목제품을 수·출입하는 유통업체간의 공동발전과 유통질서의 확립을 도모함으로써 국가경제 발전에 공헌하고 회원사들의 권익보호",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국트레킹연맹",
    purpose: "트레킹 활동을 통해 심신과 건강을 유지하고 트레킹 문화 개발과 보급.보전, 트레킹 환경 정비 및 조성으로 자연과의 지속가능한 공생 모색",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "야생자원식물 소재연구회",
    purpose: "연구기관 및 행정당국에 유용한 야생자원식물의 소재 및 정보를 제공함으로써 식물주권확보 및 자원화를 통해 국익에 이바지하며, 나아가 국가 생물종다양성 확보",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "숲과 아이들",
    purpose: "숲교육 확산을 위한 부모교육 및 홍보 등",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "산림경영정보학회(기존-한국산림자원측정학회)",
    purpose: "산림경영 및 정보를 위한 산·학·연·관의 협력체계구축",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국고열처리협회",
    purpose: "고열처리목재 생산 및 유통업체의 공동발전과 유통질서 확립을 통하여 목재산업 발전 및 회원사 권익 보호",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국숲길등산지도사협회",
    purpose: "산을 찾는 사람들에게 숲의 가치와 중요성을 알리고, 숲길과 자연생태에 관한 지식을 제공하여 자연 친화적인 숲길 체험 문화를 정립 하며 숲의 지속 가능한 이용과 보전에 바른 숲길운동을 통해 국민생활의 질적 향상을 도모하고, 숲길체험지도사 교육을 실시하여 그 능력과 자질을 높이며, 숲길체험지도사 상호간의 정보 교류와 친교",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국무늬목협회",
    purpose: "무늬목 생산관리 체계 개선·발전 및 유통질서 확립을 통하여 목재이용 증진을 도모함으로써 목재산업 발전에 기여 및 회원사 권익신장",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "나무심는 사람들",
    purpose: "나무심기와 숲 조성사업으로 지속 가능한 사회발전 선도",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국원목생산업협회",
    purpose: "원목생산업에 관한 경영합리화와 원목의 유통질서 확립을 도모함으로써 국가 경제발전에 공헌하고 회윈권익 보호",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국종자은행자원보전협회",
    purpose: "한국 내 종자은행 및 관련기관, 단체를 대표하는 협의체로서 상호 협력증진을 통해 식물종자 보전과 자생지를 복원함으로서 지구 생태계 안정에 기여함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국무궁화연구회",
    purpose: "나라꽃 무궁화의 연구와 선양운동을 수행함으로써 나라와 겨레 사랑의 마음을 함양하고 국토미화에 이바지",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국마루협회",
    purpose: "국내 마루판 생산 기술 선진화 및 연구개발을 통하여 업체의 공동발전과 유통질서 확립을 도모하고 목재산업 발전 및 회원사 권익보호",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "생태창의성 연구소 푸른상상",
    purpose: "숲,생명, 창의성 등을 원칙으로 산림교육 연구를 수행하고 유아, 어린이, 청소년에게 실천적 숲체험교육 실시",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국목공인협희",
    purpose: "국산목재를 소재로 한 공예제품의 디자인 및 가공기술을 개발하고 목재공예 제품의 품질향상과 유통체계를 확립함으로써 목재이용 활성화 도모",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림습원보호협회",
    purpose: "우리나라 산림습원 보호 및 관련 기관의 상호 협력 증진을 통해 산림습원식물 및 습원환경 보호와 지속 가능한 산림습원생태계 안정에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "푸르네정원문화센터",
    purpose: "정원문화 관련 다양한 사업을 통해 새로운 정원문화의 확산과 정원 관련 새로운 일자리 창출에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "팔공산문화포럼",
    purpose: "산림의 자연과 문화를 보전하고, 산림과 문화자원에 관한연구 및 개발에 관한 활동을 하며, 산을 사랑하는 사람들의 친목과 교양과 봉사의 증진으로 밝은 선진사회건설에 이바지함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국식물분류학회",
    purpose: "우리나라 식물분류학의 학술적 발전 및 그 지식의 보급과, 생물다양성 유지·증진에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국사찰림연구소",
    purpose: "우리나라 사찰림의 지속가능한 보존, 육성, 복원과 효율적인 활용기반 확립에 기여하고 불교 이념을 구현",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국대나무발전협회",
    purpose: "대나무에 관심있는 학자, 생산자, 재배자, 판매자, 문화예술인 등 인적네트워크 구성으로 상호간의 정보교류와 협력을 통하여 대한민국의 대나무 산업 발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "세계녹화연합",
    purpose: "지구촌의 황폐한 산지를 복원하고 세계녹화와 지구환경 개선을 극대화하여 인류 복지향상에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "산지포럼",
    purpose: "산지정책의 다양한 여건변화 등에 대응하고, 산지관련 전문가의 지식과 비전을 공유하여 미래 지향적인 산지관리제도 개선 및 정책 수립 지원",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국유아숲지도사협회",
    purpose: "산림교육활성화를 위한 유아숲지도사의 전문성, 효율성, 능률성 향상",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "전국대학학술림 협의회",
    purpose: "전국 학술림(시험림)의 설립 목적인 산림과학 분야의 교육 및 연구발전과 학술림(시험림) 운영에 관한 상호협력 증진",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림보호협력센터",
    purpose: "산림유전자원보호구역의 보전과 활용을 통한 산림생태계와 생물다양성 증진 및 지속가능한 지역활성화 실현",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국숲교육협회",
    purpose: "숲교육 연구 및 프로그램 개발∙보급 등",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국전통참숯협회",
    purpose: "한국 전통참숯생산 기능과 활용문화의 과학적 입증을 통한 계승·보전·발전 및 관련 기술을 산업화하고 보급하여 목재산업에 이바지",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국WPC산업협회",
    purpose: "국내 WPC산업의 국제 경쟁력 강화를 위한 대정부 정책 제안 및 연구, 교육사업 등을 수행하고 및 신기술 개발협력하여 균형있는 경제발전 도모",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "숲과아동 청소년교육",
    purpose: "아동청소년들이 숲에서 자유롭고 안전하게 활동할 수 있는 제반 교육적 여건을 마련하는 등 산림교육에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국아보리스트협회",
    purpose: "수목 등목(登木) 기술을 개발·보급함으로써 안전한 수목관리 및 이를 활용한 시료채취, 유전자원의 관리 등을 통해 임업발전에 기여하고, 국민이 숲과 더불어 행복한 삶을 영위할 수 있도록 지원",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "숲태교연구협회",
    purpose: "임산부가 체계적이고 과학적이며 다양한 '숲 태교'를 지속적이며 반복적으로 체험함으로써 건강하고 밝은 미래세대를 출산하는 것에 도움이 되는 여러가지 방법을 적극적으로 함께 모색하고 이를 수행.홍보",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국정원협회",
    purpose: "정원문화 관련 다양한 사업을 통해 새로운 정원문화의 확산과 정원 관련 새로운 일자리 창출에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국수목장협회",
    purpose: "친환경장례문화인 수목장의 확산 및 보급을 통하여 국민보건복지와 산림복지에 이바지함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "산림형 사회적 경제협의회",
    purpose: "산림형사회적경제 분야의 수익창출 방안을 연구, 개발, 보급함으로써 지속가능한 고용창출 및 사회서비스 제공 등 사회적 목적 실현",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "숲을 찾는 사람들",
    purpose: "숲 치유 숲길을 소개함으로써 건전한 걷기여행 문화를 전차하고 숲 보존유지",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대한트레일런협회(KTRA)",
    purpose: "트레일런과 산악, 숲길에 관한 조사연구 및 교육훈련을 통하여 건전한 트레일런 및 산악운동을 보급 장려하고 산악환경보존과 자연보호정신을 함양하여 국가와 사회발전에 이바지함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "더-좋은 나무만들기",
    purpose: "산림종묘, 임목개량 기술을 개발하여 현장에 활용시키는 업무와 산림시책을 보다 효율적으로 추진할 수 있도록 산림자원 개발을 지원",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "속리산둘레길",
    purpose: "산림자원의 다양한 가치를 지속적으로 보전․활용하기 위해 산촌마을을 포함해 숲과 숲길을 연구․조사하여 지역발전에 이바지",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "산림보호통신원협회",
    purpose: "휴대용 통신기기 및 인터넷을 활용하여 산림환경보호, 자원 보존, 재해 예방, 피해 최소화를 위한 자발적이고 적극적인 행동실천과 산불 및 재선충 피해 최소화를 위한 교육 및 시민의식의 고취",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국소나무보호협회",
    purpose: "소나무들을 아끼고 사랑하며 보호하는 선도적 역할을 하며, 전 국민의 참여를 유도하여 소나무를 나라 나무로, 국가 자연유산의 상징 브랜드로 만들어 국가의 위상과 자연보호에 앞장서 나감",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "산촌생태마을 전국협의회",
    purpose: "전국 산촌생태마을의 자주적 협동체로서 회원 상호간 친목 및 정보공유 등 교류증진산촌생태마을 대표, 운영위원장, 매니저, 주민 등의 역량강화와 복지 향상에 기여도시민의 산촌문화체험, 귀산촌 등 도농교류확산을 통해 산촌활성화에 기여 지역주민의 삶의 잘 향상과 농가소득증대를 도모궁극적으로 산촌생태마을을 포함한 산촌이 발전을 촉진",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "생태문화포럼",
    purpose: "산림문화·휴양 교육 프로그램을 통한 체계적이고 건전한 생태문화 확산으로 국민의 삶의 질 향상 및 행복시대 구현에 이바지함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림엔지니어링협회",
    purpose: "산림분야 기술증진을 통한 임업발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "우디즘 목재이용연구소",
    purpose: "도시의 목질화를 통한 국산목재 고부가가치 창출, 목재이용문화 확산 및 올바른 목재이용 도모",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "산림환경포럼",
    purpose: "산림자원을 보전하여 기후변화 및 지구온난화에 대응하며, 산림환경의 기능증진에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "이음숲",
    purpose: "숲을 중심으로 다양한 생태교육프로그램을 연구 개발하고, 소외계층 등 각계각층의 시민들을 위한 교육서비스 및 일자리를 제공함으로써 국민들의 행복증진에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 대한민국무궁화예술협회",
    purpose: "무궁화가 지닌 기품과 고귀한 아름다움을 무궁화예쑬을 통해 국민적 자긍심을 제고시키고 장애인복지법에 의한 장애인 일자리 창출을 통해 국가발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국자생식물생산자협회",
    purpose: "자생식물 재배환경 조사·연구와 회원 간의 재배기술정보 교류, 생산성 향상을 위한 공동노력 등 지원 사업전개 및 신품종개발 등 자생식물의 이용활성화를 통해 임업 발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국식물보전네트워크",
    purpose: "식물자원 보전에 관한 활동 및 교육을 통한 지구 및 국내식물의 현지 내·외 보전 역량 증진과 민간 식물 보전 관련 단체와의 협력 활성화를 통한 네트워크 구죽으로 공익 발전 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "숲사랑산사랑",
    purpose: "산림을 보호하고 산불을 방지하며 푸른 숲의 보전ㆍ발전을 통하여 국가경제 발전과 국민건강 향상에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "나눔정원가든제이",
    purpose: "정원문화 확장 및 보급을 위해 이론과 실무에 능통한 가든코디네이터를 양성하고, 자연과 소통할 수 있는 도시속 정원문화 확립",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국성형목탄협회",
    purpose: "한국 성형목탄 생산 및 유통 기능과 활용문화를 발전시키고, 관련 기술을 산업화하고 보급하여 목재산업 발전에 이바지하고, 성형목탄업 종사자들에게 직업에 대한 자긍심을 높여 성형목탄산업의 계승발전에 기여하기 위함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국목재시설물협회",
    purpose: "목재시설물을 생산 또는 유통하는 업체들 간의 공동 발전과 유통질서의 확립을 도모합으로써 국가경제 발전에 공헌하고 회원사의 권익을 보호하기 위함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "산림자원육종가협회",
    purpose: "산림종묘, 산림유전, 임목개량기술을 개발, 보급함으로써 임업발전에 공헌하고, 선진육종기술 보급 및 교육을 통해 회원 간 상호 교류",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국숯유통협회",
    purpose: "숯 유통산업 선진화를 위한 제도개선 연구 및 정책제언 등을 통해 숯 유통업 종사자의 공익신장에 공헌하며 숯 제품 생산과 품질향상을 위한 연구 활동등으로 소비자 안전관리와 국내 숯 유통산업의 발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국산림휴양경관협회",
    purpose: "산림휴양경관의 생태,환경,교육,문화 등 다원적 가치의 재구성을 통한 투럴리티 창출 및 합리적 이용에 대한 차별화된 기술방안을 지속적 개발 증진",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국산서회",
    purpose: "우리 민족에게 역사의 무대였고 문학의 배경이였던 산에 대한 산악서적과 산악문화발굴을 통해 산악문화의 뿌리를 찾고 연구하며 건전한 산악문화를 확산 보급",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국산림탄소협회",
    purpose: "산림탄소상쇄사업을 통한 공익기능 증진 및 산림경영기술 공유",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 전국무궁화생산자 협회",
    purpose: "우수한 품종의 무궁화를 생산 및 육성하여 국민들에게 나라꽃의 아름다움을 널리 알리고 무궁화 생산 및 재배기술 공유, 품종개발 보존, 분양을 통한 나라꽃 보급 확산에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림치유지도사 협회",
    purpose: "산림치유 활동을 수행함으로써 구성원의 산림치유능력을 향상시키고 국민에게는 건강한 삶을 유지하는데 이바지",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국떫은감협회",
    purpose: "떫은감 산업의 발전과 경작자의 사회적, 경제적 지위 향상",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "광릉숲친구들",
    purpose: "광릉숲의 가치를 국민에게 제대로 알리고, 숲의 혜택이 지역사회에 돌아갈 수 있도록 노력하며, 숲을 국민의 삶과 접목해 사람과 자연이 함께 공존할 수 있는 지속 가능한 모델을 제시",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국민간정원협회",
    purpose: "개별정원 특성에 맞는 민간정원 활성화 및 수익성 증진, 정원 산업 관련기술의 정보교류 및 협력 등의 노력을 통해 생활 속 정원문화 확산에 기여함을 그목적으로 함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국떫은감생산자협회",
    purpose: "떫은감의 생산·가공 기술 개발, 소비확대 등 떫은감 산업의 발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국숲사랑총연합회",
    purpose: "시민참여 나무심기, 숲가꾸기 운동 등을 통해 숲 육성과 산림 유전자원의 증식에 기여하고, 숲을 아끼고 지키는 창조적 산림운동인 숲사랑 전국민 운동으로 전개하여 국토 보존과 국민 건강 증진에 이바지",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 우리꽃무궁화교육원",
    purpose: "무궁화 등 우리꽃을 연구하고 재현, 교육, 재배 및 육성함으로 무궁화 진흥에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북산림협력포럼",
    purpose: "동북아 평화번영을 위한 산림협력, 남북산림협력을 통한 경제적 공동체 기반조성으로 평화통일에 기여 등",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대한동백협회",
    purpose: "동백의 종합적인 조사, 연구, 고유품종 보존, 우수품종 발굴, 교배육종을 통한 신품종 개발 육성 지동 등",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "365산림화재예방협회",
    purpose: "산림화재로 인한 피해를 사전에 예방하여 쾌적한 산림 및 자연환경을 보전",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국야생식물가꾸기협회",
    purpose: "국가의 산림보호와 환경관리정책에 입각하여 우리나라 산야와 도시공원 및 녹지에서 자생하는 야생식물을 심고 키우며 보호하여 산림자원 보존 및 자연환경을 보전함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "산림휴양협회",
    purpose: "건강한 산림휴양을 통한 휴식여행, 안전한 휴양시설 설치에 대한 타당성 여부의 기술자문 활동으로 국민보건 및 삶의 질 향상에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국가로수협회",
    purpose: "가로수 또는 이에 준하는 수목에 대한 조성 및 관리 등에 관한연구, 교육 활동, 캠페인 홍보, 용역사업, 시민참여활동, 자료 발간 등을 통하여 가로수의 건강하고 안전한 조성 및 관리",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국수목치료기술자협회",
    purpose: "수목치료기술자 상호협력을 바탕으로 수목치료기술 향상과 건강한 수목보호에 기여하여 국민건강 증진 및 쾌적한 생활환경 제공",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림환경운동본부",
    purpose: "산림환경보호활동과 함께 산림에 대한 국민의식을 고취시키고, 나아가서는 산림자원에 대한 관리, 보호 등 공익기능에 이바지",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림복원협회",
    purpose: "산림의 생태적 안정을 위한 산림복원기술의 개발 및 확산, 산림복원 관련 산업의 발전에 기여 등",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국생활정원진흥회",
    purpose: "생활정원 활성화, 모두가 누릴 수 있는 정원복지 여건 개선, 생활 속 정원 콘텐츠 알림 및 국제교류 등을 통한 정원문화 확산에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국나무의사협회",
    purpose: "나무의사 권익향상·복리증진 및 수목진료 기술발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산촌재생본부",
    purpose: "수도권에서 초과밀집중화현상이 나타나고 있는 현재, 우리는 새로운 꿈을 찾아 도시를 떠나고자 하는 많은 분들이 안심하고 정착할 수 있는 실현 가능한 교육과 사업모델을 제시하고, 도시와 산촌지역을 연계한 프로그램 개발을 통해 산촌마을 활성화와 낙후지역이 침체의늪에서 벗어나 활기를 되찾는데 그 목적을 둠",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국국산목제재협회",
    purpose: "국산재 고부가 가치 창출을 위한 학술 연구 및 정책제안, 국산재활용에 기여하기 위함",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "시민정원문화협회",
    purpose: "정원 유지관리 및 전시, 정원사 교육 등 정원문화 진흥",
    law: "-",
    type: "사단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "LG상록재단",
    purpose: "산림환경의 보호와 연구를 위한 각종시설의 조성 및 운영사업, 야생동·식물 보호 및 연구 지원사업",
    law: "-",
    type: "재단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "늘푸른영농재단",
    purpose: "잔디와조경관련 농업기술연구, 기술개발 및 국내외 기술보급",
    law: "-",
    type: "재단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "서울그린트러스트",
    purpose: "시민의 참여와 봉사를 바탕으로 서울시 생활권녹지를 확대․보존",
    law: "-",
    type: "재단법인(기부금)",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "소호문화재단",
    purpose: "산림․목재문화 연구개발 보존․창달을 위한 학술연구보급․산림문화시설을 조성․운영함으로서 사회 일반의 이익에 기여",
    law: "-",
    type: "재단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "천리포수목원",
    purpose: "한국식물과 세계식물의 비교연구를 통하여 한국식물의 세계적 위치 규명, 식물자원보호와 실용화를 위한 사업 및 국민에 대한 식물 교육장 제공",
    law: "-",
    type: "재단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "우면산내셔널트러스트",
    purpose: "우면산 지역의 산림자원과 산림생태유산을 공유화하여 쾌적한 생활환경 개선",
    law: "-",
    type: "재단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "화천군청정산업진흥재단",
    purpose: "국내 산림자원의 효율적 활용을 위하여 목재산업단지 조성 및 관련 산업의 지원․육성 등 성장기반 확충과 지역발전에 기여",
    law: "-",
    type: "재단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국숲",
    purpose: "숲단체와 숲단체 활동가들을 지원하기 위한 기금조성 및 운용",
    law: "-",
    type: "재단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림아카데미재단",
    purpose: "산림과 임업분야의 교육을 통해 미래지향적인 전문인재를 양성하고, 임업인들에게 올바른 산림경영 정보와 소득창출 방안을 교육‧홍보함으로써 임업경쟁력을 향상",
    law: "-",
    type: "재단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국수목장문화진흥재단",
    purpose: "자연친화적인 수목장 문화 진흥을 통해 산림자원을 보호·육성하고 산림환경기능을 증진",
    law: "-",
    type: "재단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "산림힐링재단",
    purpose: "산림교육·치유사업을 통한 산림복지증진 및 행위중독 예방치유사업을 통한 관련 사회문제 해결 지원 등",
    law: "-",
    type: "재단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 나남",
    purpose: "산림복지 활성화를 위한 수목장림의 조성·운영",
    law: "-",
    type: "재단법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "산림조합중앙회",
    purpose: "지속가능한 산림경영을 증진하고 산림의 생산력을 증진하게 함과 아울러 임산물의 유통활성화를 촉진하여 조합원의 경제적․사회적․문화적 지위향상 및 소득증대에 기여함",
    law: "-",
    type: "특수법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산지보전협회",
    purpose: "산지의 보전 및 산림자원 육성을 위한 정책 ·제도의 조사 ·연구 및 교육 ·홍보 등을 통한 산지의 보전 및 산림자원의 육성에 기여",
    law: "-",
    type: "특수법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국등산·트레킹지원센터",
    purpose: "건전한 등산·트레킹문화의 확산과 발전을 위한 교육·홍보사업과 지속가능한 등산·트레킹환경 조성을 위한 사업 등을 체계적으로 수행",
    law: "-",
    type: "특수법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사방협회",
    purpose: "사방기술의 지원과 국제 기술교류, 사방사업과 관련한 조사,평가,진단 및 사방정책의 교육,홍보 등의 사업에 기여",
    law: "-",
    type: "특수법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국임업진흥원(구 임산물품질관리위원회)",
    purpose: "산림과학분야 연구개발 성과의 신속한 실용화 촉진을 통한 경제적 파급효과를 극대화하고, 임업인의 소득증대 및 임산업의 고부가가치 창출을 통한 임업 진흥",
    law: "-",
    type: "특수법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림토석협회",
    purpose: "채석관련 제도개선 및 기술향상으로 채석업의 건전한 발전을 도모하고, 석재자원의 개발로 국가산업 발전에 기여함",
    law: "-",
    type: "특수법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "목재문화진흥회",
    purpose: "목재문화의 진흥, 목재교육의 활성화 및 목재의 지속가능한 이용을 촉진하기 위한 사업에 기여",
    law: "-",
    type: "특수법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산불방지기술협회",
    purpose: "산불방지에 관한 교육ㆍ훈련, 산불방지에 관한  연구ㆍ조사, 행정기관이 위탁하는 업무의 수행",
    law: "-",
    type: "특수법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림복지진흥원",
    purpose: "국민에게 다양하고 체계적인 산림복지서비스를 제공함으로써 국민의 건강 증진, 삶의 질 향상 및 행복추구에 기여",
    law: "-",
    type: "특수법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국수목원관리원",
    purpose: "수목유전자원의 보전 및 자원화를 위해 기후 및 식생대별로 조성한 국립수목원을 운영·관리함으로써 국민의 삶의 질 향상과 국민경제의 발전에 이바지",
    law: "-",
    type: "특수법인",
    remit: "산림청",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산림기술인회",
    purpose: "산림기술법 제13조 규정에 의하여 산림기술자의 복지증진과 산림기술 및 산림사업의 발전 도모",
    law: "-",
    type: "특수법인",
    remit: "산림청",
  ),
];
