import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> kdcaRawData = [
  ExcelRowData(
    permitDate: "1953.12.1",
    name: "사단법인 대한결핵협회",
    purpose: "결핵에 관한 조사연구와 예방 및 퇴치사업 등 국가결핵관리사업을 통하여 국민보건향상에 이바지",
    law: "-",
    type: "사단",
    remit: "질병관리청",
  ),
  ExcelRowData(
    permitDate: "1973.12.20",
    name: "재단법인 로이스기독재활원",
    purpose: "질병치료와 요양·구호",
    law: "-",
    type: "재단",
    remit: "질병관리청",
  ),
  ExcelRowData(
    permitDate: "1979.12.13",
    name: "사단법인 한국방역협회",
    purpose: "감염병 예방 및 홍보, 감염병 예방 기술 향상을 통해 국민 건강보호와 질병없는 국가건설에 기여하고 회원권익 향상과 보호",
    law: "-",
    type: "사단",
    remit: "질병관리청",
  ),
  ExcelRowData(
    permitDate: "1993.11.25.",
    name: "사단법인 한국에이즈퇴치연맹",
    purpose: "건전한 국민도의를 확립하여 에이즈를 근원적이고 효과적으로 예방하기 위한 연구와 국민운동 수행",
    law: "-",
    type: "사단",
    remit: "질병관리청",
  ),
  ExcelRowData(
    permitDate: "1994.5.6.",
    name: "사단법인 대한에이즈예방협회",
    purpose: "에이즈예방 및 퇴치와 감염자 및 그 가족의 권익을 대변하여 그들의 복지증진에 기여",
    law: "-",
    type: "사단",
    remit: "질병관리청",
  ),
  ExcelRowData(
    permitDate: "1998.12.24.",
    name: "사단법인 국제백신연구소한국후원회",
    purpose: "우리나라가 최초로 유치한 국제기구인 IVI 후원을 통해 감염병 예방을 통한 인류복지 증진, 과학기술 발전에 기여 세계적백신개발 국제기구로 발전하도록 범국민적 후원활동 지원",
    law: "-",
    type: "사단",
    remit: "질병관리청",
  ),
  ExcelRowData(
    permitDate: "2000.2.25.",
    name: "재단법인 유진벨",
    purpose: "보건의료, 교육, 기타 인도주의 실현을 위한 제반활동 수행",
    law: "-",
    type: "재단",
    remit: "질병관리청",
  ),
  ExcelRowData(
    permitDate: "2003.2.10.",
    name: "재단법인 한국에이즈예방재단",
    purpose: "우리나라 에이즈 예방 및 퇴치와 감염인 복지증진",
    law: "-",
    type: "재단",
    remit: "질병관리청",
  ),
  ExcelRowData(
    permitDate: "2009.2.18",
    name: "재단법인 국제결핵연구소",
    purpose: "결핵예방법 규정에 의한 결핵예방 관련 제반 사업을 국내외적으로 수행하되, 특히 다제내성 결핵의 치료와 예방을 위한 기초 및 임상연구, 결핵치료용 신약개발, 예방접종 및 진단기법개발·촉진, 결핵연구 및 연구기관들과의 네트워크 구축·확대, 국내외 전문가 양성을 위한 교육 및 훈련, 다제내성결핵 전반에 걸친 다양한 분야의 협력연구 활성화 등을 수행함",
    law: "-",
    type: "재단",
    remit: "질병관리청",
  ),
  ExcelRowData(
    permitDate: "2009.4.17.",
    name: "사단법인 한국생물안전협회",
    purpose: "유전자변형생물체의 안전관리 등 자율적 생물안전관리 인식 확산을 위한 교육",
    law: "-",
    type: "사단",
    remit: "질병관리청",
  ),
  ExcelRowData(
    permitDate: "2009.10.9.",
    name: "사단법인 한국가톨릭레드리본",
    purpose: "HIV 감염인 보호·지원을 위한 전문적인 의료·복지서비스 제공",
    law: "-",
    type: "사단",
    remit: "질병관리청",
  ),
];
