import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> kcgRawData = [
  ExcelRowData(
    permitDate: "1999-01-13",
    name: "한국수상레저안전연합회",
    purpose: "조종면허시험대행/해양환경보호",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2002-04-30",
    name: "대한래프팅협회",
    purpose: "래프팅가이드교육/해양환경 및 수중 정화",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2003-05-10",
    name: "한국라이프세이빙협회",
    purpose: "인명구조프로그램 개발보급/해양환경보호/수난구호활동",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2004-11-02",
    name: "전국해상도선협회",
    purpose: "국토교통부, 해양경찰청 및 지자체 주관･시행하는 해상정화 사업 지원/ 도선 안전운항 전반에 관한 공익사업 지원",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2005-02-12",
    name: "대한인명구조협회",
    purpose: "인명구조요원·래프팅가이드 교육/해양환경보호",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2005-03-29",
    name: "한국해상재난환경구조단",
    purpose: "재난지역에 신속한 인력지원을 통한 구조구난 / 해상재난 발생시 긴급물품지원 / 시설복구 및 의료지원 활동 / 해상 재난시 대처방법 및 응급조치 교육",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2006-06-16",
    name: "전국유선업중앙회",
    purpose: "해상관광발전과 유선산업의 선진화를 위한 지식정보 개발, 서비스 / 해양안전사고 방지를 위한 홍보, 지도, 계몽, 교육 활동 업무",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2006-11-03",
    name: "한국해양환경감시협의회",
    purpose: "해양환경보호/교육/봉사",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2007-05-18",
    name: "한국수상인명구조협회",
    purpose: "재난구조 및 수중 정화활동/해양환경보호",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2008-10-01",
    name: "대한파워보트연맹",
    purpose: "수상레저기법 보급/기술교류 및 각종 대회 주최, 주관",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2009-03-26",
    name: "인천낚시유선협회",
    purpose: "낚시발전과 유선사업 선진화를 위한 지식정보개발, 서비스 등",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2009-05-21",
    name: "대한잠수구조사협회",
    purpose: "수난구조지원 / 국제잠수구조사협회와 이에 가입된 각 국가와 국제 교류 / 국제잠수구조교육기관의 선진 교육 시스템의 연구 및 보급",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2010-12-15",
    name: "한국해양레저연합회",
    purpose: "면제교육기관 대행/수상레저스포츠 거점화를 위한 연구 해양환경교육 및 복원사업/수상레저스포츠 연구 용역사업",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2011-09-28",
    name: "한국수상레저안전협회",
    purpose: "조종면허 시험대행및수상레저활동안전관리",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2012-04-27",
    name: "한국해양안전협회",
    purpose: "수상에서 안전과 해양, 연안사고예방을 위한 인명구조 및 민간순찰활동 실시 / 국제협력 또는 각종 학술세미나, 해양안전교육, 장비전시 및 해양안전과 관련한 각종 대회 포럼개최",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2012-09-14",
    name: "해양환경안전학회",
    purpose: "해양환경 및 안전에 관한 학술 연구/ 해양환경 보전 및 해양 안전 증진",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2012-12-28",
    name: "한국씨카약협회",
    purpose: "씨카약 무료체험/무인도 수변정화 활동사업",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2013-01-29",
    name: "한국해양구조협회",
    purpose: "수색구조구난 업무 지원 / 해양사고 예방과 안전관리 의식의 고취를 위한 대국민홍보 / 해양사고 예방, 대응 해양환경 보전 / 해양안전을 위한 민간해양구조대 운영관리 및 국내외 단체와의 협력에 관한 사업",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2013-09-27",
    name: "수상인명구조교육협회",
    purpose: "수상사고예방과 안전관리 의식의 고취를 위한 대국민홍보 / 수색구조 구난업무와 기술에 관한 교육 조사 연구 개발 자문과 정보의 수집 분석 및 제공에 관한 사업",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2015-07-27",
    name: "대한워터스포츠협회",
    purpose: "워터스포츠 체험교실 운영/청소년워터스포츠클럽 운영",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2016-03-02",
    name: "공공안전잠수협회",
    purpose: "수상 및 수중 안전 문제에 관한 조사, 연구, 교육, 자문 수상 및 수중 안전교육 매뉴얼 및 연구 자료집, 간행물의 발간 / 수상 및 수중활동장비 인원의 안전 검사 및 관리 개발시스템 확립",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2016-07-07",
    name: "해상재난안전SAR협회",
    purpose: "해상안전 관련 교육 및 전문가 양성에 관한사업 / 재난 사고 발생시 인명구조지원 활동에 관한사업 / 재난사고예방을 위한 홍보에 관한 사업 / 안전교육을 위한 영유아, 아동청소년 보육 및 교육 사업 / 행정기관 위수탁사업 / 에스에이알 교육원 / 에스에이알 해양레저 연구소",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2016-08-02",
    name: "대한수상안전교육협회",
    purpose: "면허시험 및 면제교육/ 기구 등록, 안전점검 검사 관련 사업 각종 재난과 사고의 예방 및 대응을 위한 교육 및 연구사업 위 각호의 관련된 교재, 도서, 영상물의 제작 및 출판사업",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2016-09-22",
    name: "한국해양안전교육협회",
    purpose: "심해용 특수 장비 국산화 및 교육을 위한 연구개발, 산업 잠수사 해외 취업 자격증 발급, 재호흡기 개발 및 보급을 위한 연구 개발사업",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2016-12-05",
    name: "한국안전수영협회",
    purpose: "교육에 의해 신체부력만으로 장시간 물에 뜨는 '잎새뜨기' 안전수영법을 교육 보급하기위해 제반사업 활동 수행",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2017-06-09",
    name: "한국수상안전인력양성협회",
    purpose: "수상인명구조, 응급구조 등 수상안전교육사업",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2017-12-13",
    name: "한국해양안전순찰총연합회",
    purpose: "대한민국 연안해역에서의 각종 재난 예방을 위하여 정기적인 순찰활동 실시 / 해양환경보전과 해양봉사문화의 활성화를 위해 적극 지원",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2018-01-17",
    name: "대한민국해양경찰전우회",
    purpose: "해양경찰 권익보호 및 홍보/  해양환경 및 해양안전 활동",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2018-04-20",
    name: "재난안전연합회",
    purpose: "구조인력 양성 및 육상, 수상 구조활동 / 재해 및 재난안전 예방활동 및 홍보, 교육사업 / 재난안전관련 지도자 육성 및 활동",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2020-01-15",
    name: "장성수상안전인명구조자원봉사협회",
    purpose: "인명구조요원 및 래프팅가이드 양성을 위한 교육 및 강사 양성 / 재난사고발생시 인명구조 지원활동 및 장비등 연구개발 / 재난사고예방을 위한 국제교류, 홍보간행물 발간",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2020-03-11",
    name: "수난구조교육협회",
    purpose: "수난사고 관련 구조 전문가 양성을 위한 교육훈련사업 / 수난사고 예방과 안전의식 고취를 위한 대국민 홍보활동 / 수난사고 관련 수색구조업무지원",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2021-05-26",
    name: "국제해양경찰학회",
    purpose: "해양경비·안전 및 레저·관광 분야의 이론과 실무에 관련된 연구",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2022-09-06",
    name: "전국선박해체사업자협회",
    purpose: "선박해체 시 해양환경오염 최소화, 자원재활용방안 추진 및 봉사활동 등을 통한 회원 지위향상과 깨끗한 바다환경보전 등 공익 기여",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2024-06-24",
    name: "해병대전우 수상인명구조대",
    purpose: "수상에서 재난과 사고 예방·대응을 위한 민·관 협력, 교육훈련과 대국민 홍보 활동, 구조·구난산업 육성 및 기술향상 등",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2024-08-29",
    name: "비추온안전협회",
    purpose: "해양안전 교육 및 홍보사업, 청소년 생존수영 교실 운영, 해양안전 자원봉사 활동 및 교육, 수상구조사 및 인명구조관련 안전교육, 기타 법인의 목적 달성에 필요한 사업",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2024-11-27",
    name: "한국해양경찰 경우협의회",
    purpose: "국가정책에 부응하며 국민에 대한 봉사와 해양 치안 활동에 기여하고, 공제·교육사업을 통한 공익 증진 및 사회 이바지",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
  ExcelRowData(
    permitDate: "2025-03-17",
    name: "한국민간해양인명구조단",
    purpose: "수상에서 재난 발생 시 신속한 구조·구난 및 예방활동, 응급 처치와 심폐소생술 교육, 인명구조요원 및 교육·검정·자격증 발급 등",
    law: "-",
    type: "사단법인",
    remit: "해양경찰청",
  ),
];
