import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> moeRawData = [
  ExcelRowData(
    permitDate: "-",
    name: "한국인문사회총연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국지도자육성장학재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "인성교육 범국민실천연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "국비유학한림원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국글로벌코리아스칼라십동문회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국교육환경보호원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국마이스터정책연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국교육시설안전원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국교육녹색환경연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족미래운동",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국전문대학법인협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국교과서연구재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국대학법인협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국민간자격협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "국가공인자격협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "산학협동재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국산학연계현장실습지원협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국대학사회봉사협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)태평양아시아협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "의․치의학교육입문검사협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "법학전문대학원 협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국공학교육인증원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "참교육을위한전국학부모회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "소비자교육중앙회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "삼성꿈장학재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "두산연강재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "신한장학재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "임당장학문화재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "일주학술문화재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "호국장학재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "미래인재육성재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "STX장학재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국디지털교육협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "스마트교육재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국교육학술정보원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "동북아역사재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국약학교육협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국대학총장협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국검인정교과서협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "학습자료협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국학원총연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국향토사연구전국연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국교원단체총연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국교육삼락회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국학중앙연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국고전번역원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "국가평생교육진흥원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "서울대학교발전재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "국립대학병원협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "교육부",
  ),
];
