import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> mpvaRawData = [
  ExcelRowData(
    permitDate: "1955-02-25",
    name: "(사)일성이준열사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1963-12-14",
    name: "(사)안중근의사숭모회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1973-08-06",
    name: "(재)송재서재필박사기념재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1977-06-09",
    name: "(사)고당조만식선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1978-03-10",
    name: "(사)고헌박상진의사추모사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1979-02-26",
    name: "(사)철기이범석장군기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1983-06-01",
    name: "(사)허방산선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1986-06-01",
    name: "(사)매헌윤봉길의사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1985-08-26",
    name: "(사)조명하의사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1992-07-27",
    name: "(사)백범김구선생기념사업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1993-11-10",
    name: "(재)여순순국선열기념재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1994-12-20",
    name: "(재)고하송진우선생기념사업회",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1994-12-20",
    name: "(사)일광정시해선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1995-12-14",
    name: "(사)이봉창의사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1996-03-08",
    name: "(사)이승만건국대통령기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1996-04-10",
    name: "(사)해공신익희선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1996-08-23",
    name: "(사)박차정의사숭모회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1996-10-22",
    name: "(사)구파백정기의사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2000-12-05",
    name: "(사)6.18자유상이자회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1985-01-09",
    name: "(사)한맥",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1998-06-29",
    name: "(사)백산안희제선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1998-12-26",
    name: "(재)한국방정환재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1975-12-30",
    name: "(사)3.1동지회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1999-05-03",
    name: "(사)한국독립동지회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1999-06-11",
    name: "(사)장준하기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1999-06-24",
    name: "(사)백야김좌진장군기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1999-07-07",
    name: "(사)효창원8위선열기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1999-07-20",
    name: "(사)대한광복단기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1999-11-25",
    name: "(사)운강이강년선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2000-05-09",
    name: "(사)이재명의사추모사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2000-06-15",
    name: "(사)독립운동가백용성조사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2000-07-14",
    name: "(사)이상설선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2000-06-20",
    name: "(재)제대군인지원정책연구원",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2001-05-15",
    name: "(사)독립유공자유지계승유족회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2001-05-15",
    name: "(사)민세안재홍선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2001-05-15",
    name: "(사)심산김창숙선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2001-06-04",
    name: "(사)완주26위애국선열선양사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2001-08-22",
    name: "(사)대한기미독립정신선양사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2001-09-20",
    name: "(사)대한독립운동사적보존진흥회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2001-09-20",
    name: "(사)성재이동휘선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2001-10-10",
    name: "(사)박열의사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2001-11-13",
    name: "(사)유관순열사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2001-12-28",
    name: "(사)한국독립운동교육사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2001-12-28",
    name: "(사)안창남기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2002-02-19",
    name: "(사)양평의병기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2002-04-15",
    name: "(사)한민족독립정신연구회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2002-05-02",
    name: "(사)도산안창호선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2002-05-07",
    name: "(사)국채보상운동기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2002-05-07",
    name: "(사)유석조병옥선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2002-05-16",
    name: "(사)3.1여성동지회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2002-05-16",
    name: "(재)순국선열김순구선생외25인기념재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2002-06-04",
    name: "(사)한국보훈학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2003-01-29",
    name: "(사)한민회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2003-01-29",
    name: "(사)조선민족대동단기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2003-07-01",
    name: "(사)안재극선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2003-07-01",
    name: "(사)예산모현사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2003-07-16",
    name: "(사)송학선의사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1984-11-20",
    name: "(사)김상옥의사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "1995-03-29",
    name: "(사)3.15의거기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2004-01-27",
    name: "(사)한국광복군기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2004-03-09",
    name: "(사)단재신채호선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2004-03-29",
    name: "(사)여주시독립운동가기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2005-03-03",
    name: "(사)여천홍범도장군기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2005-03-31",
    name: "(사)군북3.1독립운동기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2005-06-17",
    name: "(사)국가유공4형제전사자추모사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2005-11-07",
    name: "(사)배설(베델)선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2005-12-16",
    name: "(사)대한민국임시정부기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2005-12-30",
    name: "(사)제대군인지원협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2006-04-27",
    name: "(사)희산김승학선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2006-05-01",
    name: "(사)대한민국특수임무수행자유족동지회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2006-05-10",
    name: "(사)운암김성숙선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2006-05-10",
    name: "(사)헐버트박사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2006-06-28",
    name: "(사)제2연평해전승전기념회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2006-06-28",
    name: "(사)한말의병대장녹천고광순의사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2006-07-25",
    name: "(사)흥남철수작전기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2006-07-25",
    name: "(사)김원국.김원범의병대장기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2006-12-22",
    name: "(사)우사김규식박사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2006-12-22",
    name: "(사)유정조동호선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2007-06-12",
    name: "(사)한국미래문제연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2007-07-06",
    name: "(사)몽양여운형선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2008-01-10",
    name: "(사)대한의열단기념회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2008-01-10",
    name: "(사)신간회기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2008-03-26",
    name: "(사)동천남상목의병장기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2008-09-24",
    name: "(사)경사변순기봉암변진설기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2008-12-18",
    name: "(사)밀양독립운동사연구소",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2008-12-18",
    name: "(사)김마리아기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2008-12-29",
    name: "독도의용수비대기념사업회",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2009-02-02",
    name: "(사)수당이남규선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2009-02-02",
    name: "(사)광복단결사대한훈의사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2009-08-12",
    name: "(사)왕산기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2009-08-12",
    name: "(사)산남의진기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2010-01-28",
    name: "(사)탄운이정근의사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2010-04-22",
    name: "(사)의병정신선양회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2010-06-21",
    name: "(사)석정윤세주열사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2010-07-13",
    name: "(사)호랑이스코필드기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2010-11-30",
    name: "(재)천안함재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2010-06-18",
    name: "(사)국가유공자복지사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2011-01-05",
    name: "(사)화성시3.1독립운동기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2011-02-24",
    name: "(사)산돌손양원기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2011-08-10",
    name: "(사)항일의병최택현일가4의사순국기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2011-12-15",
    name: "(사)대암이태준선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2012-02-03",
    name: "(사)민족대표33인기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2012-03-21",
    name: "(사)나라사랑공제회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2012-07-02",
    name: "(사)지속가능대한민국",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2012-07-02",
    name: "(사)최세윤의병대장기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2012-09-11",
    name: "(사)백산지청천장군기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2012-10-19",
    name: "(사)일우김한종의사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2012-12-04",
    name: "(사)규암독립사상연구소",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2013-01-24",
    name: "(사)부산항일학생의거기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2013-03-28",
    name: "(사)나주학생독립운동기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2013-05-03",
    name: "(사)독립운동가박준승선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2013-06-04",
    name: "(사)일문구의사선양사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2013-07-03",
    name: "(사)의암손병희선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2013-11-15",
    name: "(재)항일영상역사재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2013-12-12",
    name: "(재)경상북도호국보훈재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2013-12-27",
    name: "(사)건국부통령이시영선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2014-05-07",
    name: "(사)국제평화기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2014-05-27",
    name: "(사)영산3.1운동독립결사대유족회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2014-06-12",
    name: "(사)장병준선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2014-08-28",
    name: "(사)기려자송상도지사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2014-09-19",
    name: "(사)지평리를 사랑하는 모임",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2014-01-15",
    name: "(사)창원삼진독립의거기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2015-01-13",
    name: "(사)김영옥평화센터",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2015-01-13",
    name: "(사)호국영웅연제근기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2015-01-13",
    name: "(재)이용문장군재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2015-08-17",
    name: "(사)원심창의사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2015-10-02",
    name: "(사)애국지사검은정순만기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2015-10-15",
    name: "(사)대한항일순국열사회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2015-10-15",
    name: "(재)대한국인",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2015-10-15",
    name: "(재)피앤에프(舊 연평재단)",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2015-12-29",
    name: "(사)영해3.18독립만세운동기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2015-12-30",
    name: "(사)김규흥선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2015-01-09",
    name: "(사)군산3.1만세운동기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-02-01",
    name: "(사)한국보훈선양예술협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-01-17",
    name: "(사)부사관호국영웅현충회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-02-16",
    name: "(사)국무령이상룡기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-04-01",
    name: "(사)우당이회영기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-05-04",
    name: "(사)호국평화기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-05-30",
    name: "(사)익산의병기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-07-20",
    name: "(사)국가유공자문화예술진흥원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-07-22",
    name: "(사)나라사랑교육연구회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-08-18",
    name: "(사)독립투사만해한용운선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-11-01",
    name: "(사)충우회호국영웅추모사업단",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-11-11",
    name: "(사)양산항일독립운동기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-11-23",
    name: "(사)낭산김준연선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-12-27",
    name: "(사)송와박영관선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-12-27",
    name: "(사)국가원로회의",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-12-28",
    name: "(사)최운산장군기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2016-12-28",
    name: "(사)미래와사회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-01-17",
    name: "(사)보훈공단동우회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-02-14",
    name: "(사)삼척임원리항일운동선양사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-03-14",
    name: "(재)한미동맹재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-03-23",
    name: "(사)대한해협해전전승기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-06-14",
    name: "(사)후은김용구의병장기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-07-13",
    name: "(사)항일여성독립운동기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-07-13",
    name: "(사)조선의열단기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-07-27",
    name: "(사)심훈선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-07-27",
    name: "(사)백골전우회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-07-17",
    name: "(사)민족대표33인유족회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-09-07",
    name: "(사)손정도기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-09-28",
    name: "(사)임시정부대통령백암박은식선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-09-28",
    name: "(사)서일총재기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-11-21",
    name: "(사)항일독립선열선양단체연합",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-11-21",
    name: "(사)현봉학박사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2017-12-04",
    name: "(사)평택삼일독립운동선양회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2018-02-12",
    name: "(사)6.25참전언론인회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2018-02-20",
    name: "(사)독립운동가최재형기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2018-04-23",
    name: "(사)무후광복군기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2018-04-17",
    name: "(사)김교신선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2018-05-16",
    name: "(사)연일승씨18인독립유공자기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2018-05-16",
    name: "(사)한국보훈복지정책연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2018-05-29",
    name: "(사)K문화독립군",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2018-07-02",
    name: "(사)조소앙선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2018-09-06",
    name: "(사)우운문양목선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2019-04-25",
    name: "(사)오석김혁장군기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2019-04-25",
    name: "(사)애국지사이종헌선생선양회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2019-04-25",
    name: "(사)조달진소위추모사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2019-06-13",
    name: "(사)한국전쟁참전국기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2019-07-08",
    name: "(사)청사조성환선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2019-09-09",
    name: "(사)애국지사정재용기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2019-09-09",
    name: "(사)김용근선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2019-10-17",
    name: "(사)대한민국군가합창단",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2019-11-21",
    name: "(재)국가유공자행복나눔재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2020-03-18",
    name: "(사)채명신장군기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2020-05-18",
    name: "(사)김신장군기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2020-05-18",
    name: "(사)박재혁의사기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2020-06-18",
    name: "(재)월남이상재선생기념재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2020-08-14",
    name: "(사)면암최익현선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2021-04-01",
    name: "(사)대한민국보훈보상대상자회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2021-06-01",
    name: "(사)프로젝트-솔져",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2022-02-23",
    name: "(사)326호국보훈연구소",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2022-03-10",
    name: "(사)참전비사연구회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2022-04-26",
    name: "(사)최덕휴기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2022-07-05",
    name: "(사)한국여성독립운동연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2022-09-13",
    name: "(사)일송김동삼선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2022-09-19",
    name: "(사)소운이봉하선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2023-01-10",
    name: "(사)심정민 추모사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2023-03-14",
    name: "(사)의열단",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2023-04-10",
    name: "(사)대한민국순직국군장병유족회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2023-06-14",
    name: "(재)백선엽장군기념재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2023-06-12",
    name: "(재)유일한박사기념연구재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2023-08-24",
    name: "(사)대한민국ROTC사회공헌단",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2023-08-25",
    name: "(사)백초월스님선양회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2023-09-06",
    name: "(사)김홍일장군기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2024-01-26",
    name: "(사)육이오참전육사생도기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2024-03-14",
    name: "(사)5·18민주화운동연구소",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2024-04-02",
    name: "(사)호국문화예술위원회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2024-05-17",
    name: "(사)승려독립운동가추모사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2024-08-21",
    name: "(사)권오설·권오상기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2024-11-21",
    name: "(사)한국보훈진흥회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2025-08-12",
    name: "(사)대한민국육군3사호국봉사단",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2025-12-01",
    name: "(사)영석이석영선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "2025-11-07",
    name: "(사)향산·동은선생기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)글로벌 보훈코리아",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "국가보훈부",
  ),
];
