import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> molitRawData = [
  ExcelRowData(
    permitDate: "1956-09-10",
    name: "(사)대한민국항공회",
    purpose: "- 국제 민간 항공 문화교류- 항공 관련 학술 연구단체",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1963-04-30",
    name: "(사)한국철도차량엔지니어링",
    purpose: "철도차량기술의 발전과 철도산업의 진흥 및 회원 상호간의 친목과 복리증진 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1970-01-21",
    name: "(사)철도순직유족회",
    purpose: "순직한 철도청 직원 유덕추모 및 선양",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1965-08-28",
    name: "(사)철우회",
    purpose: "회원 상호간의 친목과 복리증진 및 철도사업의 발전을 도모하고 취약계층에게 일자리 또는 사회서비스를 제공하여 삶의 질을 향상시키는데 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1969-09-17",
    name: "(사)한국자동차협회",
    purpose: "자동차 사용자의 권익보호 및 안전확보, 건전한 자동차문화 정착",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1971-02-10",
    name: "(사)도시및지역계획연구원",
    purpose: "도시 및 지역개발 계획에 관한 제반문제를 조사연구 함으로서 생활 환경 개선에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1971-11-17",
    name: "(사)한국부동산연합회",
    purpose: "부동산활동 국제적 상호연대성 확보, 부동산관련 전문지식 보급ㆍ이용질서 확립, 도시ㆍ국토이용계획수립 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1974-05-20",
    name: "(사)건설산업연구소",
    purpose: "건설공사의 조사, 설계, 원가계산,   시공관리의 기술향상 및 건설안전을 연구ㆍ보급함으로써 건설산업발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1977-11-04",
    name: "(사)대한건설 진흥회",
    purpose: "건설행정의 제도와 기술향상, 발전에 기여하고 회원의 친목과 복리증진",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1979-04-14",
    name: "(사)철도하역협회",
    purpose: "철도하역사업의 발전과 하역근로자의 복지향상",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1979-07-28",
    name: "(사)한국실내건축가협회",
    purpose: "한국실내 건축문화 발전과 인간환경 질적 향상",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1981-01-11",
    name: "(사)대한부동산학회",
    purpose: "부동산학 기초이론 수립, 부동산학  저변확대와 학문적 이론ㆍ응용분야  연구, 공익실현을 위한 부동산정책 수립",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1984-02-17",
    name: "(사)도성회",
    purpose: "회원상호간의 친목과 유대를 공고히 하고 고속도로 건설기술과 운영관리의 향상 발전",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1985-01-23",
    name: "(사)주우회",
    purpose: "회원 상호간의 친목과 유대를 공고히 하고 주택의 건설기술과 관리 운영의발전 향상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1986-08-05",
    name: "(사)토우회",
    purpose: "전 한국토지공사 임직원 상호간 친목과 유대를 견고히 하고 동공사 발전 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1987-02-13",
    name: "(사)교우회",
    purpose: "회원 복지증진 및 친목도모와 교통정책 등 교통행정 조사연구 지원",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1987-09-17",
    name: "(사)전국보일러설비협회",
    purpose: "주택난방사업에 대한 건의, 제도조사",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1988-05-04",
    name: "(사)한국도시행정학회",
    purpose: "도시행정학의 이론적 연구를 통해   도시행정학 발전 도모, 도시개발 등에 대한 연구활동을 통해 국가발전 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1989-07-20",
    name: "(사)전국아파트연합회",
    purpose: "공동주택의 효율적인 관리, 입주민의 권익보호",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1990-06-18",
    name: "(사)한국건축물유지관리협회",
    purpose: "건축물유지관리 용역업에 관한 관련 제도나 각종 시책의 개선 및 전물기술의 향상을 통해 회원의 권익옹호와 친목 및 정보교환으로 상호이익을 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1990-09-04",
    name: "(사)한국건축내화협회",
    purpose: "내화구조, 재료의 품질 관련기술의 향상을 위한 조사연구 개발",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1991-01-09",
    name: "(재)한국건설안전기술원",
    purpose: "건설구조물의 축조․안전유지에 관한 특성과 보강에 대한 연구개발 및 자연재해를 예방하기 위하여 재해영향에 관련되는 업무, 그리고 건설공사로 인한 소음․진동 등의 환경영향평가와 문화재의 안전한 보존과 유지.보수에 관한 안전진단 및 설계와 각종 설비의 안전진단을 하여 건설안전 및 사회 발전에 기여",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1991-01-14",
    name: "(사)항우회",
    purpose: "회원복리증진 및 회원상호간의 친목도모, 공항관리에 관한 조사연구ㆍ지원",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1991-10-01",
    name: "(사)한국철도시설협회",
    purpose: "철도시설(건축, 신호, 통신, 전기시설 제외)의 신설, 개량 및 유지관리에 관한 기술의 연구개발, 철도기술정보의 보급, 철도기술인력의 양성 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1992-05-14",
    name: "(사)한국주택학회",
    purpose: "주택이론 및 정책분야연구 및 회원 상호간 친목도모, 지식정보 교환",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1959-12-13",
    name: "한국국제물류주선업협회",
    purpose: "국제물류주선업 통계 작성, 업무자료 발간, 경영자 및 종사원의 교육훈련, 국제관련단체 정보교환 및 협력증진, 국제물류학원 운영사업",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1993-01-11",
    name: "(사)한국경량기포콘크리트협회",
    purpose: "경량기포콘크리트의 보급 및 확대, 공업화건축에 의한 건축문화의 창달",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1993.01.19",
    name: "(사)한국지하공간협회",
    purpose: "지하공간 개발 및 활용에 관한 합리적 계획수립과 관련기술의 혁신을  통하여 건전하고 효율적인 토지이용과 쾌적하고 풍요로운 미래사화 구현에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1993-04-16",
    name: "(재)한국건설품질연구원",
    purpose: "건설자재 및 건설공사의 품질시험ㆍ 검사 기술개발 보급, 부실시공 방지 및 건설기술의 질적발전 도모",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1993-05-20",
    name: "(재)국토정책연구원",
    purpose: "국토정책 기본연구를 통한  국토정책과제 발굴",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1993-07-02",
    name: "(사)한국교통기술사협회",
    purpose: "교통기술사 업무수행능력 개발 증대, 권익보호, 정보교환, 전문교육, 상호친목도모, 회원의 발전, 전반적인 교통기술인력육성 및 교통분야 발전기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1993-10-13",
    name: "(사)한국건설정책연구원",
    purpose: "건설관련 제분야에 관한 조사ㆍ연구",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1994-01-21",
    name: "(사)한국건축물관리연합회",
    purpose: "효율적 건축물 관리를 위하여 일관성 있는 업무체계의 확립",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1994-03-30",
    name: "(사)한국철도물류협회",
    purpose: "철도화주와 수송업체간 건전한 발전과 철도수송의 효율도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1994-10-01",
    name: "(사)한국도시연구소",
    purpose: "도시지역 토지, 주택, 산업문제 등에 대한 연구와 정책대안을 개발하여   발전적ㆍ미래지향적 도시생활환경조성",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1994-11-14",
    name: "(재)한국플랜트건설연구원",
    purpose: "플랜트산업설비 설계ㆍ시공ㆍ안전관리 조사연구",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1994-12-14",
    name: "(재)주택산업연구원",
    purpose: "주택산업분야에 대한 체계적인 연구로 주택산업의 건전한 육성과 국민주거 복지수준 향상 및 국가경제발전 기여",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1994-12-14",
    name: "(재)한국건설산업연구원",
    purpose: "건설정책 및 제도에 관한 연구",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1995-02-17",
    name: "(사)한국항공우주의학협회",
    purpose: "항공우주의학단체와의 교류 및 항공우주의학 발전",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1995-02-23",
    name: "(사)한국항공정책연구소",
    purpose: "선진국 항공정책자료 수집 및 연구, 항공정책에 관한 강연회, 세미나 개최",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1995-05-23",
    name: "(사)한국교통장애인협회",
    purpose: "교통사고 예방활동을 통하여 교통사고로 인한 장애인 발생을 방지하고, 교통장애인의 사회참여를 유도하며 의료재활, 직업재활, 스포츠재활사업을 통한 건전한 삶을 영위케 하는데 기여함을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1995-08-04",
    name: "(사)미래건설연구소",
    purpose: "건설산업 관련 공공투자에 관한 연구",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1995-08-04",
    name: "(재)한국건설구조안전연구원",
    purpose: "구조물의 안전점검과 안전진단, 유지관리 및 보수보강방법연구 등",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1995-09-26",
    name: "(사)건설기계안전기술연구원",
    purpose: "건설기계 안전관리에 관한 자료의 수집, 조사, 통계, 분석, 교육 및 건설기계안전 및 기술에 관한 상담, 자문, 자료공유를 통한 건설기계 종사자 및 관련자의 인명과 재산을 보호",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1995-10-21",
    name: "(재)건설산업교육원",
    purpose: "건설산업의 국제화, 개방화 추세에 따른 건설전문교육 및 산업교육을 통한 기술인력의 수준 향상, 의식개혁과 산업체의 전문기술력 향상을 도모함으로써 국가산업발전에 기여함",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1995-10-21",
    name: "(사)한국조경학회",
    purpose: "조경분야의 발전을 위한 제반연구와 회원들의 지위향상 및 친목 도모를 목적으로 함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1996-06-20",
    name: "(사)한국도시계획기술사협회",
    purpose: "도시계획 기술의 연구발전과 정보교환을 통하여 도시계획실무자의 도시계획 업무수행능력을 개발 증대하고 회원의 기술향상은 물론 상호친목을 도모함으로써 국가발전과 생활환경개선에 공헌",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1996-11-22",
    name: "(사)한국파렛트컨테이너협회",
    purpose: "표준파렛트 및 컨테이너의 보급촉진, 품질향상 등 파렛트ㆍ컨테이너 산업분야의 발전을 도모하며, 물류합리화와 물류비 절감, 친환경물류 및 친환경 사업에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1996-12-30",
    name: "(사)한국지진공학회",
    purpose: "지진공학분야 학술과 지진재해방지  대책 및 기술의 발전도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1997-04-03",
    name: "(사)한국철도민자역사협회",
    purpose: "민자역사 사업의 효율적 지원 및 건전한 발전, 회원사간 친목과 공동이익 증진,  철도 선진화 및 국민경제의 향상 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1997-05-03",
    name: "(사)한국항공우주기술협회",
    purpose: "항공기술훈련 및 양성과 이에 관한 지도ㆍ자문 및 항공기술 분야에 관한 조사연구",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1997-07-23",
    name: "(사)한국지역발전연구원",
    purpose: "지역개발에 관한 연구를 통해 학문적 이론 발전 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1997-09-27",
    name: "(사)개발제한구역주민협회",
    purpose: "개발제한구역내 토지 친환경적 이용과 주민생활 환경 개선",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1997-09-30",
    name: "(사)한국미래물류연구원",
    purpose: "물류정책 및 기술개발 연구, 물류관련 학술발표, 강연회 개최",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1997-10-07",
    name: "(사)대한건설단체총연합회",
    purpose: "건설업계 공통사항에 관한 관계단체의 의견조정",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1997-12-24",
    name: "(사)한국항행학회",
    purpose: "본 학회는 항행 (Navigation)과 그 관련 분야에 대한 학술 활동을 통하여 항행 과학에 대한 이론적 체계화 및 보편화를 통하여 항행 분야의 발전은 물론 이를 통하여 국가의 발전과 국제 협력 증진을 위함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1998-04-21",
    name: "(사)경실련도시개혁센터",
    purpose: "바람직한 도시사회 건설을 위해 선도적 방안 제시, 친환경적이며 시민의 삶의 질이 우선시되는 도시만들기 운동 전개",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1998-05-20",
    name: "(사)한국설비기술협회",
    purpose: "공기조화, 냉동, 위생설비, 에너지 및 환경과 관련된 설비분야 기술연구개발",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1998-08-18",
    name: "(사)한국철도운전기술협회",
    purpose: "철도운행안전 및 철도운전기술의 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1998-11-14",
    name: "(사)한국항공운항학회",
    purpose: "항공운항학 정립 및 연구학술활동",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1998-12-16",
    name: "(사)국제부동산정책학회",
    purpose: "국제적 학술교류와 학문연구 활동을 통해 부동산학 이론을 체계화하고 국가 및 공공기관에 자료를 제공하여 부동산정책 개발에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1999-02-00",
    name: "(사)한국주택관리협회",
    purpose: "회원사의 균형발전을 위한 대책 수립 및 대정부건의, 공동주택 관리 제법규 개선보완 및 정책건의, 주택관리업자 관리소장 및 종사자 직무교육 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1999-03-29",
    name: "(사)한국건설경영진단협회",
    purpose: "건설업체 경영진단 방법의 개선ㆍ연구",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1999-05-29",
    name: "(사)한국도로학회",
    purpose: "각종 도로ㆍ공항의 설계, 시공, 유지관리에 관한 학문과 기술, 도로시설물 등 개발",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1999-05-31",
    name: "(사)한국건설교통신기술협회",
    purpose: "신기술을 확대보급하기 위한 조연연구 및 신기술 발전",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1999-07-08",
    name: "(사)한국실내조경협회",
    purpose: "실내조경분야 학술 및 기술발전 도모, 친환경적 실내환경 창출, 회원 친목도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1999-09-14",
    name: "(사)한국토지공법학회",
    purpose: "토지공법학 및 이에 관련된 학술의 조사ㆍ연구ㆍ발표 및 보급, 회원상호간 협력 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1999-09-14",
    name: "(사)한국부동산분석학회",
    purpose: "부동산학의 연구와 전파를 통하여  부동산학의 발전을 촉진하고 회원의 지위향상 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1999-10-09",
    name: "(사)한국건물행정기술관리협회",
    purpose: "건물관리기법, 관리이론, 관리기술 등 학문적 연구개발 및 건물관리 기술 체계화, 현대화 보급",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1999-12-02",
    name: "(사)한국민간항공조종사협회",
    purpose: "비행정보 제공, 학술연구 및 항공관련 국제기구 등과 정보교류",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-01-19",
    name: "(사)한국건설관리학회",
    purpose: "건설관리에 관한 학문과 기술의 발전과 보급에 기여함을 목적, 건설관리 분야의 체계적인 지식 기반의 구축및 보급, 산.학.연 협동 연구개발을 총란 건설사업관리의 효율성 제고, 전문 기술 경험 지식 정보의 교율와 교육을 통한 건설관리 분야의 저변확대, 국가간 기술 교류를 위한 국제적인 협력체계 구축",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-04-25",
    name: "(사)한국주거학회",
    purpose: "주거학의 학술적 이론과 그 응용방법 및 연구를 통한 학문발전과 주거문화향상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-05-08",
    name: "(사)한국부동산정책학회",
    purpose: "부동산정책이론과 실제에 관한 체계적 연구 및 발표, 강연회ㆍ학술토론회 개최, 국제학술 교류, 연구용역사업",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-06-05",
    name: "(사)한국GIS산업협회",
    purpose: "공간정보의 발전",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-06-20",
    name: "(사)한국풍공학회",
    purpose: "풍공학에 관한 학문과 기술의 발전ㆍ 보급 기여로써 과학기술진흥에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-07-29",
    name: "(사)한국지도학회",
    purpose: "지도학, 측지학, 지리학, 지리정보학 등 지도관련 학문에 관한 연구와 지도제작기술의 발전을 촉진하고, 회원 상호간의 친목을 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-10-18",
    name: "(사)한국자동제어건설협회",
    purpose: "자동제어공사에 관한 정보전달과 제도개선",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-10-23",
    name: "(사)건설원가협회",
    purpose: "건설원가계산업무의 학문적 연구와 전문분야 교류, 자체교육을 통한 전문성과 생산성 향상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-12-06",
    name: "(사)한국도시설계학회",
    purpose: "도시설계 및 관련분야의 발전과 동  분야 종사자의 전문가적 자질을 향상하여 도시발전 및 도시문화창달 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2001-03-17",
    name: "(사)한국감정평가학회",
    purpose: "학문연구와 실무활동을 통해 감정  평가이론 체계화, 국가ㆍ공공기관에   자료제공으로 부동산정책 개발 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2001-05-24",
    name: "(재)한국부동산연구원",
    purpose: "감정평가 및 부동산 관련분야에 관한 체계적ㆍ전문적 조사ㆍ연구, 감정평가업과 부동산업 육성발전 및 국가경제발전 기여",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2001-05-26",
    name: "(사)대한건설적산협회",
    purpose: "건설적산업무 및 건설비용관리 개선과 발전으로 건설적산기술자 기술적 수준향상 및 연구개발과 기술을 발전, 보급, 응용하여 건설생산의 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2001-09-05",
    name: "(사)한국리모델링협회",
    purpose: "1. 리모델링에 관한 법령제도 및 시책의 조사연구와 제도개선 건의2. 리모델링의 진흥 및 경영합리화에 관한 조사연구와 지도3. 리모델링 시공기술의 향상에 관한 조사연구 및 지도4. 리모델링에 관한 조사통계 및 각종 정보의 수집ㆍ개발ㆍ보급5. 리모델링에 관한 대국민 홍보6. 회원의 지도ㆍ안내ㆍ추천ㆍ알선 및 인증7. 리모델링 관련 국제기구 및 외국단체와의 제휴ㆍ연락과 국제협력 증진 8. 리모델링에 관한 국내외 정보자료의 수집ㆍ교환과 외국 리모델링에 관한 조사연구 9. 리모델링 전문인력의 양성 등 리모델링 진흥을 위한 자격검정사업10. 리모델링에 관한 연구개발 사업 및 교육사업 전담 조직의 설치 및 운영11. 우수 리모델링 사례 발굴 및 시상12. 기타 회원의 복리증진과 리모델링의 발전을 위하여 필요한 사업",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2001-09-05",
    name: "(사)한국건축시공학회",
    purpose: "건축물의 생산, 시공ㆍ재료 관리유지관리에 관한 학문과 기술의 발전 보급",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2002-01-14",
    name: "(사)항공우주정책연구원",
    purpose: "항공안전정책 및 제도, 항공우주산업 발전방안 연구 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2002-04-01",
    name: "(사)대한교통학회",
    purpose: "교통에 관한 학문과 기술을 연구ㆍ응용하여 교통의 경제, 계획, 경영, 행정 및 정책분야의 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2002-04-03",
    name: "(사)한국지능형스마트건축물협회",
    purpose: "최적의 지능형스마트건축물을 구축 하는데 필요한 학술적, 기술적, 정책적 토대를 마련하고 지속적으로 연구 발전시켜 나가기 위해 설립",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2002-04-29",
    name: "(사)국토지리학회",
    purpose: "지리학 조사ㆍ연구, 지리교육과정 연구",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2002-05-23",
    name: "(사)한국목조건축기술협회",
    purpose: "목조건축업 관련제도 및 건축경제시책 개선과 목조건축기술의 향상",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2002-10-19",
    name: "(사)전국교통단체총연합회",
    purpose: "교통시책의 효율적 시행과 교통산업의 건전한 발전 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2002-12-11",
    name: "(사)한국공간구조학회",
    purpose: "쉘 및 대공간구조의 학문적 연구와 설계, 시공, 유지관리 기술개발",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2003-01-18",
    name: "(사)부동산투자분석전문가협회",
    purpose: "부동산시장정보 및 부동산투자분석과 관련한 이론 및 연구 사업 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2003-02-20",
    name: "(사)주거환경연구원",
    purpose: "도시 및 주거환경정비사업의 쳬계적 연구ㆍ정책대안 개발, 발전적ㆍ미래지향적 도시 및 주거환경을 조성",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2003-02-24",
    name: "(사)한국자동차진단보증협회",
    purpose: "중고자동차 진단ㆍ성능점검 및 보증",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2003-07-24",
    name: "(사)건설원가연구원",
    purpose: "건설업간 협력방안, 하도급체계 개선방안 연구 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2003-09-24",
    name: "(사)서민주거복지포럼",
    purpose: "서민주택정책을 개발하고 서민주거 복지의 최적화에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2003-09-29",
    name: "(사)한국플랜트정보기술협회",
    purpose: "산업설비 기술정보시스템 구축 및 운영",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2003-11-12",
    name: "(사)한국건설문화원",
    purpose: "참 건설문화를 창출하기 위한 연구활동 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2003-12-29",
    name: "(사)한국공간환경학회",
    purpose: "공간환경에 관한 이론 및 정책분야의 연구와 실천적 대안모색을 통한 사회 발전 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2003-12-26",
    name: "(사)전국자동차경매장협회",
    purpose: "자동차경매장 사업의 균형 발전을 도모하고, 자동차경매장에 관한 조사, 연구와 기술을 개발하여 자동차경매장의 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-01-08",
    name: "(사)한국주거환경학회",
    purpose: "주거환경에 관한 연구, 산학협동,연구교류, 국제협력으로 주거생활 개선",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-01-13",
    name: "(사)한국철도건축기술협회",
    purpose: "철도건축기술 조사연구, 지식의 보급 및 향상 도모와 사회공공의 복지 증진",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-01-29",
    name: "(사)전국아파트문화연구원",
    purpose: "아파트공동체 문화창달을 위한 연구회 운영 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-02-03",
    name: "(사)전국화물자동차운송차주협회",
    purpose: "운송차주의 권리보호와 사회적 지위 향상을 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-04-21",
    name: "(사)한국환경건축연구원",
    purpose: "국가의 친환경 건설 산업 발전 시책에 협력하여 친환경·건강 건축기술의 연구개발 및 보급업무, 국민의 삶의 질 향상과 복지증진의 도모 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-05-31",
    name: "(사)한국항공경영학회",
    purpose: "항공경영에 관한 연구 및 연구개발,  항공사 경영ㆍ항공안전 및 보안ㆍ공항관리 등에 대한 자문 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-05-31",
    name: "(사)인항회",
    purpose: "공항건설ㆍ운영에 관한 조사연구,  회원 복지증진, 회원자녀 장학사업 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-08-06",
    name: "(사)한국철도정보통신기술협회",
    purpose: "철도정보통신기술조사연구",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-08-06",
    name: "(사)새로운문화를실천하는건축사협의회(KAI)",
    purpose: "개인 건축사(등록, 미등록, 외국면허소지)들의 이해를 수렴하며, 건축사업무제반 여건 개선 및 국제 상황에 능동적으로 대처하고, 건축의 사회적 위상제고를 위한 전문성, 윤리성, 사회성, 공공성을 바탕으로 건축문화 및 보다나은 도시환경 발전과 지속적인 연구의 실천을 통하여 기여함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-08-16",
    name: "(사)한국지역사회발전학회",
    purpose: "1. 지역사회발전 이론정책 기법 연구2.산학협동 연구교류, 국제간의 협력, 학술연구용역 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-10-14",
    name: "(사)한국도시철도협회(구 (사)한국신교통협회)",
    purpose: "도시철도사업의 진흥을 위한 각종 자료의 발간 및 보급, 회원사 공동이익 증진",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-12-01",
    name: "(사)한국층간차음협회",
    purpose: "층간차음제도 및 시공기술개발 지원",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-12-01",
    name: "(사)한국음향재료협회",
    purpose: "음향재료의 성능향상 및 쾌적음환경 발전",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2005-09-06",
    name: "(사)한국철도운수협회",
    purpose: "철도교통 활성화를 위한 사업 및 철도공사사업과 후생복지를 위한 기금조성",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-12-27",
    name: "(사)한국철도경영개발연구협력회",
    purpose: "철도경영개선 조사연구, 철도경영 및 관리분야 자문 및 협력사업 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-12-30",
    name: "(사)사람의도시연구소",
    purpose: "사회적 약자(장애인, 노인, 어린이 등) 배려한 사람중심의 지속가능한 도시정책수립 및 도시조성 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2005-02-05",
    name: "(사)한국건축학교육인증원",
    purpose: "1. 건축학 전문학위 교육과정을 위한 교과기준과 교육지침을 제시하고 이를 통해 인증 및 자문을 시행2. 건축학교육의 발전과 건축의 사회적 역할에 대한 이해를 높임3. 건축사가 되기 위한 기초지식과 함께 실력을 갖춘 건축학인력을 배출4. 건축학교육의 국가 간 상호인정을 위한 제반여건을 조성함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2005-04-27",
    name: "(사)한국건설품질협회",
    purpose: "건설품질관리 기술개발, 도서 보급,  연구용역 및 수탁 및  건설품질경영  시스템 개발",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2005-05-20",
    name: "(사)전국아파트입주자대표회의연합회",
    purpose: "법령에 따라 공동주택 입주자대표회의에서 수행하여야 할 사항을 효율적으로 지원을 함으로써 입주자의 권익을 보호하고, 공동주택의 쾌적한 주거환경 조성과 입주자등 상호간의 친목도모 및 공동체 운동의 활성화를 통해 입주자등의 삶의 질 향상시켜 국가 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2005-07-08",
    name: "(사)한국건강주택협회",
    purpose: "주거환경 및 건강주택 관련 제도등의 연구 및 자문",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2005-08-15",
    name: "(사)대중교통포럼",
    purpose: "대중교통분야에서 산·학·연·관과의 상호 정보교류 및 협동을 도모하여 국가발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2005-09-29",
    name: "(사)철도복합환승센터 포럼",
    purpose: "철도분야 국내외 정책 및 기술 연구ㆍ자문ㆍ홍보ㆍ교육 및 철도분야 상호 정보교류 및 산학 협동",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2005-10-19",
    name: "(사)한국건물관리학회",
    purpose: "건축관리의 경제화, 안전화, 효율화를 위한 학문연구",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2005-11-25",
    name: "(사)건설기술정책연구원",
    purpose: "건설업 관련제도·정책, 혁신기술 개발과 건설산업의 선진화 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-01-06",
    name: "(사)한국철도건설협회",
    purpose: "철도건설 계획, 설계, 시공, 경영, 정책에 관한 조사연구 보급 및 철도 건설장비와 신소재 개발 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-03-22",
    name: "(사)한국고속도로휴게시설협회",
    purpose: "업계의 진흥발전을 위한 제반사항, 휴게시설 이용고객의 편의증진을 위한 개발연구업무",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-05-04",
    name: "(사)동북아기반시설협회",
    purpose: "동북아지역 사회기반시설에 관한 제도, 정책, 법령, 기술의 조사ㆍ연구",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-06-22",
    name: "(사)한국자동차기술인협회",
    purpose: "자동차 정비ㆍ점검 검사, 교육등에 종사하는 품위유지 및 복리증진 및 복리증진과 자동차관련 정보관련",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-06-23",
    name: "(사)한국도시경영관리연구원",
    purpose: "도시경영관리이론ㆍ외국사례 등 종합ㆍ분석, 발전적ㆍ미래지향적 도시경영 및 관리기법 체계화, 전문가 양성 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-07-27",
    name: "(사)한국삭도협회",
    purpose: "회원사의 공동이익 증진과 경영 및 삭도시설의 안전과 기술에 관한 정보교류를 통하여 삭도사업의 효율적인 운영을 기하고 국가 삭도사업 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-08-17",
    name: "(재)한국건설산업품질연구원",
    purpose: "건설기술 연구개발로 건설기술 향상, 국내외 건설과련기관과의 기술정보   교류, 전문기술분야의 세미나 개최 등",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-08-18",
    name: "(사)한국독도법협회",
    purpose: "독도법 보급을 통한 등산사고 예방 및 자연사랑, 삶의 질 향상, 정확하고 사용이 편리한 지도제작에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-08-25",
    name: "(사)한국건설경영협회",
    purpose: "건설산업 각 부문의 협력을 통하여 국제경쟁력 강화, 선진건설문화정착, 국가경제발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-09-11",
    name: "(사)한국교통정책ㆍ경제학회",
    purpose: "교통정책 및 교통경제 분야에 관한 학술연구 및 회원상호간의 학술교류를 통해 학문발전과 국가발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-09-18",
    name: "(사)한국복합화피씨기술협회",
    purpose: "복합화피씨 건축시스템에 관한 조사연구를 하고, 건축시스템의 복합화피씨 기술 향상 및 보급에 노력하며, 국제협력을 도모하여 건축기술의 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-09-26",
    name: "(사)건설주택포럼",
    purpose: "주택관련 제도등의 연구와 개선 추구, 공공복리증진과 주거문화향상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-11-08",
    name: "(사)사회갈등연구소",
    purpose: "건설교통을 비롯한 공역개발사업과 관련한 갈등에 대한 체계적 연구와 공공분야으 갈등해결 역량을 강화하고, 국민참여 기회를 확대",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-12-01",
    name: "(재)국토환경재단",
    purpose: "개발제한구역 현황분석 및 연구조사, 개발제한구역 홍보 및 교육, 개발제한구역 정책·제도개선 연구 및 컨설팅 활동, 환경 캠페인, 기업 환경공헌 프로그램 전개 등",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-12-20",
    name: "(사)항공우주시스템공학회",
    purpose: "항공우주시스템 관련분야에 대한 연구활동, 항공기운용기술개발 및 항공우주정책개발을 통한 항공우주산업발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-12-28",
    name: "(사한국자동차모빌리티안전학회",
    purpose: "자동차 안전에 관한 학술과 기술의 발전, 정책수립, 산업지원 및 기준의 국제화를 통하여 산업발전과 안전문화 정착에 기여함을 목적으로 설립",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-12-27",
    name: "(사)주거권실현을 위한 국민연합",
    purpose: "서민들의 주거권 문제와 생존권 문제를 자주적으로 극복하고, 주거복지정책 개발과 사업을 통해 살기좋은 희망마을을 만들어 국민주거복지 향상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-12-29",
    name: "(재)건설경제발전연구원",
    purpose: "건설산업, 건설경제, 지역사회의 건설 관련분야 전반에 관한 사항을 체계적으로 연구조사함으로써 사회발전 및 국가경제발전에 공헌",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2007-01-12",
    name: "(사)미래도시포럼",
    purpose: "도시의 계획, 경영, 문화, 산업에 대한 전문가들의 참여를 통한 학술조사 및 연구를 진행하고, 회원들간의 상호교류, 국내외 전문가들과의 학술교류, 전문가 육성 및 인재양성을 통하여 도시발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2007-01-17",
    name: "(사)한국토지법학회",
    purpose: "토지법학의 정립과 발전 및 부동산정책에 관한 연구",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2007-02-09",
    name: "(사)한국환경조경자재산업협회",
    purpose: "건설부문중 보다 환경 친화적이고 안전하며 건축물과 공간을 아름답게 완성시킬 수 있는 조경자재와 공법에 대한 학술연구와 정보교환 등을 통하여 우수 조경자재의 홍보 및 지원하여 한국의 환경조경자재산업 발전에 기여함으로써 국가 발전에 이바지함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2007-03-07",
    name: "(재)한국건설연구소",
    purpose: "건설산업 분야 전반에 관한 사항을 체계적으로 연구, 조사함으로써 국민경제 및 국가경제 발전에 공헌",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2007-03-23",
    name: "(사)한국씨피엠협회",
    purpose: "부동산자산관리자(CPM)들의  자질향상과 저변확대 및 선진부동산관리기법을 국내에 전파하여 한국부동산시장의 선진화 및 전문화를 도모하고, 건전한 부동산관리문화의 정착에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2007-06-20",
    name: "(사)한국길포럼",
    purpose: "길을 사랑하고 도로 및 교통분야에 관심있는 사람과 전문가가 함께하는 오피니언 리더그룹의 역학을 담당하고 주요현안에 대한 의견수렴, 국제흐름 파악 및 선진국 정책 벤치마킹을 통하여 미래의 길에 대한 비전 및 정책방향을 제시",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2007-08-07",
    name: "(사)한국건축친환경설비학회",
    purpose: "한국공학교육인증원의 건축공학교육 인증에 따른 건축환경 및 설비분야의 열, 빛, 음, 공기에 대한 건축환경과 건축설비 분야의 학문연굴르 통하여 건축환경 및 건축설비 분야의 교육발전을 추구함으로써 친환경, 설비분야 관련 기술의 개발과 관련인의 지위 향상 및 사회에 공헌",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2007-12-20",
    name: "(재)주거복지재단",
    purpose: "쪽방거주자 등 도시저소득 국민의 주거안정을 도모하고 주거복지 향상에 기여",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2007-12-31",
    name: "(사)한국토지보상관리사협회",
    purpose: "보상관계 법령 연구 및 보상사례 수집발간함으로써 실무능력 향상 및 우리나라 보상업무 수준을 국제수준으로 향상",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2008-01-09",
    name: "(사)국제온돌학회",
    purpose: "민족 고유의 바닥 난방기술인 온돌의 과학적·문화적 가치와 그 기술을 계승 발전시켜 에너지의 효율적 이용과 인류의 주거환경 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2008-01-30",
    name: "(사)한국지역지리학회",
    purpose: "지역의 발전을 위한 자연.인문.환경 및 지역 관련정책에 관한 조사 및 연구활동, 국내 및 국제 할술발표회의 개최 및 지역현장 학술조사 및 답사, 학회지와 회보 및 연구간행물 발간, 국내외 유관학회 및 연구단체와의 교류 및 현력, 국내외 지역연구 진흥을 위한 제빈사업 및 기타 본회의목적에 적합한 사업",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2008-04-28",
    name: "(재)한국건설전략연구원",
    purpose: "국내 건설경제 제분야에 관한 연구수행과 각 건설주체들에 대한 합리적이고 체계적인 연구지원으로 건설주체들의 수준향상 및 기술발전, 보급과 건설사업지원 연구를 통해 건설경제발전 및 국민경제발전에 이바지함",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2008-05-23",
    name: "(사)건설문화연대",
    purpose: "참다운 건설문화 실현과 건설재해 유자녀 지원, 콘크리트박물관 건립 등 선진 건설문화의 보급과 대중화에 앞장서고, 나아가 건설현장 환경개선과 건설인 권익향상을 위한 정책 및 제도 개선으로 건설산업의 질적향상과 지속적인 발전을 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2008-05-26",
    name: "(사)임대주택사업협회",
    purpose: "임대주택 법령 및 정책,제도 등의 개선을 추구하여 임대주택사업의 건전한 발전과 국민주거생활 향상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2008-05-31",
    name: "(사)한국이륜자동차산업협회",
    purpose: "국내 이륜차 교통문화의 건전한 발전을 위하여 이륜자의 생산과 사용신고에서부터 폐차까지 관리절차 전반에 대한 개선활동에 참여하고 소비자 보호와 올바른 이륜차 운행문화 정착을 위해 각종 관련 사업전개를 추진하며 정부의이륜차관련정책 입안과 집행에 적극적으로 협조 및 참여함으로서 이륜자 관리제도와 산업의 발전 및 이륜자 건전문화 확립을 통해 교통안전 향상에 기여하며 회원사 상호간 의 친목도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2008-06-25",
    name: "(사)글로벌부동산연구원",
    purpose: "국제적인 부동산금융 관련 제도의 연구, 개발 및 교육을 통해 국내 부동산 금융시장의 전문화 및 선진화 방안을 제안함으로서 부동산시장의 발전에 기영함을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1997-03-14",
    name: "(사)한국구조물진단유지관리공학회",
    purpose: "시설물의 진단과 안정성 평가, 유지관리 및 보수, 보강에 관한 학문과 기술 연구",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2008-10-01",
    name: "(사)한국도시재생연구원",
    purpose: "도시개발전략 및 계획요소 연구, 미래재생도시을 통한 도시계획 및 설계수법 도입,신재생에너지 기술개발, 새로운 파트너쉽의 정책모델을 개발, 교육",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2008-11-25",
    name: "(재)한국철도문화재단",
    purpose: "철도에 대한 국민의 이해와 지식수준을 높이고 철도문화 창달과 철도관련 지식과 자료를 사회전반에 널리 이용 보급",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2008-12-31",
    name: "(사)국토교육협의회",
    purpose: "국토교육을 보다 효율적으로 실시하기 위하여 단체 및 기관관의 협의 조정하고 상호간의 협력증진 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-01-30",
    name: "(사)장애물없는생활환경시민연대",
    purpose: "본 법인은 건축물, 교통수단, 겨객시설, 도로 등의 물리적 장벽과 장애인, 고령자, 임산부, 어린이 등 교통약자에 대한 사회적 편견이 제거될 수 있도록 조사 연구, 정책건의 및 자문, 홍보 등을 통해 무장애도시, 무장애 교통을 실현하고자 함.",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-02-20",
    name: "(사)빌딩스마트협회",
    purpose: "- 비영리법인으로서 한국 AEC/FM 분야에서 BIM 및 첨단 IT의 연구, 보급 및 적용 촉진- 국제비영리 단체인 buildingSMART International에서 정하여 국제표준이 된 IFC, IFD, IDM, MVD 등 buildingSMART 공개표준의 개발 및 확산 활동을 수행함으로써 해당 산업의 발전과 공공복리 향상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1969-05-22",
    name: "(사)국가유공자 전국철도공상회",
    purpose: "국토교통부 및 철도청 공상자 상호간의 친목과 평생동지애로 상부상조함으로서 회원의 자활능력을 배양하고 국가유공자의 긍지를 가지고 철도발전에 봉사하며 국내외 원호단체와 제휴로서 회의 국제적 지위를 향상시키고 회원의 권리와 복리증진으로 삶의 질을 향상시키는데 기여함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-03-27",
    name: "(사)한국물류산업정책연구원",
    purpose: "선진물류제도의 정착을 위해 관계법령 및 물류정책의 연구와 물류전문가 양성을 위한 교육 등을 통해 물류정책발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-04-17",
    name: "(사)한국부동산개발전문가협회",
    purpose: "부동산개발업무에 관한 각종 이론 및 실무연구를 통해 국내부동산개발산업의 발전 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2005-10-13",
    name: "(사)한국경관학회",
    purpose: "경관분야 조사ㆍ연구활동, 국내외  유관학회ㆍ단체와 교류협력, 국토 경관보존과 형성에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-04-27",
    name: "(사)한국주거복지협회",
    purpose: "주거복지센터 설립을 위한 컨설팅 및 주거복지센터 운영 지원, 주거복지 전문가 양성을 위한 교육, 주거복지 정책 건의 등을 통행 주거,목지,고용이 안정된 사회 구현",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-05-27",
    name: "(사)대한방화문협회",
    purpose: "방화문 업계의 품위 유지 및 상호 협력 강화를 통한 회원 권익 증진, 방화문 관련 제도 개선 및 방화문 기술향상 추진으로 방화문 업계의 건전한 육성 발전 이룩",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-06-29",
    name: "(재)국토교통연구인프라운영원",
    purpose: "국토교통분야 공동활용 연구시설 및 장비의 구축․운영․관리․공동활용 촉진 등에 관한 업무 수행",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-07-14",
    name: "(사)한국부동산산업학회",
    purpose: "국민경제에 지대한 영향을 미치는 부동산산업이 긍정적이고 신뢰받을 수 있는 위상을 갖출 수 있도록 학계와 산업계가 공동으로 연구와 홍보를 통하여 이론과 실무지식을 개발, 보급함으로써 국민경제와 부동산산업의 발전에 이바지하는 동시에 회원 상호간의 협력과 성장을 도모함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-07-16",
    name: "(사)주거환경연합",
    purpose: "도시 및 주거환경에 대한 정책적 대안 제시 등 살기 좋은 주민공동체 실현",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-10-15",
    name: "한국도시부동산학회",
    purpose: "도시권의 경쟁력 강화를 위하여 도시계획, 도시교통, 도시개발, 도시행정, 도시환경 및 기타 도시 관련 학제간의 다양한 연구 활동을 통한 도시정책분야의 발전을 도모함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-07-31",
    name: "(사)한국회전익항공기사용사업협회",
    purpose: "국내 회전익 항공기 사용사업의 건전한 발전을 촉진하고 회원의 사회적 경제적인 지위향상과 상호간의 친목을 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-09-09",
    name: "(사)미래융합건설연구원",
    purpose: "건설기술 분야의 연구조사를 수행하고, 정부의 건설기술정책의 방향설정을 위한 기초자료 등을 제시함으로써 기업생산성 향상을 도모하여 국가건설기술의 균형적 발전과 위기관리능력 향상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-11-06",
    name: "(사)도시경영포럼",
    purpose: "도시환경의 특성과 지역문화적 요소를 반영하여 인간이 행복한 도시, 시민의 삶의 가치를 높이는 인간중심의 미래도시(K-City) 개발 및 구현을 위하여 산·학·연·관·민· 전문가들의 역량을 모아 미래도시개발 산업의 육성, 국내외 K-City 보급확산을 통한 국가경쟁력 향상 및 세계시민의 행복도 제고에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2003-12-05",
    name: "(사)한옥문화원",
    purpose: "한옥과 우리 문화의올바른 이해와 저변확대를 목적으로 한다.",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1997-12-19",
    name: "(재)영남건설기술교육원",
    purpose: "건설기술자 교육",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-12-09",
    name: "(사)서울부동산포럼",
    purpose: "회원의 지식과 경험을 공유·확산시킴으로써 부동산산업의 발전을 도모하며, 부동산 오피니언 리더 그룹으로서 정부정책에 조언과 부동산시장에서 선도적 역할을 통해 국가경제 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-12-14",
    name: "(사)한국지적정보학회",
    purpose: "지적 및 관련 학문에 관한 학술적 연구를 체계화함으로써 지적제도와 국가지리정보체계 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-12-24",
    name: "(사)건설경제연구원",
    purpose: "건설산업 선진화 및 정책적 제언을 통한 건설경제발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-01-15",
    name: "(사)한국항공교통관제사협회",
    purpose: "회원 상호간 친목도모, 항공교통관제 안전향상 방안 연구 및 국제연합관제사협회와의 교류확대 등으로 항공교통관제분야의 건전한 발전 촉진",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-02-04",
    name: "(사)항행안전기술협회",
    purpose: "민간차원의 차세대 항행안전시설 조사연구, 최신정보 공유 및 회원간 친목 도모 등으로 항공안전 및 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-02-05",
    name: "(사)한국자전거정책연합",
    purpose: "자전거에 관한 전문적인 지식과 기술을 활용하여 자전거이용의 활성화, 자전거산업의 진흥, 자전거에 관한 문화·교육·스포츠의 지속적이고 균형적인 발전을 도모함으로써 지속가능한 미래사회에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-03-04",
    name: "(사)한국건설경제산업학회",
    purpose: "건설산업과 연관된 경제·경영에 관한 이론 및 산업 정책분야를 연구하고 회원 상호간의 친목도모와 지식정보의 교환",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-11-21",
    name: "(사)전국자동차등록번호판교부대행자협회",
    purpose: "자동차등록번호판 교부대행자의 건전한 육성발전으로 이용객의 편의 증진을 위한 대민서비스 향상과 법령 및 개도개선을 위한 연구노력",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-03-16",
    name: "(사)국토탐방연맹",
    purpose: "우리국토의 발전상에 대한 자료를 수집하고, 국토발전 변천사에 대한 홍보 및 국토탐방 활동을 통하여 균형된 시각과 건전한 가치관을 가진 올바른 국토관 정립",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-03-16",
    name: "(사)국토해양환경보존협회",
    purpose: "국토해양분야 산업의 건전한 발전과 체계적인 연구개발로 국토해양분야의 발전과 진흥에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-04-21",
    name: "(사)한국부동산경영학회",
    purpose: "부동산학 및 부동산산업의 중개·유통·분쟁조정·중개기법개발을 통하여 부동산중개업의 발전을 유도하고, 회원 상호간의 친목도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-05-24",
    name: "(사)토목구조기술사회",
    purpose: "토목구조기술사의 사명과 역할에 관하여 연구 검토하고, 토목구조분야의 기술 및 직무수행능력의 향상을 도모하여 국가 산업기술의 발전과 더불어 건전한 사회 발전, 회원의 기술향상 및 권익신상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2003-05-07",
    name: "(사)한국자동차제작자협회",
    purpose: "자동차제작업의 건전한 발전과 회원 상호간의 권익증진을 도모함으로서 국가경제 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1981-07-16",
    name: "(사)한국측량학회",
    purpose: "측량 관련 학문에 관한 연구 및 측량기술발전 촉진, 측량기술자의 지위향상과 회원 친목 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1997-12-08",
    name: "(사)대한공간정보학회",
    purpose: "공간정보에 관한 학술적인 연구와 기술의 회원 상호간 교류를 통해 공간정보 분야의 학문과 기술 발전에 기여함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2001-09-05",
    name: "(사)주거복지연대",
    purpose: "시민들의 자발적인 국민주거복지의식 확산, 시민, 학자, 전문가, NGO, 정책결정 및 집행기관 등 네트워크를 구축, 편안한 내집ㆍ살기좋은 우리 동네 구현",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-08-10",
    name: "(사)한국부동산자산관리사협회",
    purpose: "부동산자산관리산업의 선진화를 위한 부동산조사와 연구 수행 및 정책대안을 제안하고 부동산자산관리사의 전문적인 자격과 실무능력 검증 및 향상시키며 건전하고 윤리적인 커뮤니티 네트워크를 형성하여 국민들의 올바른 부동산자산관리로 부의 균등화를 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-08-16",
    name: "(사)한국물류산업발전연구회",
    purpose: "물류산업의 국가경쟁력 제고를 위한 연구회 창립으로 물류산업 관련 종사자 및 전문가, 학자 등이 참여, 의제별 연구토론을 거쳐 대안을 제시·홍보함으로써 물류산업의 전반적인 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-08-19",
    name: "(사)새만금유시티포럼",
    purpose: "산·학·연·관·민· 전문가들이 정보 및 역량을 공유하여 새만금지역의 u-City 관련 기술 정책 및 신기술 개발",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1993-09-25",
    name: "(사)한국암반공학회",
    purpose: "회원상호간의 친목을 도모하고 ISRM와 National Group으로서 국제적 교류를 통해 이 분야의 학술연구와 기술발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-11-19",
    name: "(사)희망래일",
    purpose: "우리 옛 영토인 대륙에 대한 관심을 높이고, 대륙과의 인적·물적 교류를 위한 남북철도 및 대륙철도의 중요성 제고",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-11-22",
    name: "(사)한국부동산자산관리학회",
    purpose: "부동산의 효율적 관리를 위한 학문적 이론과 실무적 응용방법을 연구·개발하여 부동산학의 발전과 부동산자산관리(Property Management)업의 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-12-15",
    name: "(사)건설코스트엔지니어링협회",
    purpose: "건설사업 사업비관리(Cost management)에 대한 연구 및 전문인력 양성등을 통해 기술수준 향상 및 건설공사비 투명성 확보에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1992-05-18",
    name: "(사)한국지적학회",
    purpose: "지적학 및 이에 관련된 학술연구 및 발표, 학술연구지 및 기타 도서의 발행, 국내외 관련단체와의 학술교류 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-12-28",
    name: "(사)한국아이티에스(ITS)학회",
    purpose: "ITS와 관련 분야에 대한 학술활동과 기술교류를 국내외적으로 도모하여 국가발전과 국제협력증진에 공헌, 교통, 전자, 통신, 제어 등 ITS와 관련한 학제 간 원활한 상호 정보교류 및 多학제적인 공동연구 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2011-02-21",
    name: "(사)한국교통카드산업협회",
    purpose: "교통카드 관련분야 법령 및 제도 등에 관한 정책 자문 수행, 교통카드산업 분야의 국내외 표준화 지원 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2011-03-21",
    name: "(사)그린리모델링협회",
    purpose: "녹색건설의 대국민 공감대 형성 홍보, 녹색건설 확대를 위한 국내외 정책연구 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1990-06-26",
    name: "(사)전국철도노우회",
    purpose: "철도종사원의 자유민주노동운동정신함양을 위한 조사연구사업, 철도노동운동사에 관한 자료의 수집 및 발간사업 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-10-26",
    name: "(사)철도참전유공자회",
    purpose: "6.25사변종군기장증을 수여받은 철도참전유공자의 명예선양 사업 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1998-02-06",
    name: "(사)한국철도학회",
    purpose: "학술발표회 및 강연회 개최와 견학, 시찰, 철도에 관한 위탁 및 수탁연구, 기술지도, 자문, 평가 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-02-03",
    name: "(사)전국화물차주연합회",
    purpose: "화물운송사업에 관한 제반 법규 및 제도에 관한 개선 건의, 운임, 운행 기타 회원의 사업에 관한 지도 조사 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2011-05-12",
    name: "(사)한국BIM학회",
    purpose: "BIM 기술 활용 분야의 체계적인 지식기반 구축 및 보급, 산·학·연 협동 융복합형 연구개발 등을 통해 BIM에 관한 학문과 기술의 발전 및 보급에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1986-11-10",
    name: "(사)한국주차협회",
    purpose: "주차사업 공익성 구현, 회원권익 보호, 주차장 이용자에게 양질의 서비스 제공, 주차사업의 건전 발전, 공공편의 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1993-02-05",
    name: "(사)한국터널지하공간학회",
    purpose: "터널 및 지하공간의 사전조사, 건설, 시공 및 유지관리 연구, 터널 및 지하공간 공사의 안전시공 및 터널의 안전대책 연구 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-09-05",
    name: "(사)국가ㆍ지역경쟁력연구회",
    purpose: "국가 및 지역의 경쟁력에 관한 학문적, 실용적 연구ㆍ조사 및 교육, 경영자문과 국내외 관련기관과의 교류 및 협력을 통하여 한국의 지역개발 및 지방경쟁력의 향상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2012-01-10",
    name: "(사)대한민국녹색국토해양발전협회",
    purpose: "국토해양녹색환경 보호활동, 다양한 연구․녹색문화예술 활동 전개로 한반도 육지와 해양의 지속적인 녹색성장에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-06-07",
    name: "(사)한국무인기시스템협회",
    purpose: "회원 상호간의 정보 교류 및 국제 협력을 통하여 무인 항공기와 기타 무인 이동 및 운반 시스템의 연구와 기술 개발 보급, 시장 개척, 시장 활성화, 제도 정립 등 21세기 국가 전략 산업인 국내 무인기 시스템 산업 발전에 기여함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2012-05-03",
    name: "(사)한국항공우주정책법학회",
    purpose: "국내외의 항공우주법과 정책 및 항공우주관계 국제조약 연구",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2012-06-01",
    name: "(사)한옥건축학회",
    purpose: "한옥에 관한 학술적 이론과 그 응용방법을 연구함으로써 전통문화의 계승과 한옥의 학문적 발전을 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-05-12",
    name: "(사)서남해안포럼",
    purpose: "국가균형발전을 위한 친환경적ㆍ문화적 서남해안 개발을 위해 국가ㆍ사회적 동의 및 지역민 참여확보에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2012-06-29",
    name: "(사)한국주차관리협회",
    purpose: "주차사업의 전문성과 공익성을 구현하면서 주차관련 정부시책을 적극 추진․홍보하여 국가 교통난과 주차난을 해결하는데 앞장서며, 주차장 사업자에게 양질의 서비스를 제공하여 주차문화의 건전한 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2012-06-29",
    name: "(사)카셰어링포럼",
    purpose: "회원 간의 협력과 유대강화를 통해 카셰어링 관련 법․제도, 서비스 표준 연구 등을 추진함으로써 카셰어링 관련 산업 활성화에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2012-06-29",
    name: "(사)한국이륜자동차협회",
    purpose: "이륜자동차사업의 발전을 위한 수입 정비 폐차 매매 사용관리  연구 및 교육 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2012-08-13",
    name: "(사)도시환경문제연구소",
    purpose: "도시슬럼화, 뉴타운, 재건축, 재개발, 주거환경 정비사업 등에 따른 도시환경문제의 대안을 제시하여 도시거주민의 삶의 질 향상 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2012-08-24",
    name: "(사)한국카쉐어링협회",
    purpose: "공유경제 시대의 카쉐어링 제도 확산",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-08-02",
    name: "(재)한국건설경제연구소",
    purpose: "건설기술경제 및 건설관련 산업연구 등을 통하여 국가경제발전 및 국민의 삶의 질 향상에 이바지",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2012-11-09",
    name: "(사)글로벌인프라포럼",
    purpose: "건설산업 및 건설엔지니어링의 기술력과 경쟁력을 높이기 위하여 해외시장 진출의 미래비전을 제시하고 국내 건설산업의 표준화 및 지속가능한 발전을 유도",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-12-30",
    name: "(사)티에이비커미셔닝협회",
    purpose: "설비의 TAB와 커미셔닝 분야의 기술발전과 회원 상호 간의 협력과 단결을 통한 품질향상을 도모하여 관련 산업 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2011-01-12",
    name: "(사)한국초고층도시건축학회",
    purpose: "초고층 및 도시건축 문화의 진흥과 초고층 건축물의 설계, 시공기술, 디자인 향상을 위한 정책 및 제도연구, 학술대회, 국내외 기술교류",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-01-04",
    name: "(사)한국패시브건축협회",
    purpose: "에너지 절약형 건축물과 관련된 각종 현안에 대하여 조사, 연구의 수행, 관련 정보와 자료의 축적, 건설산업 현장에서의 관련기술 적용 및 인증, 간행물 발간등의 활동을 통하여, 건축물의 사용에너지 해결의 올바른 방향과 정책대안을 제시함으로써 삶의 질을 향상시키고 기후변화와 탄소문제를 해결하는데 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-01-16",
    name: "(사)한국건설이음협회",
    purpose: "1. 건설이음(재료)기술의 조사, 연구 및 중장기 발전 전략 제시2. 건설이음(재료)기술에 관련된 규정, 지침, 요령 및 편람 등의 개발3. 건설이음(재료)기술 관련된 기량검증 및 인증4. 건설이음(재료)기술에 관련된 기술 지원과 지도 및 상담5. 건설이음(재료)기술에 관련된 기술발표, 회보의 발행, 교육 및 강습회5. 건설이음(재료)기술에 관련된 자료의 수집, 정보교환 및 현안 해결방안 제시6. 관련 관청, 단체 등에 대한 건의 및 답신7. 기타 본 협회의 목적을 달성하기 위해 필요한 사업",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-12-26",
    name: "(사)희망의 러브하우스",
    purpose: "어려운 이웃의 주거공간 무료 개보수 사업, 어려운 이웃들의 주거환경 개선을 위한 후원 사업, 소외계층 복지를 위한 후원사업등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2003-02-20",
    name: "(사)한국도시개발연구포럼",
    purpose: "미래 지향적이며 친환경적인 도시개발사업 및 정비사업 등을 위한 법제와 실무를 연구하여 도시의 건전한 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-02-18",
    name: "(사)한국도시계획가협회",
    purpose: "도시계획에 대한 국민의 이해와 참여를 증진시키고, 도시계획가의 윤리강화 및 품위 보전과 권익을 보호하며, 도시문화와 전통을 발굴하여 시대에 맞는 새로운 도시문화를 창조함으로써 쾌적한 도시환경 및 품격높은 국토공간 조성에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-02-21",
    name: "(사)한국철도안전협회",
    purpose: "국내의 철도안전관련, 학계 및 산업계의 전문가 및 철도운영기관, 철도건설기관, 산업체 등으로 구성되는 단체로서, 철도안전 관련 정부 정책 수립 시 현장의 의견을 모아 제출하고 정책 추진에 협력하는 등 파트너의 역할을 수행하며, 경전철, 도시철도, 300km/h고속철도를 건설, 제작, 운영한 경험을 가진 우리나라의 철도경험과 기술을 집약하여 철도개발도상국에 효율적․경제적으로 전달하며 동시에 철도안전기술의 글로벌 진출에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-03-04",
    name: "(사)한국토목시공기술사협회",
    purpose: "토목시공기술의 발전, 보급 및 인식제고와 토목시공기술사들의 품위유지, 역량강화를 통하여 건설산업의 발전과 공공복리에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-03-07",
    name: "(사)한국도시철도학회",
    purpose: "도시철도와 관련된 학술연구 및 산학협동, 국제교류 등을 통하여 도시철도 산업발전 및 정부 도시철도 정책을 지원하고 회원 상호간 친목 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-02-03",
    name: "(사)한반도발전연구원",
    purpose: "통일 국토의 균형발전 및 경쟁력 강화을 위한 전략 및 실천방안 연구",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2011-10-31",
    name: "(사)전국건설기능훈련취업지원센터",
    purpose: "건설노동자에 대한 기능훈련을 실시하고 고숙련에 적합한 좋은 일자리 정보제공과 취업지원을 함으로써 건설노동자에 대한 헌법상의 근로권을 확보함을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-03-18",
    name: "(사)한국교통문화포럼",
    purpose: "교통문화의 선진화를 도모하여 국민경제발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1998-02-04",
    name: "(사)한국전기철도기술협회",
    purpose: "회원의 품위 유지와 복리증진, 회원 상호간의 친목을 도모하고 전기철도 기술인력의 양성과 지원, 지식의 보급으로 전기철도분야의 진흥을 통한 국민생활의 안정과 철도발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-12-28",
    name: "(사단법인 한국브이이연구원",
    purpose: "설계, 시공 및 엔지니어링 단계에서 VE활용 기술을 개발ㆍ보급하여 원가절감을 통한 국가경쟁력 향상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-04-05",
    name: "(사)한국주거복지포럼",
    purpose: "주거복지 분야의 다양한 주체들이 참여하는 토론의 장을 마련하여 주거복지 방향과 정책수단, 역할분담 등에 대한 사회적 합의를 이끌어내고, 이를 통해 지속가능한 한국의 주거복지 모델을 구현",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-04-16",
    name: "(사)응용생태공학회",
    purpose: "사회기반시설분야에 생태학적 원리를 접목하여 생태친화적인 건설과 국토관리에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-04-24",
    name: "(사)해비타트시민연합",
    purpose: "유엔해비타트의 주거권, 기후변화, 환경, 물, 토지 등의 인간정주 문제와 도시문제에 대한 해결 노력 등에 동참하고 협력함으로서 국제사회와 우리나라의 지속가능발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1997-07-22",
    name: "(사)한국건설관리협회",
    purpose: "건설사업관리에 관한 각종 제도의 연구개선, 교육훈련",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-05-02",
    name: "(사)한국건축시공기술사협회",
    purpose: "건축시공분야에서 국가적 책무를 다하고 건축시공기술사의 기술수준 향상과 업무수행 능력 증대향상, 품위유지와 지위향상에 힘써 국가 발전의 초석인 건설산업 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-04-24",
    name: "(사)한국조경협회",
    purpose: "1. 국내외 자연생태환경 조성과 복원 및 조경기술 정보교환2. 건설과 조경관련 강연회, 전시회 등 조경관련 행사3. 조경실무능력 향상을 위한 교육관련 사업4. 국제기구 및 국내외 관련단체와의 협력과 교류5. 조경관련 정책, 법령연구 및 제도개선6. 조경문화 진흥을 위한 사업7. 회원의 권익 및 복지증진을 위한 사업",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1985-02-13",
    name: "(사)한국지반공학회",
    purpose: "지반공학에 관한 학술 및 기술의 발전을 도모하여 국민 복지향상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-06-12",
    name: "(사)한국여성건설인협회",
    purpose: "여성건설인의 전문성 향상, 권익증진 및 사회참여 확대를 도모하고, 해외 여성건설단체와 건설기술향상을 위한 정보교류 및 국제협력 사업 추진",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-07-18",
    name: "(사)한국이륜차안전협회",
    purpose: "이륜자동차를 소유하거나 아륜차로 사업 관련 교통안전 교육을 실행하여 국민교통생활 안전제고 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-6-10",
    name: "(재)건설산업정보센터",
    purpose: "건설산업에서 발생하는 정보의 효율적인 관리를 통해 건설산업의 선진화와 투명성 제고에 기여",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1988-05-06",
    name: "(재)대한산업경제연구소",
    purpose: "건설업세무에 관한 교육, 세무진단",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-08-17",
    name: "(재)대한건설정책연구원",
    purpose: "건설산업 정책 및 제도, 건설산업 장단기 발전과제 등 연구, 건설업 관련 교육훈련사업",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-06-27",
    name: "(사)한국이륜자동차관리협회",
    purpose: "이륜자동차 정비 매매 폐차 연구 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1989-09-06",
    name: "(사)한국강구조학회",
    purpose: "강구조 기술 향상 및 강구조공학 발전과 강구조물의 보급 촉진",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-08-19",
    name: "(사)한국오토바이정비협회",
    purpose: "이륜차 정비사, 판매자 사용자들을 위한 이론 및 실기교육",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-07-24",
    name: "(재)서민주택금융재단",
    purpose: "국민주택기금 수탁은행 출연금을 재원으로 주택기금 발전 및 주거취약계층 복지사업지원을 통하여 국민주거 안정을 도모하고 주거복지 향상에 이바지",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-09-25",
    name: "(사)한국물류과학기술학회",
    purpose: "물류에 관한 과학과 기술의 발전, 정보교류를 통하여 물류비 절감, 친환경 물류, 스마트 물류 구현에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-10-02",
    name: "(사)한국로지스틱스학회",
    purpose: "로지스틱스의 이론과 실무에 관련된 연구, 국내 및 국제 학술 대회 개최, 국내외 학회 및 기관과의 제휴, 회원사 교육 등 로지스틱스 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-10-15",
    name: "(사)한국지반조사협회",
    purpose: "1. 지반조사 사업자 및 지반조사 기술자 간 상호 기술정보 및 자료 협력체계 구축2. 신기술 및 특수기술의 보급 등을 통한 지반조사 분야 경쟁력 강화 및 권익 보호 등에 필요한 업무3. 지반조사에 관련된 규정, 기준 및 업무편람 등의 개발4. 정부 및 지방자치단체 등이 위탁하는 업무5. 기타 협회의 목적 달성에 필요한 사업",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-10-24",
    name: "(사)한국자동차튜닝협회",
    purpose: "자동차 튜닝산업의 건전한 발전과 권익증진 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1989-10-04",
    name: "(사)한국콘크리트학회",
    purpose: "콘크리트의 재료, 구조물의 설계, 시공,  유지관리와 제품제조에 관한 학문과 기술의 발전 보급에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1956-03-17",
    name: "(사)대한토목학회",
    purpose: "토목공학 발전, 토목기술자 자질향상 도모, 토목인 지위향상, 학술ㆍ기술ㆍ건설산업 발전을 통해 사회ㆍ국가에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2013-12-11",
    name: "(재)물류산업진흥재단",
    purpose: "중소물류업체의 경쟁력 강화를 위한 역량강화 활동, 연구개발, 학술활동 등을 지원하고, 물류산업계의 유기적인 상생 협력체제 구축을 통한 물류산업계의 발전을 도모함으로써, 국가 경제에 이바지",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-04-06",
    name: "(사)한국물류관리사협회",
    purpose: "ㅇ 물류전문인으로서 회원 및 일반인에 대한 물류에 관한 전문교육 실시 및 연수ㅇ 물류업무 영역개발 및 선진외국 물류산업, 물류기술, 물류제도 연구, 개발사업 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-02-11",
    name: "(사)한국교량및구조공학회",
    purpose: "교량ㆍ구조공학에 관한 기초과학과 기술향상을 도모, 회원상호간 전문지식 교환, 선진실무기술을 보급 및 사회발전 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1989-05-17",
    name: "(사)한국철도신호기술협회",
    purpose: "회원 상호간의 친목을 도모하고 철도신호기술에 관한 교육과 연구개발·보급 및 열차의 안전운행 확보를 위한 사업 수행",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2004-07-12",
    name: "(사)건설산업비전포럼",
    purpose: "건설산업 미래비번 및 혁신전략 연구",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2012-06-12",
    name: "(사)한국자동차부품협회",
    purpose: "자동차부품의 유통구조 개선, 보급 활성화 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1971-12-31",
    name: "(사)대한설비공학회",
    purpose: "우리나라 설비공학 분야 학술진흥 및 기술발전",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2002-08-13",
    name: "(재)건설산업정보연구원",
    purpose: "건설산업분야에 대한 연구, 자문, 발표, 교육, 조사분석 등",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2014-05-01",
    name: "(사)도시지식산업집단",
    purpose: "도시에 관련된 지식을 활용하여 국가발전에 기여하고, 이를 세계에 전파함을 목적으로써 성공적인 도시지식산업화 모델의 확산 및 품격 높은 도시공간 조성에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2008-10-09",
    name: "(사)한국녹색물류학회",
    purpose: "물류와 환경 분야에 관련되는 학문의 연구를 통하여 녹색물류의 이론적 체계를 정립하고, 친환경적인 물류의 실현에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2008-01-30",
    name: "(사)영남지역발전연구원",
    purpose: "지역발전 전략 수립을 위한 지역의 현황 및 특성에 대해 체계적인 조사와 분석을 수행하고 지역특성을 고려한 특화사업모델 개발 및 정책연구를 통환 지역발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2014-06-23",
    name: "(사)한국건축정책학회",
    purpose: "국가건축전략, 건축정책, 건축관련 법과 제도에 관한 조사, 연구, 토론, 제안 등의 활동을 통해 건축 및 관련산업의 선진화와 대국민 건축서비스 증진",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2014-07-03",
    name: "(재)화물복지재단",
    purpose: "화물운송사업 발전지원기금을 받아 설립·운영하는 법인으로, 화물운송업 관련 연구지원 및 법률구조사업, 장학사업, 교통사고 생계지원사업 등 복지사업을 수행",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2014-07-08",
    name: "(사)공공창의연구원",
    purpose: "ㅇ 낙후된 도심 개선 및 변화를 통해 지역 불균형 해소ㅇ 도시건축 디자인, 지역개발 과제 및 정책대안을 체계적으로 조사.분석.연구.개발ㅇ 도시환경 발전과 낙후된 구도심 도시재생 활성화를 위한 연구.실천",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2006-09-22",
    name: "(사)국제물류연구회",
    purpose: "한반도의 동북아 물류중심지화 실현을 위한 국제물류분야 관련 연구 및 토론을 진행함으로써 우리나라 국제물류 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2014-08-28",
    name: "(사)교통정보플랫폼포럼",
    purpose: "교통정보의 공유 및 교통정보플랫폼 이용활성화를 통해 교통데이터의 가치를 극대화하고자 산․학․연․관의 공조체제를 구축",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1967-03-11",
    name: "(사)대한건축학회",
    purpose: "건축에 관한 학술ㆍ예술ㆍ기술 연구, 건축인 지위향상, 건축문화 창달 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2014-11-05",
    name: "(재)대한기계설비산업연구원",
    purpose: "기계설비산업 관련분야 전반에 관한 체계적인 정책 및 기술 연구를 통해 기계설비산업의 건전한 육성발전을 도모하고 국가경제발전에 공헌",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2010-01-01",
    name: "(사)한국물류학회",
    purpose: "물류(국내 및 국제) 및 상류, 전자상거래, 마케팅, 무역 등의 물류관련분야에 대한 학문의 이론적인 체계구축, 산업발전을 위한 산학협동, 정책연구와 회원 상호간의 친목도로를 목적으로 함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-01-07",
    name: "(사)안전재해환경대책본부",
    purpose: "건축물의 해체·철거공사 시 안전관리요령을 홍보 및 지도함으로써 해체·철거공사 시 발생할 수 있는 재해를 사전에 예방하여 국민의 생명과 재산을 보호",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-01-20",
    name: "(재)택시 감차보상재원 관리기관",
    purpose: "조세특례제한법 제106조의7제3항에 따라 부가가치세 경감세액을 징수 집행 정산 등 관리",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-01-21",
    name: "(사)아름다운주택포럼",
    purpose: "사단법인 아름다운주택포럼은 주거복지 분야의 전문가들이 모여 도움을 필요로 하는 이들이 아름다운 주택과 동네를 만들 수 있도록 지원함으로써 주거복지 향상과 아름다운 국토를 만드는데 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-02-03",
    name: "(사)한국도시재생학회",
    purpose: "도시재생에 관한 학문적, 실용적 연구를 통하여 도시.지역발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-02-04",
    name: "(사)북한지역발전연구소",
    purpose: "북한 미시지역 전반에 대한 공간정보 데이터베이스 구축, 공간정보에 기초한 미시지역 국토개발 잠재력 및 발전방안 마련 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-02-06",
    name: "(사)전국개발제한구역국민협회",
    purpose: "개발제한구역의 합리적 이용연구와 효율적 관리와 실태조사를 목적으로 함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-02-23",
    name: "(사)한국도로기술사회",
    purpose: "도로 및 공항분야 주요 현안에 대한 의견수렴, 국제흐름 파악 및 장래 비전 및 정책방향  제시 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-03-18",
    name: "(사)부동산융합학회",
    purpose: "도시재생, 도시설계 및 부동산투자금융 등 전문가들이 공동 참여하여 학술교류, 전문가 양성, 도시재생의 효율적 방안을 제시함으로 도시발전, 시민의 삶 증진에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-03-23",
    name: "(사)한국항공보안협회",
    purpose: "항공보안관련 이론, 정책 등 학술연구, 학술 간행물, 학회지 발행, 관련기관 간 학술교류, 보안자격제도 연구 및 보안교육 프로그램 개발 등 비영리 사단법인 설립목적 달성에 필요한 사업",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2011-02-18",
    name: "(사)대한지리학회",
    purpose: "한국의 국토, 도시, 지역 및 세계지역에 대한 지리학적 조사 및 연구업무, 국내 및 국제 학술발표회, 지역답사회, 강연회의 개최 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1959-07-25",
    name: "(사)대한국토ㆍ도시계획학회",
    purpose: "지속가능한 국토의 계획 및 관리에 이바지할 국토·지역·도시계획의 연구 및 교육 그리고 기술 발전을 도모하고, 계획가의 지위향상 및 상호친목을 도모함으로써 국가발전에 공헌하며, 이를 실현하기 위한 학술연구 활동을 수행함을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-05-14",
    name: "(사)한국제로에너지건축협회",
    purpose: "지구온난화와 기후변화, 화석연료 고갈에 의한 에너지 위기 등의 문제 해결을 위하여 제로에너지빌딩의 보급·확산",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-06-10",
    name: "(사)한국드론협회",
    purpose: "드론의 안전증진 및 전문인력의 양성, 산업 활성화 및 저변 확대, 기술․콘텐츠 개발과 제도 지원에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2005-03-08",
    name: "(사)한국도시지리학회",
    purpose: "도시 및 도시지리학의 연구와 교육을 통해 도시발전에 이바지하고 도시의 각종 문제를 해결하는데 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-07-16",
    name: "(사)한국드론산업협회",
    purpose: "무인운송수단과 무인이동체 산업의 발전을 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-08-24",
    name: "(사)대한민국 항공보안협회",
    purpose: "항공보안 관련 법규, 제규정 등의 제개정에 관한 연구 및 지원협력, 국가 항공보안정책 및 중장기 추진방향에 관한 지원, 항공보안 수준관리, 사고예방 및 점검 등의 지원협력, 국제 및 국내 항공보안 관련 기관과의 정보교류 등 지원협력 사업 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2002-09-04",
    name: "(사)교통문화협의회",
    purpose: "교통기관의 공간을 21세기 문화사업의 공간으로 활용하여 건전한 문화운동을 주도하고 국민의 문화수준 향상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-11-19",
    name: "(사)해외인프라개발협회",
    purpose: "해외인프라개발과 관련된 사업정보교류와 협력, 사업개발, 금융 등의 전문가 양성 등을 통해 우리기업의 해외인프라개발사업 발전과 회원의 권익증진을 도모하여 국가경제에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-12-24",
    name: "(사)한국공동주택입주자대표연합회",
    purpose: "공동주택 입주자등의 권익을 보호하고 공동체 활성화를 도모하기 위한 역할을 수행함으로써 입주자 등의 주거의 질을 향상하고 공동주택관리제도와 국가발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-12-29",
    name: "(재)건설산업 사회공헌재단",
    purpose: "건설업계의 사회공헌활동 확대와 나눔경영의 실천을 통해 사회취약계층 등 국민의 복리증진과 삶의 질 향상을 추구함으로써, 건설산업의 건전한 발전에 기여",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-01-07",
    name: "(사)한국외단열건축협회",
    purpose: "건축물 열손실 저감 및 외단열건축 구현을 위해 효율적 단열공법인 외단열 공법을 정착 건물환경 성능과 안전성능의 균형적 품질 확보를 통해 외단열건축 산업의 지속적이고 균형적인 발전",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-01-11",
    name: "(사)한국블록협회",
    purpose: "기후변화에 따른 도심지 재해재난 최소화 및 사전예방을 위한 기술적 측면에서의 도시정책을 지원하고, 블록에 대한 설계·시공기준 정립 및 기술력 향상을 통한 블록산업의 저변 확대에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-01-21",
    name: "(재)한국주차안전기술원",
    purpose: "기계식주차시설의 검사 등을 통하여 주차기 이용자의 안전유지와 사고예방에 기여",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-01-26",
    name: "(사)한국자동차공학한림원",
    purpose: "자동차공학 및 기술, 산업 발전에 현저하게 기여해 온 원로 자동차공학인들의 참여로 학술연구와 기술 지원 사업 그리고 정보 교류를 통해 자동차산업 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-02-11",
    name: "(사)한국건설법무학회",
    purpose: "건설분쟁, 건설감정, 건설·부동산정책 등 건설과 관련된 법률 및 정책에 관한 연구와 교육활동",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-03-14",
    name: "(사)한국자동차튜너협회",
    purpose: "자동차 튜닝 전문가의 기술 증진 및 건전한 자동차 튜닝문화 형성에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-04-07",
    name: "(사)한국지적연구소",
    purpose: "국토의 효율적인 관리와 국민의 소유권 보호를 위한 지적제도의 발전 및 정책 수립 지원에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-04-27",
    name: "(사)한국항공객실안전협회",
    purpose: "항공기 객실안전 연구, 객실승무원 교육지원을 통한 안전한 항공여행문화 정착 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1996-02-14",
    name: "(사)한국빌딩협회",
    purpose: "회원 상호간의 유대 강화와 협력을 통하여 빌딩 임대와 관리 산업의 육성과 발전을 위하고 임대와 건물관리 기술 개발을 위한  인력 양성과교육 훈련에 힘쓰며 관련 산업의 보호와 권익 신장을 위하여  공동 노력하고 국제화 추진을 통한 경쟁력 강화로 국민 경제 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-10-12",
    name: "(사)대한주차산업협회",
    purpose: "주차산업의 공익성을 구현하고 정부시책을 적극 추 진하여 회원의 권익을 보호하고 주차장 이용자에게 양질의 서비스를 제공하여 주차 산업의 건전한 발전과 공공의 편의를 도모함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-10-13",
    name: "(사)한국항공ㆍ철도사고조사협회",
    purpose: "국․내외 항공․철도사고조사 관련 기법연구, 기술자문, 연구용역, 교육훈련 및 연구활동 참여 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-11-09",
    name: "(사)한국부동산경제단체연합회",
    purpose: "부동산 경제단체간의 상호 긴밀한 협력 증진과 친목을 도모하며, 부동산 경제인의 권익을 신장하고 건전한 부동산 문화 창달과 각종 부동산 정책연구·기획 등을 통하여 부동산산업 및 국가경제 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1995-09-13",
    name: "(사)한국해비타트",
    purpose: "무주택 영세민들을 위한 사랑의 집짓기 건축활동",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-11-25",
    name: "(사)한국무인기안전협회",
    purpose: "무인기의 안전운항을 확보하고, 무인기시장의 건전한 육성과 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-11-25",
    name: "(사)한국드론비즈포럼",
    purpose: "로봇기술과 드론 기술 융복합 커뮤니티 조성 등으로 드론 상용화 촉진 및 융복합 비즈니스 모델 발굴 등 드론기술과 산업발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-11-25",
    name: "(사)한국드론레이싱협회",
    purpose: "국내외 드론 레저스포츠 활성화를 통한 저변확대와 드론 산업촉진 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-12-06",
    name: "(사)대한민국일반항공협회",
    purpose: "대한민국 일반항공의 발전을 위하여 일반항공의 안전한 비행활동을 최우선으로 새로운 운항기술을 도입ㆍ전파하고, 일반항공의 인프라 개선 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-12-27",
    name: "(사)한국교통안전시민협회",
    purpose: "교통안전문화 조성에 기여하는 활동 및 교통안전법 준수를 위한 교육‧지도 계몽활동 등을 통하여 교통안전문화 정착에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2016-12-27",
    name: "(사)초원회",
    purpose: "하나의 풀잎들이 모여 초원을 이루듯이 정성어린 성금과 봉사의 손길을 모아 사회에서 어려운 청소년 등 취약계층에게 주거환경개선 서비스를 제공하여 삶의 질을 향상하는데 기여하고 건전한 사회풍토 조성에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2017-01-04",
    name: "사단법인 한국창호커튼월협회(舊 사단법인 한국파사드협회)",
    purpose: "○ 고효율 에너지 파사드 제품 및 신기술 개발유도○ 국내외 파사드 분양 시장정보 및 통계 자료수집, 제공○ 녹색 에너지 파사드 관련 정기간행물 발간 및 기술정보 제공○ 파사드분야 고급인력 육성 및 교육○ 건축외피의 에너지 및 각종성능시험○ 에너지효율 개선을 위한 관련 기술 세미나 개최",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2017-03-16",
    name: "(사)세상을 품은 건설인",
    purpose: "후진국 젊은이들에게 건설기술을 교육하고, 건설현장에 채용하여 스스로 자립기반을 닦아 기아와 빈곤의 악순환을 스스로 퇴치할 수 있도록 봉사활동에 주력",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2017-04-04",
    name: "(사)한국바이오텍경관도시학회",
    purpose: "생명경관도시 재생을 위한 전략, 기술, 소재, 프로그램 등에 관한 담론 생성하고 공유하며 학술적 연구, 개발에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2017-04-12",
    name: "(사)한국주거서비스소사이어티",
    purpose: "주거서비스 분야의 다양한 주체들이 참여하여 주거서비스를 공공지원과 민간의 신산업으로 육성하는데 기여하고, 주거서비스의 사회적, 정책적 기반을 조성함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2017-05-10",
    name: "(사)글로벌항공우주산업학회",
    purpose: "항공우주산업 관련 산/학/관/연/군 다양한 관계자 간 협력 기반 조성 및  글로벌 경쟁력 강화 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2017-08-16",
    name: "(사)한국사회적약자네트워크",
    purpose: "사회적약자와 그 가족들의 안전하고 편리한 주거생활을 위해 주거문제 개선과 해결을 지원하고 정부와 지자체의 지원제도 홍보와 교육으로 사회적약자 주거안정과 환경개선, 경제적활동, 여가활동에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2017-08-16",
    name: "(재)에스와이행복나눔재단",
    purpose: "저소득층 및 사회소외계층에 대한 주거복지 개선 및 계층 간 격차 해소와 행복 나눔을 구현하여 복지사회 건설에 이바지함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2017-08-18",
    name: "(사)한국지하안전협회",
    purpose: "지하의 안전한 개발 이용과 관련한 산업의 건전한 육성과 연구개발, 교육홍보 및 교류협력을 통해 공공의 안전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2017-08-31",
    name: "(사)한국기계설비기술사회",
    purpose: "기계설비기술사들이 관련 분야 최고의 전문 기술인으로서 기계설비관련산업 발전에 기여할 수 있도록 기술사의 기술수준 향상, 업무수행능력 증대, 기술지원 및 권익신장을 통하여 국가와 사회발전에 이바지",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2017-09-29",
    name: "(재)일반택시 운수종사자 복지재단",
    purpose: "일반택시운수종사자의 복리후생증진 및 공공복리 향상",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2017-10-17",
    name: "(재)한국건설인정책연구원",
    purpose: "건설기술·건설산업 및 관련분야에 관한 체계적인 연구로 건설기술·건설산업의 건전한 육성발전을 이룩하고 건설산업의 경쟁력제고를 통한 국가경제발전에 기여",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1936-07-01",
    name: "(재)홍익회",
    purpose: "철도청 시절 우리나라 철도발전에 기여한 자의 위상정립과 공상을 당한 자 및 순직한 자에 대한 추모 및 생계를 원호하며 그 희생 정신 고취를 목적으로 함",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2017-12-28",
    name: "(사)한국부동산경제협회",
    purpose: "부동산산업, 부동산경제 및 부동산정책 등의 올바른 이론 정립과 정책대안 제시를 하는 한편, 부동산산업의 발전과 부동산경제 활성화, 국민 주거복지 안정을 도모하여 궁극적으로 공공의 이익실현",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2015-08-31",
    name: "(사)사회주택협회",
    purpose: "사회주택의 보급 및 활성화를 위해 일하는 단체들의 연합체로서 회원사 간 상호협력을 통해 사회주택 보급 및 활성화 사업, 사회주택 인프라 구축, 정책연구 및 제안사업, 사회주택 관련 교육사업, 사회주택 홍보사업 등을 진행함으로써 서민에게 안정적인 주택을 보급하고 주거복지를 향상시킴",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2017-12-28",
    name: "(사)한국건설안전학회",
    purpose: "건설사업의 안전, 보건, 환경 및 품질 분야의 학문과 기술의 통합적 발전을 도모하여 안전한 건설사업의 수행을 통한 시민의 행복에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-04-02",
    name: "(사)한국장애인교통문화협회",
    purpose: "장애인의 교통안전 교육 및 바른운전 홍보사업을 수행함으로써 우리사회에 올바른 교통문화가 정착될 수 있도록 함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-04-25",
    name: "(사)유라시아평화철도포럼",
    purpose: "남한과 북한을 포함한 한반도와 유라시아대륙의 철길을 연계하여 우리나라 및 유라시아대륙 제 국가들의 평화, 상생발전, 공동번영을 위한 다양한 활동으로 통일, 도시, 경제, 교통, 문화, 관광, 환경, 에너지, 복지 영역에서 안전, 형평, 생명, 평화의 가치를 실현하고 유라시아대륙철도 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-05-17",
    name: "(사)한국물류장비협회",
    purpose: "물류장비산업 발전 및 조사연구, 표준화, 안전화 사업",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-06-12",
    name: "(사)한국냉동공조시공관리협회",
    purpose: "중소 규모 냉동공조∙냉장의 시공 및 유지관리 분야에서 실무개발 및 전문 기술인 양성을 통해 국내 냉동공조 관련 산업 발전을 이루어, 공익 및 국가발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-07-23",
    name: "(사)한국건설계측협회",
    purpose: "건설계측 분야의 설계, 설치, 유지관리등에 관한 학문과 기술의 개발과 보급을 통해 국민복지 향상에 기여함과 동시에 회원상호간의 친목도모와 회원의 권익을 보호",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-08-07",
    name: "(사)공항운송기계협회",
    purpose: "공항운송기계 분야에 대한 해외시장 개척, 신기술개발을 지원하여 회원사 권익증진 및 공항운송기계산업 발전과 활성화 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-08-22",
    name: "(사)경부고속도로기념사업회",
    purpose: "경부고속도로의 역사성을 제고하고, 계승ㆍ발전시켜 국민의 자긍심 고취 및 고속도로 건설사업 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2009-01-23",
    name: "(사)주민참여도시만들기연구원",
    purpose: "주민참여도시만들기 관련 연구, 교육‧홍보, 지역주민과 관련 전문가 간 협력체계 도모를 통하여 지역역량 강화‧지역공동체 회복‧지역경제 활성화‧주민복지 및 삶의 질 향상‧도시문화 창출 등 공헌",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-09-30",
    name: "(사)건설기계개별연명사업자협의회",
    purpose: "건설기계 개별․연명 사업자로서 사회적 책무를 이행하고, 건설기계 개별․연명 사업자의 발전과 권익보호 및 회원 상호 간의 친목을 도모하고자 함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-09-30",
    name: "(사)천공 항타항발기협의회",
    purpose: "천공기, 항타 및 항발기 기술연구와 정책 개선사업을 통해 관련분야의 기술개발을 이루고, 회원 상호간의 효율적인 업무수행과 관련 산업의 발전을 이루어 더 나아가 국가경제발전및공익에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-11-02",
    name: "(사)도시재생활동가네트워크",
    purpose: "도시재생 활동가의 권익보호와 사회적 지위향상·정책연구·활동지원·기반구축 등의 역량강화를 통해 도시재생 네트워크 활성화 및 국토의 균형발전과 공동체 기반의 도시재생 발전 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-11-07",
    name: "(사)한국부동산금융투자포럼",
    purpose: "부동산금융투자 분야의 연구와 제도개선 및 정책건의 등을 통해 국내 부동산금융투자 산업의 선진화에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-11-22",
    name: "(사)해외건설전문가포럼",
    purpose: "해외건설 이슈 공유, 전문인력 역량강화 및 네트워크 구축 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-11-30",
    name: "(사)한국건축물마감재관리협회",
    purpose: "건축물의 최초 설계시부터 건축물의 사용용도와 목적에 맞는 마감재를 LCC(Life Cycle Cost)를 고려하여 선택하고 마감재를 과학적으로 관리하여 건축물의 물리적ㆍ경제적 수명을 장수명화시켜 건축 환경의 유지보존과 자원절약에 기여하며 마감재관련 유지관리제도의 연구와 관리기술 향상을 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-11-30",
    name: "(재) 한국항공재단",
    purpose: "우수항공인재 발굴, 양성과 조종훈련생의 교육훈련 지원(장학대출), 사회공헌사업을 도모하여 공공복리의 증진에 기여",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-12-20",
    name: "(사)펌프카협의회",
    purpose: "건설기계 대여업을 영위하고 있는 콘크리트 펌프 사업자로서의 사회적 책무이행‧현장에서의 역할 수행‧회원 상호간의 상부상조 등을 도모하고, 우수한 콘크리트 펌프 조종 전문 인력을 교육하여 지역 취약 계층에게 취업을 지원하고, 사고예방 및 정상적인 안전시공 환경을 조성하여 국가경제발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018-12-28",
    name: "(사)한국항공교통학회",
    purpose: "항공안전법의 규정에 의한 항공교통관리 및 항공교통 시스템의 안전성과 효율성 개선을 위한 연구 수행을 통해 항공교통분야의 학문적 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-01-09",
    name: "(사)교통사고피해자지원희망봉사단",
    purpose: "교통사고로 인해 어려움을 겪고 있는 피해자 및 유가족을 위한 다양한 활동으로 그들이 사회구성원으로서의 안정된 삶을 살아갈 수 있도록 지원하여 사회발전에 기여함을 목적",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-01-16",
    name: "(사)한국시설안전기술협회",
    purpose: "시설물 안전에 관한 학술적 연구와 안전 산업의 발전을 통하여 국민안전을 확보하며, 국가 정책의 홍보화 사회 안전망을 구축하는데 이바지하고, 국민 삶의 질 향상에 기여함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-02-12",
    name: "(사)한국드론기업연합회",
    purpose: "드론 기업 중심의 집약적 협력체계 구축을 통해 기술교류, 생태계 조성 및 동반시장 개척 도모 등으로 드론산업 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-04-04",
    name: "(사)도시재생안전협회",
    purpose: "국내 도시재생안전산업의 건전한 발전과 국가 전반의 사회안전시스템 수준 제고를 위한 산업육성과 사업 환경 조성 등을 통해 안전한 선진 사회 구현과 국민 경제 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-03-05",
    name: "(사)한국주거복지사협회",
    purpose: "주거복지사의 권익을 보호하고, 주거복지정책 개발 및 주거복지사 역량강화 교육 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-04-16",
    name: "(사)도시재생협치포럼",
    purpose: "도시재생 뉴딜사업 추진간 다양한 정보교류 및 정책제언을 위한 협치 플랫폼 구축",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-04-23",
    name: "(사)굴삭기협의회",
    purpose: "굴삭기대여사업자를 대표하는 단체로, 굴삭기대여사업자로서 사회적인 책무이행 및 굴삭기 대여사업자 발전과 권익보호, 회원 상호간의 친목도모 등을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-05-16",
    name: "(사한국부동산마케팅협회",
    purpose: "주택법의 규정에 의한 아파트 분양대행 등 부동산 마케팅업무 수행과정에서의 문제점 극복과 제도개선 등을 추구함으로써 국민주거생활의 향상과 부동산 마케팅업의 건전한 육성 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-05-17",
    name: "(사)차량기술사회",
    purpose: "차량기술사 고유업무 개발, 차량기술사의 업무 교육지원 및 자동차 관련 정보교류를 통해 차량기술사의 직무능력 향상과 권인신장에 앞장 서고 자동차산업발전에 이바지, 자동차가격조사,산정",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-06-13",
    name: "(사)건축물에너지평가사협회",
    purpose: "건축물의 온실가스 배출량 감축과 녹색건축물의 확대, 저탄소 녹색성장 실현, 녹색기술정보교류를 통한 연구개발 및 교육 등을 통한 에너지정책 실현",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-06-24",
    name: "(사)항공소음정책포럼",
    purpose: "항공 소음 등 관련 정보 교류, 의제 발굴과 논의, 학술 연구 활동 등을 통해 소음 정책 발전 방향 제시",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-07-09",
    name: "(사)한국자동차안전협회",
    purpose: "친환경자동차의 제도적 인증방안 모색, 애프터마켓의 안전인증기준 연구 등 자동차의 안전을 확보하기 위한 제반사업 추진",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-07-23",
    name: "(사)한국프롭테크포럼",
    purpose: "부동산과 ICT의 융복합을 통한 부동산 혁신육성사업, 국내외 부동산 및 프롭테크 관련 교류협력사업, 프롭테크 관련 전문 지식정보 제공 서비스업 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-08-19",
    name: "(사)스마트도시·건축학회",
    purpose: "스마트 도시와 건축에 관련된 전문지식을 활용하여 국가발전에 기여하고 이를 국내외에 전파",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-10-10",
    name: "(사)더나은도시디자인포럼",
    purpose: "도시경관디자인에 관한 학술적 교류 및 도시경관디자인문화의 창달과 발전을 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-10-25",
    name: "(사)동아시아철도포럼",
    purpose: "동아시아  철도 네트워크 구축과 공동협력 실행기반을 마련하고 다양한 정책 대안 도출",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-10-25",
    name: "(사)전국자동차성능평가협회",
    purpose: "중고자동차의 성능상태점검 및 보증업무의 발전과 보급을 통해 소비자 보호",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-11-04",
    name: "(사)한국장애인주거복지협회",
    purpose: "장애인 및 취약계층의 주거 편의시설 개선 지원 추진 등을 통해 기본적 권리인 주거권 보장과 더불어 사회적 통합에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-11-06",
    name: "(사대한여성건축사회",
    purpose: "안전하고 쾌적한 도시.건축 환경의 실현 및 양성평등을 기초로 한 여성정책과 제도의 개발.건의 등을 통해 여성건축사의 사회참여 확대 및 건축문화 발전에 이바지",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-11-13",
    name: "(사)대한셔터협회",
    purpose: "셔터산업의 건전한 발전을 위해 회원간 단결을 도모하고 셔터제품의 경쟁력 강화 및 표준기술 이행확산에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2019-12-03",
    name: "(사)미래도시환경연구원",
    purpose: "도시 전반에 걸쳐 도시재생 및 지역 활성화를 위한 정책, 제도 등 다양한 분야의 연구와 관련 교육, 상담을 진행함으로써 도시재생 및 지역 활성화의 조력자로써 지속가능한 도시를 실현하고 균형 있는 국가 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2020-01-03",
    name: "(사)불도저협의회",
    purpose: "불도저를 보유한 대여사업자를 대표하는 단체로, 불도저의 기술연구와 정책 사업을 통해 회원들의 효율적인 업무 수행과 관련 산업 발전, 국가 결제 발전 및 공익에 기여함을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2020-01-31",
    name: "(사)기중기협의회",
    purpose: "기중기를 소유한 대여사업자 단체로, 기중기의 기술연구와 정책사업을 통해 회원들의 권익향상, 관련 산업과 국가경제발전 및 공익에 기여함을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2020-03-03",
    name: "(사)한국건설방수학회",
    purpose: "건설구조물의 방수 관련 설계∙시공∙재료∙품질∙ 누수보수 및 유지 관리 등에 관한 학문의 연구, 기술 개발 및 보급을 통하여 국가 건설 산업 및 경제발전에 기여함으로써 국민 생활의 안전과 공공의 이익을 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2020-05-21",
    name: "(사)한국드론혁신협회",
    purpose: "드론산업분야의 인재육성을 위한 교육플랫폼 구축 등 제반사업 추진 등을 통해 드론산업 발전을 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2020.07.17",
    name: "(사)국가철도공단동우회",
    purpose: "회원의 복리증진과 상호간의 친목을 도모하고 철도시설 및 건설산업의 발전을 통한 국가발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2020.07.29",
    name: "(사)한국도로시설안전산업협회",
    purpose: "산ㆍ학ㆍ연 기관과의 공조체제를 구축하고 각 분야의 다양한 의견을 수렴하여 회원사의 기술경쟁력을 강화함으로써 도로 또는 도로안전시설 산업의 발전과 정부정책 지원 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2020.7.30",
    name: "사단법인 근대도시‧건축연구와 실천을 위한 모임",
    purpose: "근대도시근대건축자산･도시에 관한 조사･연구 및 재생 그리고 교육･홍보･아카이브 구축활동을 통하여 근대건축자산 및 도시유산에 대한 연구, 보존 및 활용과 역사도시 재생에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2018.1.18.",
    name: "대한설비설계협회",
    purpose: "건축물·산업·환경시설 설비설계용역업체의 권익보호, 품위유지, 상호협력 증진을 도모하고 설비관련제도·경제시책·친환경·녹색건축과 관련된 설비설계기술 향상을 위한 제반사업 추진 등을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2020-08-11",
    name: "재단법인 한국골재산업연구원",
    purpose: "골재산업 관련 분야에 관한 체계적인 연구로 골재산업의 건전한 발전을 도모하고, 골재자원의 안정적 확보 및 품질 향상과 체계적 관리를 통하여 국가경제발전에 공헌함을 그 목적으로 함",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2003.7.31",
    name: "사단법인 한국지반신소재학회",
    purpose: "지반신소재의 발전과 그 응용산업의 진흥을 통하여 국민의 복지향상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2020.11.02",
    name: "사단법인 한국환기산업협회",
    purpose: "고성능의 환기 관련 기자재 및 시스템 보급을 통하여 실내 공기오염 방지와 국민 건강 및 국가 에너지절약에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2020.12.01",
    name: "사단법인 한국자동차매매산업연구회",
    purpose: "자동차매매산업 연구 및 학술발전과 각종 개선방안 마련",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2021.01.18.",
    name: "사단법인 전국이륜차배달라이더협회",
    purpose: "회원 상호간의 친목과 복리증진을 도모하고, 배달산업의 발전 및 종사자들의 권익보호와 안전을 강화하기 위하여 안전한 배달방법 등에 대한 연구.자문 및 배달업 종사자의 사고피해 지원",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2021.3.8.",
    name: "사단법인 철도기술사회",
    purpose: "철도토목 및 철도궤도의 기술연구와 정책 개선사업을 통해 기술개발을 이루고 전문성을 활용하여 공익에 이바지함을 목적",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2021.3.3.",
    name: "재단법인 자율주행기술개발혁신사업단",
    purpose: "자율주행기술개발혁신사업의 효율적인 추진을 위해 사업의 기획ㆍ관리, 사업단 운영 등 사업수행 전반에 관한 업무 총괄 및 이사회ㆍ각 부처 보고 등 수행",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2021.3.22.",
    name: "사단법인 배수성아스팔트기술협회",
    purpose: "배수성아스팔트포장의 기술발전, 보급, 개발을 촉진하여 배수성아스팔트 기술 수준을 향상시키고 이를 바탕으로 관련 산업을 발전시켜, 배수성아스팔트포장 품질을 높이고 내구성과 공용성을 확보함으로써 도로사용자의 편익과 공공복지 증진 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2021.5.21.",
    name: "사단법인 스마트건설교육원",
    purpose: "스마트 건설기술 중심의 건설기술인 교육 등",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2021.",
    name: "사단법인 한국도시재생진흥협회",
    purpose: "도시재생산업 정보의 조사, 연구 및 제공도시재생산업 전문가의 육성, 마을기업의 창업 및 지원도시재생산업박람회 개최 및 지원도지새애지원센터의 운영 및 지원기타 법인의 목적달성에 필요한 사업",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2021-06-07",
    name: "사단법인 한국막구조물협회",
    purpose: "막구조물 산업의 경쟁력을 향상시키고 막구조물의 보급을 활성화하며 업계의 협력강화를 통해 건설산업 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "1982.7.9",
    name: "사단법인 철도공제조합",
    purpose: "본 조합은 조합원 및 그 가족의 상호 친목, 상호부조, 문화향상과 복리증진을 목적으로 한다.",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2021.06.21.",
    name: "사단법인 스마트도시 블록체인 포럼",
    purpose: "스마트도시 프로젝트와 블록체인 등 기술발전 연구, 스마트도시 전문인력 양성 및 학술활동 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2021.7.22",
    name: "사단법인 민간임대협동조합연구원",
    purpose: "민간임대주택법 제5조의3의 \"민간임대협동조합\"을 통한 민간임대주택사업의 표준화 등으로 서민,청년 주택공급에 획기적으로 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2021.10.8.",
    name: "사단법인 한국자율주행산업협회",
    purpose: "자율주행 관련 연구, 조사, 자문, 교육ㆍ훈련 등을 통해 국내 자율주행 산업의 성장 및 기술보급 기반 조성에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2021.10.27",
    name: "사단법인 한국철도교통관제협회",
    purpose: "한국철도교통관제분야의 발전에 필요한 연구개발 및 활성화 방안을 제시, 철도교통의 안전성 향상에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2021-12-06",
    name: "사단법인 한국건축물해체기술연구원",
    purpose: "국내 건축물 해체·철거기술의 질적 향상을 위한 조사·연구·교육·자문 및 전문가적 기술을 지원하고, 선진화된 일상생활 속의 안전문화 환경조성, 국민경제발전 유도 등 공익증진에 기여함을 목적으로 하는 단체",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2021.12.22.",
    name: "사단법인 한국건설자동화로보틱스학회",
    purpose: "건설자동화·로보틱스 관련 학술연구 및 각종 행사 계획 등 사업을 수행하여 건설산업의 생산성 향상 및 스마트건설산업 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2022.1.11",
    name: "사단법인 스마트건설드론협회",
    purpose: "드론과 첨단스마트 기술을 건설 재난 안전분야에 적극 활용하여 드론 산업 발전에 이바지",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2022.1.21.",
    name: "사단법인 교통안전선진화연구원",
    purpose: "교통안전선진화에 필요한 연구, 건의, 홍보 등을 통하여 우리나라가 교통안전선진국이 될 수 있게 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2022-03-23",
    name: "사단법인 대한기계설비유지관리기술인협회",
    purpose: "기계설비 유지관리자 및 기술인 등에 대한 자질향상  및 기계설비 유지관리 분야의 연구개발 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2022-04-29",
    name: "사단법인 전국장애인이동권연대",
    purpose: "장애인 이동권 확보를 위한 조사·연구, 사회적 인식 개선을 위한 홍보활동 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2022-05-18",
    name: "사단법인 한국스마트건설안전협회",
    purpose: "스마크건설안전기술의 연구 및 조사, 표준화, 민‧관‧학‧연간 협력 촉진 등을 통해 국가 핵심 산업인 건설 산업 현장에 발생하는 중대재해와 각종 안전사고 예방에 기여함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2000-08-31",
    name: "사단법인 한국그린빌딩협의회",
    purpose: "그린빌딩이란, 건축물의 설계부터 건축, 운영, 관리, 수선 및 해체까지 빌딩 전 생애주기에 걸쳐 인간과 환경에 대한 피해를 최소화하고 자원활용의 효율성을 극대화한 건축물을 말하며, 본 협의회에서는 국내 그린빌딩산업의 진흥 확대보급에 기여하고, 녹색건축강국을 실현하며, 그린빌딩 관련 국제 경쟁력을 제고하고, 환경친화적이고 지속가능한 건설 문화를 창달하는 것을 목적으로 한다.",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2022-08-25",
    name: "사단법인 한국레저자동차산업협회",
    purpose: "레저 자동차(캠핑용자동차) 기술, 제도 등 관련 제반환경을 구축하여 관련 산업의 발전과 업계의 교류 활성화를 통해 레저자동차 기술발전과 레저자동차 문화발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2022-09-05",
    name: "사단법인 한국퍼스널모빌리티산업협회",
    purpose: "퍼스널모빌리티와 관련된 ①강연·토론회·전시회·간담회 ②학술연구 및 조사, 분석 ③정책·제도 제언 ④서비스 이용자 안전 교육 및 안전 이용 캠페인 ⑤기타 본회의 목적달성에 필요한 사업 중 허가관청의 승인을 득한 사업 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2022-10-18",
    name: "사단법인 한국부동산융복합학회",
    purpose: "부동산융복합과 관련된 ①부동산 융복합의 기초이론 ②부동산 융복합 관련 학문연구 및 자문 ③부동산 융복합 관련 학술연구 발표회 및 세미나 개최 ④부동산 융복합 관련 국내 학술지 발간 및 배포 ⑤부동산 융복합 관련 연구용역 수행 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2022-12-02",
    name: "사단법인 건설법학회",
    purpose: "건설행정법학과 관련된 ①학술연구 및 교육 ②학술지 등 기타 간행물의 발간 ③연구발표회 및 강연회 개최 ④목적을 같이 하는 내외 여러단체 제휴 ⑤기타 학회의 목적달성에 필요한 사업",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-01-16",
    name: "사단법인 내화채움구조협회",
    purpose: "내화채움구조의 발전을 위한 기반을 조성하고, 연관 산업의 국제경쟁력 확보를 통해 국민 생활 안전 및 소방산업 번영과 발전 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-02-01",
    name: "사단법인 한국생활물류택배서비스협회",
    purpose: "중소 택배사업자 및 종사자의 상호연대를 도모하고 생활물류택배서비스 산업의 향상을 위한 연구개발 및 발전을 위함",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-02-22",
    name: "사단법인 한국수입자동차정비협회",
    purpose: "수입자동차 정비분야 연구, 수입자동차 관리사업 발전",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-04-14",
    name: "사단법인 케이블시설기술협회",
    purpose: "케이블시설의 안전 및 품질향상 관련, 법령‧정책‧제도의 제안, 선진기술의 조사 연구 및 성과의 보급, 국내외 학술발표회와 세미나 개최, 기관·단체·기업 등과 협력 네트워크 구축, 기술인력 양성 및 교육 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-05-02",
    name: "사단법인 도시와 미래 연구소",
    purpose: "도시와 미래에 관련한 정책연구를 통하여 국가발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-05-10",
    name: "사단법인 한국이륜차안전운전자협회",
    purpose: "이륜차 운전자와 시민의 교통안전 관련 교육 및 정책을 제안하고 조사연구를 통해 시민의 교통안전 증진에 이바지",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-05-10",
    name: "사단법인 한국자동차공정정보협회",
    purpose: "자동차성능, 상태점검 및 보증에 관한 연구와 그 사업",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-06-12.",
    name: "사단법인 한국주택분양상담사협회",
    purpose: "주택분양 상담전문가 양성 및 보수교육을 위한 온, 오프라인 사업 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-06-22",
    name: "사단법인 국제드론축구연맹",
    purpose: "드론 축구를 매개로 국가별 회원단체 간의 교류활동을 통해 건전한 드론 활용을 증진하여 드론산업발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-07-21",
    name: "사단법인 한국이륜자동차제작자협회",
    purpose: "소규모 이륜자동차 제작·수입업체의 자기인증 기반조성 활동지원과 제품개발에 필요한 안전기준 적합 교육지원 등을 통해 이륜자동차제작자의 서비스 품질 향상과 경쟁력 강화에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-08-04",
    name: "사단법인 저탄소 사회를 지향하는 목조건축협회",
    purpose: "저탄소 목조건축 관련 ○ 플랫폼 구축 및 운영사업 ○ 기술, 제도 등 연구 및 정책제안 ○ 사업자 조언, 지원·협력사업 ○ 세미나, 포럼, 견학, 교육 사업 ○ 국내외기관 및 업계 간 네트워크 구축 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-08-28",
    name: "사단법인 한국리모델링융합학회",
    purpose: "리모델링과 관련된 ①관련 현안 및 기술 조사②학술세미나 등 학술교류 ③리모델링 연구개발 용역 및 기술자문 ④학회지, 논문집 등 발간 ⑤기타 학회의 목적달성에 필요한 사업",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-08-25",
    name: "사단법인 한국부동산학술회의",
    purpose: "부동산학 이론의 연구·개발 등 정관 제3조에서 정한 사항",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-09-21",
    name: "사단법인 한국우크라이나뉴빌딩협회",
    purpose: "한국, 우크라이나 간 전후복구를 위한 여건을 조성하고 재건협력을 위한 협력체제를 구축하며, 한국 기업의 우크라이나 재건사업 참여에 유리한 환경을 조성하기 위한 다층적 지원활동 수행",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-10-06",
    name: "사단법인 한국도시정비학회",
    purpose: "도시정비에 관한 학문 분야의 연구와 교육, 학술 활동, 정부(기관) 의뢰 연구, 장학사업, 기타 학회 목적 달성 상 필요 사업 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2023-10-10",
    name: "사단법인 건설품질검사엔지니어링협회",
    purpose: "건설품질시험분야 종사자의 전문성 및 위상 제고, 책임의식 고취, 권익보호 등을 추구하여 품질검사 신뢰도를 향상시키고, 궁긍적으로 건설산업 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2024-01-15",
    name: "재단법인 폭스바겐그룹 우리재단",
    purpose: "첨단자동차 분야 교육 프로그램 개발, 장학 사업, 첨단자동차 분야 교육 프로그램의 국내 도입 및 확산, 재단 목적과 관련되거나 부수되는 사업 및 활동",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2024-02-29",
    name: "사단법인 한국미래부동산산업연구회",
    purpose: "부동산산업에 미래 신기술 접목 등 정관 제4조에 정한 사항",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2024-05-02",
    name: "사단법인 한국미래친환경차서비스협회",
    purpose: "친환경차 등 미래모빌리티에 대한 ① 제조사와 연계한 표준정비지침 및 교육매뉴얼, 서비스 플랫폼 구축 ② 친환경차 전문 정비인력 양성을 위한 온라인 교육체계 구축·시행 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2024-05-28",
    name: "사단법인 한국신소재건설협회",
    purpose: "신소재(FRE 등) 건설기술, 공법 및 지침 등에 관한 연구와 정책제안을 통해 국가경쟁력을 강화하고 건설산업 발전을 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2024-06-17",
    name: "사단법인 한국드론학회",
    purpose: "드론 학제적 접근과 연구활성화를 통해 국내 산업계, 지역사회 등과 적극적 정보교류로 국내 드론산업 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2024-07-14",
    name: "사단법인 외국인 이민자 주거지원을 위한 시민들의 모임",
    purpose: "외국인 이민자 주거지원을 목적으로 대상사 발굴 및 상담, 주거서비스 지원 및 연계, 교육 및 네트워크 홍보를 통한 주거정책 지원",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2024-12-23",
    name: "사단법인 한국온라인자동차매매정보제공업협회",
    purpose: "온라인 자동차 매매정보 제공의 활성화, 자동차 관련 정보의 원활한 제공",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2024-12-23",
    name: "사단법인 온라인내차팔기협회",
    purpose: "온라인 자동차 매매정보 제공의 진흥과 발전 추구",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2024-12-26",
    name: "사단법인 한국국토교통데이터진흥협회",
    purpose: "ㅇ(기능) 국토 및 교통분야 데이터에 대한 ①비즈니스 발굴을 위한 회원간의 교류 ②포럼·세미나 개최 등을 통한 소통, ③데이터 개방 정책 제안 등ㅇ(목적)국토 및 교통 분야 데이터 이용 촉진을 통해 데이터 기업의 진흥을 이끌고 국토 및 교통 분야 데이터 산업 발전지원",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2025-02-03",
    name: "사단법인 철도승강장안전문기술협회",
    purpose: "철도승강장안전문 기술기준 및  전문기술인력양성, 유지관리품질향상 등 안전확보",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2025-01-20",
    name: "사단법인 한국드론배송협회",
    purpose: "드론 배송 관련 연구와 산.학.연의 활발한 교류를 통해 안전하고 체계적인 배송 서비스 확산 및 국내 드론 산업 발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2025-02-03",
    name: "재단법인 카카오모빌리티 상생재단",
    purpose: "모빌리티산업의 건전한 발전 도모하고, 모빌리티 사업자 및 종사자의 수익 및 복지증진과 이용자의 교통편익 증진 도모",
    law: "-",
    type: "재단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2025-04-25",
    name: "사단법인 한국녹색플랜연구원",
    purpose: "국내공원의 표준적인 조성·개발·관리 방법 연구, 학술연구, 연구사업 및 정책 제안을 통한 공원·조경분야의 지속적인 발전 도모",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2025-07-09",
    name: "사단법인 한국공항학회",
    purpose: "공항 및 비행장 산업 관련 학술과 기술을 연구, 응용하여 정책 및 기술발전을 통해 사회적 공익 증진에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2025-07-09",
    name: "사단법인 건축시공기술사회",
    purpose: "건축시공분야 정책개발 및 관련 건축법령의 연구 및 정책 제안을 통해 건축산업 수요발전에 기여",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
  ExcelRowData(
    permitDate: "2025-07-21",
    name: "사단법인 한국건설감정사회",
    purpose: "건설감정 세미나 개최, 건설감정 교육 및 교재 편찬 발행, 건설감정의 학술연구 지원사업 등",
    law: "-",
    type: "사단",
    remit: "국토교통부",
  ),
];
