import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> mssRawData = [
  ExcelRowData(
    permitDate: "1962-07-09",
    name: "중소기업중앙회",
    purpose: "-",
    law: "-",
    type: "사단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1980-12-10",
    name: "한국중소기업학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1986-07-30",
    name: "한국경영기술지도사회",
    purpose: "-",
    law: "-",
    type: "사단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1987-02-28",
    name: "한국표면공학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1989-09-27",
    name: "한국벤처캐피탈협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1993-10-28",
    name: "경영기술개발원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1995-05-29",
    name: "광주광역시경제고용진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1995-06-01",
    name: "중소기업융합중앙회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1995-06-20",
    name: "대전일자리경제진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1995-12-16",
    name: "벤처기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1996-03-19",
    name: "경기신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1996-05-15",
    name: "경남신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1996-06-24",
    name: "광주신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1996-07-05",
    name: "제주경제통상진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1996-11-07",
    name: "대구신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1996-11-12",
    name: "전라북도 경제통상진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1997-04-01",
    name: "대전신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1997-05-09",
    name: "한국원적외선협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1997-06-16",
    name: "부산신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1997-06-24",
    name: "경기도경제과학진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1997-07-22",
    name: "한국산업용재협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1997-09-04",
    name: "충청북도기업진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1997-11-27",
    name: "경상북도 경제진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1997-12-05",
    name: "한국중소기업경영자협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1997-12-26",
    name: "부산경제진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-01-09",
    name: "한국산학연협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-02-03",
    name: "인천신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-02-25",
    name: "한국중소유통연구센터",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-03-31",
    name: "서울경제진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-06-03",
    name: "대덕이노폴리스벤처협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-06-08",
    name: "중소기업혁신전략연구원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-07-29",
    name: "한국벤처산업연구원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-09-17",
    name: "충남신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-11-06",
    name: "한국여성벤처협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-12-02",
    name: "충남경제진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-12-15",
    name: "한일인재기술협력기구",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1999-03-08",
    name: "울산 경제진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1999-04-10",
    name: "강원신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1999-04-15",
    name: "충북신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1999-06-16",
    name: "서울신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1999-07-07",
    name: "국제벤처네트워크",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1999-07-10",
    name: "한국여성경제인협회",
    purpose: "-",
    law: "-",
    type: "사단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1999-10-13",
    name: "경기벤처기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1999-10-19",
    name: "한국소호진흥협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2000-01-25",
    name: "벤처리더스클럽",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2000-03-22",
    name: "경북신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2000-04-11",
    name: "울산신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2000-05-25",
    name: "한국장애인기업협회",
    purpose: "-",
    law: "-",
    type: "비영리민간단체,사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2000-12-27",
    name: "한국기술벤처재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2001-02-26",
    name: "중소기업신지식경영인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2001-03-15",
    name: "한국경영컨설팅협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2001-06-14",
    name: "전남신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2001-07-09",
    name: "한국소기업소상공인협회",
    purpose: "-",
    law: "-",
    type: "비영리민간단체,사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2001-08-26",
    name: "한국학생복산업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2001-09-10",
    name: "한국소자본창업컨설팅협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2001-10-19",
    name: "초당벤처포럼",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2002-09-02",
    name: "한국창업경영컨설팅협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2002-12-06",
    name: "전북신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2002-12-10",
    name: "한국과학기술산업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2002-12-31",
    name: "중소기업기술혁신협회(INNO-BIZ)",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2003-08-04",
    name: "제주신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2003-12-26",
    name: "중소기업경영전략연구원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2004-01-08",
    name: "한국기업협력협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2004-05-13",
    name: "중기회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2004-12-01",
    name: "대구경북첨단벤처기업연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2005-02-22",
    name: "중소기업진흥회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2005-03-08",
    name: "한국전략경영학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2005-09-26",
    name: "한국렌탈협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2005-09-30",
    name: "한국경제인연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2005-10-18",
    name: "한국경영컨설팅학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2006-02-02",
    name: "한국생활용품소상공인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2006-03-20",
    name: "한국특설판매상공인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2006-05-17",
    name: "전국상인연합회",
    purpose: "-",
    law: "-",
    type: "사단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2006-05-18",
    name: "한국장애경제인협회",
    purpose: "-",
    law: "-",
    type: "특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2006-05-26",
    name: "한국벤처창업학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2006-09-06",
    name: "한국컴퓨터판매인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2006-10-02",
    name: "전국경제진흥원협의회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2006-12-20",
    name: "전라남도 중소기업일자리경제진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2006-12-28",
    name: "한국창업교육협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2007-01-12",
    name: "중소기업시대포럼",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2007-04-03",
    name: "부산벤처기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2007-04-26",
    name: "한국웨딩산업진흥협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2007-04-27",
    name: "한국중소기업경영진흥협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2007-10-01",
    name: "여성기업종합지원센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2008-01-24",
    name: "글로벌네트워크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2008-01-25",
    name: "장애인기업종합지원센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2008-02-29",
    name: "유통과 미래",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2008-01-29",
    name: "중소자영업총연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2008-03-31",
    name: "한국중소화학기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2008-09-05",
    name: "한국자동차외장관리협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2008-09-17",
    name: "경기중소벤처기업연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2008-12-17",
    name: "한국창업학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2008-12-22",
    name: "1인 창조기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2008-12-31",
    name: "한국베어링판매협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2009-01-12",
    name: "한국글로벌최고경영자협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2009-01-13",
    name: "한국중소기업무역활성화협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2009-06-12",
    name: "동북아시장대외교류원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2009-07-29",
    name: "한국소상공인마케팅협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2009-09-03",
    name: "한국유통경영학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2009-10-28",
    name: "한국정보통신AS산업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2010-01-08",
    name: "한국소상공인학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2010-01-11",
    name: "프랜차이즈시스템연구소",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2010-02-09",
    name: "한국신용카드네트워크",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2010-04-20",
    name: "한국유통물류정책학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2010-04-27",
    name: "한국남성패션문화협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2010-05-07",
    name: "한국경영혁신중소기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2010-06-05",
    name: "중소기업융합학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2010-08-09",
    name: "한국창업경영연구원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2010-10-21",
    name: "한국청년기업가정신재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2010-12-30",
    name: "국제중소유통학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-01-31",
    name: "충북우수중소기업협의회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-02-07",
    name: "한국창업보육협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-03-21",
    name: "한국티인스트럭터협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-03-31",
    name: "한국전통시장연구포럼",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-04-04",
    name: "한국고시원협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-04-07",
    name: "한국디자인경영협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-04-18",
    name: "중소기업우수제품판로개척연합",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-04-20",
    name: "한국소상공인컨설팅협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-05-18",
    name: "대전충청CTO포럼",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-05-31",
    name: "충청미래연구원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-06-09",
    name: "온라인컨텐츠유통업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-07-25",
    name: "대구경북온라인셀러협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-08-03",
    name: "재기중소기업개발원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-08-03",
    name: "한국고시원업중앙회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-08-09",
    name: "한국전자칠판협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-08-24",
    name: "김창준 미래한미재단",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-11-02",
    name: "동해시장상권활성화재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-12-12",
    name: "한국앱융합산업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-12-16",
    name: "대구경북성공CEO포럼",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-12-22",
    name: "한국스마트컨설팅협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2011-12-26",
    name: "창원시상권활성화재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-01-13",
    name: "한국소공인진흥협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-01-13",
    name: "한국뷰티산업진흥협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-01-19",
    name: "국제뷰티산업교역협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-04-13",
    name: "성남시 상권활성화재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-04-10",
    name: "광주전남벤처기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-04-16",
    name: "중소기업사랑나눔재단",
    purpose: "-",
    law: "-",
    type: "공익재단",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-04-17",
    name: "대경벤처창업성장재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-04-18",
    name: "동그라미재단",
    purpose: "-",
    law: "-",
    type: "공익재단",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-04-30",
    name: "한국전통시장학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-09-10",
    name: "한국엔젤투자협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-09-21",
    name: "국제중소기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-11-13",
    name: "카이트창업가재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2013-03-15",
    name: "한국재도전중소기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2013-04-11",
    name: "대전충남글로벌중소기업경제교류회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2013-05-09",
    name: "글로벌창업네트워크",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2013-07-03",
    name: "한국모바일기업진흥협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2013-07-30",
    name: "공정사회를 위한 변호사 모임",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2013-08-08",
    name: "더씨이오창업경영협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2013-09-05",
    name: "전통시장 서민경제 살리기 국민운동본부",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2013-10-04",
    name: "광주.전남여성벤처협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2013-12-10",
    name: "대전세종충남프랜차이즈협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-01-06",
    name: "인액터스 코리아",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-01-28",
    name: "한국기업회생경영협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-02-27",
    name: "중소기업미래경영원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-03-24",
    name: "한국인적자원개발학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-04-24",
    name: "아셈중소기업친환경혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-04-30",
    name: "소상공인연합회",
    purpose: "-",
    law: "-",
    type: "특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-08-13",
    name: "엔케이경제인연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-09-29",
    name: "한국서비스경영개발협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-10-14",
    name: "글로벌M&A협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-11-10",
    name: "한국컨설팅학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-11-18",
    name: "의정부시 상권활성화재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-01-06",
    name: "한국뿌리산업인력지원협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-01-21",
    name: "한국키움경제포럼",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-01-29",
    name: "한국장수기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-01-29",
    name: "한국가족기업 연구원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-03-05",
    name: "앙트러프러너십교육원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-03-19",
    name: "한국헤어케어칼라협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-04-02",
    name: "중소기업을 돕는 사람들",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-04-10",
    name: "인천소기업소상공인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-04-21",
    name: "한국청년멘토링협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-05-15",
    name: "글로벌창업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-05-18",
    name: "한국창업진흥협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-05-27",
    name: "한국중소기업협업진흥협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-06-09",
    name: "한국M&A진흥협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-09-09",
    name: "한국소공인학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-09-18",
    name: "대구경북 중소기업 무역인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-09-23",
    name: "지기지우2모작그룹",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-10-14",
    name: "중소기업경영개선협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-10-14",
    name: "국제뷰티화장품산업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-12-24",
    name: "한국중소기업프랜차이즈협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-01-06",
    name: "한국가족기업학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-01-13",
    name: "한국헤어디자인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-01-13",
    name: "소상공인연구원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-02-12",
    name: "한국기업혁신진흥원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-02-16",
    name: "케이비즈중우회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-05-27",
    name: "소상공인방송정보원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-05-30",
    name: "한국스타트업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-06-04",
    name: "한국융합기술경영협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-06-07",
    name: "대구전통시장진흥재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-06-08",
    name: "피엠전문가협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-06-20",
    name: "중소기업융합대구경북연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-07-19",
    name: "한국창업멘토협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-08-03",
    name: "한국펫산업수출협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-08-23",
    name: "한국폐업지원희망정책협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-09-08",
    name: "윤민창의투자재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-10-14",
    name: "자랑스러운 중소기업인 협의회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-12-28",
    name: "한국가구소공인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-01-09",
    name: "한국푸드트럭협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-02-01",
    name: "한국지식경영인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-07-08",
    name: "한국구조조정회생지원협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-02-17",
    name: "국제차세대융합기술학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-04-06",
    name: "행복한성공",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-06-02",
    name: "네트워크고리",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-06-27",
    name: "시니어벤처협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-06-27",
    name: "한국마트협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-07-20",
    name: "케이에스콘컨설팅지원단",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-09-05",
    name: "국제중소기업수출협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-09-08",
    name: "벽지발전협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-09-29",
    name: "전국중소유통상인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-11-13",
    name: "뷰티창업경영전문가협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-11-01",
    name: "중소기업융합경기연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-12-05",
    name: "글로벌중소기업지원협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-12-22",
    name: "초기투자액셀러레이터협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-01-12",
    name: "한국중소벤처무역협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-02-05",
    name: "한국벤처혁신학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-03-27",
    name: "전국중소기업중소상공인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-03-27",
    name: "한국정책경영연구원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-04-02",
    name: "전국편의점가맹점협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-04-03",
    name: "한국펫산업연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-04-09",
    name: "코리아스타트업포럼",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-04-11",
    name: "대한의류수선리폼협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-05-11",
    name: "한국사회과학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-05-29",
    name: "한국메이커스진흥협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-05-31",
    name: "한국화장품수출협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-05-31",
    name: "(사)K뷰티인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-06-14",
    name: "한국소공인단체연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-06-20",
    name: "한국글로컬마케터양성협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-06-21",
    name: "청년창업네트워크프리즘",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-08-02",
    name: "한국물기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-10-02",
    name: "지식일자리포럼",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-10-11",
    name: "한국SNS커머스협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-10-11",
    name: "청년벤처CEO협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-10-30",
    name: "시니어공유경제연구원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-11-05",
    name: "글로벌기업가정신협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-12-07",
    name: "블록체인기술진흥협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-12-21",
    name: "중소기업혁신개발원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-12-27",
    name: "한국창업문화진흥협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-01-07",
    name: "한국소상공인교육진흥원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-01-16",
    name: "넥스트챌린지",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-09-05",
    name: "대구창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-11-11",
    name: "경북창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-11-19",
    name: "전북창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-12-09",
    name: "대전창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-01-16",
    name: "인천창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-02-26",
    name: "울산창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-03-10",
    name: "충북창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-03-12",
    name: "충남창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-03-19",
    name: "제주창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-03-20",
    name: "경기창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-03-31",
    name: "경남창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-04-03",
    name: "전남창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-04-10",
    name: "강원창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-05-13",
    name: "부산창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-06-23",
    name: "광주창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-07-24",
    name: "서울창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-08-12",
    name: "세종창조경제혁신센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-04-28",
    name: "창조경제혁신센터협의회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2015-02-26",
    name: "한국창조경영인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2013-10-24",
    name: "창조벤처융합협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-07-06",
    name: "연구소4점0",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-04-15",
    name: "청년창업가협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2006-12-07",
    name: "한국알아이씨협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2010-12-30",
    name: "한국지역특화산업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2006-06-22",
    name: "한국테크노파크진흥회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-08-27",
    name: "경북테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2003-12-24",
    name: "충북테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-12-02",
    name: "대구테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2000-06-28",
    name: "경남테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-09-17",
    name: "경기테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2003-12-26",
    name: "전북테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2003-01-28",
    name: "울산테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1999-01-15",
    name: "충남테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1999-12-18",
    name: "부산테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2003-12-24",
    name: "전남테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1999-12-17",
    name: "광주테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2003-12-24",
    name: "강원테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1998-06-18",
    name: "인천테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2000-02-28",
    name: "포항테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2005-01-10",
    name: "경기대진테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2004-12-17",
    name: "서울테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2002-12-26",
    name: "대전테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2010-08-26",
    name: "제주테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2005-11-16",
    name: "한국지역산업진흥학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1994-01-17",
    name: "한경협중소기업협력센터",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-03-26",
    name: "밥일꿈",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-02-03",
    name: "한국강소기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-12-28",
    name: "한국블록체인스타트업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-02-21",
    name: "제주스타트업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-02-21",
    name: "한국냉난방기유지관리협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-03-21",
    name: "전통시장육성재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-04-18",
    name: "전국청년상인네트워크",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-05-02",
    name: "한중연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-05-02",
    name: "한-베트남중소기업교류협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2012-08-16",
    name: "동반성장연구소",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-05-27",
    name: "한국빨래방협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-06-10",
    name: "동반성장기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-06-14",
    name: "대한뷰티산업진흥연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-06-19",
    name: "국제모발연구협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-06-19",
    name: "한국아트앤뷰티연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-06-18",
    name: "헤이스타트업",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-06-28",
    name: "한국커리어패스협의회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-07-03",
    name: "세종테크노파크",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-07-03",
    name: "창업인재경영협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-07-15",
    name: "한국스마트휴먼테크협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-08-12",
    name: "재기희망지원협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-10-01",
    name: "해운대상권활성화재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-06-25",
    name: "단디벤처포럼",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-08-12",
    name: "한국반려동물기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-08-22",
    name: "한국스마트데이터협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-08-22",
    name: "한국중소스마트혁신협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-09-03",
    name: "중국한국인 기업가협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-09-09",
    name: "경청",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-09-11",
    name: "한국간편결제진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2014-10-21",
    name: "대전세종충남여성벤처협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-04-23",
    name: "중소기업융합 대전세종충남연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-06-27",
    name: "정선군상권활성화재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2018-04-27",
    name: "중소기업미래발전협의회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2016-08-11",
    name: "글로벌청년창업가재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-10-21",
    name: "영비즈니스리더스네트워크",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-11-15",
    name: "한국자영업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-11-12",
    name: "청소년행복재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-12-16",
    name: "인플루언서경제산업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-12-23",
    name: "통신서비스소상공인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-12-30",
    name: "기업가정신학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-12-30",
    name: "중소기업정책개발원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-01-02",
    name: "한국상생협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-12-16",
    name: "한국창업기업가협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-01-17",
    name: "부산메이커스협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-01-22",
    name: "글로벌멘토링협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2017-12-27",
    name: "한국주방유통협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-03-04",
    name: "중소벤처기업정책학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-03-12",
    name: "한국소공인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-11-12",
    name: "대전세종충남 소상공인협동조합진흥원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2019-12-17",
    name: "군산시 상권활성화재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-03-13",
    name: "스타트업 기업인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-03-13",
    name: "대구경북창업포럼협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-03-25",
    name: "대구경북 차세대리더스클럽",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-04-10",
    name: "한국중소기업발전협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-04-17",
    name: "한국청년스타트업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-04-17",
    name: "한국온라인플랫폼비즈니스상생협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-05-12",
    name: "구리시 상권활성화재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-05-13",
    name: "한중경제통상진흥원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-06-01",
    name: "공정거래지원협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-06-03",
    name: "대한민국 청년 스타트업 네트워크",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-07-03",
    name: "경남투자경제진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-07-23",
    name: "한국스타트업콘텐츠진흥협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-07-24",
    name: "한국소상공인협동조합연맹",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-08-11",
    name: "뷰티산업소상공인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-09-07",
    name: "아시아혁신 및 기업가정신학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-09-07",
    name: "중소기업글로벌육성협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-10-20",
    name: "스마트제조혁신협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-10-27",
    name: "한국초기투자기관협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-11-05",
    name: "아시아중소기업학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-11-27",
    name: "한국장애인상공인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-12-11",
    name: "한국인공지능제조이니셔티브",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-12-10",
    name: "연제구상권활성화재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-01-21",
    name: "중소기업융합 충북연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-03-23",
    name: "대전세종경영시스템협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2020-07-15",
    name: "대전세종에스엔에스감성진흥원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-02-22",
    name: "한국수출기업발전지원협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-02-25",
    name: "가족기업학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-02-26",
    name: "코스타트업",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-02-25",
    name: "여성소상공자영업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-03-16",
    name: "전국자영업소상공인중앙회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-04-16",
    name: "여성스타트업 포럼",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-05-27",
    name: "한국크리에이터진흥협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-05-31",
    name: "차세대 기업인 클럽",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-06-01",
    name: "대경신산업연구협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-06-09",
    name: "한국판매자보호협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "1997-06-24",
    name: "강원특별자치도경제진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-04-22",
    name: "사단법인 한국임팩트금융민간자문단",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-06-30",
    name: "한국보청기판매자협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-07-08",
    name: "한국중소상인기업진흥원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-07-28",
    name: "사단법인 케이시니어협회(K-시니어협회)",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-08-27",
    name: "재단법인 오렌지플래닛 창업재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-10-06",
    name: "한국장애인기업진흥회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-10-19",
    name: "한국커피로스터연합",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-11-04",
    name: "세종신용보증재단",
    purpose: "-",
    law: "-",
    type: "재단법인,특수법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2021-11-08",
    name: "한국산업세탁협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-01-05",
    name: "재단법인 문경시상권활성화재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-01-17",
    name: "아태지역경제연구원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-02-03",
    name: "한국중소벤처디지털혁신협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-02-18",
    name: "전국스마트홍보배달대행소상공인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-02-18",
    name: "국제발건강전문가협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-02-18",
    name: "사단법인 부산울산경남여성벤처협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-02-23",
    name: "전국지역및골목상권활성화협의회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-03-08",
    name: "한국이에스지경영개발원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-03-23",
    name: "한국상권총연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-03-24",
    name: "재단법인 진도군상권활성화재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-05-20",
    name: "한국창업융합컨설팅 학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-06-23",
    name: "벤처한림회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-07-05",
    name: "사단법인 세종벤처기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-07-06",
    name: "전국소기업총연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-07-06",
    name: "한국가업승계협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-07-20",
    name: "사단법인 한중글로벌협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-07-29",
    name: "한국스타트업전문가협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-08-30",
    name: "로컬브랜드포럼",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-09-29",
    name: "한국뷰티화장품연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-10-26",
    name: "중소기업경제진흥원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-11-01",
    name: "중소기업‧상공인희망트리",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-11-15",
    name: "사단법인 한국팹리스산업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-12-20",
    name: "혁신과금융포럼",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-12-19",
    name: "사단법인 한국스케일업팁스협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-01-26",
    name: "청년지식융합협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-02-10",
    name: "사단법인 한국혁신산업학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-02-24",
    name: "중소벤처기업 코칭컨설팅협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-03-02",
    name: "사단법인 스타트업규제혁신포럼",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-05-03",
    name: "사단법인 한국경제분석연구원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-05-11",
    name: "한국미래산업진흥재단",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-07-13",
    name: "스마트산란계산업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-07-31",
    name: "사단법인 온라인유통MD협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-08-07",
    name: "한국벤처기업탄소중립선도협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-08-08",
    name: "한국지속가능경영협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-09-22",
    name: "한국지속가능소셜벤처협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2022-07-28",
    name: "재단법인 진주시상권활성화재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-10-24",
    name: "사단법인 수리·용역 수탁사업자협의회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-11-09",
    name: "국가경제발전진흥원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-11-24",
    name: "국가경제전략연구원",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-11-24",
    name: "학제간경영학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-11-24",
    name: "히든기업경영전략연구소",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-11-29",
    name: "광주전남창업지원사업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-11-23",
    name: "미라클 클럽",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2023-12-11",
    name: "재단법인 세종일자리경제진흥원",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-01-31",
    name: "광주전남기술경영진흥회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-02-01",
    name: "사단법인 스타트업 커피챗",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-02-06",
    name: "한국스마트혁신기업가협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-01-30",
    name: "한국커피머신코디네이터협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-01-30",
    name: "전국주택관련인테리어소상공인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-02-19",
    name: "올대경온라인셀러연합",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-02-20",
    name: "브랜드지식재산권보호협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-02-27",
    name: "한국화장실산업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-03-19",
    name: "전국 도시형소공인 연합회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-04-01",
    name: "안산시 상권활성화재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-04-01",
    name: "사단법인 온라인유통센터",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-04-29",
    name: "한국스타트업피봇팅협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-05-17",
    name: "아시아비즈니스혁신학회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-07-17",
    name: "사단법인 시장경영혁신협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-08-07",
    name: "사단법인 대한민국백년기업협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-08-29",
    name: "사단법인 미주한인상공회의소총연합회한국지회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-09-30",
    name: "한국자율제조플랫폼협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-10-28",
    name: "사단법인 한국무역전문위원협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2024-12-26",
    name: "재단법인 한국아카이브재단",
    purpose: "-",
    law: "-",
    type: "재단법인",
    remit: "중소벤처기업부",
  ),
  ExcelRowData(
    permitDate: "2025-02-10",
    name: "사단법인 한국이주기업인협회",
    purpose: "-",
    law: "-",
    type: "사단법인",
    remit: "중소벤처기업부",
  ),
];
