import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> moelRawData = [
  ExcelRowData(
    permitDate: "1964-07-06",
    name: "대한산업보건협회",
    purpose: "작업환경측정, 건강진단, 교육, 보건관리대행 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1964-07-06",
    name: "대한산업안전협회",
    purpose: "안전관리대행, 안전검사 및 안전인증, 기술지도 및 안전교육 실시 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1967-06-10",
    name: "한국의류기술진흥협회",
    purpose: "의류기능 개발 및 국제기술교류개발",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1970-12-22",
    name: "한국경영자총협회",
    purpose: "사용자에 대한 노동관계 조정 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1971-10-27",
    name: "한국노동연구소",
    purpose: "노동관계 제문제 연구분석",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1974-08-26",
    name: "서울예술실용전문학교",
    purpose: "직업능력개발훈련법인 (국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1975-05-12",
    name: "한국귀금속보석기술협회",
    purpose: "귀금속보석업계의 기술향상과 발전을 도모",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1977-11-18",
    name: "한국외국어평가원",
    purpose: "실용 외국어, 한자 등의 활용능력 검정, 교육, 훈련",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1980-09-30",
    name: "동원복지재단",
    purpose: "소속 근로자를 위한 복지사업",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1985-05-08",
    name: "한국맞춤양복협회",
    purpose: "맞춤양복기술 및 양복업 종사자의 친목도모 및 기술개발",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1986-03-08",
    name: "한국안전학회",
    purpose: "안전 연구․조사, 학회지 및 도서 발간 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1986-06-17",
    name: "한국공인노무사회",
    purpose: "공인노무사 권익신장 및 취약계층 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1986-07-18",
    name: "한국산업훈련협회",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1986-11-26",
    name: "꿈을 이루는 재단",
    purpose: "청소년 비전제시 및 청년 해외일자리 지원, 진로지도 등 관련 사업 수행",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1987-03-30",
    name: "로이교육재단",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1988-01-23",
    name: "한국산업카운슬러협회",
    purpose: "산업카운셀링에 관한 위탁교육 및 실기교육",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1993-12-07",
    name: "국제기능개발협회",
    purpose: "기능인 능력개발 및 상호 협력 도모으로 국제교류 이바지",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1988-08-25",
    name: "한국인력개발원",
    purpose: "직업능력개발 프로그램 개발, 운영 및 인재양성",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1988-12-24",
    name: "한국직업능력개발원",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1988-12-24",
    name: "서울교육재단",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1989-05-03",
    name: "대덕인재개발원",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1987-05-16",
    name: "한국피아노조율사협회",
    purpose: "피아노제작 및 조율 관련 기술개발, 회원의 권익신장",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1989-07-07",
    name: "한국건설안전협회",
    purpose: "건설재해예방 기술지도 및 건설사업장 진단",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1989-06-14",
    name: "한국호텔관광교육재단",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1990-04-16",
    name: "중앙종합직업전문학교",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1990-07-16",
    name: "중앙노동경제연구원",
    purpose: "◦ 노사관계 및 노동문제 전반에 관한 조사 및 연구◦ 요양보호사 교육기관 설립 운영 - 간병인 교육, 간호보조원 교육",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1983-10-15",
    name: "노정회",
    purpose: "고용노동부 퇴직공무원의 친목 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1992-10-05",
    name: "국제노동법연구원",
    purpose: "국제노동기구와 그 협약권고에 관한 연구",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1992-10-13",
    name: "국제인재능력개발원",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1992-11-07",
    name: "온터두레회",
    purpose: "여성관련 직업개발사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1992-12-03",
    name: "상무대학직업전문학교",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1992-12-29",
    name: "한국능력개발원",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1992-12-29",
    name: "부산인재개발원",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1993-01-27",
    name: "대원산업기술교육원",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1993-01-27",
    name: "서울호서직업전문학교",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "34024",
    name: "현대산업직업전문학교",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1993-02-11",
    name: "아세아항공직업전문학교",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1993-02-24",
    name: "서울현대교육재단",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1993-05-21",
    name: "백제직업전문학교",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1993-07-10",
    name: "이찬",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1993-09-01",
    name: "대한민국명장회",
    purpose: "명장의 친목과 권익 도모, 기능 개발 향상",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1993-09-18",
    name: "전택노련복지협회",
    purpose: "택시근로자를 위한 장학사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1993-11-20",
    name: "원진직업병관리재단",
    purpose: "직업병확정자 자활사업, 위로금지급",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1993-12-07",
    name: "한국인적자원개발협회",
    purpose: "인적자원 개발을 통한 우수 인력 양성 및 직업능력개발",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1993-12-14",
    name: "한국세무직업전문학교",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1993-12-20",
    name: "(사)전국직업전문학교총연합회",
    purpose: "직업능력 개발 업무 지도, 자율적인 규제 및 상호협조",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1993-12-30",
    name: "한국산업기술개발원",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1994-03-24",
    name: "한국직업건강간호협회",
    purpose: "산업간호 학술 연구, 보건관리자 직무교육 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1994-06-07",
    name: "안전보호구협회",
    purpose: "우량보호구의 개발, 보급 및 제품검사 등 실시",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1994-09-17",
    name: "여성자원금고",
    purpose: "여성인력의 활용을 촉진하는 사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1994-10-28",
    name: "한국노동경제학회",
    purpose: "노동경제학 관련 연구조사 발표 및 보급",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1995-04-28",
    name: "노동인권회관",
    purpose: "근로자 인권 옹호 및 노동조합 운동 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1995-04-29",
    name: "미래인력연구원",
    purpose: "국내외 학술대회 및 학회 지원",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1995-06-10",
    name: "한국여성노동자회",
    purpose: "여성노동자들의 정치적, 경제적, 사회적 지위향상과 평등실현을 통한 인간다운 삶 실현",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1995-09-20",
    name: "한국ILO협회",
    purpose: "ILO관련 홍보활동 및 국제노동정세 자료수집 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1996-03-06",
    name: "세우방송예술직업전문학교",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1996-05-23",
    name: "안전생활실천시민연합",
    purpose: "안전의식 계몽, 안전관련 연구․정책 건의",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1996-07-16",
    name: "매경안전환경연구원",
    purpose: "안전보건․환경 조사․연구, 교육․홍보 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1996-09-11",
    name: "한국산업기술융합학회",
    purpose: "인재 양성 및 직업능력을 개발, 산업별 교류확대",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1996-09-13",
    name: "한국건설가설협회",
    purpose: "건설기자재 연구․시험, 성능검정",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1996-11-08",
    name: "한국산업보건학회",
    purpose: "산업보건교육 및 연구, 학회지 발간 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1996-11-11",
    name: "신한금융희망재단",
    purpose: "중소기업 인력 채용 지원사업을 수행함으로써 일자리 창출 및 실업난 해소",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1997-05-20",
    name: "원화",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1997-06-26",
    name: "한국산업구강보건원",
    purpose: "구강건강진단, 교육․상담, 학술연구 및 조사",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1997-07-08",
    name: "한국보석감정사협회",
    purpose: "보석감정인의  능력개발을 촉진, 전문인력 배출",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1997-11-03",
    name: "한국노동문화예술협회",
    purpose: "근로자의 문화생활 향상 및 예술활동 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1998-02-24",
    name: "한국산업안전·보건지도사협회",
    purpose: "산업안전․위생 기술용역, 기술지도, 교육 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1998-04-30",
    name: "전남인력개발원",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1998-04-30",
    name: "일과 건강",
    purpose: "산업안전교육·상담 및 조사·연구, 정책건의",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1998-06-10",
    name: "여성인력개발협회",
    purpose: "여성능력개발 및 여성 전문인력 양성-여성정책개발 및 권익사업을 통한여성의 사회적 지위 향상",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1998-06-29",
    name: "한영교육재단 한국전기직업전문학교",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1998-09-07",
    name: "영진건설기술교육원",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1998-09-19",
    name: "한국아이티교육재단",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1998-09-25",
    name: "한국여성경영자총협회",
    purpose: "여성경영자의 경제적․사회적 활동여건 및 지위향상및 노사간의 이해증진을 통한 기업경영의 합리화 달성과 교육훈련사업을 통한여성의 인력개발",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1998-11-12",
    name: "대구직업전문학교",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1998-12-14",
    name: "한국플로리스트협회",
    purpose: "꽃 관련 장식 기술 개발 보급",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1998-12-21",
    name: "한국개선협회",
    purpose: "교육훈련 컨설팅을 통해 기업내 개선활동 도입 및 활성화",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1998-12-21",
    name: "한겨레일과사람연구소",
    purpose: "고용, 임금, 실업 등 노동시장정책과 관련된 조사연구와 정책 대안 제시",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1998-12-21",
    name: "한국경영교육협회",
    purpose: "기업교육 활성화와 정착을 위한 연구체계를 정립",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-02-18",
    name: "좋은친구 산업복지재단",
    purpose: "사회일반의 이익에 공여하기 위하여 산업복지사회건설에 기여",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-02-19",
    name: "BBS미용예술실용전문학교",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-03-05",
    name: "한국장애인고용안정협회",
    purpose: "지방장애인 기능경기대회, 장애인인식개선사업 수행 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-03-29",
    name: "근우회",
    purpose: "친목도모 및 근로자를 위한 복지사업, 보험사업의 조사, 연구사업 전개",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-04-03",
    name: "한국노동사회연구소",
    purpose: "노동운동 관련 문제 연구",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-04-12",
    name: "서울종합예술실용학교",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-04-29",
    name: "전국진폐재해자협회",
    purpose: "진폐 또는 그 합병증에 걸린 자의 권익보호, 복지후생 증진, 교육문화 향상,자녀 장학사업 및 진폐 또는 합병증의 예방 및 관리를 위한 필요한 사항 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-05-10",
    name: "인우회",
    purpose: "공공직업훈련기관 퇴직자를 위한 복리증진, 상부상조, 교육훈련 강사지원 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-05-31",
    name: "서연부설서강직업전문학교",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-06-12",
    name: "한국기능선수회",
    purpose: "우수한 기능보유자를 체계적 관리, 발굴, 육성",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-08-20",
    name: "영진",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-09-14",
    name: "대한안전경영과학회",
    purpose: "안전경영과학 연구 및 제도 정비, 정보교류 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-09-20",
    name: "한국직업교육재단",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-09-21",
    name: "일과 삶",
    purpose: "실업자 종합지원을 통한 실업자 자활 및 권익신장",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-12-17",
    name: "미래의동반자",
    purpose: "실업자 취업, 한미 관계 증진",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1999-12-28",
    name: "전북노동복지센터",
    purpose: "실업자 자활자립 및 권익신장 제고",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-01-02",
    name: "한국인사전문가협회",
    purpose: "인적자원관리 학자와 기업 인력관리 실무자들 간 공동 연구로 인적자원관리효율성 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-01-03",
    name: "한국인사관리학회",
    purpose: "인적자원의 효과적인 관리와 개발, 육성, 활용",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-01-11",
    name: "한국에이치알산업협회",
    purpose: "파견근로자 등의 고용 유지 및 근로조건 개선",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-02-11",
    name: "지구촌사랑나눔",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-02-14",
    name: "한국비서사무협회",
    purpose: "여성비서직 종사자의 권익향상 도모및 국제협력기구와의 교류증진 및 능력개발을 통한 여성비서직의 전문화와 지위향상",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-02-19",
    name: "한국산재장애인협회",
    purpose: "산재근로자의 권익보호",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-02-26",
    name: "한국선물포장디자이너협회",
    purpose: "선물포장기능인 양성 및 경제적 사회적 지위 향상",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-06-13",
    name: "대한산업인력개발원",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-07-10",
    name: "한국비정규노동센터",
    purpose: "비정규노동자의 삶의 질 향상 및 민주적노사관계 정립",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-07-10",
    name: "여수일과복지연대",
    purpose: "실업자와 저소득측의 경제적, 사회적 권익 신장",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-09-20",
    name: "한국전문자격협회",
    purpose: "직업교육훈련과 연계된 있는 자격 운영",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-09-20",
    name: "한국직업연구진흥원",
    purpose: "각종 직업분야의 민간자격 개발연구 및 교육",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-09-28",
    name: "고려직업전문학교",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-10-26",
    name: "대구대재단",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2000-12-30",
    name: "한국직업능력평가원",
    purpose: "지식정보화 사회의 요구에 부응하는 자격검정을 시행",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2001-01-20",
    name: "한국일용노동자복지협회",
    purpose: "일용근로자의 안정적인 복지시스템 확립을 통해 일용근로자의 삶의 질 향상및 권익신장",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2001-03-06",
    name: "한국고용노사관계학회",
    purpose: "고용 및 노사관계에 관한 학제적 연구",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2001-04-10",
    name: "한국산업연수원",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2001-06-08",
    name: "여성노동법률지원센터",
    purpose: "여성근로자에 대한 법률지원, 상담, 교육 등을 통한 권익보호 및 사회참여 활성화 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2001-07-06",
    name: "노동인권연대",
    purpose: "노동자와 실업자 저소득계층 권익옹호",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2001-07-23",
    name: "한국산업교육원",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2001-07-24",
    name: "한국자격진흥협회",
    purpose: "민간자격증의 체계적 보급과 직업수행 능력개발",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2001-08-21",
    name: "청년취업훈련센터",
    purpose: "직업능력개발훈련법인(국민평생 직업능력개발법 제32조)",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2001-09-11",
    name: "미래를 준비하는노동사회교육원",
    purpose: "근로자와 시민들을 대상으로 교육 실시",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2001-10-09",
    name: "한국사회보험연구소",
    purpose: "사회보험제도 연구 및 조사",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2001-11-19",
    name: "한국산업의학연구소",
    purpose: "특수 및 일반건강진단, 석면조사 등",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2001-11-21",
    name: "장애인직업안정연구원",
    purpose: "장애인고용관련 간행물 발간 등을 통한 장애인 인식개선사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2001-12-21",
    name: "한국안전전문기관협의회",
    purpose: "기술정보자료 교류, 안전진단 및 위험성평가, 학술대회 개최, 안전업무 개선및 연구 등 안전기술 개발 촉진",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2002-01-29",
    name: "한국노동복지센터",
    purpose: "노동자의 복지향상을 위한 정책개발 연구사업, 복지정보공유체계 구축 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2002-06-08",
    name: "한국특수건강진단협회",
    purpose: "근로자건강진단제도 개선방안 조사․연구",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2002-07-02",
    name: "아주산업의학연구소",
    purpose: "작업환경측정, 건강진단, 보건관리대행",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2002-07-30",
    name: "한국재료조직학회",
    purpose: "재료조직관련 기술개발, 재료조직평가 직종 전문기술 인력양성",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2002-10-08",
    name: "한국크레인협회",
    purpose: "크레인 및 건설장비에 대한 기술개발과 표준화 보급, 기술지도 및 컨설팅 검사,안전교육 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2002-11-19",
    name: "제일산업의학연구소",
    purpose: "특수 및 일반건강진단, 직업성질환 연구 등",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2002-12-24",
    name: "한국장애인중심기업협회",
    purpose: "장애인고용사업장 활성화를 통한 장애인의 직업안정 및 신규고용창출",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2003-02-11",
    name: "실업극복인천본부",
    purpose: "인천지역의 취약계층 및 저소득층 실업극복",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2003-03-25",
    name: "한국자격진흥원",
    purpose: "자격소지자의 발전을 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2003-05-06",
    name: "경남고용복지센터",
    purpose: "저소득 비정규직 노동자와 실업자의 고용안정 및 복지향상",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2003-06-03",
    name: "노사공포럼",
    purpose: "노사포럼지 발간",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2003-06-03",
    name: "참여성노동복지터",
    purpose: "영세사업장 여성노동자의 가정과 직장생활 상담, 노동환경 개선연구 등을 통해그들의 사회적 지위와 삶의 질 향상에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2003-06-20",
    name: "한국이러닝협회",
    purpose: "이러닝 관련 기업의 경쟁력 확보, 회원사간 정보 교류 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2003-06-23",
    name: "함께일하는재단",
    purpose: "실업극복 활동을 지원하여 품위있는 노동의 확보, 국민의식 개혁 및 공동체성회복을 통한 사회통합",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2003-07-23",
    name: "전국산재장애인단체연합회",
    purpose: "산재근로자의 권익보호",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2003-07-23",
    name: "원진산업재해자협회",
    purpose: "원진레이온 피폭자 상호부조 및 권익보호",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2003-08-22",
    name: "대전실업극복시민연대일어서는사람들",
    purpose: "취약계층 및 실업인 생활 안정",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2003-09-29",
    name: "대한민국기능전승자회",
    purpose: "기능전승자의 친목 도모, 기능개발, 전통 기능 전승 보전사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2003-10-27",
    name: "한국산업보건환경연구소",
    purpose: "직업병, 근골격계질환 예방, 진단사업 등",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2003-12-10",
    name: "조리기능장려협회",
    purpose: "조리기능인의 직업능력 향상",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2003-12-31",
    name: "한국장애인e-Work협회",
    purpose: "온라인원격분야 직종에 대한 장애인의 고용촉진 및 직업능력개발지원에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2002-01-21",
    name: "디지털노동문화복지센터",
    purpose: "◦ 근로자를 위한 디지털상 문화활동과 보급사업.연구.조사.개발사업◦ 근로의욕증진을 위한 교육.기획.출판사업 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2004-02-11",
    name: "한국항만운송노동연구원",
    purpose: "노동관계 문제 조사 연구",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2004-07-05",
    name: "외국인근로자문화센터",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2004-07-26",
    name: "여성이 만드는 일과 미래",
    purpose: "여성의 경제활동과 자기 경영능력 제고를 통하여 여성의 사회참여 확대와리더쉽 향상에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2004-11-01",
    name: "나눔고용복지재단",
    purpose: "취약계층 근로자 및 이주근로자를 위한 종합적인 복지사업을 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2004-12-03",
    name: "국제직업능력개발교류협회",
    purpose: "민간차원의 국제간 직업능력개발분야 상호교류 활성화",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2004-12-07",
    name: "한국산재장애인복지진흥회",
    purpose: "산재근로자의 권익보호",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2004-12-07",
    name: "전국보험사무대행기관연합회",
    purpose: "보험사무대행기관의 권익보호와 제도연구",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2004-12-07",
    name: "한국산재장애인복지협회",
    purpose: "산재장애인의 권익보호",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2004-12-07",
    name: "한국산재장애인근로자협의회",
    purpose: "산재장애인 및 산재근로자의 권익보호",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2004-12-08",
    name: "일과 사람",
    purpose: "취약계층에 대한 지원을 통해 실업을 극복하고 양극화 해소",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2005-01-26",
    name: "한국직업상담협회",
    purpose: "직업상담에 관한 학술적인 연구와 전문성을 향상하여 직업상담의 학문적 발전도모와 직업상담사 활동을 증진시키기 위한 제반 지원 활동을 수행하며,직업상담의 확대 및 보급을 위한 각종 사업을 전개",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2005-02-19",
    name: "한국인력개발학회",
    purpose: "인적자원개발관련 연구, 창의적 성과와 생산성 향상 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2005-02-28",
    name: "전태일을따르는민주노동연구소",
    purpose: "참노동운동의 발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2005-03-04",
    name: "한국여성노동연구소",
    purpose: "근로여성 및 청소년에 관한 정책 및 근로환경 개선에 대한 조사연구",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2005-04-26",
    name: "외국인노동자와함께",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2005-08-17",
    name: "한국직업기술진흥원",
    purpose: "근로자 직업기술능력 진흥, 국내외 유관기관 인적, 학술적 교류",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2005-09-06",
    name: "한국이주노동자복지회",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2005-10-25",
    name: "한국진폐재해자협회",
    purpose: "진폐재해자 권익보호 및 복지향상 등 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-01-04",
    name: "한국코치협회",
    purpose: "“코칭”의 보급 및 저변확대",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-02-10",
    name: "동아건설퇴직자새출발지원센터",
    purpose: "동아건설(주) 퇴직(예정) 임직원들의 재취업 및 창업 등에 대한 정보제공과각종 교육 참여 등 새출발을 지원하며, 전현직 직원의 상부상조와 친목도모를통하여 생활안정과 복지증진에 기여",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-02-22",
    name: "미용능력개발협회",
    purpose: "미용기능인의 직업능력 개발향상, 기술능력 개발 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-02-28",
    name: "여성직업능력개발원",
    purpose: "여성이 사회에서 자기 능력을 발휘하고, 유효  적절한 직업을 선택할 수 있도록지원함으로써 여성직업능력의 극대화를 통해 자아발전 및 사회  발전 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-03-15",
    name: "일하는공동체",
    purpose: "실업자의 자활 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-03-29",
    name: "한국진폐재해재가환자협회",
    purpose: "진폐재해자 권익보호 및 복지향상 등 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-04-24",
    name: "금속산업사용자협의회",
    purpose: "회원상호간의 금속산업경영에 관한 정보교류",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-06-14",
    name: "나섬공동체",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-07-18",
    name: "한국미용직업교육협회",
    purpose: "미용관련 전문직업인의 정착과 직업능력개발연구 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-09-11",
    name: "국민일복운동본부",
    purpose: "여성들이 즐겁게 일할 수 있는 희망적인 사회를 만들어 국가의 정책에 부응하며여성의 미취업, 실업문제를 체계적으로 해결하고자 함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-09-19",
    name: "행복나눔재단",
    purpose: "급식센터 설립 및 자립지원",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-10-16",
    name: "전국고용서비스협회",
    purpose: "국가고용정책에 입각하여 직업소개사업자의 공동노력과 협력으로 산업발전에필요한 인력의 원활한 공급 및 수급균형을 도모하며, 직업소개사업의 자체자율정화를 주관하여 건전한 직업소개사업자가 육성될 수 있도록 지원함으로서국가산업발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-10-25",
    name: "제주외국인평화공동체",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-11-03",
    name: "대한제과제빵기술자협회",
    purpose: "제과, 제빵기술의 보급과 기능인의 권익보호",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-11-06",
    name: "한국제과기능장협회",
    purpose: "제과,제빵기술 향상, 제과기술과 장인정신 전수",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-11-28",
    name: "한국장애인IT고용협회",
    purpose: "장애인 및 사회적 취약계층의 정보격차 해소와 일자리 창출",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2006-12-15",
    name: "이주민과 함께",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-01-29",
    name: "한국안전관리사협회",
    purpose: "안전관리자 관련 조사 연구 및 교육 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "1992-10-15",
    name: "한국산업보건연구재단",
    purpose: "종합건강진단, 일반건강진단, 질병조기치료 및 재활 등",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-02-02",
    name: "한국인재뱅크",
    purpose: "고령자 고용촉진을 위한 취업 및 사회적 일자리 창출, 고용지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-03-16",
    name: "김태환기념사업회",
    purpose: "특수고용직 포함한 비정규직노동자 권리보호",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-04-13",
    name: "한국노동조합총연맹동우회",
    purpose: "노사관계 발전 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-05-18",
    name: "한국노동경제연구원",
    purpose: "노동관계문제 연구 분석",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-05-29",
    name: "경남이주민노동복지센터",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-07-02",
    name: "한국이에이피협회",
    purpose: "직장인 대상 상담 및 지원프로그램 개발, 상담전문가 인증 및 관리,관련 조사연구 등을 통한 근로복지향상에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-07-30",
    name: "한국산업재해보상보험학회",
    purpose: "산재보험 학술연구",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-08-28",
    name: "한국인적자원관리학회",
    purpose: "인사, 조직, 노사분야의 학제적 연구",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-09-19",
    name: "한국조정중재협회",
    purpose: "협상, 조정, 중재서비스 제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-10-01",
    name: "한국산재중앙법인단체연합",
    purpose: "산재단체간 교류",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-10-05",
    name: "다솜이재단",
    purpose: "취약계층 일자리 제공 및 간병서비스 제공",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-10-08",
    name: "충북사회교육센터",
    purpose: "취약계층 일자리 제공 및 간병서비스 제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-10-10",
    name: "한국외국인근로자복지봉사단",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-10-17",
    name: "희망을 나누는 사람들",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-10-30",
    name: "실업자지원협회",
    purpose: "실업자 생활 안정",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-11-07",
    name: "한국고용복지센터",
    purpose: "취약계층 일자리 창출 및 교육",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-12-20",
    name: "한누리",
    purpose: "자주학습 교육 및 평생교육",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2007-12-31",
    name: "한국사회적기업실천연구회",
    purpose: "사회적기업 모델개발 및 교육훈련",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-01-11",
    name: "미래산업보건의료재단",
    purpose: "산업보건 및 직업병 예방 연구개발 등",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-01-29",
    name: "한국사회서비스정책연구원",
    purpose: "사회서비스 발전 정책수립",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-03-04",
    name: "한국미용장협회",
    purpose: "미용 기술 발굴ㆍ개발, 국내외 홍보 및 미용인 권익보호 사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-03-05",
    name: "함께 하는 아시아 생명연대",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-03-11",
    name: "한국지역고용학회",
    purpose: "취약계층 일자리제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-04-01",
    name: "국제협력개발협회",
    purpose: "두피모발관리 분야에 종사하는 여성의 직업능력을 제고하여 전문가로 육성하고,회원간 체계적인 네트워크 구축, 직업의식 고취 등을 통하여 여성의 취업을촉진하며, 해외관련기관과의 국제교류를 통하여 최첨단 지식과 정보 제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-04-02",
    name: "사회적기업청람",
    purpose: "취약계층 일자리창출 및 농촌 일손 돕기",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-05-19",
    name: "한국산업위생협회",
    purpose: "산업위생 전문기술 연구용역 및 전문가양성, 각종 산업위생 연구개발 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-06-17",
    name: "한국이주노동재단",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-06-27",
    name: "한국사회적기업중앙협의회",
    purpose: "사회적기업 지원 및 협력강화",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-08-07",
    name: "노동법이론실무학회",
    purpose: "노동법에 대한 학술적 연구발표",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-06-30",
    name: "안산시흥시 근로자파견협회",
    purpose: "노동력 수급의 원활화, 노동시장 유연화와 기업 경쟁력 제고, 파견근로자의고용유지와 근로조건 개선 노력을 통하여 근로자파견사업의 건전한 발전을이룩함으로써 국가 산업발전에 이바지함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-09-05",
    name: "전남고용포럼",
    purpose: "취약계층 일자리제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-09-06",
    name: "서울고용포럼",
    purpose: "취약계층 일자리제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-09-09",
    name: "한국파독광부,간호사,간호조무사연합회",
    purpose: "과거 파독(派獨) 광부, 간호사, 간호조무사 출신 근로자의 복지 향상과 친목 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-09-23",
    name: "한국인재개발협회",
    purpose: "지식기반정보사회의 인재개발 전문가 네트워크 구축, 정책연구, 교육훈련 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-09-29",
    name: "해피웨이",
    purpose: "지역의 사회취약계층에게 일자리 제공 및 사회서비스 제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-10-16",
    name: "희망을 키우는 일터",
    purpose: "일자리 창출 및 사회서비스 제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-09-29",
    name: "우리가 꿈꾸는 세상",
    purpose: "취약계층 일자리 및 다양한 사회복지적 서비스 제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-10-17",
    name: "한국메이크업전문가직업교류협회",
    purpose: "국제적 정보교류로 메이크업산업의 발전과 업무영역 확대 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-10-17",
    name: "한국기능연합회",
    purpose: "기능장려 사업을 수행하여 우수 기능 인력을 발굴, 기능전수와 기술개발",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-10-20",
    name: "가경사회서비스지원센터",
    purpose: "취업취약계층 일자리 제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-10-27",
    name: "나비뜰동산",
    purpose: "취약계층 사회복지서비스 제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-11-26",
    name: "미래노사발전연대",
    purpose: "근로자의 권익증진 및 고용안정 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-12-04",
    name: "한국여성인적자원개발원",
    purpose: "인적자원 개발 활성화와 여성의 사회적 진출에 대한 사회적 인식 확대를 통한여성의 고용안정 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-12-19",
    name: "한국뷰티산업능력개발협회",
    purpose: "피부미용분야 학술, 교육활동, 연구활동",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2008-12-26",
    name: "국경없는세상",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2009-01-22",
    name: "한국안전기술협회",
    purpose: "위험기계․기구의 안전검사, 안전진단 및 안전교육 실시 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2009-02-12",
    name: "한걸음더",
    purpose: "사회취약계층 일자리 창출 및 사회복지서비스 제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2009-02-23",
    name: "네오위즈마법나무",
    purpose: "취업취약계층 교육사업",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2009-03-19",
    name: "한국화훼장식장애우교육협회",
    purpose: "장애인들에게 화훼장식연구와 강습을 통한 직업교육시행",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2009-05-12",
    name: "한국크리스천코치협회",
    purpose: "코칭 보급으로 자기주도 직업능력개발 지원, 양질의 코치 양성",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2009-05-21",
    name: "한국노동법학회",
    purpose: "노동법에 대한 학술적 연구발표",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2009-05-26",
    name: "국민노동정책교육개발원",
    purpose: "노동운동의 질적인 발전 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2009-06-24",
    name: "한국산업인재융합협회",
    purpose: "노동관계 각종 문제에 관한 조사연구",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2009-07-28",
    name: "한국HRD기업협회",
    purpose: "인적자원개발 관련 기업의 협력 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2009-10-19",
    name: "가족친화전략연구원",
    purpose: "양성평등 및 일․가정 양립을 지향하는 기업 및 사회 문화 창달, 일․가정양립제도의 조성 및 발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2009-10-20",
    name: "한국실천공학교육학회",
    purpose: "실천공학교육관련 학술활동 및 회원 상호간 친목 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2009-12-21",
    name: "한국전직지원협회",
    purpose: "회원사의 민간 취업지원인 전직지원 서비스를 적극 홍보하여 저변을 넓히고전문가 양성 및 선진수준의 전직지원서비스 프로그램 개발",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2010-01-20",
    name: "금융산업사용자협의회",
    purpose: "금융산업 사용자들에 대한 노동관계 조정, 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2010-01-25",
    name: "한국비교노동법학회",
    purpose: "노동관계법 관련 학술 연구 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2010-04-15",
    name: "한국장애인표준사업장협회",
    purpose: "장애인표준사업장의 시장경쟁력과 안정성을 제고",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2010-04-15",
    name: "한국근로장애인진흥회",
    purpose: "장애인에게 일자리를 제공하고 근로장애인의 근로의욕을 고취",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2010-04-21",
    name: "사랑나눔",
    purpose: "저소득층 및 실업자를 위한 종합적인 지원, 실업자 자활 및 저소득층 권익신장",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2010-05-20",
    name: "피플",
    purpose: "산재보험제도 학술 연구 및 교육",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2010-05-20",
    name: "광산진폐권익연대",
    purpose: "진폐재해자 권익보호 및 복지향상 등 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2010-06-01",
    name: "다문화가정인력개발센터",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2010-07-13",
    name: "씨즈(Seed:s)",
    purpose: "사회적기업 모델발굴 및 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2010-11-15",
    name: "한국HRM협회",
    purpose: "직무분석, 직무 표준화 작업을 통해 중소기업에 적합한 IT기반의인사시스템 구축을 지원하여 직무별 인력수요를 정확히 예측, 산정",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2010-12-07",
    name: "국제기능올림픽선수협회",
    purpose: "우수기능ㆍ기술인 발굴ㆍ양성, 국제기능올림픽대회 출전 국가대표선수출신의권익 보호",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2010-12-09",
    name: "경북외국인다문화지원센터",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2010-12-15",
    name: "이웃사촌",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2010-12-30",
    name: "한국노사문화진흥원",
    purpose: "노사관계의 발전과 근로자의 삶의 질 향상 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-01-28",
    name: "한국사회적기업학회",
    purpose: "사회적기업 연구 및 활성화 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-02-07",
    name: "한국고용지원협회",
    purpose: "고용서비스 관련 교류, 협력, 교육, 상담, 연구사업 및 프로그램 개발 추진을 통하여 동 사업의 발전을 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-03-24",
    name: "에이지연합",
    purpose: "중장년인력을 적극 활용할 수 있는 사회적 환경을 조성하여, 중장년층의취업, 지역사회 봉사 등 사회참여 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-04-25",
    name: "장애인노동진흥회",
    purpose: "장애인 직업재활을 지원하고 권익을 보호",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-05-02",
    name: "한국취업진로학회",
    purpose: "취업․진로와 관련된 실용적인 학문연구를 통해 직업능력 개발 및일자리 창출에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-06-13",
    name: "이웃사랑",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-08-30",
    name: "러브아시아",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-08-30",
    name: "이주노동희망센터",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-10-24",
    name: "한국안전보건협회",
    purpose: "안전보건교육, 안전진단, 컨설팅",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-11-11",
    name: "인천지역금속노동자회",
    purpose: "제조업 취약계층 노동자 권리보호",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-11-15",
    name: "행복그린넷",
    purpose: "취업취약계층 일자리제공",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-11-23",
    name: "한국항만재단",
    purpose: "해운 항만 종사자 복리증진사업",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-12-16",
    name: "나누리",
    purpose: "양성의 평등한 삶, 여성노동 및 여성고용 전반에 관한 연구·교육·상담·홍보·새로운 직업설계·개발, 그 밖의 활동",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-12-16",
    name: "행복아이씨티",
    purpose: "취업취약계층 일자리제공",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2011-12-22",
    name: "커뮤니티와 경제",
    purpose: "사회적기업 지원을 통한 지역경제 활성화",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-01-10",
    name: "지속가능경영재단",
    purpose: "사회적기업 지원을 통한 지역경제 활성화",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-02-01",
    name: "한국직업자격학회",
    purpose: "직업과 자격에 대한 학술 연구",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-02-02",
    name: "지역고용정책연구원",
    purpose: "사회적기업 지원을 통한 지역경제 활성화",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-02-24",
    name: "고령사회고용진흥원",
    purpose: "공공・민간기관, 사회적 기업 등과 연계한 장년 일자리 창출, 재능기부및 사회공헌 활동 기회 제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-03-29",
    name: "세디경영연구소",
    purpose: "사회적기업 지원을 통한 지역경제 활성화",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-05-01",
    name: "커리어컨설턴트협회",
    purpose: "커리어컨설팅을 통해 일하는 가치와 행복을 찾아주고, 건강한 직업인을 육성",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-05-15",
    name: "평등사회노동교육원",
    purpose: "노동교육을 통한 한국노동운동 발전 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-06-01",
    name: "대한진폐재해자보호협회",
    purpose: "진폐재해자 권익보호 및 복지향상 등 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-07-12",
    name: "한국장애인일자리협회",
    purpose: "장애인 일자리창출을 도모하고 최상의 노동력을 발휘 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-07-12",
    name: "글로벌인재경영원",
    purpose: "직업훈련ㆍ상담 및 인사관리 시스템 구축 기술 제공으로 글로벌 역량 향상",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-08-01",
    name: "기능한국인회",
    purpose: "숙련기술인의 사기 진작 및 국가 산업발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-08-08",
    name: "정해산업보건연구소",
    purpose: "건강검진, 작업환경측정, 보건관리대행",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-08-09",
    name: "한국경력개발진흥원",
    purpose: "개인 경력관리 및 직업능력개발 촉진 지원, 자격습득 역량 제고",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-08-29",
    name: "함께하는행복한돌봄",
    purpose: "취약계층 여성들에게 가사·돌봄 서비스 등의 일자리를 창출하여 무료로알선하고, 전문 직업 교육 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-10-31",
    name: "국제고용개발원",
    purpose: "고용창출, 법·제도 개선, 국제개발협력 등을 위한 연구, 평가, 자문, 교육,연수 등의 활동",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-01-07",
    name: "한국취업능력개발원",
    purpose: "취업․능력개발을 위한 취업서비스 사업 및 무료직업소개사업 운영",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-02-05",
    name: "대한안전교육협회",
    purpose: "사업주 및 근로자 안전교육 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-02-20",
    name: "백세사회시민연대",
    purpose: "사회 각층과 세대에 적합한 직업능력 유지 강화 등, 지속 생산활동 가능한100세사회 공동체 패러다임 선도 및 건설",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-02-22",
    name: "한국커리어",
    purpose: "청년들의 진로 및 취업, 창업에 이르는 통합적인 생애진로개발 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-02-26",
    name: "미래고용노사네트워크",
    purpose: "퇴직한 장년들에게 적합한 일자리 모델을 개발하고 재취업을 위한 교육을 제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-03-12",
    name: "지식콘텐츠기업협회",
    purpose: "콘텐츠 개발 분야 우수인력양성, 재직근로자 직업능력향상 훈련 지원,이러닝 분야 교육훈련 활성화 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-03-14",
    name: "부천이주민지원센터",
    purpose: "외국인근로자 고충상담, 교육 등 체류지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-05-31",
    name: "사단법인 한국커리어혁신진흥원",
    purpose: "우리사회 일자리 사각지대에 놓여 있는 대구지역 취업에정자, 학생,재취업예정, 실업으로 고통 받는 모든 이들에게 심리, 정서적 지원과취업교육 혜택을 누리게 하여 지역사회 공동체 형성에 이바지함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-05-31",
    name: "한국퀵서비스종사자협회",
    purpose: "퀵서비스 업계 종사자들의 근로환경 수준 향상, 사회안전망 확충 및 권익향상 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-07-04",
    name: "병원코디네이터협회",
    purpose: "여성에 적합한 직업인 병원코디네이터 제도에 관한 연구 및 병원코디네이터능력개발 등을 통해 전문직업인으로서의 역량을 강화하고여성의 일자리 창출에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-07-25",
    name: "노동법연구소 해밀",
    purpose: "노동법에 정통한 법률가 육성과 노동법에 대한 시민교육을 통한노동인권의 지평 확대 및 노동법 분야의 문제를 사회통합적 관점에서연구하고, 실행방안을 모색하여 사회적 갈등 조정에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-07-29",
    name: "한국퇴직연금개발원",
    purpose: "퇴직연금제도의 발전과 진흥을 도모하고 퇴직연금 가입자의 안정된노후생활을 준비하기 위해 퇴직연금 제도에 대한 올바른 정보 제공과교육훈련 사업을 운영하며 근로자의 은퇴설계와 퇴직자의 재취업 등 컨설팅 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-08-23",
    name: "한국장애인고용창출협회",
    purpose: "장애인이 사회구성원으로서 삶을 영위하기 위하여 온오프라인으로구직상담, 취업알선 등 일반고용연계서비스 제공하여 직무능력이있는 장애인에게 일반고용시장진출 및 사회참여기회 부여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-09-03",
    name: "한국청년취업연구원",
    purpose: "국내외 청년 일자리 창출은 위한 청년 취업, 고용을 위한 실무 교육, 훈련 시행 및 자기개발프로그램 개발",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-10-15",
    name: "(사)외국인과 동행",
    purpose: "외국인근로자의 인권보호 및 복지증진",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-10-18",
    name: "건설근로자일드림협회",
    purpose: "건설일용근로자를 소개하는 유료직업소개사업자의 자질향상, 품위유지,권익보호 및 업무개선 등을 통하여 유료직업소개사업의 원활하고 건전한운영을 도모하고, 이를 통한 건설일용근로자 고용창출 및 고용안정에 이바지",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-11-15",
    name: "한국비계기술원",
    purpose: "비계 등 가설구조물 조립·해체 작업 근로자 기능 교육훈련 등",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-12-20",
    name: "노동희망",
    purpose: "노동법률 지원사업, 노동건강 및 문화지원사업, 근로환경 조사ㆍ연구사업, 비정규직 근로자 지원사업, 일자리 창출사업, 지역기반노동네트워크 형성",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-12-27",
    name: "한국우리사주조합연합회",
    purpose: "우리사주제도 관련 정보공유를 위하여 교육․홍보활동을 실시하고,정책개발 활동을 통해 우리사주제도개선에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2013-12-30",
    name: "한국직업지도진흥원",
    purpose: "공공기관, 민간기관, 사회적기업 등과 연계하여 취업취약계층에게 일자리 창출지원, 취업상담, 알선 및 교육을 제공하여 고용서비스확산",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-01-07",
    name: "한국조리기능장협회",
    purpose: "참여와 나눔의 가치 아래 조리분야의 축적된 기술을 활용하여 후진양성과한국음식문화사업을 발전시키고 사회봉사를 통하여 국민의 삶의 질향상에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-02-13",
    name: "한국일자리창출진흥원",
    purpose: "지역맞춤형 인력수급을 위한 고용역량강화 교육 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-02-25",
    name: "한국직업훈련총연합회",
    purpose: "근로자직업능력 개발법」에 의해 설립, 지정, 인정된 직업 훈련기관의발전을 통하여 근로자 평생직업능력개발에 기여함으로써 고용의증대와 국민경제 발전에 이바지 함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-02-26",
    name: "노동복지나눔센터",
    purpose: "노동자의 복지향상을 위한 정책개발 연구사업 추진 및 노동복지관련정보공유체계 구축으로 실질적인 노동복지 나눔 구현에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-03-13",
    name: "한국산업안전심리상담협회",
    purpose: "안전·보건 교육, 심리 상담, 기술지도, 컨설팅, 각종 연구개발 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-03-13",
    name: "안전보건진흥원",
    purpose: "산업재해 예방을 위한 안전·보건 사업 수행",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-03-27",
    name: "한국석면안전관리협회",
    purpose: "석면 함유 건축물의 안전 관리를 위한 석면 건축물 관리, 석면 조사,폐기물 처리, 신기술 개발, 적정 처리 방안 연구 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-03-27",
    name: "한국안전보건교육연구원",
    purpose: "안전·보건 교육, 재해 예방활동을 통한 안전·보건 문화 정착 및안전·보건 의식 선진화",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-10-28",
    name: "국제안전보건재단",
    purpose: "외국인근로자에게 필요한 인권통합서비스를 신속하게 지원하여외국인 근로자들의 산업안전 향상과 국제적인 인권증진에 기여",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-03-31",
    name: "스파크",
    purpose: "사회적경제 영역에서 활동하고 있는 소셜 이노베이터의 사회․경제적 가치 창출을 지원하고 이를 통해사회 문제를 시스템적으로 해결",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-04-17",
    name: "대한안전문화협회",
    purpose: "안전 문화의 기업 현장 정착 및 무재해 사업장 확산",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-04-28",
    name: "한국생애설계협회",
    purpose: "생애설계 교육 프로그램과 관련 전문인력의 개발 및 양성, 보급 사업 등을 통해 국민의 삶의 질 향상에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-03-31",
    name: "진주사랑의 집",
    purpose: "고용 및 체류와 관련한 외국인근로자와 사용자의 이해 관계 조정, 외국인근로자 본국과 한국과의 관계발전 기여 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-05-09",
    name: "사회적기업학회",
    purpose: "사회적기업에 대한 체계적인 연구와 토론의 장을 마련하여 우리나라 사회적기업의 발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-05-14",
    name: "한국고용복지연금연구원",
    purpose: "저출산 고령사회를 대비하여 국민의 삶의 질 증진에 기여할 수 있는중장년의 고용, 복지, 연금에 관한 연구를 수행",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-06-11",
    name: "한국음료직업교육개발원",
    purpose: "글로벌 바리스타, 바리스타 트레이너, 카페메니저, 카페수퍼바이저를양성하는 교육과정을 개발하고 새로운 직업분야의 전문가로 양성하여음료산업 분야 직업의 정착과 해외진출의 기반을 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-06-23",
    name: "행복투게더",
    purpose: "취약계층의 사회적 자립지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-07-10",
    name: "자기고용지원연구소",
    purpose: "취약계층에게 일자리창출 및 사회서비스 확충",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-07-29",
    name: "국제비즈니스코치협회",
    purpose: "빠르게 변화하고 있는 현대사회의 글로벌 인재육성 및 기업 등안정적인 운영을 위해 코칭서비스를 제공하여 사회에 공헌하고 국가의경쟁력 강화에 이바지",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-07-29",
    name: "한국미용건강총연합회중앙회",
    purpose: "미용.건강과 관련된 분야의 기술을 개발하고 전문직업능력을발전시켜 경쟁력을 갖춘 고용창출사업을 실행하여 미용건강산업분야의창업 및 고용능력을 극대화함으로써 국가발전과 일자리 창출에 크게 기여함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-07-30",
    name: "한국미용건강총연합회",
    purpose: "휴먼(미용건강)올림픽대회 개최, 미용건강 부문별 산학연계, 직업훈련교육을 통하여 미용건강 산업의 발전과 미용건강기능인의 처우개선에 이바지",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-07-30",
    name: "한국청소방역정리직능협회",
    purpose: "청년실업자, 중고령자, 경력단절여성, 여성인력 등 취업애로계층의 일자리 관련 전문인력을 양성하기 위하여 직업능력 향상 및 진로직업교육이 필요한 대상자에게 각종 기회를 제공하는 등 인력수급정책을 수립",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-07-30",
    name: "한국뷰티스타일리스트직업기능협회",
    purpose: "뷰티스타일리스트의 직업능력개발을 통해 전문인력창출,업무영역 확대 및 기능향상, 민간자격제도운영, 우수한 인력풀 구성,교육기관과 연계활동, 정보교류 등을 통해 건전한 국가발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-07-30",
    name: "한복기술진흥원",
    purpose: "한복의 전통복식기술을 계승하고 시대적 변화에 맞는 창작기반을조성하여 한복산업계의 과학화.현대화.표준화를 통한 교육발전 및기술장려를 위한 기틀을 마련하고, 회원의 공동이익실현을 위한 사업을 수행하여 자주적인 경제활동과 경제적 지위향상을 도모하며, 한복산업계의 건전한 발전과 회원의 복지증진에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-08-01",
    name: "한국취업컨설턴트협회",
    purpose: "취업계층별 특성에 맞는 행동중심의 현실적 취업프로그램의 개발보급을통해 일자리 창출에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-08-06",
    name: "한국뷰티전문가직업교류협회",
    purpose: "국내외 미용전문가들의 정보교류를 통한 직업적업무영역확대 및기능향상과 학술적 연구를 추구하며, 이의 교련을 통하여 고용인력창출 사업을 시행함으로써 건전한 국가사회발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-08-12",
    name: "오이원",
    purpose: "사회적경제 활성화",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-08-22",
    name: "석면피해예방지원센터",
    purpose: "석면 취급 근로자의 안전한 석면 처리 방안 수립, 석면 관리 관련 연구 사업 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-08-27",
    name: "성원근로장애인협회",
    purpose: "장애인이 사회 구성원으로서의 삶을 영위하기 위하여 구직상담, 직업능력개발,취업알선 등 고용  연계지원 서비스를 제공하여 장애인에게 고용시장 진출 및사회참여 기회부여를 목적으로 함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-09-16",
    name: "딜라이브파트너사협의회",
    purpose: "노사관계 발전 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-10-02",
    name: "한국창직협회",
    purpose: "새로운 직업(직무)를 창출하는 창직과정을 주도함으로써 고용창출이라는국가적 현안을 해결하고, 신직업을 발굴·연구·분석하여 신일자리로서 육성·보급·교육을 시행하여 신일자리를 통한 개인과 국가의 경제부흥과 발전에 공헌",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-10-10",
    name: "한국능력평가협회",
    purpose: "직무능력 연구개발 및 문화.창업사업을 수행하는 기업들의 상호연대를도모하고, 자기능력개발의 성장 및 발전을 위하여 노력함으로써 우리나라 전문적 서비스.문화 활동의 효율화, 내실화를 통해 산업의 고도화와 선진화 실현에 적극 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-10-13",
    name: "한국사회서비스인력직업훈련협회",
    purpose: "사회적 취약계층들에게 채용예정자 전문교육 등 종합교육시스템을 통해고용촉진 교육서비스를 제공하여, 이들의 취업을 촉진하고 동등한 사회구성원으로 권익 보호는물론, 이를 위한 양성 및 심화.보수교육, 종합사회서비스인력의 관리책임자 교육프로그램 시행",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-10-22",
    name: "점프",
    purpose: "사회적 경제 활성화 및 일자리창출",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-11-20",
    name: "월천사회법연구회",
    purpose: "합리적인 노사관계 및 노동법 등에 관한 학술적 연구발표 및 각종 프로젝트를수립함으로써 노동관련 분야의 학문적 발전을 도모하고, 노동문제에 관한상담·교육 등을 통한 산업평화 및 근로자의 권익증진에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-12-16",
    name: "꿈나누리",
    purpose: "4050 아카데미운영사업, 사회적기업 네트워크를 구성 운영, 채용정보 시스템을개발 보급 사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-12-16",
    name: "대구경북고용복지연구원",
    purpose: "고령자를 위한 일자리 지원 및 복지증진 사업, 직업능력강화 사업, 고용창출을위한 연구 개발 사업 등의 사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-01-27",
    name: "한국산업기술협회",
    purpose: "국내산업기술의 발전과 회원상호간의 직무능력향산 및 직업능력개발 촉진",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-02-10",
    name: "한국중장년인력정책개발원",
    purpose: "중장년층 직업교육사업, 중장년 취업알선 사업, 중장년 인식 개선사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-03-06",
    name: "한국직업기술교류원",
    purpose: "숙련전문기술, 기술능력개발 기법, 자격정보 등의 교류를 통해 기술인들의경쟁력 향상과 복리증진에 기여함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-03-10",
    name: "한국진로취업서비스협회",
    purpose: "구직자에게 진로설정 및 취업지원 서비스 제공을 통하여 기업과 구직자 간의미스매칭을 해소하고 올바른 진로․ 취업문화 조성을 목적으로 함.",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-03-10",
    name: "한국미용교육협회",
    purpose: "미용전문기술가를 발굴하여 보다 체계적이고 기능적인 직무능력교육을교습하여 방과후 미용교육강사의 전국 초,중,고등학교 및 미용관련기관에출강지원을 육성",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-03-17",
    name: "한국중장년고용협회",
    purpose: "중장년 인력정책 연구 ➁중장년 고용안정 컨설팅 ➂기업환경 개선 지원 컨설팅 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-03-31",
    name: "(사)한국안전경제교육연구원",
    purpose: "재난, 안전, 근로자 보건 및 산업재해 예방 등에 관한 연구와 교육 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-07-16",
    name: "제니엘 푸른꿈일자리재단",
    purpose: "젊은이들과 취업애로계층을 대상으로 올바른 직업관 형성과 실업문제 극복,직장생활의 안정적 정착에 도움을 줌으로써 사회 안정에 기여",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-08-04",
    name: "공감직업환경의학센터",
    purpose: "산업보건 취약계층의 건강증진을 위한 학술 연구, 교육·홍보 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-08-18",
    name: "한국가사노동자협회",
    purpose: "경력단절여성에게 좋은 일자리 창출, 돌봄노동의 가치가 인정 받는사회환경 조성, 가사노동자의 사회,경제,문화적 지위 향상 및 지역사회 발전",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-08-20",
    name: "한국건축시공기능장협회",
    purpose: "건설기능인 품위유지 및 복리증진 건설기능인의 경제적.사회적 지위향상",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-10-12",
    name: "다문화근로자복지협회",
    purpose: "다문화 근로자의 취업지원 및 직업훈련을 통한 자립지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-10-15",
    name: "한국건설기능인협회",
    purpose: "건설기능인 근로환경개선을 통한 권익 향상",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-11-19",
    name: "지역과 소셜비즈",
    purpose: "지역의 사회 및 경제 발전",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-11-19",
    name: "전남사회적경제연구소",
    purpose: "지역사회의 발전과 국민경제의 균형있는 발전",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-12-10",
    name: "희망철도재단",
    purpose: "철도노사 공동으로 사회공헌사업을 수행하고 다양한 협력활동 등을체계적으로 지원하고 활성화하며, 노사신회를 바당으로한 협력을 통해공공적 책임과 역활을 다하며 합리적 노사관계 구축과 발전에 기여",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-12-17",
    name: "한국안전교육기술원",
    purpose: "안전·보건 교육, 휴먼 에러 방지 연구 사업, 공정안전관리 관련 사업 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-12-22",
    name: "한국안전돌봄서비스협회",
    purpose: "맞춤형 전문 안전돌보미를 양성하여 각계각층에 안전돌보미를 공급함으로써일자리 창출 및 고용안정 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2015-12-28",
    name: "한국산업의료복지연구원",
    purpose: "감정노동 및 직무스트레스 연구, 근로자 심리 상담, 유해 화학물질 취급근로자 구강질환 예방 등",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-01-11",
    name: "울산외국인센터",
    purpose: "외국인 근로자의 인권보호와 복지 증진을 도모하여 국내에서의 안정된생활과 자력기반을 마련하고 삶의 질 향상",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-01-11",
    name: "고용이민연구원",
    purpose: "국내에 유입된 외국인 근로자 등과 관련된 사회현상애 대한 학문연구를 통해이민정책 발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-02-03",
    name: "한국멘토교육협회",
    purpose: "청소년의 건전한 직업관 형성을 위한 멘토발굴, 진로 및 취업지도",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-03-08",
    name: "강서구사회적경제협의회",
    purpose: "사회적경제 영역의 협력강화",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-03-08",
    name: "광주사회적경제연합회",
    purpose: "사회적경제 조직의 활성화 및 발전",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-04-08",
    name: "한국인테리어필름도배장판협회",
    purpose: "고령자 대상 취업훈련(인테리어필름래핑)및 지원사업을 통해 취업기회를제공하고 수익창출을 유도",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-05-02",
    name: "한국종합안전보건진흥원",
    purpose: "근로자, 국민의 안전·보건 의식 고취 및 안전·보건 실천을 위한 관련 교육,연구, 문화사업 추진",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-05-12",
    name: "한국고용서비스진흥원",
    purpose: "공공기관, 민간기관, 사회적기업 등과 연계하여 취업취약계층에게일자리 창출지원, 취업상담, 알선 및 교육을 제공하여 고용서비스확산",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-05-25",
    name: "미래안전문화포럼",
    purpose: "안전 문화에 관한 이론과 실천에 관한 연구, 안전 문화 교육, 홍보",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-05-25",
    name: "한국기능장애인협회",
    purpose: "장애인들의 기능기술 양성을 통해 직업재활과 일자리 창출 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-06-10",
    name: "한국마케팅진흥원",
    purpose: "마케팅 직종의 직무능력향상을 위한 콘테츠 연구개발 및 회원 상호간학술협력을 통한 온라인 마케팅 직업 훈련매체 개발",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-06-16",
    name: "한국코칭심리협회",
    purpose: "글로벌형 코치육성과 관련 프로그램 개발․보급을 통해 코칭심리를 산업및 직업으로 발전시켜 일자리 창출에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-07-18",
    name: "일미래센터",
    purpose: "취업취약계층을 주요 대상으로 안정적인 일자리를 제공하기 위해 교육및 제반 취업지원서비스를 실시함으로써 지역사회 공헌함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-09-02",
    name: "한국직업훈련기관협회",
    purpose: "직업훈련 기관의 발전을 위하여 다양한 정보를 제공하며, 정부주도의직업훈련 정책을 적극적으로 추진하고, 새로운 정책을 제시하여 직업능력개발사업과 국가경제 발전에 이바지",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-09-18",
    name: "사단법인 건설화학안전협회",
    purpose: "석면 관련 전문 교육, 기술 연구 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-10-28",
    name: "한국호흡보호구학회",
    purpose: "호흡 보호구와 관련 각종 사업 추진",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2016-11-30",
    name: "한국직업인성개발원",
    purpose: "청년직업인성과 선진 청년취업‧진로 및 직업문화 조성을 통한 건전한고용문화 창달 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2017-01-25",
    name: "SK그룹노동조합임직원협의회",
    purpose: "SK그룹의 정책에 부응하여 SK그룹에서 종사하는 임직원의 복지증진 및경제적․사회적 지위를 향상시키고 국․내외적 활동을 촉진시켜 그의건전한 발전을 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2017-05-10",
    name: "한국장애인고용환경연구회",
    purpose: "다양한 직업교육과 직종개발을 통해 장애인이 직업인으로서 자립할 수있도록 도모하고 장애인의 고용환경을 적극적으로 개선하여 장애인의사회 진출과 자립 촉진",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2017-05-11",
    name: "지역일자리창출진흥원",
    purpose: "취약계층의 안정적 일자리 설계 및 지역맞춤형 일자리 창출 등 지역사회서비스 확충 등을 통해 지역사회의 통합과 시민의 삶의 질향상에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2017-05-31",
    name: "건설재해예방협회",
    purpose: "재해예방 전문지도기관의 발전을 위한 정책 개발, 기술지도 업무 보증 사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2017-06-08",
    name: "한국고용진흥협회",
    purpose: "고용창출을 위한 고용유발업종 수요조사, 고용유발업종 중소기업의애로사항, 구인난 해소책 연구 및 시스템개발 지원, 포럼 및 세미나 개최,연구, 진흥활동, 직업(취업)교육·훈련프로그램 개발 및 실행, 취업알선, 도서출판, 간행물 발간 등을 통하여 바람직한 고용활성화 분위기를정착시켜 국가경제발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2017-06-08",
    name: "한국고용서비스협회",
    purpose: "회원 대상 직무교육을 통해 민간고용서비스의 이미지개선 및 자질향상에기여하며 산업발전에 필요한 인력을 원활하게 공급하고 직업소개사업종사원의 품격향상과 고객서비스 제고를 통하여 국가산업 발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2017-06-14",
    name: "대한민국숙련기술인총연합회",
    purpose: "숙련기술인 간의 교류 및 원활한 활동을 지원하여 숙련기술인의 사회경제적지위를 향상하시코, 국가의 산업경쟁력을 높여 국민경제 발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2017-06-20",
    name: "동반성장산업협회",
    purpose: "모든 장애인이 권리의 주체라는 인식을 갖고 사회 활동에 참여할 수 있도록업무 환경을 개선하고 특히 전문 기술을 가지고 있으나 소외받는 장애인전문 인력에게 일자리 정보를 제공하고 고용을 확대함으로써 장애인과비장애인이 사회적 동반자로 성장하고 지역 사회와 국가경제의 발전에 이바지",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2017-09-12",
    name: "한국고용복지학회",
    purpose: "국민의 고용복지, 저출산 고령화 및 미래고용시장의 불확실성 관려 연구 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2017-09-21",
    name: "페이스디자이너협회",
    purpose: "뷰티미용산업분야에 대한 지식과 기술을 일반인 및 뷰티미용산업 분야종사자들에게 강의할 수 있는 뷰티미용산업 분야 전문강사를 배출함으로써산업인력을 확충하고, 나아가 뷰티미용산업 분야 종사자들의 능력 및 자질 계발에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2017-12-01",
    name: "미래고용서비스협회",
    purpose: "새로운 사회적일자리를 개발하고, 취업지원센터 등을 운영하여 취약계층의고용확대에 기여하고자 함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2017-12-08",
    name: "공공상생연대기금",
    purpose: "공공기관 노동자 및 사용자들의 자발적 출연과 공공기관 성과연봉제의폐지에 따른 인센티브 환수 및 반납 금액 등을 활용하여 공공부문 비정규칙처우개선 및 양질의 일자리 창출 등을 통한 사회 공공성 확대",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-01-22",
    name: "대한민국이용장회",
    purpose: "이용장인의 사회적 지위향상과 직업윤리 준수하며 기술증진과 일자리창출을 통하여 국가경제발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-04-11",
    name: "한성인력개발원",
    purpose: "취업희망자에게 양질의 직업소개 및 직업지도 직업에 대한 정보제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-04-13",
    name: "청소년노동인권노랑",
    purpose: "청소년들의 인권 및 노동권 증대, 청소년 교류활동, 교육·문화·연구 활동 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-04-16",
    name: "일터개발원",
    purpose: "직장인의 올바른 직업관 구축과 정서, 스트레스 관리를 통해 조직의안정을 꾀하며 코칭 프로그램을 연구․개발하여 직장인을 대상으로잠재력 및 리더십 개발",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-05-03",
    name: "소셜커뮤니티",
    purpose: "소셜벤처 등 사회적경제기업에 대한 교육 및 컨설팅, 연구개발 등을 통해사회적경제 활성화에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-06-05",
    name: "한국산업인재육성협회",
    purpose: "산업인재 육성을 위한 직업능력개발 교육훈련 및 정책연구, 무료 직업소개,취업 관련 민간자격증 운영, 회원 상호간 산업인재 육성에 관한 정보 교육",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-06-12",
    name: "미래고용나눔협회",
    purpose: "지역주민의 취업관련 교육, 취업지원서비스, 홍보활동 등을 통해 구인,구직자 간 최상의 욕구를 충족",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-07-17",
    name: "한국장애인근로복지협회",
    purpose: "근로장애인 고용확대사업, 직능 및 기능개발 프로그램 교육 사업, 장애인보호작업장 운영, 근로장애인 사회적 인식개선 사업 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-07-28",
    name: "(사)환경안전기술원",
    purpose: "산업재해 예방을 위한 산업안전·보건 제도개선 조사·연구활동, 산업안전·보건을 위한 기술의 연구개발 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-07-30",
    name: "한국어쎄서협회",
    purpose: "어쎄스먼트 산업의 발전을 위한 연구개발, 정보제공, 교육지원을 통해어쎄서(전문평가자)를 육성하여 능력중심의 공정한 사회실현에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-08-13",
    name: "한국기능올림픽연구원",
    purpose: "국내 및 국제기능경기대회 분야의 발전을 위한 토론 및 연구활동을 전개하여 국가의 산업경쟁력 강화에 필요한 우수 숙련기술인 육성에 이바지",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-09-10",
    name: "고향의봄",
    purpose: "일자리 관련 연구와 정책개발, 직업훈력과 사업개발, 지역사회인식개선 활동 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-09-12",
    name: "노동.실업 광주센터",
    purpose: "실업자를 위한 종합적인 지원활동을 통해 실업자의 자립을 돕고 취약계층 권익신장에 기여함을 목적",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-11-19",
    name: "기독교사회연대경제네트워크",
    purpose: "대한예수교장로회 교단 내 사회적기업 활성화 관련 사업 수행등을 통해건강한 사회적경제 생태계 조성, 한국 교회의 사회적경제 활성화 방안에관한 연구, 조사 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-12-03",
    name: "대경워라벨인재개발협회",
    purpose: "중소기업, 영세자영업자 및 취약계층 등  고용정책연구 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-12-04",
    name: "장애인한빛",
    purpose: "인식개선 사업, 장애인 일자리 개발사업, 장애인직무능력 향상 지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2018-12-17",
    name: "(사)이수포럼",
    purpose: "연구를 통한 노동행정과 국민경제 발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-01-11",
    name: "유니온센터",
    purpose: "청년 노동자의 권리보호와 근로조건 향상을 위한 제반 사업을 수행하여사회경제적 지위와 삶의 질을 향상시키는데 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-01-25",
    name: "한국고용서비스연구학회",
    purpose: "고용서비스 분야의 이론적 배경을 확립하고, 고용 및 조직의 인적자원관리와 관련되는 문제의 해결을 지원함으로써 우리나라 고용서비스의 발전에 기여함을 목적",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-05-08",
    name: "한국사회적일자리협회",
    purpose: "사회적기업 확산을 위한 사업, 사회적기업 활성화 네트워크 구축 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-06-11",
    name: "스마트플랫폼기술인관리협회",
    purpose: "지식정보화 및 산업구조 고도화에 따른 4차 산업 핵심기술인 비아이엠,블록체인, 3D프린팅 기술 등을 융합한 전문기술인에게 구인·구직 정보, 인력수급 상황, 미래 시장예측 등 고용서비스를 제공하고, 융합전문기술인구직자와 구인기업 간의 인력 미스매칭을 해소하여 고용안정을 도모하고, 각종 연구·교육 등 통해 융합전문기술인의 경제·사회적 지위향상",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-08-01",
    name: "사단법인 한국상생지원협회",
    purpose: "노동정책에 대한 연구와 분석을 통하여 정책에 방향을 제시하여 노동행정과근로자의 삶의 질을 향상시키고 근로자 지위향상과 국민경제 발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-08-02",
    name: "(사)민중교육연구소",
    purpose: "노동교육 교재연구, 편찬 및 교육 강좌 진행",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-09-06",
    name: "노인·청장년일자리창출개발본부",
    purpose: "정부의 일자리 활성화 정책에 맞춰 협력 및 소통을 바탕으로 노인·청장년 일자리 창출 및 제공을 통해 고용을 높여 국가경제 발전과 지역사회 일자리 확충에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-10-07",
    name: "밴드",
    purpose: "사회적경제 생태계 활성화를 위한 기금 조성 및 운영 등",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-10-10",
    name: "타워크레인설치해체기술안전협회",
    purpose: "타워크레인 기술인들간 교류를 통하여 안전사고예방교육 및 실무업무에대한 정보를 공유하고 실습을 통해 타워크레인 기술인 업무의 질적인 향상뿐 아니라 종사자 전문성을 제고하여 사고로 인한 중대재해 예방 및 관련산업 육성에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-10-30",
    name: "한국기능장연합회",
    purpose: "기능장단체 상호간의 발전방안 교류, 기술발전 연구, 품질향상 및 기능장들의고용안정을 통한 진흥 및 발전에 기여, 기능인의 경제적.사회적 지위향상",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-11-07",
    name: "해피파파",
    purpose: "대한민국 남성의 권익신장과 복지증진을 위한 취업 및 일자리창출 사업과사회·경제·문화적 활동 역량증진을 위한 사업을 통하여 남성을 미래 사회의 인재로 육성함으로써 새로운 남성문화를 조성하여 우리사회의 발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-11-12",
    name: "한국노동교육진흥원",
    purpose: "근로자들에 대한 교육을 통하여 4차 산업혁명 시대를 주도할 수 있는인재를 양성하고 이를 통해 국민의 권익증진에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-11-13",
    name: "사단법인 철근콘크리트 서경인 사용자연합회",
    purpose: "철근콘크리트 서경인 사용자들에 대한 노동관계의 조정, 지원과 제휴, 회원사들이 가입한 노동조합과의 단체협약 체결 및 정보교류, 연구와 교육 등을 통하여 건설산업의 건전한 발전과 합리적인 노사관계 정착에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-11-26",
    name: "상생과 동행",
    purpose: "지역의 고용시장에 관한 연구조사, 취업취약계층에 대한 교육과 취업지원을통해 지역 일자리 창출에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-12-09",
    name: "사단법인 김용균재단",
    purpose: "고 김용균 추모 및 안전한 일터 만들기를 위한 노동안전보건사업 추진",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-12-26",
    name: "행복일자리운동본부",
    purpose: "사회적 약자의 사회적 일자리를 창출하여 사회적 경제 영역을 활성화 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2019-12-19",
    name: "전국일자리협회",
    purpose: "국가 고용정책에 따라 직업소개 사업자의 공동노력과 협력으로국가산업발전에 필요한 인력의 원활한 공급 및 수급균형을 도모하고직업소개 사업의 자율시정지도개선등을 통하여 건전한 민간 고용서비스사업자가 육성될 수 있도록 지원함으로서 구인자 및 구직자에게 최상의서비스를 제공하고 국가산업발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2020-01-09",
    name: "서울공고 총동문관악회",
    purpose: "근로취약계층 노동자를 상급기술인재 및 다기능기술인재로 육성함으로써 근로취약계층 노동자가양질의 일자리를 제공받고 생계의 안정을 누릴수 있도록 조력",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2020-01-31",
    name: "한국고용협회",
    purpose: "사업주(사업주단체), 산학협력기관, 교육훈련기관, 사회복지기관과 연계하여 실업자, 졸업예정자, 경력단절자 등 구직자와 구인자에게직업정보 제공 등 고용서비스, 인적자원개발 등 지역과 산업현장에필요한 종합적인 서비스를 제공하고 지역 일자리 창출 및 평생학습활성화에 필요한 사업을 실시함으로써 고용·인적자원개발 및 진흥에 이바지",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2020-02-25",
    name: "한국커리어개발협회",
    purpose: "커리어개발에 대한 올바른 이해를 도모하고, 직업능력향상을 비롯한 생애커리어 개발과 관련된 아이디어와 경험을 공유하는 포럼 및 컨퍼런스등의 개최를 통해 대한민국과 국제사회의 발전에 기여함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2020-02-25",
    name: "한국유압크레인기술협회",
    purpose: "기중기운전기능사 숙련공 양성 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2020-04-01",
    name: "한국직업능력개발훈련법인협의회",
    purpose: "훈련법인 상호 간의 이해 증진, 훈련의 공공성 강화, 산업현장에필요한 근로자의 직업능력개발",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2020-04-23",
    name: "한국장애인근로협회",
    purpose: "장애인직업훈련및 일자리 알선, 장애인기업육성, 장애인종합상담, 장애인사회참여 촉진을 위한 교육및 제도개선 사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2020-06-24",
    name: "직장갑질119",
    purpose: "직장의 갑질과 불합리한 관행 개선 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2020-08-19",
    name: "교육의봄",
    purpose: "기업의 블라인드 채용시스템 실태조사 및 우수사례 발굴·보급",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2020-02-07",
    name: "노동포럼",
    purpose: "미조직 노동자 및 비정규직 근로자 지원 등 지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2020-09-29",
    name: "ELTS연구원",
    purpose: "고용안정 및 합리적인 노무관리 컨설팅 등 지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2020-10-07",
    name: "한국일자리지원연합회",
    purpose: "공익기반 일자리 공유 서비스를 통해 일자리 발굴과 우수인력 양성",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2020-12-29",
    name: "미래희망포럼",
    purpose: "일자리가 최고의 복지라는 목표아래 여성 및 청년, 노인 등 취약계층의일자리 확보에 이바지함을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2021-01-15",
    name: "(사)한국고용정책연구원",
    purpose: "지역노동시장 현안에 관한 해결방안과 정책 제시, 지역내 고용주체와의네트워크 강화 등을 통해 고용여건 개선 및 지역일자리 창출에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2021-02-01",
    name: "한국노동경제연구원",
    purpose: "기업 등 각종 조직과 근로자 간의 유연한 노사문화 확립과 상생적 경영풍토 조성 및 노사간 유대 증진에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2012-02-29",
    name: "사회적경제활성화지원센터",
    purpose: "사회적기업운동 추진 및 전국네트워크 활성화",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2021-05-13",
    name: "글로벌취업지원센터",
    purpose: "청년의 취업능력 향상을 위해 지자체와 고용 희망기업 및 대학교가함께하는 교육지원사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2014-04-15",
    name: "세계노동운동사연구회",
    purpose: "노동운동 역사 연구, 자료수집 및 출판 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2021-04-22",
    name: "사단법인 풀빵",
    purpose: "노동자 자조조직 형성 지원, 공제사업 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2021-08-17",
    name: "한국간병근로자직업능력개발원",
    purpose: "간병근로자의 직업능력개발 촉진하고 산업현장에서 필요한 기술기능인력양성",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2021-10-05",
    name: "소통과혁신연구소",
    purpose: "노동자들의 생각과 생활과 활동을 소통하고, 21세기 한국사회의 현실에 맞는이념·노선·방법·자세를 연구·교육·토론하여 노동운동의 혁신과 발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2021-10-15",
    name: "한국플랫폼프리랜서노동공제회",
    purpose: "상호부조를 기반으로 플랫폼노동자 등비정형 노동자들의 생활안정을 위한 공제사업, 건강 및 복지증진, 직업환경개선 및 직업능력의 개발과 향상을 도모하며 지원체계 구축을 통해노동자들의 권익보호 및 이해 대변 역량을 강화하고 양질의 노동환경을 조성하여 지속 가능한 경제사회 발전에 기여",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2021-10-28",
    name: "한국고소자동차제작안전협회",
    purpose: "이삿짐 운반용 리프트, 고소작업대 및 크레인의 발전과 안전에 관한 조사연구 및 정책 제안사업 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2021-12-01",
    name: "푸른고래리커버리센터",
    purpose: "청년 진로상담 및 취업지원사업, 취업정보 제공 및 일자리창출 관련유관단체와 교류사업 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2021-11-23",
    name: "사단법인 한국사회법학회",
    purpose: "노동관계법, 사회보험법 등 사회법 분야의 연구와 학술활동을 통한고용복지 사회 실현",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2022-03-25",
    name: "위드커리어",
    purpose: "국민의 직업능력개발을 개발하고 지역 사회에 필요한 인력을 양성하는 등국민의 고용안정에 이바지",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2022-01-13",
    name: "사단법인 호남, 제주 철콘연합회",
    purpose: "철근콘크리트공사업 사용자들에 대한 노동관계의 조정, 지원과 제휴, 노동조합과의 단체협약 체결 및 정보교류, 연구와 교육 등을 통하여 건설산업의 건전한 발전과 합리적인 노사관계 정착에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2022-05-12",
    name: "사단법인 안전의 전당",
    purpose: "안전 관련 학술과 문화 관련 회의, 안전문화활동 장려 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2022-06-13",
    name: "사단법인 한국산림산업안전보건협회",
    purpose: "산린산업 안전보건에 관한 교육, 산림사업장 안전·보건진단, 위험성평가 등기술지원 및 컨설팅 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2022-06-13",
    name: "사단법인 안전보건기술인협회",
    purpose: "산업전반에 대한 안전보건교육 실시 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2022-07-06",
    name: "사단법인 집으로가는길",
    purpose: "취약계층 청년의 취업을 위한 전문교육, 취업교육 과정에서 소외계층의 주거환경 개선을 통한 직무체험과 진로체험 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2022-08-02",
    name: "사단법인 한국안심일터기술원",
    purpose: "산업현장의 산재예방활동 지원, 안전보건에 관한 교육, 안전관리 업무 기술지원, 위험성평가 및 안전문화 컨설팅 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2022-09-06",
    name: "사단법인 아시아모니터리소스센터",
    purpose: "노동관련 연구, 교육, 네트워킹, 캠페인을 통해 노동인권을 감시하고 연구하는아시아 지역의 풀뿌리 노동단체들을 지원함으로써 아시아의 노동자들의 좋은일자리와 개선된 노동조건, 민주적 권리와 젠더평등에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2022-09-26",
    name: "차세대ICT융합협회",
    purpose: "ICT융합산업 활성화 및 연구 인력의 역량간화",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2022-10-04",
    name: "재단법인 산업안전상생재단",
    purpose: "산재예방을 위한 안전관리체계 점검 및 기술지원사업, 교육 및 연수지원 사업 등",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2022-11-03",
    name: "사단법인 사회고용정책개발원",
    purpose: "산·학·연·관 네트워크를 바탕으로 고용과 복지에 관련한 연구 활동 등을 통하여지역 주민의 삶의 질을 높이는 데 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2022-11-24",
    name: "사단법인 중대안전보건예방협회",
    purpose: "산업안전보건교육사업, 산업안전보건교육 관련 정책 및 연구개발사업 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2022-12-21",
    name: "(사)한국비정규직고용협회",
    purpose: "비정규직 등 취업취약계층과 소외계층 노동자에 대한 차별해소 및 노동권 보호",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-01-25",
    name: "한국직무능력개발협회",
    purpose: "직무능력개발 교육을 시민에게 널리 보급하여 직무 만족도 향상에 기여하며,다양한 일자리에 맞는 창의적 인재를 육성하고 건전한 직무활동을 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-01-30",
    name: "(사)한국배관기능장협회",
    purpose: "배관 관련 분야의 조사, 연구활동을 수행하고, 국가기술자격자로서 배관기능장의기술향상과 직무향상을 위한 교육과 다양한 활동을 수행함으로써 국가사회발전과공익에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-02-14",
    name: "(사)한국스마트안전보건협회",
    purpose: "스마트안전기술 관련 조사 및 연구, 교육 및 캠페인 등 정관에서 정한 사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-02-22",
    name: "(사)한국퇴직자총연합회",
    purpose: "고령 퇴직자들에게 제2인생 설계를 지원하고 그에 필요한 제도개선 등 권익보호를강구하면서 그들이 활동할 기업과 지역사회 참여환경을 구축함으로써 개개인의 고용 및 복지증진, 국가경제 및 사회발전에 기여함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-03-03",
    name: "(사)새롬공익사업재단",
    purpose: "고령자에 대한 취업알선과 재능기부, 멘토링, 카운슬링 지원을 통한 공익사업 수행",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-03-09",
    name: "(사)한국대리운전기사연합회",
    purpose: "회원이 보유한 경험 및 정보를 활용하여 대리운전기사의 인권 및 권익을 보호하고 복지향상 및 친목 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-03-17",
    name: "(사)한국스마트안전보건기술협회",
    purpose: "스마트안전보건기술에 대한 연구, 개발 및 표준화 수립 기반으로 관련 교육 등을 통해산업 현장에 보급 확산 지원 사업으로 안전보건관리의 스마트화 추진 등 정관에서정한 사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-03-14",
    name: "(사)대한민국사회적기업중앙협회",
    purpose: "사회적기업에 관한 조사연구 및 정책개발, 사회적기업 홍보 및  출판, 임직원 교육 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-03-21",
    name: "사단법인 중소기업안전협회",
    purpose: "안전보건진단, 위험성평가 등 안전 컨설팅, 안전보건교육 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-04-07",
    name: "(사) 대한스마트안전협회",
    purpose: "선진화된 스마트 안전 제품 및 관리 시스템 연구개발, 국외 스마트 안전우수제품에 대한 기술 도입 및 국산화를 위한 연구개발 등 정관에서 정한 사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-05-09",
    name: "한국에이치알디협회",
    purpose: "인적자원개발(HRD) 조사‧연구를 통하여 인적자원개발의 지표와 방향을 제시하고HRD 컨퍼런스‧포럼 등의 교류활동과 HRD 전문가 양성을 통하여 체계적이고 성과지향적 인적자원개발 활동을 지원하여 한국적 HRD 발전과 저변확대를 통해",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-05-30",
    name: "(사)한국방폭협회",
    purpose: "방폭안전기술 연구개발 보급과 방폭안전 전문인력의 양성 등 일련의 활동을수행함으로써 화학공장의 대형 화재·폭발사고 및 중대산업사고 예방과 방폭안전기술 발전에 이바지함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-06-05",
    name: "(재)일환경건강센터",
    purpose: "원하청 상생협력 모델 구축, 산업보건지원자원, 소규모사업장 및 취약노동자 산업보건지원 사업 등",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-06-08",
    name: "(사)대한로프운용기술안전협회",
    purpose: "산업로프 관련 매뉴얼 제작 및 인력지원센터 운영, 산업재해 예방 캠페인 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-06-08",
    name: "(사)재해예방시스템협회",
    purpose: "재해예방시스템 증진을 위한 진단‧평가 및 컨설팅 사업, 새로운 재해예방시스템의 개발‧교육 및 확산 사업, 새로운 재해예방시스템 관련 출판 및 홍보사업 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-06-22",
    name: "한국직업정보협회",
    purpose: "직업정보제공 및 고용 서비스 관련 산업 제도 및 정책 개선을 도모하고, 회원의 경영활동을 발전시키며, 더 나아가 고용노동시장 발전을 통한 국민경제의 균형발전에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-06-22",
    name: "한국장애인HR협회",
    purpose: "①기본적인 바리스타 교육을 통한 취업 준비 장애인들의 업무 수행 능력 제고및 고급 바리스타 교육과정을 통한 자격증 취득지원으로 공공기관이나 장애인고용희망기업에 취업할 수 있도록 하며, ②장애인들의 취업 활성화를 위한 직업교육 연구 및 이를 홍보하기 위한 자료집 및 매뉴얼 발간을 통해 보다 많은 장애인들이 취업의 폭을 넓힐 수 있도록 함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-07-20",
    name: "(사)한국서치펌협회",
    purpose: "사업자의 공정한 경쟁과 상호교류를 통해 양질의 취업정보를 제공하고 경력직 채용시장의 발전과 유료직업소개사업자의 경쟁력 제고를 통해 민간고용서비스시장의발전에 이바지함을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-07-31",
    name: "(사)경북디지털산업고용혁신협의회",
    purpose: "지역 여건과 기업 환경에 특화된 일자리 창출을 통하여 지역민의 고용활성화와기업의 생산성 향상에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-08-11",
    name: "(사)신복지원",
    purpose: "중장년층 예비 사회복지사 대상 맞춤형 취업지원 (교육 및 일자리 지원, 심포지엄 개최 등)",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-08-11",
    name: "(사)거제외국인노동자비전센터",
    purpose: "본회는 대한민국에 체류하고 있는 외국인들의 차별 및 인권 보호, 내국인과의 상생 협력을 도모하고 국내에서의 안정된 생활과 자력 기반을 마련하고 환경 개선과 복진 증진하여 내국인과 외국인 간 상생, 삶의 질 향상을 목적으로 한다.",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-09-05",
    name: "(사)주한외국기업인사관리자협회",
    purpose: "외국계 글로벌기업 인사관리자를 대상으로 정기적인HR학술 심포지엄 개최, 전국 대학 취업지원센터 및 일자리센터와의산학 교류를 통한 청년취업지원 및 HR교육훈련을 통한 글로벌인사관리 전문인력양성 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-09-08",
    name: "(사)내일의 내일",
    purpose: "노동 및 일자리 관련 연구 및 실태조사, 비정규직․특수고용․프리랜서․이주․고령 노동자 등 취약노동자 보호, 노동자와 일하는 시민 교육에 관한 사업과 이를 위한 출판 및 콘텐츠 제작, 위 사업을 수행하기 위한 용역․위탁․지원, 기타 사업목적에 필요한 사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-09-15",
    name: "한국보건안전단체총연합회",
    purpose: "일터 안전 및 일하는 사람의 보건·안전 단체의 연대와 소통을 도모하고, 보건·안전 단체의 의견을 정부 및 지방자치단체에 건의함으로써 국민의 보건과 안전을 실현시키는데 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-11-22",
    name: "사단법인 재한태국인협회",
    purpose: "태국인 근로자의 인권, 권익보호, 법률상담, 건강증진, 문화교류, 불편사항 해소",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-12-19",
    name: "사단법인 광양만권인력양성사업단",
    purpose: "지역산업 특성을 반영한 산업・일자리전환으로 지역의 미래를 위한 새로운 일자리를 발굴하고,지역에 투자하는 기업에 대해 최적의 기술인력을 매칭시켜 광양만권 및 지역경제발전에 이바지",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2023-12-28",
    name: "사단법인 한국건설기계협회",
    purpose: "산업재해예방을 위한 정책 연구·개발, 안전교육 및 건설기계에 대한 지도 및 점검 등을 통하여 특수형태근로종사자를 보호하고 쾌적한 작업 환경을 조성하는 것을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-01-19",
    name: "사단법인 이에스지노동사회협회",
    purpose: "기업이 국내·외 노동 기준 등을 충실히 준수하도록 지원함으로써 기업의 ESG(환경ㆍ사회ㆍ지배구조) 지속가능 실사 능력을 강화하고, 이를 통해우리 기업의 글로벌 경쟁력을 높이며 근로자의 권리를 신장하는데 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-01-19",
    name: "사단법인 화순광산실직근로자협회",
    purpose: "화순군 소재 폐광 광산에서 실직한 근로자의 일자리창출 및 재취업지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-02-26",
    name: "사단법인 케이씨안전기술센터",
    purpose: "산업안전보건에 관한 교육 및 정보제공, 사업장 안전보건 진단 위험성평가 기술 지원, 산업재해 및 중대재해 예방 홍보활동 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-03-20",
    name: "(사)한국신중년중앙회",
    purpose: "신중년 일자리 창출을 통한 경제적 지위 향상 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-04-02",
    name: "아름드리",
    purpose: "장애인 및 사회적 취약계층에 대한 근로환경 및 인식개선을 위해 고용촉진 연구와직업교육 및 취업지원 사업을 진행함으로써 당사자의 경제적 자립과 삶의 질 향상에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-04-08",
    name: "(사)한국로베드협회",
    purpose: "산업재해보상보험법상 노무제공자인 화물차주 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-05-30",
    name: "한국패럴런트협회",
    purpose: "패럴런트들의 재능과 역량을 발휘할 수 있도록 후원하고 취업을 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-06-04",
    name: "사단법인 대한중대재해예방협회",
    purpose: "① 중, 소규모 사업장의 산업재해 예방 관련 연구, 교육 및 정보 제공을 통해 중대재해예방,     예측 및 대응 방안 이해 증진② 중, 소규모 사업장 안전 캠페인 및 이벤트를 통해 사업장의 안전한 환경 조성 촉진③ 산업안전보건 관련 평가, 컨설팅, 자문 사업④ 중대재해 예방에 관한 정책과 표준에 대한 연구 개발 및 제안⑤ 기타 본회의 목적 달성에 필요한 사업",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-06-05",
    name: "사단법인 첨단산업인재지원협회",
    purpose: "청년고용정책 활성화를 위한 정책연구 및 산·학·관 연계를 통한 정보교류 지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-06-10",
    name: "재단법인 에이치디현대희망재단",
    purpose: "조선산업현장 중대재해 사망 근로자 유가족 지원",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-07-08",
    name: "사단법인 상생의가치",
    purpose: "노사민정 이해관계자 간 대화와 상생의 가치를 기반으로 사회의 공감대를 형성하고 지역사회의 지속 가능발전을 도모함으로써 지역 현안 해결 및 경제발전에 기여함을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-07-18",
    name: "사단법인 미래고용노동연구회",
    purpose: "노동관련 법제, 고용안정 및 근로환경 개선, 산업안전보건 및 직업능력개발 등에 관한 컨설팅 지원사업을 통해 건강한 노사문화 정착에 이바지함을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-10-04",
    name: "사단법인 한국전문면접관협회",
    purpose: "직무수행능력 평가모델을 적용하여 전문면접관을 양성.교육하고, 직무수행역량평가모델에 따른 문항 및 면접도구를 개발하여 고용증진에 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-12-05",
    name: "사단법인 한국긱워커네트워크",
    purpose: "우리 사회 대표적인 불안정 노동자인 초단기 노동자의 노동권익 향상",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-12-10",
    name: "사단법인 한국연금학회",
    purpose: "퇴직연금, 공적연금, 개인염금,연금보험 기타 노후생활안정 관련 분야 이론과 실무에 관한 연구",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2024-12-26",
    name: "재단법인 한국노동재단",
    purpose: "노동이 존중받고 연대하는 사회로 나아가는 것으로 목적으로 함",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-01-31",
    name: "한국일자리지원재단",
    purpose: "일하려는 사람 및 취약계층에게 일경험 제공 및 일자리지원사업 수행,  일하는 사람에 대한 안전, 건강 및 복지증진 사업 수행, 고용노동 관련정부 시책 홍보 및 학술 연구 등",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-02-25",
    name: "한국장애인복지단체표준사업장연합회",
    purpose: "장애인복지단체가 운영하는 장애인표준사업장 연합체로서 양질의 장애인 일자리 창출, 훈련시스템 구축 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-03-07",
    name: "사단법인 지역혁신과 이민",
    purpose: "인구 변동과 산업구조 변화에 따른 지역고용 및 외국인 정책에 대한 연구 및 학술활동",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-03-17",
    name: "사단법인 한국시니어산업융복합협회",
    purpose: "“시니어 전성시대”의 맞는 종합 솔루션을 준비하고, 시니어의 사회 참여, 시니어의 권익 지원등으로 사회발전에 기여",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-04-21",
    name: "사단법인 패션봉제산업 상생협의회",
    purpose: "패션봉제 산업 및 종사자들의 상생협력을 통한 생산 및 유통구조, 노동조건 개선, 권익 및 권리증진, 지역사회 교류 및 협력 확대 등을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-05-12",
    name: "사단법인 카부기공제회",
    purpose: "플랫폼 노동자(대리운전기사)의 삶의 가치를 보호하고, 열악한 근무환경을 개선해 안정적인 직업인으로서사회적 공익에 이바지하기 위함",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-05-15",
    name: "사단법인 사회적가치혁신센터",
    purpose: "노인 일자리, 재취업을 위한 진로상담과 교육, 정책연구 및 제안활동을 통해 노인들의 심리안정으로 삶의 질 향상",
    law: "-",
    type: "재단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-06-05",
    name: "사단법인 더 안전한 교육협회",
    purpose: "대한민국의 산업안전과 산업보건의 증진을 위하여 교육, 컨설팅, 자문 등의다양한 방법을 통하여 우리 사회에 생명 존중과 안전이 최고의 가치로 자리 잡을 수 있도록 하는데 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-06-12",
    name: "사단법인 더 월드",
    purpose: "고용허가제 외국인근로자에 대한 직업‧직장 적응력 강화 지원, 사업장 내외 고충의 상담 및 권익 보호, 관련 정책‧제도 개선활동 등을 통해 외국인근로자 제도의 정착과 고용안정 및 국민경제 발전 도모",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-06-16",
    name: "대한직업환경의학회",
    purpose: "작업환경의학에 관한 학술연구, 교육 등",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-07-24",
    name: "사단법인 미래HRD진흥원",
    purpose: "취업취약계층 대상 일경험, 교육, 연구용역 등을 수행하여 지역에 적합한 일자리사업 창출",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-10-16",
    name: "사단법인 돌봄요양보호사 고용지원협회",
    purpose: "요양보호사 교육기관 운영 및 훈련참여자 대상 직업상담‧취업 알선 서비스 제공",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-11-05",
    name: "사단법인한국신장년진흥회",
    purpose: "신장년세대 하이테크 기반의 일자리 창출 교육 및 취업지원",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-11-05",
    name: "사단법인 한국중대재해학회",
    purpose: "중대재해 예방 연구와 기술개발 촉진 통한 정책 제안과 교육 선도, 관련 학계, 산업계 등 협력을 통한 안전한 근로환경 조성 기여",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
  ExcelRowData(
    permitDate: "2025-11-05",
    name: "사단법인 한국비정규직노동단체네트워크",
    purpose: "비정규직 노동단체 간 연대 및 취약노동자 관련 정책 개발과 제도 개선 추진",
    law: "-",
    type: "사단",
    remit: "고용노동부",
  ),
];
