import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> mndRawData = [
  ExcelRowData(
    permitDate: "'91.6.4",
    name: "한국전략문제연구소",
    purpose: "안보정책과 군사전략 연구 활동 수행",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'91.11.26",
    name: "한국방위산업학회",
    purpose: "방위산업관련 정책개발로 방위산업의 진로모색 및 정부와 산․학․연 간의 협력증진",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'93.3.18",
    name: "한미안보연구회",
    purpose: "동아․태지역 평화와 한․미 안보 협력 방안 연구토의 및 관계국간의 학술교류",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'93.6.28",
    name: "한국군사사회연구소",
    purpose: "국방정책 및 민･군 관계에 대한 체계적 연구를 통해 국방발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'94.1.1",
    name: "한국군사문제연구원",
    purpose: "국방/군사 제반분야를 연구ㆍ분석 하여 국방정책 수립 및 군사발전에 기여하고, 예비역 지원 (취ㆍ창업 및 사회적응)",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'94.11.9",
    name: "동북아전략연구소",
    purpose: "동북아지역 문제를 연구하여 국가 안보정책 수립에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'95.12.15",
    name: "한국군사학회",
    purpose: "군사․국방과제 연구 발표, 정책/ 전략개발을 통해 국방정책 수립에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'98.4.27",
    name: "한국군사과학기술학회",
    purpose: "군사과학기술 국내외 관련 기관 간의 학술교류 및 정보교환을 통하여 국방력 강화에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'00.8.18",
    name: "한국국방경영분석학회",
    purpose: "국방경영분석과 관련되는 이론, 응용연구와 학술교류 등을 통하여 국방정책 발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'01.1.31",
    name: "21세기군사연구소",
    purpose: "국방정책 및 국방과학 기술의 전문성 향상에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'01.5.2",
    name: "한국리더십학회",
    purpose: "국방정책에 관한 학술 및 연구활동",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'02.8.1",
    name: "대륙전략연구소",
    purpose: "국내외 국방정책 및 군사전략 연구‧개발을 통한 미래지향적인 국방력 발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'02.12.17",
    name: "한국융합보안학회",
    purpose: "융합보안학문연구와 사이버테러 및 정보전에 관한 학문 연구·기술개발·기반 관련 국내·외 관계기관과 학술교류와 정보교환을 통한 국방융합 보안체계 발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'04.3.19",
    name: "해병대전략연구소",
    purpose: "한미 연합전력, 주변국 국가의 안보 정책과 군사전략의 체계적 연구",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'04.7.3",
    name: "국방경비대창군학회",
    purpose: "군사 전술전략의 연구활동을 통하여 국방정책 수립 발전",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'05.5.12",
    name: "국방보건복지연구원",
    purpose: "국방 보건정책 개발 및 예방의무/ 교리교범연구 개발, 군 의료 협력 체계 연구",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'05.12.7",
    name: "성우안보전략연구원",
    purpose: "국가 안보와 통일문제 연구, 국방정책 부서 및 연구기관에 자문",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'06.1.3",
    name: "국방소프트웨어협회",
    purpose: "국방 소프트웨어 관련 기술교육·지원 및 협력연구 증진 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'06.5.29",
    name: "한국국방안보포럼",
    purpose: "국방정책 관련 연구 및 학술활동",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'07.1.9",
    name: "대한민국 육군발전협회",
    purpose: "국방 및 육군정책 제분야 연구･ 분석을 통한 발전 방향 제시",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'07.11.5",
    name: "대한민국공군발전협회",
    purpose: "국방정책 및 공군정책 연구활동, 군사 및 자문 등 지원으로 국방 발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'07.12.6",
    name: "국방시설연구협회",
    purpose: "국방 시설, 안보, 환경 분야 정책수립을 지원하는 현안에 대해 조사, 연구, 자료제공, 간행물 발간 등을 통해 국가·국방 건설 발전에 이바지",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'08.4.22",
    name: "한국군사회복지학회",
    purpose: "현역․예비역․가족의 복지서비스를 연구․실천함으로써 지속적인 복지 향상에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'08.5.27",
    name: "글로벌전략개발원",
    purpose: "안보 및 국방･군사 관련 제분야 연구로 국방정책 발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'08.9.4",
    name: "6.25 국군포로유족회",
    purpose: "귀환 국군포로의 생활안정과 삶의 질 향상을 위한 지원사업 및 회원 간 친목과 상부상조",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'08.12.18",
    name: "충호안보연합",
    purpose: "안보에 관한 정책연구와 교육강좌 개최 등을 통해 국군장병 및 국민의 확고한 안보 통일관 확립",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'`09.2.24",
    name: "대한민국해군발전협회",
    purpose: "국방정책 및 해군정책 발전을 위한 연구, 지원",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'09.3.20",
    name: "국민생활안보협회",
    purpose: "대국민 안보의식 함양을 위한 공감대확산, 시･도 대학생 등 청년 조직 구축, 안보지킴이 회원확보, 안보의 핵심인 군대사랑 활동, 북한 바르게 알리기 및 탈북자 안정화 지원",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'09.4.6",
    name: "자유대한지키기 국민운동본부",
    purpose: "대한민국을 지키기 위한 범국민 안보 교육 활동 전개하고, 한미동맹 강화를 위한 주한미군, 미국 주요 인사 초청 행사 및 친선 교류, 안보강사 지원",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'09.12.30",
    name: "한국군상담학회",
    purpose: "군 상담이론 개발, 군 간부 및 군내 상담 관련 종사자의 상담능력 육성 지원, 군인가족 상담, 외국 군 상담 조직과 연계 및 공동 프로그램 개발 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'09.12.30",
    name: "대한군상담학회",
    purpose: "군 상담이론 발전 및 장병 정신건강증진 위한 상담 기법 개발, 군 지휘역량 강화를 위한 상담교육 프로그램 개발, 군 상담‧상담교육 지원, 군 상담관련 학술세미나 개최 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'10.3.2",
    name: "육군부사관학교발전기금",
    purpose: "∙육군 부사관의 군사분야 학술연구 및 육군 부사관 피교육생의 교육지원",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'10.3.29.",
    name: "을지연구원",
    purpose: "남북한 평화관계 발전을 위한 대북 정책 및 남북 군사회담 전략연구, 국군포로 및 납북자 송환 등 안보 현안 타결 전략 발전",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'10.3.15",
    name: "국군문화진흥원",
    purpose: "병영문화 개선 및 장병 정서함양을 위하여 도서 보급 및 독서운동, 강연, 문화예술 활동 등을 기획하고 지원",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'10.5.26",
    name: "국방정보통신협회",
    purpose: "국방정보통신의 연구활동 및 신개발 장비 전시회, 학술회의, 교육훈련, 정보통신지발간사업 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'10.6.17",
    name: "국방정보기술진흥원",
    purpose: "국방정보기술 혁신형 중핵기업 및 벤처육성을 위한 지원업무 수행, 국방 첨단정보기술관련 산‧학‧연 협력을 위한 개발, 연구 및 자문 지원 업무 수행 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'10.10.25",
    name: "호국문화진흥위원회",
    purpose: "국군 교향악단의 공연과 국가 및 국방부의 주요 행사지원, 세계 주요 국가(특히, 유엔참전국) 국군교향 악단 순회공연, 사회공익을 위한 공연 활동 협력사업 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'10.11.25",
    name: "통일안보전략연구소",
    purpose: "국가안보 및 국방정책, 전쟁의 역사 등과 관련된 학술연구",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'10.11.29",
    name: "군사정보발전 연구소",
    purpose: "정보관련 교범, 정보전사, 정보역사 등 교리연구, 북한 및 주변국 군사위협연구 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'10.12.17",
    name: "나라사랑포병연합",
    purpose: "포병의 위상제고와 발전책 강구, 6‧25포병전사 재정립, 6‧25전쟁 호국포병 전투 선양",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'10.12.24",
    name: "한국국방발전연구원",
    purpose: "미래지향적 국방태세 발전 및 군사 학술연구, 미래전장에서 소요되는 전력의 획득정책 및 전쟁지속능력 발전방안 연구",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'11.6.10",
    name: "21C안보실천연합",
    purpose: "범국민 안보의식 제고를 위한 홍보, 안보정신 교육 및 군복무에 대한 자긍심 고취를 위한 강연 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'11.7.13",
    name: "파월전사연구소",
    purpose: "파월전사 연구사업, 국방정책연구, 파월 제50주년 재조명 사업지원, 파월전사 홍보사업 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'11.7.25",
    name: "자주국방네트워크",
    purpose: "국방력 강화를 위한 연구 및 세미나, 병영문화 개선을 위한 정책제안, 국방홍보 공익활동 사업",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'11.9.1",
    name: "대한민국특전사동지회",
    purpose: "특수전에 대한 연구 사업, 국방부의 안보교육· 체험, 참여 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'11.9.2",
    name: "국방NCW포럼",
    purpose: "네트워크중심전(NCW)의 전장환경 연구와 분석을 통해 국방전장환경을 NCW 중심으로 발전시키는데 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'11.9.2",
    name: "한국국방정책학회",
    purpose: "국방정책 관련 연구발표 및 학술회의 개최, 목적을 같이하는 국·내외 기관 및 학술단체와 교류",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'11.10.31",
    name: "국방대학교발전기금",
    purpose: "국방대학교의 교육발전과 학술연구에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'11.11.30",
    name: "한국인력진흥원",
    purpose: "국방전직정책 학술세미나 개최 및 연구, 국방전직 지원을 위한 사업 지원 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'12.1.18",
    name: "국방안보교육진흥원",
    purpose: "참군인의 표상 발굴, 사례집 발간 및 선양활동을 통해 국민과 군의 안보의식 제고",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'12.2.21",
    name: "미래군사학회",
    purpose: "군사학 및 관련학문 연구를 통한 국가안보와 평화통일에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'12.3.26",
    name: "한국사이버국군발전협회",
    purpose: "사이버군 발전에 필요한 민간기술에 대한 기술수집과 대·내외 사이버전 수행분야에 대한 연구를 통해, 국방 정책 수립의 토대를 제공",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'12.6.21",
    name: "북극성안보연구소",
    purpose: "국방 및 군사분야에 대한 정책연구를 통하여 국가안보와 방위태세 발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'12.6.28",
    name: "대한민국예비역부사관 총연합회",
    purpose: "국가안보 및 사회봉사활동(유해발굴 현장 조언, 안보 전적비 관리 등), 안보관련 우수사례 발굴 및 전파",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'12.10.18",
    name: "한국국방수송협회",
    purpose: "民·官·軍·學이 연계한 선진 국방수송체계 구축 및 국가안보 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'12.11.14",
    name: "한국문화안보연구원",
    purpose: "국방문화정책 개발에 대한 연구협력 및 지원",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'12.12.4",
    name: "대한민국을지키는 행복의나무",
    purpose: "현역/예비역 군인과 가족의 복지와 행복증진,",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'12.12.24",
    name: "호림안보협의회",
    purpose: "호림부대 활약상 홍보 및 선양활동을 통해 국가안보의식 고취",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'13.3.28",
    name: "한국국방안보연구소",
    purpose: "안보국방분야에 대한 정책 및 전략평가",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'13.3.29",
    name: "국방인재개발원",
    purpose: "입영예정자 무료상담 및 전역장병 취업지원 프로그램 운영 등을 통한 군 인적자원의 최적화 활용방안을 마련하여 우수 국방인력 육성 및 전역자원의 사회활용에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'13.4.15",
    name: "공군역사재단",
    purpose: "공군의 정책과 항공우주분야에 관한 제반활동을 지원하고 공군의 역사 및 전통을 계승∙발전",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'13.10.29",
    name: "한국참전연예예술인협회",
    purpose: "참전 예술인들을 근간으로 숭고한 호국정신 계승과 친목 도모,",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'13.11.1",
    name: "한국군사시설연구소",
    purpose: "국방･군사시설 기준, 구조물 방호평가 및 진단, 군사시설 사업관리 관련 학술연구 및 국방시설 정책 및 군사시설 기술 전문성 향상으로 국방･군사시설 발전",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'13.12.9",
    name: "국방국악문화진흥회",
    purpose: "군내 국악 전통문화 보급을 위한 협력⋅지원 사업의 개발 및 연구로 장병 사기 진작 및 군 전투력 향상에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'14.2.10",
    name: "군인자녀교육진흥원",
    purpose: "현역 군인의 자녀와 전몰⋅순직 군경 유자녀의 교육지원 및 교육 프로그램 개발⋅운영을 통한 군인의 자녀교육 부담 경감과 안정적인 복무여건 조성에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'14.2.13",
    name: "한국전쟁헌충사업회",
    purpose: "수많은 전쟁에서 조국을 위해 헌충한 호국인물에 대한 현양사업을 통해 호국 선열들의 호국정신 계승과 위훈 추모",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'14.8.26",
    name: "국방민군사업발전협회",
    purpose: "민･관･군의 협력을 통한 군사자문/군사지원체계의 구축과 관련된 연구를 수행하고 정책대안을 제시하여 국방경영발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'14.10.8",
    name: "해군사관후보생장교중앙회",
    purpose: "∙국가안보 관련 연구 및 교육사업",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'14.11.3",
    name: "귀환국군용사회",
    purpose: "귀환 국군포로의 권익보호 및 국내정착 지원",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'14.11.27",
    name: "대한민국잠수함연맹",
    purpose: "잠수함 전력 홍보, 잠수함부대 후원, 해양안보 및 잠수함 관련 학술 연구 등의 활동을 통하여 잠수함 부대의 발전과 국가 안보에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'14.12.17",
    name: "국가미래포럼",
    purpose: "국민 안보의식 함양 위한 안보전문가 초청 정기세미나 시행 및 국방관련 민∙군 유대강화 홍보활동 전개 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'15.1.19",
    name: "국방MICE연구원",
    purpose: "국방정책 운영과 방산물자 수출․입 간에 발생하는 MICE 관련 업무를 학술적, 실무적으로 지원함으로써 국방정책의 효과적인 시행과 예산의 효율적인 집행, 방위산업의 활성화를 도모",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'15.3.3",
    name: "청목평화동지회",
    purpose: "국민 안보의식고취 및 평화통일을 위한 기틀 마련에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'15.5.11",
    name: "대한민국 헌병전우회",
    purpose: "군 관련 사건・사고 예방과 관련된 연구 및 자문, 안보행사 참여, 현역・예비역 및 주한 외국군 헌병과 유대관계를 통한 민・군 통합에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'15.5.19",
    name: "한국국가전략연구원",
    purpose: "국가안보 정책과 전략에 관한 지속적이고 체계적인 연구 활동을 수행함으로써 국가안보 정책과 전략 수립 및 시행에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'15.10.12",
    name: "한국융합안보연구원",
    purpose: "융합안보 이론체계 정립, 융합안보 기반의 정책 연구⋅개발과 인재 육성",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'15.11.18",
    name: "광복청년아카데미",
    purpose: "항일 독립정신의 계승 및 선양 활동, 독립군 활동사 및 전투사 발굴∙연구 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'15.11.26",
    name: "항공우주전략포럼",
    purpose: "∙항공우주전략과 관련된 학술의 연구 및 보급",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'15.11.30",
    name: "한국미래사회교육원",
    purpose: "군 장병의 정신무장 강화 및 청년세대들의 올바른 나라사랑 정신함양에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'15.12.10",
    name: "한중안보평화포럼",
    purpose: "∙한․중 안보포럼 개최",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'15.12.21",
    name: "육군학생군사학교 발전기금",
    purpose: "∙글로벌 인재 육성을 위한 우수인력 획득 및 10개 과정의 후보생 장학사업",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'15.12.21",
    name: "6⋅25진실알리기본부",
    purpose: "전후세대에게 6⋅25 전쟁의 진실을 알려 자유민주주의 체제에 대한 신념과 안보의식 고취를 통해 평화증진에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'16.1.7",
    name: "군 인성교육진흥원",
    purpose: "군 장병 인성교육 진흥을 위한 교육지원 및 발전방안 제시를 통해 건전한 시민의식 확립",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'16.1.29",
    name: "미래안보산업전략연구원",
    purpose: "안보산업과 전략에 관련된 업무를 학술적⋅실무적으로 지원함으로써 안보산업이 미래지향적으로 발전하는 데에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'16.2.1",
    name: "미래안보전략연구소",
    purpose: "국가안보⋅국방정책⋅군사전략⋅평화통일에 관한 연구",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'16.3.9",
    name: "대한해외참전전우회",
    purpose: "참된 파병의 뜻과 성과의 올바른 인식 및 대한민국 국가안보와 국가경제발전, 호국이념 제고에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'16.5.2",
    name: "대한민국EOD(이오디) 협회",
    purpose: "대테러 폭발물 처리 기술과 정보 교류, 대테러 기술개발연구와 전문가 육성",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'16.7.7",
    name: "공군학사장교회",
    purpose: "국방 문화활동 참여를 통한 국가사회와 군 발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'16.7.8",
    name: "대한민국 해병대전우회",
    purpose: "대한민국의 정체성을 수호하고 국가의 안전보장과 번영에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'16.8.19",
    name: "캠프리딩 코리아",
    purpose: "장병 가치관정립 및 자기계발, 소통문화를 통한 정신전력향상",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "'16.10.20",
    name: "국방지능정보기술융합협회",
    purpose: "정보혁명 시대에 맞는 지능형 국방ICT와 산업생태계의 융합을 통하여 국방 안보 및 군 정보화 발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "‘17.02.28",
    name: "한국안보협업연구소",
    purpose: "복합적 안보위협 효율적 대처를 위한 안보협업 기반의 안보정책 개발",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’17.3.23",
    name: "사단법인 학도의용군전우회",
    purpose: "학도의용군의 숭고한 희생정신을 홍보 및 계도하고, 호국정신 계승과 선양활동으로 안보의식 고취",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "‘17.4.12",
    name: "한국주니어사관(JROTC)연맹",
    purpose: "한국주니어사관(JROTC)연맹은 청소년들에게 제대군인의 군 경험과 전문성을 활용하여 “올바른 인성과 리더십, 국가관”을 함양할 수 있는 기회를 제공하여 올바른 민주시민으로 성장할 수 있도록 돕기 위함.",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "‘17.11.27",
    name: "한미포럼",
    purpose: "주한미군 평택기지 이전에 따른 대한민국인과 미국인간의 상생우호발전 도모",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "‘18.1.2",
    name: "사단법인 21C안보전략연구원",
    purpose: "대국민 안보의식과 국가발전을 도모하고 장병 정신 전력 강화",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "‘18.07.27.",
    name: "한국국방외교협회",
    purpose: "해외 주재 무관 예비역 등 국방외교 관련 역임자들의 경험과 전문성을 활용하여 국가와 군 발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’19.2.11.",
    name: "한국국방기술학회",
    purpose: "국방과학기술 정책의 연구와 조사를 통해 자주국방 확립, 방위산업발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’19.5.13.",
    name: "군사상유가족협회",
    purpose: "군 복무 중 사망자의 유족 지원을 위한 봉사활동 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’19.9.17.",
    name: "한국지뢰안전협회",
    purpose: "'지뢰로부터 안전한 세상 만들기'를 위한 국제교류 및 협력 전개",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’20.5.01.",
    name: "고등국방정책연구소",
    purpose: "국방정책과 군사전략에 관한 지속적이고 체계적인 연구 활동 수행, 국방정책의 수립,  국방 발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’20.6.01.",
    name: "대한민국 폭발물 기술자협회",
    purpose: "폭발물처리 관련 기관 및 회원 대상 폭발물처리 대응방법 연구 및 교육훈련 지원, 재해재난 사고지원 활동 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’20.6.23.",
    name: "재단법인 특수전학교 발전기금",
    purpose: "특수전학교 군사 분야 학술 연구 및 교육과정의 군사훈련 및 국내외 견학 지원 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’20..7.07.",
    name: "대한국방교육진흥회",
    purpose: "선배군인의 경험과 전문성을 바탕으로 장병들에게 군인정신 및 인성 함양교육 등 지원",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’20.10.06.",
    name: "국방과사람들",
    purpose: "국방정책 및 군사전략 관련 연구 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’21.3.22",
    name: "글로벌국방연구포럼",
    purpose: "미래지향적인 국방정책 및 전력연구를 위한 국방전문 씽크댕크(Think Tank)를 구축하여 국가안보역량 강화에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’21.4.27.",
    name: "국방로봇학회",
    purpose: "국내외 국방로봇에 관련된 학술과 기술의 정보교환과 학술활동 도모 및 산학군연 협동을 촉진함으로써 국방로봇 기술발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’21.7.12.",
    name: "성무안보연구소",
    purpose: "미래지향적인 국방정책 및 군사분야 정책연구를 통해 국가안보와 지역사회 발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’21.8.30.",
    name: "국제평화품앗이학회",
    purpose: "유엔 평화유지활동 관련 국내외 학술·교류활동, 국방 분야 보훈활동 및 청소년 국제 교류 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’21.12.16.",
    name: "한미육군동맹협회",
    purpose: "주한 미육군의 장병, 가족 그리고 군속들이 대한민국의 문화와 전통을 이해하는데 도움을 주고 조기에 적응토록 지원하여 양국 상호간에 결속력 강화와 한미동맹을 굳건히 하는데 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’22.01.13.",
    name: "사단법인 대한민국 군가 기념사업회",
    purpose: "군가에 깃든 가치 발굴 및 정신 계승과 선양을 위한 사업 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’22.01.17.",
    name: "사단법인 한국국방우주학회",
    purpose: "국방우주 관련 조사와 학술연구, 학술세미나·강연회 등의 개최 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’22.3.17",
    name: "대한민국 군수산업연합회",
    purpose: "군수산업 박람회 개최(DX-KOREA, ADEX 등 연계)",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’22.4.4.",
    name: "국제인성교육진흥협회",
    purpose: "국군장병 인성지도자 양성 및 세미나 개최, 문화예술교육 프로그램 개발, 위문공연, 인성교육, 군인문화예술 발전에 필요한 지원 사업 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’22.5.03.",
    name: "한국군사법학회",
    purpose: "군사법 분야의 연구를 촉진, 한국 군사 법학 발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’22.11.15.",
    name: "사단법인 밝은미래운동본부",
    purpose: "대한민국의 밝은미래 건설을 위한 유·무형의 애국·호국활동과 동시에 민·군상생 조성 및 국방정책 발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’22.11.17.",
    name: "사단법인 대한민국호국총연합회",
    purpose: "자주국방의 기틀을 바로 세우기 위한 국방정책연구 및 안보교육 추진을 통해 정부의 평화통일 노력에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’22.12.13.",
    name: "국방재난안전연구소",
    purpose: "재해·재난 등 비전통 위협 대비 및 국민안전 관련 시스템과 정책 연구, 안전 관련 사회기반시설과",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’23.0.1.20.",
    name: "국방전투태권도연구소",
    purpose: "군 전투력 향상을 위한 태권도 활성화, 전투태권도 시범단 운영 및 활성화, 태권도 발전을 위한 군내ㆍ외 유관기관 교류, 태권도 및 스포츠 관련 대회 개최ㆍ후원, 출판물 발간 및 연구, 기타 장병 체력향상 및 스포츠 발전을 위해 필요한 사업",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’23.02.28.",
    name: "한국-유엔사 친선협회",
    purpose: "유엔사의 중요성 홍보 및 유엔사, 유엔사 회원국, 중감위에 대한 활동 지원",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’23.3.3.",
    name: "국방산업연구원",
    purpose: "국방산업 클러스터 조성사업, 국방산업 고도화 관련 연구과제 수행, 미래 도전국방기술 연구개발사업 제안 및 연구수행",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’23.3.29.",
    name: "서울 안보 포럼",
    purpose: "국방정책연구, 안보 교육사업 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’23.4.7.",
    name: "대한민국ROTC국방안보연합회",
    purpose: "군 부대 문화 활동 지원 및 보급, 군부대 및 청소년 등에 대한 정훈교육 프로그램 개발, 참전국과의 외교활도 ㅇ지원 및 국제 평화유지 활동",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’23.5.3.",
    name: "한국회복탄력성협회",
    purpose: "군장병대상 맞춤형 회복탄력성 프로그램 개발 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’23..6.30.",
    name: "국군명예회복운동본부",
    purpose: "국군의 명예를 고양하고 왜곡된 명예를 회복, 국민의 안보의식 강화를 위한 안보강의, 세미나 언론 기고 활동, 장병 문화활동 지원",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’23.8.24.",
    name: "시니어 아미",
    purpose: "언론매체 및 SNS를 통해 국민 안보의식 고취를 위한 홍보 활동, 국방 전문가 초청 특강 및 세미나를 통한 회원들의 안보의식 고취, 지역예비군훈련 참가, 희망자는 지원예비군으로 지원 유도",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’23.10.4.",
    name: "해군첩보부대 동지회",
    purpose: "해군과 교류 및 지원(장비 및 물자 획득 후 기증, 안보체험 등), 사회봉사 및 재해ㆍ재난시 대민지원, 국민들의 안보의식을 고취 활동 등을 하며 국가 위기시 지원예비군으로 군사작전을 지원",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’23.10.5.",
    name: "사단법인 전쟁기념관회",
    purpose: "기념관 전시지원 및 자원봉사 활동, 학술자료와 조사연구 지원 및 전시지원 등 전쟁기념관 관련 문화사업",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’23.11.27.",
    name: "한국전쟁학회",
    purpose: "6·25전쟁 및한국관련전쟁에관한연구및학술교류를통해전쟁을바라보는건전한관점 및 외교·국방정책 조언제공",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’23.12.8.",
    name: "대한민국 해군 동지회 중앙회",
    purpose: "군인정신 및 자긍심 함양을 위한 연구, 교육지원등 장병의 올바른 가치관 확립과 국가 재난지원에 솔선수범하여 재난극복에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’24.1.8.",
    name: "한국군사랑모임",
    purpose: "장병 사기와 복지를 위한 군인 자녀 교육지원, 군인 자녀 해외인턴 프로그램 시행 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’24.1.2.",
    name: "퍼플하트",
    purpose: "군 복무중 중증 외상부상을 당한 환자 및 그 가족에 대한 금전적 심리전 지원을 통해 대상자들의 회복을 도모",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’24.1.11.",
    name: "군 소음 난청 이명 예방협회",
    purpose: "군 사격 피해예방을 위한 학술연구 등 예방활동으로 대한민국 국민과 국군에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’24.1.31.",
    name: "대한민국예비역장교연합회",
    purpose: "예비역장교의 나라사랑 거양 및 굳건한 장교정신 신념화",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’24.2.14.",
    name: "국방혁신기술보안협회",
    purpose: "군 관련 최신 혁신기술 및 보안기술 발전을 위한 연구개발, 전문인력 양성을 위한 교육, 산·학·연·군 관계자 네트워크 구축 등 급변하는 보안 위협에 능동적으로 대비하는 미래지향적 군 관련 보안업무 진흥",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’24.4.2.",
    name: "국군위문예술단",
    purpose: "성별, 종교, 장애, 나이, 사회적 신분, 출신지역, 인종 등을 초월한 문화예술활동과 봉사의 조화로운 실천을 추구함으로써 국가와 국민을 수호하는 국군을 위한 관련 지원사업을 수행",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’24.4.24.",
    name: "밀리테크협회",
    purpose: "미래 전쟁수행개념의 변화를 연구하여 대안을 제시하므오써 국가안보에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’24.5.17.",
    name: "창끝전투",
    purpose: "창끝전투(첨단 전투 기술·국방혁신·인력 양성 교육 등) 관련 세미나 및 자료발간, 창끝전투 관련 학술 유관단체 교류, 창끝전투 관련 학술연구 등 학술발전과 정책수립 지원 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’24.7.31.",
    name: "사단법인 국군사랑",
    purpose: "국민들이 군을 신뢰하고 감사하는 분위기를 조성하여 군 사기 진작",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’24.8.23.",
    name: "사단법인",
    purpose: "미래세대가 지뢰 등의 위험으로부터 완전히 안전한",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국지뢰대응기술협회",
    purpose: "상태에서 살아갈 수 있는 환경을 조성하는데 전력하는 것",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’24.9.5.",
    name: "퓨쳐링크",
    purpose: "한반도의 대내외적 안보·사회환경 변화에 능동적으로 대응하기 위한 국가전략 및 정책 아젠더 발굴 등을 통해 국가역량 강화 및 공공복리 증진에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’24.10.2.",
    name: "국방혁신공학회",
    purpose: "국방혁신을 위한 공학기술 및 학술을 조사·교육·연구·개발하고 국내외 관계기관과의 학술교류·정보교환으로 대한민국 자주국방의 확립과 국방혁신 산업의 발전에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "’24.10.22.",
    name: "해공회",
    purpose: "한국 및 세계 각국의 군사시설 연구, 국방건설기술의 지속적 연구개발, 국방시설정책 발굴, 국토 및 해양영토의 특성 분석 등을 통해 대한민국 국토방위에 이바지",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "‘25.1.2.",
    name: "국군예우사업회",
    purpose: "대한민국 군인에 대한 사회적 예우와 존경을 높일 수 있는 다양한 지원사업 수행",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "2025.1.21",
    name: "미해군연맹한국협회",
    purpose: "대한민국 안보에 기여하는 미 해군·해병대 장병 등을 지원하고, 한미동맹 강화에 기여",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "2025.2.4",
    name: "공군ROTC장교회",
    purpose: "공군의 국방문화 연구, 교육지원 등으로 군의 정신전력 발전에 기여함.",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
  ExcelRowData(
    permitDate: "2025.4.14",
    name: "한국방위산업보호협회",
    purpose: "기술유출 등 방산 침해 위협에 대한 민간 주도 보호 활동 추진 및 국내외 방산 정보공유·수출·정책지원 등",
    law: "-",
    type: "-",
    remit: "국방부",
  ),
];
