import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> mojRawData = [
  ExcelRowData(
    permitDate: "-",
    name: "한국민사법학회",
    purpose: "민사법 연구",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국부동산법학회",
    purpose: "부동산 관계법 연구",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국비교사법학회",
    purpose: "사법의 비교 연구",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "행복세상",
    purpose: "법치주의 문화 확산 및 사회 공동체간 신뢰 확보",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "굿소사이어티",
    purpose: "진정한 법치주의 실현으로 인한 시장 경제 정착",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국재산법학회",
    purpose: "국내외 재산법 연구",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국법철학회",
    purpose: "법철학 연구",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 중앙법학연구소",
    purpose: "법이론과 현실에 관한 연구, 발표, 연구자료 출판",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국가족법학회",
    purpose: "가족법 및 가족관계에 관한 연구",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국교회법학회",
    purpose: "교회내 법적 분쟁을 예방하고, 교회재판에 대한 기준 제시",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국성년후견학회",
    purpose: "장애인의 인권보호와 권익신장을 위한 법과 정책을 연구하고 관련 실천활동을 수행",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국법이론실무학회",
    purpose: "변호사 등 법조실무가와 법률이론가의 커뮤너티 형성, 법학교육 및 법률문화의 건전한 육성과 발전",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 장애인법연구회",
    purpose: "장애인법 연구, 법 관련 법률가 및 전문가 교육, 장애인 인권 관련 공익소송 및 자문",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한ㆍ불민사법학회",
    purpose: "한국 프랑스 민사법을 널리 알리는것을 목적으로 한국프랑스 민사법연구, 도서발간, 학술교류, 공동연구 등의 사업 수행",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국후견협회",
    purpose: "치매, 고령 등 의사결정능력 장애 성인의 인권보호 및 권익신장을 위한 업무수행",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국후견사회복지사협회",
    purpose: "장애인, 노인 등의 복지 및 권익옹호, 전문후견인 양성",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국집합건물진흥원",
    purpose: "집합건물 분야의 학술,교육,문화,법제도의 발전에 기여하고 사회발전에 따른 집합건물 관리현실의 변화에 대응함으로써 집합건물 문화창달에 기여하고 사회에 봉사함",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국법학원",
    purpose: "법학 연구, 법률 문화 향상",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국법학교수회",
    purpose: "법학교육의 발전과 법학계와 법조실무계의 협력 및 법률 문화 향상",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "서울대학교법학발전재단",
    purpose: "법학 연구, 교육지원, 학술교류 발전사업 등",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "영산법률문화재단",
    purpose: "법률문화의 창달",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대한의료법학회",
    purpose: "의료 법학 전문 분야 법률문화 향상 기여",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "해송법률문화재단",
    purpose: "법률문화 발전에 기여",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국포렌식학회",
    purpose: "포렌식분야 학문의 발전 기여",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국성년후견지원본부",
    purpose: "장애인, 노인 등의 복지 및 권익신장을 위하여 국가나 지방자치단체 및 법원과의 연계활동",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 사랑샘",
    purpose: "변호사들이 사랑나눔과 봉사헌신의 주체가 되어 법률복지를 몸소 실천함으로써 국가 사회의 성숙한 성장과 인류 평화에 기여",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국여성변호사회",
    purpose: "한국여성의 기본적 인권옹호와 사회적 지위향상 및 여성변호사의 권익향상과 복지증진, 문위 보전과 지식함양",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 온율",
    purpose: "법률관련 연구, 입법지원 등을 통해 법치주의 확립 및 개인의 기본적 인권 확립에 이바지",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 선",
    purpose: "사회적 취약 계층, 범죄피해자 등에 대한 지원사업",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "천고법치문화재단",
    purpose: "법률문화의 창달에 이바지하기 위함",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 생활법률문화연구소",
    purpose: "생활법률문화 연구 개발, 상담,강의 및 사이버 생활법률 콘탠츠 개발을 통해 소회계층 등을 위한 생활법률서비스 제공",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 두루",
    purpose: "공익을 위한 소송, 법률자문, 입법지원 등 법률활동 등을 통해 인권을 옹호하고 공정한 사회에 이바지함",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 나눔과 이음",
    purpose: "사회통합을 이루기 위한 사업을 영위함",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 화우공익재단",
    purpose: "우리사회의 법률복지 증진과 법률문화의 발전에 이바지 함",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국지적재산권변호사협회",
    purpose: "지적재산권 전문 변호사들의 커뮤니티",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국환태평양변호사회",
    purpose: "아․태지역 법제와 법률문화의 발전, 아․태지역 내 또는 동 지역에 관심이 있는 법률가들 사이의 교류 지원 등",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사회적협동조합 제주로",
    purpose: "사회적기업, 소상공인 및 마을기업 상대 법률.창업 컨설팅 진행 및 제주 지역내 취약계층 상대 법률 상담 제공",
    law: "-",
    type: "사회적협동조합",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 전국법과대학교수회",
    purpose: "전국 법과대학 상호간 교류를 통한 학술활동 증진, 법조계와의 협력을 통한 법학교육의 발전 도모 등",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 홍진기 법률연구재단",
    purpose: "실무 및 학문으로서의 법학 연구 장려 및 관련 법률문화 발전에 기여 등",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국디지털포렌식전문가협회",
    purpose: "디지털포렌식 제도와 기술발전에 기여하여 국가의 사법제도와 과학기술 발전에 이바지 함",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 나은",
    purpose: "법률 분야 연구 및 법률약자들의 권익 향상을 위한 활동 지원을 통한 기여",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 크레도",
    purpose: "법률, 경제, 문화 등 사회 각 영역에서 법률과 제도를 연구하고, 건전한 윤리의식에 기초한 발전된 법문화 구현을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 정",
    purpose: "사회적 취약계층의 경제적 지원 및 법률구조를 통해 바른 사회를 구현함",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한결",
    purpose: "사회 취약계층의 인권을 옹호하고 증진하며 국내외 공익인권 단체와의 협력을 통하여 민주적이고 정의로운 사회에 기여함",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 함께하는 빛",
    purpose: "우리 사회의 기본적 인권 옹호, 한센인의 인권 회복 및 증진 등",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)국제거래법학회",
    purpose: "국제거래법 분야의 기술적 연구와 연구자 상호 교류 및 공동연구 등",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)한중일 민상법통일연구소",
    purpose: "한중일 민상법을 연구하여 법률통일 실현",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한중법학회",
    purpose: "중국법조사연구, 한중 법문화발전 공익사업 전개",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 국제사법학회",
    purpose: "국제사법, 국제민사절차법, 비교사법 및 관련 분야의 이론과 실무에 대한 학술적 연구와 상호간의 교류 및 공동연구 등을 촉진",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 국제사이버법연구회",
    purpose: "사이버공간에 관련된 국제법 및 국내법의 관련 주제를 연구.토의함으로써 사이버 공간의 평화적 이용과 발전 도모",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한불법학회",
    purpose: "프랑스의 법제도 및 법문화 연구",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국 베트남ㆍ인도네시아 법ㆍ문화연구회",
    purpose: "베트남.인도네시아 법.문화 관련 분야의 학술적 발전 및 국가간 이해 및 교류증진",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국 보험법학회",
    purpose: "보험에 관한 국내외 법규범의 연구와 정보의 국제적 교류",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국 상사판례학회",
    purpose: "상사에 관한 국내외의 판례 및 법 연구",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국 도산법학회",
    purpose: "우리나라와 외국의 채무자회생·파산법의 법제도와 운영실태 조사, 연구",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "도산법 연구회",
    purpose: "도산법 연구를 통해 우리나라 도산법의 이론과 실무 발전에 기여",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 인하우스카운슬포럼",
    purpose: "기업에서 발생하는 각종 법률문제의 연구 및 보급",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국준법통제원",
    purpose: "준법통제에 관한 연구활동 지원 및 조성",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국사내변호사회",
    purpose: "기업법무와 관련된 각종 이론의 연구 등을 통한 사내변호사의 효과적 법률서비스 제공 및 준법경영에 대한 연구를 통해 기업의 경쟁력 제고에 기여",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국채무자회생법학회",
    purpose: "채무불이행자 구제방안 마련을 통해 건전한 사회발전 및 국가경제 발전에 기여",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국기업회생지원협회",
    purpose: "경영위기 기업의 신속한 회생을 위하여 필요한 법률적 자문과 절차적 지원 무료 제공 등",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 대한상사중재원",
    purpose: "상사분쟁의 중재, 조정, 알선 및 선적전 검사와 관련한 분쟁조정",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 대한중재인협회",
    purpose: "중재제도의 확대보급으로 경제질서를 정립함으로서 사회공익과 국민 편익 도모",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국신탁학회",
    purpose: "신탁제도 발전에 기여",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북부청소년문화재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "청지선도재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "효원선도재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남부소년선도재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "영월소년선도재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "춘천사랑잇기청소년재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "원주한마음청소년재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "영동해맞이청소년선도재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "푸른마음장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "인천사랑잇기청소년재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "경남선도장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "포항청소년선도재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평안밀레니엄선도장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "서부소년선도재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "전남동부지역선도장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "목포지역한마음장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "여주검찰범방장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "제주선도장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "푸른쉼터장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "월석부산선도장학회",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한빛장학회",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통영한마음장학회",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "광주한마음장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한마음장학회",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한사랑선도장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "푸른날개장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "은행나무청소년선도장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대경청소년선도장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "전주지역한마음장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "임수복장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "거창지역다림장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "푸른장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "충주지역예성드림장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한북장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "영동지역청포도장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "부산동부푸른장산장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남원지역지리산장학재단",
    purpose: "청소년에 대한 장학사업과 청소년선도활동 및 범죄예방활동에 대한 지원 등을 통하여 청소년을 비행과 범죄로부터 보호하고 건전한 사회인으로 성장하도록 도와주는데 목적",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 법사랑군산익산지역장학회",
    purpose: "불우, 모범 청소년 장학금 지급 및 생활부조 등",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 늘푸른장학회",
    purpose: "청소년에 대한 장학금 지급 등 장학사업",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 법사랑대전지역장학회",
    purpose: "청소년 범죄예방 활동의 일환으로 지역사회의 유능한 인재를 발굴하여 지속적으로 지원함으로써 국가와 민족을위해 공헌할 수 있는 사회지도 자로 육성",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국안보형사법학회",
    purpose: "안보형사법 연구",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국형사법학회",
    purpose: "형사법학 및 그 주변과학의 연구를 촉진시켜 한국형사법학의 발전에 이바지함을 목적",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국비교형사법학회",
    purpose: "비교형사소송법의 연구를 활성화 시켜 한국형사법학의 발전에 밑거름이 됨을 목적",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국형사소송법학회",
    purpose: "형사소송법의 연구를 통하여 한국형사소송법학의 발전에 기여함을 목적",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국과학수사학회",
    purpose: "범죄수사 및 과학수사에 관련한 학술 연구, 법과학 증거 관련 공익적 자문",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "갱생보호육성재단",
    purpose: "법무부가 추진하는 갱생보호, 보호관찰, 소년보호, 법교육, 범죄예방 등 범죄예방 시책사업 지원",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)한국소년보호협회",
    purpose: "청소년자립생활관 및 사회정착지원센터 운영, 창업보육기업 운영, 소년보호기관 교육활동 지원, 소년보호 관련 연구활동 지원",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국범죄방지재단",
    purpose: "아시아지역 형사사법관계자간 상호협력과  결속의 바탕위에 학술연구 등의 활동을 통하여 효과적인 범죄인 교화를 도모함으로써 궁극적으로 세계평화와 안정에 이바지함을 목적으로 함",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "자녀안심하고학교보내기운동국민재단",
    purpose: "청소년선도보호사업",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "청소년희망재단",
    purpose: "유해환경으로 부터청소년을 보호하고 안전한 사회환경을 조성함으로써 청소년이 건전한 사회인으로서 성장할 수 있도록 도와주는데 그 목적이 있음",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국사법교육원",
    purpose: "법교육프로그램 연구개발, 일반시민의 생활법률교육, 상담 등",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "행복공장",
    purpose: "법문화체험기회제공, 재소자 및 가족에 대한 치유지원 사업을 통하여 건강하고 행복한 삶을 누리게 하고 우리사회를 범죄로 부터 보호하는데 일익을 담당하는것을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국교화복지재단",
    purpose: "갱생보호사업",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "세계교화갱보협회",
    purpose: "갱생보호사업",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "담안선교회 자활원",
    purpose: "갱생보호사업",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "빠스카교화복지회",
    purpose: "갱생보호사업",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "양지뜸",
    purpose: "갱생보호사업",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "뷰티플라이프",
    purpose: "갱생보호사업",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "열린낙원",
    purpose: "갱생보호사업",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 뉴라이프재단",
    purpose: "출소자의 일자리 창출 및 직업훈련을 통한 범죄예방과 행복한 사회 만들기에 기여",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국법무보호복지학회",
    purpose: "법무보호복지사업 및 제도에 대한 제반 학술연구를 통해 법무보호복지제도 발전에 기여하고 회원의 자질향상",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국보호관찰학회",
    purpose: "보호관찰 정책과 행정에 관한 학술이론과 기법을연구 한국보호관찰제도의 발전에 기여함",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국회복적사법정의센터",
    purpose: "회복적사법정의를 바탕으로 교정 및 범죄예방사업을 수행하여 국내의 교정관련 프로그램 개발 및 제도의 발전에 기여함",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)대한범죄학회",
    purpose: "범죄, 청소년비행, 범죄심리, 범죄예방, 형사법 등 범죄와 관련된 분야에 관한 제반학술연구 및 교육연수",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "제로캠프",
    purpose: "청소년 범죄예방을 위한 사회적 관심과 참여를 촉구하고 비행청소년의 사회적응 역랼 개선 및 준법정신을 함양하여 건강한 대한민국 국민으로 성장할 수 있도록 지원 함",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국인권옹호협회",
    purpose: "국민 기본권 신장을 위한 인권운동, 인권 상담소를 통한 법률상담이나 무료변론",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "국제인권옹호한국연맹",
    purpose: "인권옹호에 관한 국제연합의 기본정신에 입각하여 국헌에 보장된 국민의 기본적 권리를 보장",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국인권재단",
    purpose: "인권에 관한 연구와 교육, 인권의 보호와 향상을 위해 노력하는 개인 및 단체 지원",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 대한변협인권재단",
    purpose: "인류의 인권향상에 기여",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 인권정책연구소",
    purpose: "인권관련 법,제도 모니터링",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국인권학회",
    purpose: "인권증진을 위한 정책 제시 및 활동",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 비온뒤무지개재단",
    purpose: "보편적 인권의 가치 실현",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국가정법률상담소",
    purpose: "국민의 기본적 인권 옹호 및 법률복지의 증진을 위한 법률구조사업",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "부산가정법률상담소",
    purpose: "국민의 기본적 인권 옹호 및 법률복지의 증진을 위한 법률구조사업",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대한가정법률복지상담원",
    purpose: "국민의 기본적 인권 옹호 및 법률복지의 증진을 위한 법률구조사업",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "로시컴법률구조재단",
    purpose: "국민의 기본적 인권 옹호 및 법률복지의 증진을 위한 법률구조사업",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대한변협법률구조재단",
    purpose: "국민의 기본적 인권 옹호 및 법률복지의 증진을 위한 법률구조사업",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "동천",
    purpose: "국민의 기본적 인권 옹호 및 법률복지의 증진을 위한 법률구조사업",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국범죄피해자지원중앙센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)부산범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)진주범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)광주전남범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)밀양창녕범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)인천범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)부산동부범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)경남범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)통영거제고성범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전주범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)천안아산범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)정읍범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)대전범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)수원범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)청주범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)고양범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)안산범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)부천범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)목포범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)장흥강진범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전남동부범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)군산익산범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)성남범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)논산범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)경기북부범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)공주청양범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)평택범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)충주음성범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)울산범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)서울동부범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)서울남부범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)서울북부범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)서울서부범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)춘천범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)강릉범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)원주횡성범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)속초범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)영월범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)대구경북범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)경북북부범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)경주범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)포항범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)김천구미범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)상주문경예천범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)의성범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)영덕울진영양범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)제주범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)대구서부범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)남원순창장수범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)제천단양범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)여주범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)영동범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)거창합천함양범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)서산범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)홍성범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국범죄피해자지원연합회",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)안양범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해남완도진도범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국피해자지원협회",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)마산범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국피해자학회",
    purpose: "범죄피해 및 피해자에 관하여 학제적이며 종합적인 연구를 통하여 피해자학 관련 학문의 발전에 기여하는 동시에, 피해자학 연구자들의 상호협력을 꾀함",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)범죄피해자지원부산스마일센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)부산서부범죄피해자지원센터",
    purpose: "범죄피해자 보호.지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "교정공제회",
    purpose: "교정공제회원 생활안정과 복리후생 및 장학·원호사업",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 아시아교정포럼",
    purpose: "교정보호학의 학문적 성격 확립 및 인간학적인 통합적 교정문화 창달",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사회적협동조합 한울배터리",
    purpose: "사회적 취약계층 고용 등 일자리 창출을 통한 사회공헌 활성화",
    law: "-",
    type: "사회적협동조합",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "기독교세진회",
    purpose: "수용자 선교 및 봉사",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국불교교화복지선도회",
    purpose: "불교 자비정신 구현으로 수용자 교화",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "새생명운동본부",
    purpose: "복음주의 신앙에 입각한 수용자 선교",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국교정선교회",
    purpose: "수용자 복음 전도와 교정교화사업",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "천주교사회교정사목위원회",
    purpose: "수용자 선교 및 재범방지를 위한 교정사목 활동",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "교정자원봉사지원센터",
    purpose: "범죄예방에 기여",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국교정복지회",
    purpose: "기독교를 통한 수용자 교화 및 사회복귀 지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 새희망교화센터",
    purpose: "수용자와 출소자에게 심리적, 물질적, 환경적 도움을 주고, 효율적인 교정교화 기법 연구",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 같이함께",
    purpose: "수용자, 출소자의 안정적 수용생활 및 사회복귀 지원",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)아가페",
    purpose: "소망교도소 설립. 운영",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국이민재단",
    purpose: "출입국․외국인정책본부 및 소속기관의 행정지원전․현직 출입국․외국인정책본부 및 소속기관 직원의 복리증진재한외국인 및 귀화자와 그 자녀의 한국사회 적응지원",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)동포교육지원단",
    purpose: "국내에서 취업하고자 하는 재외동포에 대해 취업 전 관련 산업분야의 기능을 습득할 수 있도록 지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한성화교협회",
    purpose: "국민과 화교 상호간 민간교류를 통해 국내 체류중인 화교들의 고충이나 문제 등 해결",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "고려인마을",
    purpose: "고려인의  사회정착지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)IOM이민정책연구원",
    purpose: "국제이주에 관한 연구와 교육활성화를 통해 국가간 인적 자원의 이동촉진과 국제사회의 경제 및 문화발전에 기여",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국이민학회",
    purpose: "이민자 사회통합연구",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국이민법학회",
    purpose: "학술조사와 연구를 통한 이민법학의 발전과 이민법제 및 정책에 기여",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국이민정책학회",
    purpose: "이민 및 사회통합 정책과 행정, 외교, 법제도에 관한 학술 및 연구 활동을 수행함으로써 이민·사회통합 관련 법제 및 정책 구축에 기여",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "함께하는 다문화 네트워크",
    purpose: "결혼이민자 정착지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국다문화학회",
    purpose: "다문화관련 학술연구",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재한외국인사회통합지원센터",
    purpose: "재한외국인 정착지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국이주동포정책개발연구원",
    purpose: "이주동포지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "이주민사회통합지원센터",
    purpose: "재한외국인고충상담",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "건강사회운동본부",
    purpose: "재한외국인의 건강 등 증진에 기여",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "Dream C.T. 다문화공동체",
    purpose: "재한외국인 지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "코리아에이드",
    purpose: "외국인 재난피해자 등 지원",
    law: "-",
    type: "재단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재한외국인지원협회",
    purpose: "재한외국인 사회적응 지원",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "너머",
    purpose: "국내거주 고려인 동포의 안정적인 국내사회적응 지원 사업수행 및 정책제안을 통해 이민자사회통합에 기여",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "김해이주민의 집",
    purpose: "이주노동자, 이민자, 난민 및 다문화가정의 권익 옹호",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국이민사회전문가협회",
    purpose: "다문화사회전문가의 역량을 강화하고 내외국인 상호문화 이해교육 및 상호교류 활성화를 통해 사회통합에 기여",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)피난처",
    purpose: "국내외 난민과 북한난민의 구호 등",
    law: "-",
    type: "사단",
    remit: "법무부",
  ),
];
