import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> mojRawData = [
  ExcelRowData(
    permitDate: "1956-07-31",
    name: "한국법학원",
    purpose: "법학 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1957-11-16",
    name: "국제인권옹호한국연맹",
    purpose: "인권 보장",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1966-08-18",
    name: "한국가정법률상담소",
    purpose: "법률구조",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1968-06-26",
    name: "부산가정법률상담소",
    purpose: "법률구조",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1979-04-11",
    name: "교정공제회",
    purpose: "교정공무원 복지후생 및 원호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1980-03-24",
    name: "(사)세진회",
    purpose: "수용자 선교 및 봉사",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1983-06-08",
    name: "법무보호복지재단",
    purpose: "범죄예방 사업 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1985-06-11",
    name: "한국교화복지재단",
    purpose: "갱생보호사업",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1989-04-22",
    name: "(사)한국교정복지회",
    purpose: "수용자 교화 및 사회복귀",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1989-12-28",
    name: "(사)한국불교교화복지선도회",
    purpose: "수용자 교화",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1994-12-08",
    name: "한국범죄방지재단",
    purpose: "범죄예방 및 범죄인 교화 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1995-03-01",
    name: "북부청소년문화재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1995-07-19",
    name: "재단법인청지선도장학재댠",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1995-09-06",
    name: "효원선도재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1996-04-22",
    name: "세계교화갱보협회",
    purpose: "갱생보호사업",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1997-03-26",
    name: "담안선교회 자활원",
    purpose: "갱생보호사업",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1997-11-27",
    name: "빠스카교화복지회",
    purpose: "갱생보호사업",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1998-06-05",
    name: "남부소년선도재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1998-08-26",
    name: "영월소년선도재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1998-08-31",
    name: "춘천사랑잇기청소년재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1998-12-04",
    name: "한국소년보호협회",
    purpose: "위기청소년 사회정착",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1999-01-20",
    name: "원주한마음청소년재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1999-02-11",
    name: "영동해맞이청소년선도재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1999-04-20",
    name: "푸른마음장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1999-10-20",
    name: "인천사랑잇기청소년재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1999-11-24",
    name: "경남선도장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "1999-12-07",
    name: "대한가정법률복지상담원",
    purpose: "법률구조",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2000-02-14",
    name: "한국법학교수회",
    purpose: "법학 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2000-04-27",
    name: "자녀안심하고 학교보내기운동 국민재단",
    purpose: "청소년 범죄예방, 장학사업",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2000-05-24",
    name: "로시컴법률구조재단",
    purpose: "법률구조",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2000-06-24",
    name: "(사)국제거래법학회",
    purpose: "국제법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2000-06-28",
    name: "포항청소년선도재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2000-12-09",
    name: "평안밀레니엄선도장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2001-03-23",
    name: "서부소년장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2001-03-23",
    name: "전남동부지역선도장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2001-05-25",
    name: "목포지역한마음장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2001-06-08",
    name: "(사)새생명운동본부",
    purpose: "수용자 선교",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2001-06-11",
    name: "여주검찰범방장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2001-07-26",
    name: "한국인권재단",
    purpose: "인권문화 확산",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2001-08-07",
    name: "(재)아가페",
    purpose: "민영교도소의 설립•운영",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2001-09-06",
    name: "(사)한국교정선교회",
    purpose: "수용자 선교 및 교화",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2002-01-10",
    name: "제주선도장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2002-07-27",
    name: "재단법인푸른쉼터장학회",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2002-12-31",
    name: "서울대학교법학발전재단",
    purpose: "법학 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2003-03-04",
    name: "월석부산선도장학회",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2003-03-19",
    name: "대한변협법률구조재단",
    purpose: "법률구조",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2003-05-12",
    name: "한빛장학회",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2003-05-15",
    name: "(사) 천주교 사회교정사목회",
    purpose: "수용자 선교 및 교정",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2003-08-18",
    name: "통영한마음장학회",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2003-08-18",
    name: "광주한마음장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2003-11-06",
    name: "한마음장학회",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2003-11-13",
    name: "한사랑선도장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2004-03-11",
    name: "영산법률문화재단",
    purpose: "법률문화 창달",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2004-03-29",
    name: "푸른날개장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2004-05-04",
    name: "은행나무청소년선도장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2004-06-23",
    name: "한국이민재단(구 출입국관리협회)",
    purpose: "재한외국인 및 귀화자 지원 등",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2004-09-08",
    name: "한국민사법학회",
    purpose: "법학 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2004-12-08",
    name: "양지뜸",
    purpose: "갱생보호사업",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2005-01-25",
    name: "대경청소년선도장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2005-01-28",
    name: "(사)한국범죄피해자지원중앙센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2005-01-31",
    name: "(사)부산범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2005-10-12",
    name: "전주지역한마음장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2005-11-07",
    name: "임수복장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2005-11-08",
    name: "(사)피난처",
    purpose: "난민 구호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-03-22",
    name: "청소년희망재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-03-28",
    name: "대한의료법학회",
    purpose: "의료법학 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-04-26",
    name: "(사)진주범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-04-28",
    name: "(사)광주전남범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-05-23",
    name: "(재)한중일 민상법통일연구소",
    purpose: "동북아 무역 법률 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-05-24",
    name: "(사)밀양창녕범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-06-08",
    name: "(사)인천범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-06-12",
    name: "(사)부산동부범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-06-21",
    name: "(사)경남범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-06-21",
    name: "(사)통영․거제․고성범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-06-21",
    name: "(사)전주범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-06-27",
    name: "(사)울산범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-07-04",
    name: "(사)천안․아산범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-07-04",
    name: "(사)정읍범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-07-12",
    name: "한국 보험법학회",
    purpose: "보험 관련 법규범 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-08-14",
    name: "(사)대전범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-08-25",
    name: "(사)수원범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-08-30",
    name: "(사)청주범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-09-07",
    name: "(사)고양파주지역범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-09-11",
    name: "(사)안산광명시흥지역범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-09-12",
    name: "(사)부천김포범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-09-12",
    name: "(사)목포지역범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-09-12",
    name: "(사)장흥․강진범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-09-12",
    name: "(사)전남동부범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-09-14",
    name: "(사)군산․익산범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-09-15",
    name: "(사)성남. 광주. 하남범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-09-15",
    name: "(사)논산범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-09-19",
    name: "(사)경기북부범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-09-22",
    name: "(사)공주․청양범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-09-25",
    name: "(사)평택안성범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-10-10",
    name: "(사)충주․음성범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)서울동부범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)서울남부범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)서울북부범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)서울서부범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)춘천범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)강릉범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)원주․횡성범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)속초범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)영월범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)대구․경북범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)경북북부범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)경주범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)포항범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)김천․구미범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)상주․문경․예천범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)의성군위청송범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)영덕․울진․영양범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-11-17",
    name: "(사)제주범죄피해자 지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2006-12-03",
    name: "(사)대구서부범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-02-08",
    name: "한국부동산법학회",
    purpose: "부동산관계법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-02-22",
    name: "(사)남원․순창․장수범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-03-06",
    name: "한국비교사법학회",
    purpose: "사법 비교 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-04-02",
    name: "(사)제천․단양범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-04-10",
    name: "(사)여주이천양평지역범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-04-18",
    name: "뷰티플라이프",
    purpose: "갱생보호사업",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-04-18",
    name: "열린낙원",
    purpose: "갱생보호사업",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-04-26",
    name: "(사)영동옥천범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-05-16",
    name: "(사)한국이민학회",
    purpose: "이민 관련 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-06-18",
    name: "함께하는 다문화 네트워크",
    purpose: "다문화가정 정착 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-07-27",
    name: "(사)거창․합천․함양범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-08-17",
    name: "(사)서산지역범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-09-18",
    name: "(사)홍성지역범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-10-11",
    name: "거창지역다림장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-10-25",
    name: "푸른장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-10-31",
    name: "해송법률문화재단",
    purpose: "법학 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2007-12-11",
    name: "행복세상",
    purpose: "법치주의 문화 확산",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2008-01-03",
    name: "한국 상사판례학회",
    purpose: "상사법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2008-05-02",
    name: "굿소사이어티",
    purpose: "법치주의 실현",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2008-07-01",
    name: "한국사법교육원",
    purpose: "법교육",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2008-09-12",
    name: "(사)전국범죄피해자지원연합회",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2008-10-29",
    name: "한국재산법학회",
    purpose: "재산법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2008-11-21",
    name: "한국사회통합학회",
    purpose: "다문화 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2009-01-05",
    name: "한국 도산 법학회",
    purpose: "채무자회생·파산법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2009-04-22",
    name: "(사)안양범죄피해자 지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2009-05-06",
    name: "도산법 연구회",
    purpose: "도산법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2009-06-11",
    name: "동천",
    purpose: "법률구조",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2009-07-16",
    name: "한북장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2009-07-17",
    name: "충주지역예성드림장학재단",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2009-08-03",
    name: "재한외국인사회통합 지원센터",
    purpose: "재한외국인 정착 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2009-08-26",
    name: "재단법인 이민정책연구원",
    purpose: "이민정책 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2009-09-12",
    name: "(사)해남․완도․진도범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2009-12-01",
    name: "행복공장",
    purpose: "청소년 등 대상 행복 프로그램",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2009-12-22",
    name: "재단법인영동옥천청포도장학회",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2010-01-15",
    name: "한국다문화이민통합협회",
    purpose: "이주동포 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2010-03-17",
    name: "재단법인 푸른장산장학회",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2010-04-16",
    name: "재단법인지리산장학회",
    purpose: "청소년 보호 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2010-06-15",
    name: "이주민사회통합지원센터",
    purpose: "재한외국인 정착 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2010-07-16",
    name: "사단법인 인하우스카운슬포럼",
    purpose: "기업 관련 법률 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2010-11-05",
    name: "사단법인 한국법철학회",
    purpose: "법철학 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2010-11-22",
    name: "(사)한중법학회",
    purpose: "중국법제 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2010-11-23",
    name: "한국포렌식학회",
    purpose: "포렌식 분야 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2010-11-26",
    name: "재단법인 대한변협 인권재단",
    purpose: "국제 인권 교육",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2010-12-13",
    name: "(사)한국피해자지원협회",
    purpose: "피해자 및 사회적 약자 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2011-04-13",
    name: "건강사회운동본부",
    purpose: "재한외국인 정착 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2011-04-14",
    name: "사단법인 한국보호관찰학회",
    purpose: "보호관찰 정책 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2011-05-13",
    name: "사단법인 중앙법학연구소",
    purpose: "법학 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2011-06-09",
    name: "사단법인 아시아교정포럼",
    purpose: "교정보호학 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2011-07-01",
    name: "Dream C.T. 다문화공동체",
    purpose: "재한외국인 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2011-07-14",
    name: "사단법인 한국회복적사법정의센터",
    purpose: "회복적사법정의 실천 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2011-07-14",
    name: "사단법인 인권정책연구소",
    purpose: "인권 관련 연구 및 교육",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2011-07-18",
    name: "(사)대한범죄학회",
    purpose: "범죄 관련 학술연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2011-08-09",
    name: "재단법인 뉴라이프재단",
    purpose: "출소자 중심 사회적 기업 운영",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2011-09-02",
    name: "한국성년후견지원본부",
    purpose: "장애인·노인 권익신장",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2011-09-21",
    name: "한국준법통제원",
    purpose: "준법통제 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2011-10-18",
    name: "(사)마산함안의령범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2011-12-16",
    name: "사단법인 한국가족법학회",
    purpose: "가족법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2012-01-04",
    name: "사단법인 한국피해자학회",
    purpose: "범죄피해 및 피해자 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2012-02-06",
    name: "한국사내변호사회",
    purpose: "기업법무 관련 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2012-09-28",
    name: "사단법인 한국여성변호사회",
    purpose: "여성 권익 향상",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2012-10-09",
    name: "(사)범죄피해자지원 부산스마일센터",
    purpose: "강력범죄 피해자 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2013-01-10",
    name: "(사)교정자원봉사지원센터",
    purpose: "교정복지 확대",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2013-08-01",
    name: "사단법인 한성화교협회",
    purpose: "화교 출입국 관련 고충 해결",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2013-09-10",
    name: "사단법인 한국교회법학회",
    purpose: "교회법 관련 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2013-09-17",
    name: "(사)대한민국재향교정동우회",
    purpose: "퇴직교정공무원 네트워크",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2013-10-29",
    name: "사단법인 온율",
    purpose: "법학 연구 및 입법 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2013-11-15",
    name: "사단법인 선",
    purpose: "사회적 취약계층 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2013-11-28",
    name: "사단법인 한국채무자회생법학회",
    purpose: "도산법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2013-12-27",
    name: "(사) 새희망교화센터",
    purpose: "교정교화 기법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2014-03-24",
    name: "사단법인 한국법무보호복지학회",
    purpose: "법무보호복지사업 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2014-04-04",
    name: "코리아에이드",
    purpose: "외국인 재난피해자 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2014-04-18",
    name: "고려인마을",
    purpose: "고려인 사회정착지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2014-05-30",
    name: "천고법치문화재단",
    purpose: "법률문화 창달",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2014-06-13",
    name: "제로캠프",
    purpose: "청소년 범죄예방, 교육 등",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2014-07-14",
    name: "사단법인 생활법률문화연구원",
    purpose: "생활법률 연구 및 교육",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2014-08-26",
    name: "사단법인 두루",
    purpose: "공익 법률상담 및 공익법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2014-08-26",
    name: "사단법인 나눔과 이음",
    purpose: "사회적 취약계층 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2014-09-19",
    name: "재단법인 법사랑군산.익산지역장학회",
    purpose: "불우, 모범 청소년 장학사업",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2014-10-07",
    name: "재단법인 늘푸른장학회",
    purpose: "청소년 장학사업",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2014-11-10",
    name: "사단법인 한국기업회생협회",
    purpose: "기업회생 법률 자문 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2014-11-24",
    name: "재단법인 화우공익재단",
    purpose: "법률구조",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2014-12-11",
    name: "재한외국인지원협회",
    purpose: "재한외국인 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2015-02-27",
    name: "사단법인 한국지적재산권변호사협회",
    purpose: "지적재산권 전문 변호사 양성",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2015-04-14",
    name: "사단법인 한국법이론실무학회",
    purpose: "법률이론과 실무 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2015-04-24",
    name: "사단법인 한국성년후견학회",
    purpose: "장애인, 후견제도 관련 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2015-07-03",
    name: "(재) 같이함께",
    purpose: "수용자, 출소자 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2015-08-31",
    name: "사단법인 한국환태평양변호사회",
    purpose: "아태지역 법제 발전",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2015-10-16",
    name: "사회적 협동조합 제주로",
    purpose: "법률 상담 제공",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2015-12-21",
    name: "사단법인 한국이민법학회",
    purpose: "이민법학 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2016-01-11",
    name: "사단법인 국제사법학회",
    purpose: "국제사법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2016-02-04",
    name: "사단법인 전국법과대학교수회",
    purpose: "법과대학 교류, 법학교육 발전",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2016-05-16",
    name: "사단법인 한국안보형사법학회",
    purpose: "안보형사법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2016-06-15",
    name: "사단법인 대한상사중재원",
    purpose: "상사분쟁 조정",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2016-06-17",
    name: "사단법인 한국과학수사학회",
    purpose: "범죄수사 및 과학수사 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2016-06-20",
    name: "재단법인 홍진기 법률연구재단",
    purpose: "법학 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2016-07-22",
    name: "사단법인 한국이민정책학회",
    purpose: "이민정책 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2016-12-19",
    name: "사단법인 한국디지털포렌식전문가협회",
    purpose: "디지털포렌식 기술 발전",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2017-01-31",
    name: "사단법인 크레도",
    purpose: "법률 및 제도 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2017-02-01",
    name: "사단법인 장애인법연구회",
    purpose: "장애인법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2017-02-10",
    name: "너머",
    purpose: "고려인동포 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2017-02-14",
    name: "사단법인 한ㆍ불민사법학회",
    purpose: "한국 프랑스 민사법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2017-03-28",
    name: "재단법인 나은",
    purpose: "법률 분야 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2017-06-05",
    name: "사단법인 국제사이버법연구회",
    purpose: "사이버공간 관련 법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2017-06-05",
    name: "사단법인 한불법학회",
    purpose: "프랑스 법제도 및 법문화 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2017-06-05",
    name: "사단법인 한국 베트남ㆍ인도네시아 법ㆍ문화연구회",
    purpose: "베트남·인도네시아 법 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2017-06-08",
    name: "사단법인 한국후견협회",
    purpose: "의사결정능력 장애 성인 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2017-06-16",
    name: "사단법인 한국후견사회복지협회",
    purpose: "장애인, 노인 등 복지",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2017-09-01",
    name: "(사)부산서부범죄피해자센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2017-09-06",
    name: "사단법인 정",
    purpose: "사회적 취약계층 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2017-12-05",
    name: "사단법인 대한중재인협회",
    purpose: "중재제도 확대보급",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2018-01-09",
    name: "한국이주민의 집",
    purpose: "이민자 등 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2018-01-09",
    name: "사단법인 함께하는 빛",
    purpose: "공익소송 및 공익 입법 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2018-05-23",
    name: "사단법인 한국인권학회",
    purpose: "인권 관련 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2018-05-24",
    name: "한국신탁학회",
    purpose: "신탁 관련 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2018-06-18",
    name: "사단법인 비온뒤무지개재단",
    purpose: "보편적 인권의 가치 실현",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2018-06-19",
    name: "재단법인 법사랑대전지역장학회",
    purpose: "모범청소년 장학사업",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2018-09-11",
    name: "사단법인 한국이민사회전문가협회",
    purpose: "다문화사회 관련 교육 등",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2018-09-28",
    name: "사단법인 한국집합건물진흥원",
    purpose: "집합건물 관련 학술사업 등",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2018-12-06",
    name: "한국중재학회",
    purpose: "중재제도 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2018-12-11",
    name: "모두를 위한 이주인권문화센터",
    purpose: "재한외국인 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2019-01-04",
    name: "한국집합건물관리사협회",
    purpose: "집합건물 관리인력 양성",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2019-05-21",
    name: "사단법인 올",
    purpose: "인권 관련 법학연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2019-10-01",
    name: "사단법인 한국 집합건물법학회",
    purpose: "집합건물 관련 법리 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2019-11-14",
    name: "사단법인 한국공공안전연구원",
    purpose: "범죄예방 관련 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2019-11-15",
    name: "사단법인 정책법령연구소",
    purpose: "상사, 인권 등 관련 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2019-12-03",
    name: "사단법인 코사코리아",
    purpose: "갱생보호대상자 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2020-01-29",
    name: "사단법인 착한법 만드는 사람들",
    purpose: "법치주의 실현",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2020-02-21",
    name: "사단법인 후견",
    purpose: "후견제도 관련 사업",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2020-03-25",
    name: "사단법인 옳음",
    purpose: "공익입법 및 법집행 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2020-04-23",
    name: "사단법인 굿라이프",
    purpose: "갱생보호사업",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2020-10-16",
    name: "세이브월드",
    purpose: "소년원생 사회복귀 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2021-02-03",
    name: "사단법인 한국이민행정학회",
    purpose: "이민행정 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2021-02-19",
    name: "사단법인 한반도 이주민센터",
    purpose: "재한외국인 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2021-06-08",
    name: "사단법인 지평법정책연구소",
    purpose: "법학 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2021-06-10",
    name: "사단법인 홀스케치",
    purpose: "보호관찰대상자 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2022-01-16",
    name: "평창법교실 사회적협동조합",
    purpose: "법률상담 및 법문화제도 교육",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2022-02-24",
    name: "사단법인 우리모두친구",
    purpose: "이주민 정착 및 사회통합 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2022-03-24",
    name: "사단법인 두리",
    purpose: "후견제도 정착 연구 및 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2022-05-02",
    name: "(사)경기동부범죄피해자지원센터",
    purpose: "범죄피해자 지원 및 보호",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2022-11-07",
    name: "한국중독범죄학회",
    purpose: "중독범죄 관련 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2022-11-07",
    name: "사단법인 한국안전사회연구원",
    purpose: "범죄예방 및 범죄대책 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2022-12-23",
    name: "사단법인 디지털금융법포럼",
    purpose: "디지털금융산업 관련 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2023-01-16",
    name: "사단법인 대한노인법학회",
    purpose: "노인 대상 법률서비스 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2023-03-24",
    name: "재단법인 변호사공제재단",
    purpose: "법률서비스 접근성 향상",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2023-05-01",
    name: "사단법인 한국산업법제연구원",
    purpose: "산업법제 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2023-06-05",
    name: "사단법인 국제중재실무회",
    purpose: "국제중재법 및 중재실무 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2023-08-02",
    name: "사단법인 아이브이알 2024 조직위원회",
    purpose: "법철학 및 사회철학 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2023-08-21",
    name: "사단법인 □한국공공복지신탁연구원",
    purpose: "공공복지신탁 연구 용역 등",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2023-10-31",
    name: "보다피플",
    purpose: "마약사범 치료 및 상담",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2024-07-03",
    name: "세계중독예방협회",
    purpose: "중독성 물질 오남용 방지 사업",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2024-07-22",
    name: "사단법인 보은",
    purpose: "사회적 취약계층 법률지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2024-11-20",
    name: "사단법인 수원사회통합협의회",
    purpose: "국내 체류 외국인 지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2025-01-07",
    name: "한국범죄학회",
    purpose: "범죄예방 정책 연구",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2025-01-16",
    name: "참신한 네이버스 사회적협동조합",
    purpose: "이주민 정착지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2025-02-19",
    name: "사단법인 인연법",
    purpose: "소외계층 법률지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
  ExcelRowData(
    permitDate: "2024-08-06",
    name: "사단법인 희망과동행",
    purpose: "사회적 취약계층 법률지원",
    law: "-",
    type: "-",
    remit: "법무부",
  ),
];
