import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> mohwRawData = [
  ExcelRowData(
    permitDate: "1952.",
    name: "한국아동복지협회",
    purpose: "○ 전국아동복지시설의 발전과 합리적 운영관리를 위한 제반사항을 지원하고 법인 또는 시설간의 상호협조",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1948.",
    name: "한국한센복지협회",
    purpose: "○ 한센병에 관한 진료조사 연구 및 교육홍보사업을 수행하고 국제교류를 통한 정보교환 등으로 한센병을 퇴치, 예방",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1958.",
    name: "대한한약협회",
    purpose: "○ 한약 및 한약학의 진흥과 회원간의 친목을  도모하며 한약업자의 권익신장 및 국민보건향상에 기여함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1959.",
    name: "대한병원협회",
    purpose: "○ 병원제도와 운영에 관한 연구 및 개선, 의사 및 병원종사자등에 대한 수련교육의 향상",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1964.",
    name: "대한접골사협회",
    purpose: "○ 국민보건 및 접골시술의 향상을 도모하며, 의료법 및 관계법령에 의거한 의료유사업자로서의 법적 권익을 증진하며 학술 연구발전과 회원간의 친목을 도모함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1964.",
    name: "대한의료영상진단협회",
    purpose: "○ 각종 의료영상진단에 따른 정확한 판독사업과 검진 후 평가 분석된 위해 요인에 대한 지도, 계몽으로 방사선에 의한 피해를 사전에 방지케 함으로써 국민건강 보호증진에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1966.",
    name: "대한암협회",
    purpose: "○ 암의 예방과 치료 등에 관한 사업을 함으로써 국민보건과 복지향상에 기여하고 국제적인 암퇴치운동에 협력",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1967.",
    name: "한국원폭피해자협회",
    purpose: "○ 원폭피해자와 그 후세들의 건강관리, 복지향상 및 권익옹호",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1968.",
    name: "요산요수회",
    purpose: "○ 가정과 사회 윤리도덕관 정립○ 경로효친사상 재교육을 위한 계몽활동 전개",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1968.",
    name: "한국지적발달장애인복지협회",
    purpose: "○ 지적장애인의 권익옹호, 복지증진",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1968.",
    name: "자행회",
    purpose: "○ 정신지체인 교육, 복지 증진",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1970.",
    name: "한국장애인재활협회",
    purpose: "○ 장애발생예방, 권익보호, 재활사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1971.",
    name: "한국장례협회",
    purpose: "○건전한 장례문화 구현을 통한 장례업 발전 도모 - 회원업체의 업권 및 회원의 권익 도모 - 장례 관련 제도 개선 및 회원의 자질 향상 도모 - 국민과 종사자의 공공복리 및 보건 증진 - 장례업 발전을 통해 국민과 국가에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1972.",
    name: "한국여자의사회",
    purpose: "○ 회원 상호간의 친목과 국제친선 및 학문교류를 통하여 여자의사의 자질을 향상하고 권익을 옹호하며 국민보건향상에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1973",
    name: "한국노인복지중앙회",
    purpose: "○노인복지시설의 균형발전 및 질 향상○ 시설 종사자 자질향상",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1974.",
    name: "한양로타리클럽",
    purpose: "○ 사회봉사를 위한 정보 모집·교환 - 재난발생시 구조사업  - 사회봉사에 기여할 수 있는 기술자의 양성 및 훈련지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1974.",
    name: "한국뇌전증협회",
    purpose: "○ 박애정신에 그 기반을 두고 뇌전증환자의 치료 및 재활, 사회복지, 교육 등의 활동과 회원 상호간의 유대강화 및 교류를 통하여 뇌전증환자의 삶의 질을 향상시키고 권익신장에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1974.",
    name: "대한간호조무사협회",
    purpose: "○ 회원의 자질향상을 위한 기술과 지식습득 도모",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1975.",
    name: "대한노인회",
    purpose: "○ 노인지위향상, 노인복지증진 기여, 회원 친목도모",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1975.",
    name: "한국의지보조기협회",
    purpose: "○ 보장구 제작기술 향상",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1975.",
    name: "대한보건협회",
    purpose: "○ 국민보건에 관한 사항 조사, 연구, 홍보○ 보건의 국제적 동향 지식 및 정보수집, 분석, 평가○ 보건정책수립 및 국민보건 향상",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1976.",
    name: "제주복지회",
    purpose: "○ 사회복지사업의 운영 향상을 위한 지원 - 사회복지에 관한 제문제의 조사‧연구와 발표 - 제주도내의 복지시설의 육성을 위한 계도 및 지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1977.",
    name: "I.C.A 지역사회복지원",
    purpose: "○ 지역사회복지 - 지역사회 종합복지사업  - 주민생활관 설치 및 유지관리  - 주민의료복지 및 교육사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1977.",
    name: "한국경로복지회",
    purpose: "○ 노인건강증진 및 노인교육○ 경로효친사상 앙양",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1978.",
    name: "한국만성질환관리 협회",
    purpose: "○ 각종 만성질환 예방대책 강구와 진료기술개발보급 및 대국민 지도계몽",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1978.",
    name: "한국뇌성마비복지회",
    purpose: "○ 뇌성마비인의 발생예방, 재활복지사업 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1978.",
    name: "한국농촌의학회",
    purpose: "○ 농ㆍ어촌지역 주민의 보건의료 위생에 관한 지도 계몽으로 생활개선 도모",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1978.",
    name: "복지마을진흥회",
    purpose: "○ 새마을정신에 입각한 복지사회를 구현함으로써 인류공영과 조국에 기여하고     범국민적 계도활동으로 인정 많은 복지마을 진흥에 진력",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1979.",
    name: "해외희생동포추념 사업회",
    purpose: "○ 제2차대전시중 해외희생동포 위령사업 - 희생자 진상조사와 유족의 실태조사 - 유해발굴‧수집‧봉안 및 추념행사 - 위령탑 및 기념지 건립",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1980.",
    name: "한국농아인협회",
    purpose: "○ 농아인의 사회계몽, 자질향상, 능력개발, 생활안정",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1981.",
    name: "한국시각장애인연합회",
    purpose: "○ 시각장애인의 복지증진 및 권익옹호",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1981.",
    name: "한국신체장애인복지회",
    purpose: "○ 장애인복지증진",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1982.",
    name: "한국구라봉사회",
    purpose: "○ 한센병 구강보건향상을 위하여 한센병 환자 진료 및 구강보건발전과 한센병 환자를 위한 봉사활동",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1982.",
    name: "국제사회복지회",
    purpose: "○사회복지발전과 실현을 위해 각종 서비스 제공 -보호대상자의 자활ㆍ자립능력 배양 - 사회복지관 설치‧운영",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1983.",
    name: "한국장애인복지시설협회",
    purpose: "○ 장애인 복지시설의 육성.발전 사회참여 유도",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1983.",
    name: "한국노숙인복지시설협회",
    purpose: "○ 노숙인 복지시설 상호간의 조직적인 활동과 협조로 노숙인의 인간다운 생활을 할 권리 보호, 재활 및 자립을 위한 기반조성, 노숙인 복지향상에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1983.",
    name: "보사동우회",
    purpose: "○ 회원 상호간의 친목도모○ 보건복지행정에 관한 정책 건의○ 복지행정 발전에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1984.",
    name: "한국치과교정연구회",
    purpose: "○ 특수장애자의 치과무료진료 및 교정사업, 치과교정학 연구 및 학술교류 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1984.",
    name: "대한여자치과의사회",
    purpose: "○ 치과의학 및 공중구강보건의 발전을 통하여 국민구강보건의 향상 도모",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1984.",
    name: "전국공원묘원협회",
    purpose: "○ 전국공원묘원의 향상‧발전과 묘지의 집단화‧공원화 사업 - 무료장례상담소설치‧운영 - 화장장 및 납골당 설치 권장사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1984.",
    name: "한국정신요양시설협회",
    purpose: "○ 정신요양시설 발전을 위한 운영관리개선○ 대국민 지도‧계몽으로 국민보건향상 및 복지사회구현",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1985.",
    name: "강원보건연구회",
    purpose: "○ 지역주민 건강증진○ 학생 및 보건요원 훈련",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1971.",
    name: "한국기독교의료선교협회",
    purpose: "○ 기독교 정신에 입각한 의료선교와 의료봉사 사업 실시",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1986.",
    name: "한국장애인부모회",
    purpose: "○ 장애인부모교육, 재활에 필요한 정보교환",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1985.",
    name: "대한병원행정관리자협회",
    purpose: "○ 의료행정의 연구개발 및 의료행정분야 종사자간의 유대강화",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1988.",
    name: "대한한방병원협회",
    purpose: "○ 한방병원의 건전한 발전과 운영제도 개선 연구 및 한방의료요원의 교육을 통하여 한방병원 의료의 질적 향상을 도모함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1989.",
    name: "한국사회정책연구원",
    purpose: "○ 복지정책연구 - 사회정책에 대한 자료수집 및 조사‧분석 - 연구발표회 및 세미나 - 국내‧외 기관과의 교류",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1989.",
    name: "한국한센총연합회",
    purpose: "○ 한센병력자들에 대한 건강증진 및 자립기반 확충을 위한 정착농원, 공공사업 운영으로 공익사업을 수행하고 축산기술 등에 대한 교육홍보사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1989.",
    name: "한국지체장애인협회",
    purpose: "○ 장애인상담, 계몽, 재활사업, 자립심 고취 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1990.",
    name: "정해복지",
    purpose: "○ 사회복지연구  - 각종 복지시설에 대한 연구ㆍ조사 사업  -복지문제에 대한 정책개발 사업  -복지부문에 대한 각종의 계몽 및 출판사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1990.",
    name: "한국국제기아대책 기구",
    purpose: "○ 국내‧외구호 및 선교사업 -기아자에 대한 음식물의 공급 -빈곤‧질병문제 등에 대한 정책개발 및 조사‧연구 -구호대상지역의 기술개발교육 및 자원봉사자의 훈련 -구호대상지역의 자립지원과 의료봉사‧선교활동",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1991.",
    name: "대한진단검사정도관리협회",
    purpose: "○ 임상병리 검사기구, 장비시약 및 검사기술 등에 관한 정도 관리와 임상병리검사의 표준화를 통한 국민보건 향상 도모",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1992.",
    name: "태평양전쟁희생자유족회",
    purpose: "○제2차대전시중 강제동원되어 희생된 원혼 위로 및 유족 복지 지원 -유족 실태조사와 상호협조‧교류 -유해발굴‧봉안추진 및 위령제 봉행 -유족자녀,손자녀장학사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1992.",
    name: "한국사회복지정책연구원",
    purpose: "○ 사회복지 정책개발  -사회복지에 대한 정책연구사업 -장애인복지시설등 사회복지시설 지원사업 -불우아동 및 청소년 장학사업 -사회복지 전문가 훈련 및 학술세미나 개최",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1993.",
    name: "안구기증운동협회",
    purpose: "○ 각종 안구기증운동과 시각장애인의 시력회복 및 국민 안 보건 향상에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1993.",
    name: "대륙복지회",
    purpose: "○ 의료적으로 소외된 해외거주 우리민족과 그 지역에 주민들에게 질병예방과 진료를 통하여 건강한 삶을 누리게 함으로서 국제간의 우호를 증진하고 국위를 선양하며 나아가 인류평화와 복지사회 실현에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1993.",
    name: "한국신장장애인협회",
    purpose: "○ 신장장애 예방 및 인식 개선",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1994.",
    name: "한국조혈모세포은행협회",
    purpose: "○ 조혈모세포이식을 요하는 환자와 비혈연 조혈모세포공여자 사이에 조혈모세포이식이 원활하게 이루어질 수 있도록 홍보, 등록 및 조정역할 수행",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1994.",
    name: "한국의료복지건축학회",
    purpose: "○ 의료복지시설에 관계가 있는 모든 분야의 전문인 또는 단체들이 모여 서로 협력하고 힘을 모아 우리나라 의료복지시설의 수준향상에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1994.",
    name: "한국금연운동협의회",
    purpose: "체계적인 금연운동을 전개하여 흡연으로 인한 건강피해를 최소화하여 국민건강증진에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1994.",
    name: "장애우권익문제연구소",
    purpose: "○ 장애인 문제 조사. 연구사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1994.",
    name: "한국노인의전화",
    purpose: "○노인복지증진을 위한 유용한 정보 제공○노인들의 성공적인 삶을 위한 양질의 서비스 제공",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1995.",
    name: "한국치매협회",
    purpose: "○ 치매연구, 예방‧치료관리○ 국가치매관련사업 지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1995.",
    name: "한국영양학회",
    purpose: "○영양학의 발전도모○식생활 개선으로 인한 국민건강증진",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1995.",
    name: "아드라코리아",
    purpose: "○ 국내‧외 난민구호사업 - 이재민등 난민구호사업 -재난대비를 위한 계몽사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1995.",
    name: "한국당뇨협회",
    purpose: "○ 당뇨병예방과 치료 및 관리에 대한 정보수집, 교육, 홍보, 조사, 연구진료사업을 통해 국민의 건강과 복지증진에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1995.",
    name: "한국노인샬롬복지원",
    purpose: "○장년 및 노년을 위한 복지 및 문화사업 수행",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1995.",
    name: "용해노인복지회",
    purpose: "○경로효친사상 앙양과 노인문화 창당",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1996.",
    name: "한국의료기관세탁물처리협회",
    purpose: "○ 의료기관에서 발생되는 세탁물을 위생적으로 수거 및 처리함으로써 국민 보건위생에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1995.",
    name: "한국의료법학연구소",
    purpose: "○ 의료 관련 법규 연구를 통하여 의료분쟁 예방",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1995.",
    name: "한국전립선 배뇨관리협회",
    purpose: "○ 인구노령화를 맞아 전립선비대와 암에 대한 예방대책을 강구하고 대국민지도계몽을 실시하므로 국민건강증진과 복지사회구현에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1995.",
    name: "한국재가노인복지협회",
    purpose: "○ 재가노인복지사업 및 노인장기요양사업 개발ㆍ보급○ 현장중심 조사연구, 교육 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1995.",
    name: "대한노인복지후원회",
    purpose: "○ 노인복지후생사업○ 청소년, 미아 후원 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1995.",
    name: "한길봉사회",
    purpose: "○ 무의탁노인 무료급식○ 재가노인복지사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1995.",
    name: "생명나눔 실천본부",
    purpose: "○ 불교의 자비사상으로 생명나눔을 실천함으로써 맑고 밝은 복지사회 구현",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1996.",
    name: "자원봉사애원",
    purpose: "○ 복지대상자에 대한 복지향상 -사회취약계층에 대한 지원사업 -사회봉사 및 자원봉사 활동",
    law: "②공익법인법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1996.",
    name: "한국정신사회재활협회",
    purpose: "○ 정신사회재활을 통한 만성정신장애인의 삶의 질 향상과 사회복지 도모",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1996.",
    name: "한국목회지원회",
    purpose: "○ 빈민지역의 재가복지활동, 무료치과진료소 운영 - 문제지역의 유아교육, 공부방, 야학, 청소년 상담 및 경로교실 운영",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1996.",
    name: "전국노인복지단체연합회",
    purpose: "○ 노인복지 조사연구○노인복지사업 협력‧지원○ 노인복지 국민참여촉진",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1996.",
    name: "사랑채",
    purpose: "○결식노인 무료급식 및 재가노인복지",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1996.",
    name: "대한위생사협회",
    purpose: "○ 회원 상호간의 친목단결○ 국민보건 향상 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1996.",
    name: "한국제이티에스",
    purpose: "○ 국내‧외 소외계층 지원 - 해외구호사업 - 결손가정 지원사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1996.10.8.",
    name: "한국아동학대예방협회",
    purpose: "○ 아동학대예방교육 및 홍보○ 기타 아동의 권익보호에 관한 사항",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1996.",
    name: "한민족행복찾기국민운동본부",
    purpose: "○ 노인의 가치관 정립교육○ 결혼상담 일자리 알선 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1996.",
    name: "문화생활복지회",
    purpose: "○ 재가노인복지 및 무의탁노인 무료급식",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1996.",
    name: "세민얼굴기형돕기회",
    purpose: "○ 불우한 처지의 얼굴기형 환자의 교정을 지원하며 정상적인 사회생활을 영위할 수 있도록 지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1996.",
    name: "동산의료선교복지회",
    purpose: "○ 기독교 정신에 입각한 의료봉사와 복지",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1997.",
    name: "한국장루장애인협회",
    purpose: "○ 배변 및 배뇨기 계통의 인공항문 시술을 받은 자에게 정기적으로 전문화된 교육과 정보를 제공",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1997.",
    name: "한국효도회",
    purpose: "○ 경로효친사상 고취○ 노인복지증진",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1997.",
    name: "대한노인복지회",
    purpose: "○ 노년자원봉사 정책프로그램 연구개발○ 자원봉사의 새로운 문화창조",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1997.",
    name: "한국노인과학학술 단체연합회",
    purpose: "○ 국내외 연구기관간 학술교류 및 노인문제 학술세미나 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1997.",
    name: "이웃을돕는사람들",
    purpose: "○ 국내‧외 소외계층 지원 - 도시빈민층 및 소년ㆍ소녀가장 결연사업 - 질병‧기아 구제사업",
    law: "②공익법인법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1997.",
    name: "한국지역복지봉사회",
    purpose: "○ 지역복지에 대한 조사연구 및 저소득층 지원 - 지역복지모형 개발을 위한 조사‧연구사업 - 저소득층, 아동, 노인, 장애인 등의 지원사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1997.",
    name: "온누리약국복지회",
    purpose: "○ 사회복지증진에 기여 -재가노인의 요양 및 봉사사업과 재가장애인 복지사업 - 사회복지시설 운영 지원사업 - 의료서비스 제공, 장학사업 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1997.",
    name: "한국기독교사회발전협회",
    purpose: "○ 국ㆍ외의 사회복지사업 지원 - 복지사업 수행기관에 대한 후원사업 - 저개발국가의 사회발전 지원사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1997.",
    name: "한국복지회",
    purpose: "○ 무의탁 노인 무료급식○ 재가노인복지사업 및 노인취업 알선 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1997.",
    name: "상록회",
    purpose: "○ 노인복지 증진○ 건전한 사회풍토 조성○ 불우 청소년 후생사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1998.",
    name: "한국치과경영정보협의회",
    purpose: "○ 치과경영합리화를 위한 정보교류, 진료자세연구개발, 회원간의 친목도모 등 사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1998.",
    name: "한국간건강협회",
    purpose: "○ 생명사랑, 인간회복을 위한 간염퇴치운동 및 예방, 치료, 홍보 등 환자 권익보호",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1998.",
    name: "글로벌케어",
    purpose: "○ 국내외 질병, 기아, 전쟁, 천재 등으로 소외된 이웃에게 봉사",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1998.",
    name: "한국아동단체협의회",
    purpose: "○ 어린이와 청소년을 위한 정책 및 프로그램 개발, 국내․외 조사연구, 정보, 자료 교환과 유통, 계몽과 홍보 활동, 국제기구와의 협력사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1998.",
    name: "대한정신장애인가족협회",
    purpose: "○ 정신장애인의 삶의 질을 향상시키고 가족교육을 통하여 정신장애인의 올바른 인식과 치료기간 단축 및 회원상호간의 격려와 지지",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1998.",
    name: "사랑의친구들",
    purpose: "○ 가난하고 차별받고 소외된 계층의 지원사업 -어린이 교육증진 및 복지사업 -연구사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1998.",
    name: "대한한의약해외의료봉사단",
    purpose: "○ 한방의료구제사업 실시로 범인류애적 인도주의     실천과 한의학의 세계화와 국위선양에 기여함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1999.",
    name: "대한응급구조사협회",
    purpose: "○ 응급환자의 생명과 건강을 보호하는 응급구조사의 활동에 관한 사항을 도모함으로써 국민보건향상에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1999.",
    name: "한국장애인단체총연맹",
    purpose: "○ 전국장애인단체 상호유대 강화 및 협력",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1999.",
    name: "한국장묘문화개혁 범국민협의회",
    purpose: "○ 새로운 장사문화의 연구, 개발 및 보급과 화장장, 납골당 및 장사시설의 현대회 추진 - 장사관련 정보관리를 위한 데이터베이스 구축 - 장사관련 출판, 홍보사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1999.",
    name: "한국수양부모협회",
    purpose: "○아동의 건강한 양육을 통해 아동복지 및 권리향상에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1999.",
    name: "한국보건정보정책연구원",
    purpose: "○ 사회봉사활동, 보건의료정보, 정책에 대한 연구활동, 보건관련분야 종사자에 장학금 제공등을 통한 전문인력 양성을 지원함으로써 보건의료에 대한 국민교육과 건강증진의 시대적 요구에 부응",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1999.",
    name: "루푸스를이기는사람들협회",
    purpose: "○ 전신성홍반성낭창 예방계몽 및 국민의 건강증진과 사회복지 향상에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1999.",
    name: "한국장례문화연구원",
    purpose: "○ 장례문화창출을 위한 조사연구와 매장 및 화장제도에 대한 정책개발 지원 - 장례제도 개선을 위한 계몽운동 - 장례문화 의식개혁운동을 위한 학술지, 출판물의 발간.배포 - 정책사업에 부응하는 새로운 장례문화 창출을 위한 조사.연구",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1999.",
    name: "인도주의실천의사 협의회",
    purpose: "○ 국민건강증진을 위해 노력하고 보건의료영역의 권리를 누리지 못하는 계층을 위한 의료활동",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1999.",
    name: "한국운동지도협회",
    purpose: "○ 국민건강운동보급, 지도 ○ 운동관련 지도자 양성교육등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1999.",
    name: "국민연금공단동우회",
    purpose: "○ 국민연금제도에 관한 연구, 홍보사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2000.",
    name: "부스러기사랑나눔회",
    purpose: "○가난한 사람에 대한 자립.자활을 할수 있도록 지원하고 그들에 대한 사회문제의 조사와 그 결과 해결을 통하여 사회 발전에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2000.",
    name: "한국사회복지학회",
    purpose: "○ 사회복지 및 사회사업에 관한 학술연구를 통하여 한국의 사회발전에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2000.",
    name: "한국백혈병소아암협회",
    purpose: "○ 백혈병 소아암 환아들의 후원사업 활성화를 통해     사회복지 발전에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2000.",
    name: "한국정신건강전문요원협회",
    purpose: "○ 정신보건전문요원의 양성과 정신질환자의 사회복귀 촉진 및 국민정신건강증진 도모",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2000.",
    name: "한국장애인복지관협회",
    purpose: "○ 장애인복지관 상호간 교류협력 강화 및 종사자 전문성 제고, 장애인 사회참여 및 복지증진 확대",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2000.",
    name: "대한치과병원협회",
    purpose: "○ 치과병원 제도와 운영 연구, 평가 및 개선, 치과의사 및 치과의료기관 종사자의 수련·교육 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2000.",
    name: "한국여성장애인 연합",
    purpose: "○ 여성장애인이 연합하여 공동체를 형성, 상호유대 강화 및 교류협력을 강화하고 여성장애인의 권익신장과 삶의 질을 향상시킴으로써 여성장애인의 사회참여 확대 및 복지증진",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2000.",
    name: "대한턱관절협회",
    purpose: "○ 턱관절분야 회원 상호간 친목을 도모, 턱관절질환에 관한 국제교류 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2001.",
    name: "인터내셔널에이드한국본부",
    purpose: "○ 국내외 어려운 이웃에게 기독교 정신에 입각하여 구호.봉사활동",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2001.",
    name: "한국노인복지봉사회",
    purpose: "○ 경로효친 사상을 앙양하고 노인들의 노후생활 안정과 교육, 봉사활동 및 건강관리등 노인복지 증진에 기여하기 위함.",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2001.",
    name: "보건산업벤처협회",
    purpose: "○ 생명공학, 정보통신, 의공학, 의료정보서비스업 등 보건산업분야 벤처기업 상호 협력을 통한 국민 삶의 질 향상 및 국가경쟁력 제고",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2001.",
    name: "한국화상협회",
    purpose: "○ 화상인에 대한 이해증진, 권익신장 및 사회복귀",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2001.",
    name: "한국한약제약협회",
    purpose: "○ 한약재 및 한방의약품 원료 제조업의 건전한 발전을 기하고 우수한약품을 생산공급함으로써 국민보건향상에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2001.",
    name: "국제절제협회한국총본부",
    purpose: "○ 담배, 술에 대한 절제운동을 전개하여 국민건강증진기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2002.",
    name: "한국노인종합복지관협회",
    purpose: "○ 노인종합복지관 운영의 내실화 및 지역사회노인복지 증진",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2002.",
    name: "한국정신재활시설협회",
    purpose: "○ 정신질환자 사회복귀시설의 육성 및 균형발전을 위한 제반 사업수행 및 정신장애인의 사회복귀 및 국민건강증진 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2002.",
    name: "한국장애인연맹(DPI)",
    purpose: "○ 연맹회원 상호간 이해증진",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2002.",
    name: "한국워킹협회",
    purpose: "○ 걷기운동을 통한 건강증진",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2002.",
    name: "열린치과봉사회",
    purpose: "○ 치과의료봉사, 신문발행 등을 통한 치과계 위상고양 및 사회 발전 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2002.",
    name: "한국사회복지교육협의회",
    purpose: "○ 한국사회복지교육의 건전한 발전을 지원하고 국제사회복지교육기관과의 연락과 협조 도모 - 사회복지교육과정 조사ㆍ연구 - 국내ㆍ외 사회복지단체와의 교육․협력",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2002.",
    name: "한국장애인단체총연합회",
    purpose: "○ 장애인 당사자의 주권주의를 제창하며 장애인이 인간으로서의 존엄과 가치를 지닌 국민의 일원으로 완전한 참여와 평등을 실현하는데 제약이 되는 모든 편견과 차별을 철폐하고, 장애인과 비장애인이 더불어 행복을 추구하며 살아가는 사회통합에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2002.",
    name: "한국복지경제연구원",
    purpose: "○ 사회복지분야의 경제에 관한 조사연구를 수행함으로써 사회보험 및 보건경제의 정책발전에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2002.",
    name: "함께 만드는 세상",
    purpose: "○ 자활의지 및 능력이 있는 빈곤충과 사회 취약계층의   빈곤퇴치를 위한 창업을 위해 자문과 교육훈련 및 경영기술을 지원함으로써 자립․자활촉진에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2003.",
    name: "한국묘교정연구회",
    purpose: "○ 치과교정학의 연구 및 학술교류사업, 특수장애인의 치과무료진료 및 교정사업 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2003.",
    name: "한국혈액암협회",
    purpose: "○ 백혈병등 혈액암 환자들이 사회에 복귀할 수 있도록 후원 및 교육지원사업을 활성화시키고 국민들의 참여 촉진으로 복지증진에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2003.",
    name: "한국시니어클럽협회",
    purpose: "○ 노인 자활∙자립을 위한 사업수행○ 시니어 클럽의 공동사업∙교육 및 훈련∙정책개발 등 제반사업 지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2003.",
    name: "부모효도하기운동",
    purpose: "○ 가정의 행복을 회복하는 것이 목적이며 자라나는 청소년들과 모든 자녀들을 대상으로 실천하는 효도운동을 통해 행복이 넘치는 가정과 사회를 이룩",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2003.",
    name: "한국희귀난치성질환연합회",
    purpose: "○ 희귀난치성질환자와 그 가족에게 정보를 제공하고,   육체적․정신적․경제적 지원을 통하여 인간다운 삶을 영위할 수 있도록 함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2003.",
    name: "한국입양홍보회",
    purpose: "○ 입양에 대한 인식개선 홍보 및 국내입양 장려, 입양아동과 그 가족들에게 복지 및 권리향상에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2003.",
    name: "릴리회",
    purpose: "○ 한센병환자 및 한센병력자들의 복지증진과 이들이    사회에서 동등한 인격으로 살아갈 수 있도록 지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2003.",
    name: "한국이주민건강협회 위프렌즈",
    purpose: "○  이주민의 건강할 권리를 인식하고, 보호하며, 이를 증진하기 위해 회원활동을 통한 진료활동과 조사연구 및 지원활동을 함으로써 이주민들의 건강증진과 복지향상 및 이를 통한 다문화사회 진작과 국가 이미지 제고에 이바지",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2003.",
    name: "장애인먼저실천운동본부",
    purpose: "○ 장애인 실천운동을 통한 대국민의식개선",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2004.",
    name: "지구촌공생회",
    purpose: "○ 인종과 국경을 초월한 지구촌 복지공동체 실현과 인류평화에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2003.",
    name: "한국병원약사회",
    purpose: "○ 의료기관 근무약사 연수교육등 자질향상",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2004.",
    name: "한국자살예방협회",
    purpose: "○ 자살예방에 대한 교육, 홍보 및 연구, 프로그램 개발 등을 통해 생명존중운동 정신구현",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2004.",
    name: "한국천식알레르기협회",
    purpose: "○ 천식 등 알레르기 질환에 관한 학술, 교육 및 연구활동 지원과 이들 질환의 예방을 위한 제공 및 홍보 활동을 수행하여 국민건강 증진과 복지사회 건설에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2004.",
    name: "대한실버산업협회",
    purpose: "○실버산업의 민간 차원 육성",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2004.",
    name: "열린문화",
    purpose: "○ 국민의 문화복지 증진과 저소득층 등 소외계층의 문화적인 소외감극복과 자활의지 고취 및 문화서비스 제공",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2004.",
    name: "한국아동학회",
    purpose: "○아동관련 연구, 프로그램 및 정책개발을 통하여 아동의 건전한 발달을 도모하고 한국 아동학 및 아동정책의 발전에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2004.",
    name: "대한심폐소생협회",
    purpose: "○ 사회일반의 이익에 기여하기 위하여 심폐소생술의 표준화된 지침을 제정하고 국민보건증진에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2005.",
    name: "대한의료정보산업협회",
    purpose: "○ 보건의료 및 바이오관련 정보기술의 향상, 품질 및 안전성의 확보 등을 통하여 국민건강증진과 삶의 질 향상, 국가경쟁력 강화",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2005.",
    name: "선우복지마을",
    purpose: "○노인복지정책 및 프로그램연구,개발○노인여가시설 운영",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2005.",
    name: "한국뇌병변장애인인권협회",
    purpose: "○ 뇌성마비 장애인의 사회활동에 장벽과 차별 제거",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "1987.",
    name: "색동회",
    purpose: "○어린이의 권리ㆍ복지ㆍ문화증진을 통하여 어린이를 건전한 국민으로 육성",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2005.",
    name: "전국지방의료원연합회",
    purpose: "○ 지방의료원의 공동관심사항 대변 및 운영에 관한 연구 개선",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2005.",
    name: "시민건강연구소",
    purpose: "○시민단체차원에서 건강증진 실천방안 연구 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2005.",
    name: "선한 사마리아인 운동본부",
    purpose: "○ 응급환자돕기실천시민운동전개 및 응급환자생명과 건강을 보호하는 정책개발 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2006.",
    name: "국민건강보험동우회",
    purpose: "○ 회원 상호간 친목도모 및 상호부조와 노인일자리 지원 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2006.",
    name: "한국장애인인권포럼",
    purpose: "○ 장애인 인권 및 권익보호와 장애인 복지증진 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2006.",
    name: "전국지역아동센터협의회",
    purpose: "○ 지역사회 안에서 사회적 돌봄이 필요한 아동들의 전인적 발달과 권리 보장을 위해 통합교육 및 사회복지활동을 하며 전국적인 지역사회 공동체를 형성하고 지역아동센터와 아동 및 가족의 성장과 발전을 도모하고자 한다",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2006.",
    name: "대한의료정보학회",
    purpose: "○ 의료정보화에 관한 연구와 응용을 도모함으로써, 의학 및 의료정보분야의 발전에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2006.",
    name: "한국척수장애인협회",
    purpose: "○ 척수장애인들의 권익을 보호하고 대변함으로써 척수장애인들이 동등한 기회와 권리를 가진 사회의 주류로서 살아갈 수 있도록 지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2006.",
    name: "참길복지",
    purpose: "○ 한센인의 자활지원등을 위한 봉사단체로 소록도병원   등 방문 봉사전개",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2006.",
    name: "홍법문화복지법인",
    purpose: "○ 저소득가정의 자녀의 장학사업과 저소득층의 자립.자활사업 및 해외 재난지역 인도적 사업지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2006.",
    name: "한국장애인직업재활시설협회",
    purpose: "○ 장애인직업재활시설 상호간의 교류․협력 활성화  및 시설종사자 자질향상과 전문성 증진 도모로 장애인의 권익 및 복지증진",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2006.",
    name: "돕는사람들",
    purpose: "○ 국적, 인종, 이념, 종교, 성별등과 상관없이 기아와 재난으로 고통 당하는 국내외 사람들의 생존을 돕는 구호사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2006.",
    name: "한국종교계사회복지협의회",
    purpose: "○ 종교간 사회복지에 관한 상호협력과 교류를 통하여 종교사회복지발전과 사회복지증진에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2006.",
    name: "한국기독교사회복지협의회",
    purpose: "○ 한국기독교의 사회복지증진을 위한 협의체로서 교회 본래의 사명인 이웃사랑의 구현과 실천을 위한 체계적이고 전문적인 활동 전개",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2006.",
    name: "한국자폐인사랑협회",
    purpose: "○ 자폐인(자폐성 발달장애인)의 복지증진과 자폐인과 그 가족들이 인간다운 삶을 영위하게함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2007.",
    name: "위스타트",
    purpose: "○ 복지와 교육 등을 지원하여 아동의 공정한 삶의 출발과 건강한 시민으로 성장하도록 지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2007.",
    name: "한국피부미용사회중앙회",
    purpose: "○ 피부미용인 지위향상○ 회원간 친목도모 및 피부미용문화 창달",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2007.",
    name: "생명을나누는사람들",
    purpose: "○ 올바른 장기기증의 정착 및 생명나눔운동",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2007.",
    name: "일촌공동체",
    purpose: "○ 복지사각지대 문제에 대한 활동과 발굴, 육성, 지원하여 이들의 지역공동체 형성",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2007.",
    name: "대한의학회",
    purpose: "○ 의학연구의 기반조성과 회원의 학술활동을 지원하고 의학의 전문성 강화를 위한 교육 및 정책개발을 통해 의학 발전에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2007.",
    name: "미래복지경영",
    purpose: "○ 사회복지서비스의 질적향상과 경영마인드 함양을 위한 교육, 연구, 자문, 평가 등을 통하여 한국의 복지향상에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2007.",
    name: "한국아동청소년그룹홈협의회",
    purpose: "○ 보호가 필요한 아동을 보호하는 공동생활가정 및 아동을 지원하는 제반사업을 목적으로 함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2007.",
    name: "대한기관윤리심의기구협의회",
    purpose: "○ 생명윤리법에 의한 생명과학기술에 있어서의 생명윤리 및 안전을 확보하고, 의약품 임상시험관리기준 등에 의한 윤리적이고 과학적인 임상연구 등의 여건을 조성",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2008.",
    name: "한국마이크로크레딧 신나는조합",
    purpose: "○ 자활.자립의지는 있으나 사회경제적으로 소외된 빈곤.사회취약계층에 소규모 창업자금의 무담보.무보증 대출을 통해 경제.사회.심리적 자활지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2008.",
    name: "대한민국의학한림원",
    purpose: "○ 의학 및 관련 전문분야의 석학으로 구성하여, 우리나라 의학의 지속적인 진흥 창달과 선진화를 효과적으로 유도하는 사업을 함으로써 의학발전과 국민건강증진에 이바지",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2008.",
    name: "한국가톨릭의료협회",
    purpose: "○ 가톨릭계 의료관계인의 상호협력을 통해 의료서비스를 원활히 수행하여 국가의료발전에 기여, 의료자원사업과 봉사활동을 통해 모든 이가 건강한 삶을 영위하도록 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2008.",
    name: "한국사회서비스연구원",
    purpose: "○ 사회서비스관련 정책 및 관리기술의 개발 보급",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2008.",
    name: "한 자녀 더 갖기 운동 연합",
    purpose: "○ 캠페인 등을 통해 출산에 대한 긍정적 사회인식변화○ 저출산문제 개선을 위한 세미나, 토론회 개최○ 저출산문제에 관한 조사․연구, 자문, 지원 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2008.",
    name: "한국글로벌의약산업연구회",
    purpose: "○ 신성장동력을 발굴하여 한국 의약계에서 국가발전과 국민보건의 향상에 기여함을 목적으로 함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2008.",
    name: "건강안전복지연합",
    purpose: "○ 보건의료 및 사회복지정책에 대해 현실적이고 체계적인 연구분석과 국민의견수렴 및 이해증진을 위한 활동을 수행함으로써 국민건강복지 향상에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "한국교회노인학교연합회",
    purpose: "○노인학교운영을 통한 노인복지증진에 이바지(노인학교 프로그램 개발 및 보급, 노인학교 지도자 교육훈련 등)",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "늘푸른장사문화원",
    purpose: "○ 지속가능한 장사문화 발전과 장사복지 증진(장사문화에 대한 국민의 이해증진을 위한 교육 및 홍보 등)",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "한국노인장기요양기관협회",
    purpose: "○ 노인복지개인시설(장기요양기관) 종사자 교육훈련 및 복지증진○ 노인복지에 관한 조사.연구 및 정책건의 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "본사랑",
    purpose: "○ 독거노인생활비지원사업○ 소년.소녀가장 생활비 및 교육비 지원사업○ 사회소외계층에 대한 무료급식 지원사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "좋은사람들",
    purpose: "○ 복지지원사업○ 자원봉사조직 및 육성사업○ 다문화가정 사회적응지원사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "한국장애인자립생활센터총연합회",
    purpose: "○ 중증장애인의 자립생활에 필요한 정책개발 및 제도연구○ 자립생활센터간의 정보교환, 상호지원 및 인적교류○ 활동보조인과 활동보조서비스 이용자 교육사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "해냄복지회",
    purpose: "○ 발달장애인 교육 및 재활사업○ 뇌병변장애인 예방 및 재활사업○ 중증장애인의 자립생활기반 조성사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "한국난임가족연합회",
    purpose: "○ 난임 극복하고 출산 희망하는 사람들의 온·오프라인의 정보교류, 상담, 상호이해○ 난임부부 지원, 난임인식개선 캠페인, 관련 학술연구 및 연구용역 사업 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "한국소아당뇨인협회",
    purpose: "○ 소아당뇨인의 권익보호와 복지증진을 위한 홍보 및 후원사업 수행",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "한국시니어비전연합회",
    purpose: "○ 고령사회와 노인문제 연구와 노인·고령자에 대한 교육, 상담, 역할증진사업 실시○ 신노인운동을 전개하여 다가오는 고령사회를 향한 긍정적 비전제시·실천함으로 국가사회발전에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "전국장애인부모연대",
    purpose: "○ 장애인과 그 부모 및 가족을 지원하는 사업을     펼치며 장애인의 교육·복지·노동 등 보편적     권리확대를 통해 장애인의 인간다운 삶을 실현",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "한국은빛희망협회",
    purpose: "○ 중고령자들의 전직의 고귀한 경험·지식·기술을 바탕으로 한 일자리 창출, 사회봉사활동 등 사회참여확대를 통하여 활기찬 노년생활을 보장하고 고령화시대를 대비",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "생명잇기",
    purpose: "○ 장기 및 조직기증에 대한 올바른 인식 확산과 기증문화 정착을 위한 운동을 통하여 생명나눔의 정신을 실현하고 국민건강 증진과 국가사회 발전에 이바지",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "해피실버",
    purpose: "○ 노인일자리 창출과 자원봉사 연계를 통한 노인 삶의 질 향상",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "한국침구사협회",
    purpose: "○ 침구의료질서 확립 및 침구의학 발전으로 국민보건 향상에 기여하며, 침구의료업자의 권익옹호신장",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "연우",
    purpose: "○ 고령화 사회의 취약노인계층에게 교육·문화·복지의 기회제공으로 사회양극화 해소 및 노인복지증진에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2009.",
    name: "한국골든에이지포럼",
    purpose: "○ 고령자 삶의 질 증진과 정부 고령사회정책의 방향정립 및 지원을 통하여 국민복지에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2010.",
    name: "한국글로벌헬스케어협회",
    purpose: "○ 한국의 외국인환자 유치사업의 활성화와 우수 한국의료의 해외진출을 도모함으로써 한국의 이미지 향상에 기여하고, 국가 경제발전에 이바지",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2010.",
    name: "한국국제의료협회",
    purpose: "○ 한국의료서비스의 발전현황을 해외에 널리 알리고, 회원의료기관의 국제화를 도모함으로써 해외환자 유치 및 해외진출 활성화에 이바지",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2010.",
    name: "사단법인 범부처통합헬스케어협회",
    purpose: "○ 스마트 헬스케어 서비스의 보급․확산 및 이용촉진, 신기술 연구, 인재양성 등을 통하여 국민 건강증진 및 국가 경쟁력 강화에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2010.",
    name: "지구촌보건복지",
    purpose: "○ 국내외 보건의료지원사업과 복지부문 지원사업을 수행함으로써 인도주의를 실천하고 국제사회에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2010.",
    name: "한마음장례실천나눔회",
    purpose: "○ 독거노인 및 저소득층 대한 무료장례 ○ 법적으로 지원받지 못하는 소외 계층에 대한 무료장례○ 장례방법 및 장례용품의 연구․기술 개발",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2011.",
    name: "정신의료기관협회",
    purpose: "○ 정신의료기관의 지도계몽,각종 공익사업의 수행 정신건강의료서비스체계의 능률적 구축, 정신질환자에 대한 의료서비스제공등의 사업수행으로 국민정신건강증진에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2011.",
    name: "한국사회보장학회",
    purpose: "○ 사회보장에 관한 학문적연구와 학술활동을 통해 사회보장발전에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2011.",
    name: "나눔국민운동본부",
    purpose: "○ 우리사회 나눔문화를 널리 확산하기 위하여 국민운동을 전개하고, 나눔에 대한 각종 홍보와 협력사업 및 조사 · 연구 및 교육사업 등을 통해 나눔문화 정착",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2011.",
    name: "한국장기기증협회",
    purpose: "O 각종 장기부전으로 고통받는 환우들을 위한 대국민 장기기증 홍보사업을 통하여 장기기증운동이 국민상호간의 기부문화활동이 될 수 있도록 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2011.",
    name: "한국언어재활사협회",
    purpose: "○ 언어장애인 의사소통능력 향상과 언어재활사     권익보호, 교육프로그램 개발, 언어장애인의     권익 및 복지증진에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2011.",
    name: "국제키비탄한국본부",
    purpose: "○ 지역사회에서 장애인의 재활과 복지기여,     각종봉사활동을 통한 시민정신 함양을 목표",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2011.",
    name: "아름다운공동체",
    purpose: "○ 국내로는 사회소외계층의 복지증진에 관한 사업을 수행하며, 국외로는 국제구호사업을 수행하여 국가 복지정책 및 인류애 실현에 공헌함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2011.",
    name: "프로라이프",
    purpose: "○ 낙태를 예방하고 임신․출산과 관련한 생명살리기 운동 등을 실천하여 생명존중이라는 보편적 가치 실현에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2011.",
    name: "한국재가장기요양기관협회",
    purpose: "○ 장기요양보험 관련 정책 및 관리기술을 연구, 정보나눔 사업○ 노인장기요양서비스분야 교육 및 보수교육사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2011.",
    name: "국경없는의사회 한국",
    purpose: "○ 긴급재난 구호활동○ 구호활동 및 현지 의료기술 향상을 위해 의료인을     비롯한 각 분야의 전문인력을 파견하고 물자를     지원하는 활동",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2011.",
    name: "국제연꽃마을",
    purpose: "○노인보건복지연구 및 복지증진과 해외(베트남) 사회복지시설 지원 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2012.",
    name: "바른이봉사회",
    purpose: "O 청소년치아교정지원사업 등의 의료봉사사업, 장학사업, 부정교합질환에 대한 학술연구지원 등을 행함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2010.",
    name: "실종아동찾기협회",
    purpose: "○ 실종아동(장애인 포함)의 조속한 가족상봉을 지원하고 실종아동의 안전과 인권보호에 적극 동참하며 실종예방 활동에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2012.",
    name: "한기범희망나눔",
    purpose: "○ 나눔문화를 확산하고, 사회 동반자와 긴밀한 협력을 통해 어려운 이웃을 지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2013.",
    name: "해피기버",
    purpose: "○ 지역별 특성에 맞는 지원 프로그램 개발과 구제 및 상담 지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2013.",
    name: "한국 아르브뤼․아웃사이더 아트 협회",
    purpose: "○ 예술가적 재능을 가진 정신적 장애인의 사회활동 및 예술창작품 지원을 통하여 이들의 삶의 질 향상, 직업재활 및 정신적 장애인에 대한 일반인의 인식 개선을 목적으로 함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2013.",
    name: "대한한의학회",
    purpose: "○ 한의학의 발전을 위하여 한의학 학술에 관한 제반사항과 회원학회의 학술활동을 지원하고 회원 상호간의 유대를 강화하여 국민보건 향상에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2013.",
    name: "대한여한의사회",
    purpose: "○ 국민보건 향상과 사회복지 증진에 기여하고, 한의 학술의 발전과 회원간의 친목을 도모하며 여한의사의 권익 옹호 및 자질향상을 위한 국제교류 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2013.",
    name: "대한의사협회 의료배상공제조합",
    purpose: "○ 의료사고 배상금 지급을 위한 공제사업",
    law: "③개별법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2014.",
    name: "한국의료행정실무협회",
    purpose: "○ 의료행정 발전을 위한 학술, 교육 및 연구 활동을 지원하여 의료행정 서비스 질 향상에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2003.",
    name: "한국조직은행연합회",
    purpose: "○ 조직기증 및 조직이식에 대한 교육 및 홍보 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2014.",
    name: "한국모금가협회",
    purpose: "○ 비영리 모금분야(교육, 보건의료, 사회복지, 문화예술, 시민사회, 국제개발 분야 등)의 모금종사자들이 모금의 윤리성과 전문성을 강화하고, 우리 사회의 자선과 나눔 문화의 확산에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2007.",
    name: "우리복지",
    purpose: "○ 어린이 심장병 지원사업, 다문화가정사업,인재양성 농구교실, 꿈나무지원사업등을 통해 나눔문화확산, 어려운 이웃지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2014.",
    name: "한국사회복지법인협회",
    purpose: "사회복지법인의 건전성과 전문성을 높이고 사회적 책임을 공유함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2012.",
    name: "한국시각장애노인복지협회",
    purpose: "○ 시각장애노인의 복지향상과 권익신장에 앞장서며 각종 건강활동과 회원 상호간의 상부상조 및 친목도모를 통하여 고독과 고립에서 벗어나 보람된 노후생활을 영위",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2014.",
    name: "사전의료의향서 실천모임",
    purpose: "○ 사전의료의향서에 관한 이해의 증진 및 그 실천과 존중에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2012.",
    name: "동행연우회",
    purpose: "○ 저소득층, 다문화가정, 아동·청소년, 노인·장애인 등에 대한 돌봄, 보육, 상담, 후원, 봉사활동, 학비지원 등에 관한 사업○ 어린이집, 유치원, 아동 및 청소년 시설 위탁사업○ 장애인의 생활시설, 재가시설 등 운영사업○ 노인상담 봉사활동○ 그 밖에 법인의 목적달성에 필요한 사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2015.",
    name: "사랑의 쌀 나눔운동본부",
    purpose: "○ 노인의 삶의 질 향상을 위해 노력하며, 현대를 사는 사회구성원으로서의 역할을 하여 존경받는 노인이 될 수 있도록 지원함을 목적으로 함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2015.",
    name: "인구와 미래 정책연구원",
    purpose: "○ 인구변동 추이, 원인, 파급효과, 대응전략, 정책방안 등 연구○ 인구현상에 대한 이해증진, 인식개선과 국민의 적극    적 참여를 도모하기 위한 교육과 홍보활동 수행",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2015.",
    name: "한국메이크업미용사회",
    purpose: "○ 미용업(화장‧분장) 발전 및 공중위생과 국민보건의 향상",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2001.",
    name: "국제위러브유운동본부",
    purpose: "○불우아동 교육비 및 의료비 지원사업○저소득·빈곤 가정 생활지원사업○재난가정 복구지원사업○청소년 자원봉사활동 및 인성 발달을 위한 교육·문화 활동지원사업○그 밖에 법인의 목적달성에 필요한 사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2015.",
    name: "참행복 나눔운동",
    purpose: "○ 참행복 나눔포럼 전개, 나눔생활 실천 대국민 교육홍보와 조사 수집, 소외청소년에 대한 멘토링, 후원사업 등을 통해 우리 사회 조건없는 나눔확산에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2015.",
    name: "희망나눔협의회",
    purpose: "○ 봉사정신과 헌신, 지식나눔, 토론회 등을 통하여 각종 노인문제에 대한 민간차원의 캠페인 및 선진시민의식 함양",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2015.",
    name: "또하나의열매",
    purpose: "아동인권보호사업, 아동 자립 리더십 교육사업, 아동전문 자원봉사자 양성 및 관련 전문인력양성 위탁사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2015.",
    name: "플러스 나눔",
    purpose: "○ 다양한 복지수요에 부응하고 지역복지서비스의 전문성을 증진하여 노인, 장애인, 여성 등 취약계층에 대한 선제적 사회복지서비스 기회제공과 취약계층의 삶의 질 제고에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2015.",
    name: "일과복지",
    purpose: "○ 한국의 지속가능한 사회보장시스템 운영에 필요한 다양한 정책개발 등으로 국가발전 및 국민의 삶의 질 향상에 이바지",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2015.",
    name: "희망누리복지회",
    purpose: "○ 지역사회 등의 노인복지서비스 제공 및 확대, 자립, 자활을 위한 사업을 수행하고 각 사회복지단체의 균형적인 발전과 활성화를 위하여 연대와 협력을 통한 공동사업, 교육 및 훈련 등 제반 사업을 지원, 공유하며, 더 나아가 사회복지서비스를 확대, 정착시키는데 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2015.",
    name: "무궁화복지월드",
    purpose: "○ 아동의 권리옹호 및 아동학대예방사업○ 취약계층 아동 및 가정 등 불우이웃 지원 사업○ 지역사회 교육 및 문화증진 사업○ 아동권익 향상을 위한 연구 및 조사 사업 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2015.",
    name: "마을과아이들",
    purpose: "○ 아동복지사업을 행하는 단체나 개인 간 정보 교류, 사랑과 나눔,연대를 통하여 아동의 권리와 복지를 향상시키고, 관련 종사자의 전문성을 고취시키며, 지역사회내 안전망을 구축하여 아동들의 건강한 성장을 지원하여, 올곧은 인간으로 성장하여 아름답고 행복한 삶을 누릴수 있도록 이끄는데 그 목적을 둔다.",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2015.",
    name: "한국효문화 실천운동본부",
    purpose: "○ 우리 사회에서 흔들리는 효의 전통을 다시 살리고 젊은 세대들에게 2007년 발표된 효비전 선언문과 7효에 기초한 올바른 효의 가치관을 심어주고 효문화 확산을 위한 실천운동을 전개하는 것을 목적으로 함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2016.",
    name: "대한네일미용사회",
    purpose: "○ 미용업(손톱‧발톱) 발전 및 공중위생과 국민보건의 향상",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2016.",
    name: "전국병원불자연합회",
    purpose: "○ 의료 혜택을 제대로 받지 못하는 취약지역 주민을 대상으로 의료지원과 사회봉사활동을 전개",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2016.",
    name: "사회복지법제학회",
    purpose: "○ 사회복지학과 법학의 학문적 융합을 기반으로 한 사회복지법제와 관련된 실천적·학술적 제반활동과 회원 상호간의 교류와 협력을 통하여 더불어 사는 사회 형성과 발전에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2016.",
    name: "한중성형의료교류협회",
    purpose: "○ 한국과 중국간 성형의학 공동연구 및 세미나 개최 등 학술교류",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2016.",
    name: "한국사랑나눔공동체",
    purpose: "○ 국내 저소득층 및 사회소외계층에 대한 의료비 지원 및 식량지원 등 복지증진에 관한 사업 수행, 국외 저개발국가의 국제 구호사업 수행",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2017.",
    name: "전국노숙인시설협회",
    purpose: "○ 노숙인 인권보호, 재활자활프로그램, 시설종사자 역량강화",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2017.",
    name: "대한치의학회",
    purpose: "○ 치의학 발전을 위하여 새로운 학술 또는 기술을 개발하는 학술활동 지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2017.",
    name: "임산부약물정보센터",
    purpose: "○  임산부 등에게 약물 등 유해물질에 관한 적절한 정보를 제공하여 인공임신중절 예방 및 안전한 출산환경조성 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2017.",
    name: "아침고요둥지복지회",
    purpose: "○ 국내입양 활성화 및 입양가정에 대한 정서적, 경제적, 교육적 지원을 통한 올바른 입양문화 선도",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2017.",
    name: "한국장애인주간이용시설협회",
    purpose: "○ 장애인주간보호시설의 발전을 통하여 장애인과 비장애인이 지역사회 안에서 더불어 살아갈 수 있게 하며, 시설종사자의 전문성 향상과 회원시설 간 연대를 통해 장애인복지 증진에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2017.",
    name: "한국의사한의사 복수면허자협회",
    purpose: "○ 의학지식 및 정보의 교류를 위한 학술대회, 청소년쉼터건강진료서비스 제공 등 대국민 의료봉사 보수교육 시행 및 기관지, 학술지, 학술서적 발간 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2018.",
    name: "대한통합암학회",
    purpose: "○국민보건향상과 의료복지를 증진하고, 통합암학의 발전보급, 회원의 친목과 권익옹호, 회원수련, 연수와 각종사업을 통하여 의료사업발전에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2018.",
    name: "한국검체검사전문수탁기관협회",
    purpose: "○ 검체검사 서비스의 선진화, 검체검사수탁산업의 건전한 발전 및 국민보건의료 향상에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2018.",
    name: "한국장애인재활상담사협회",
    purpose: "○장애인의 권익과 사회참여를 위해 전문지식과 기술을 개발·보급하며, 장애인재활상담사의 권익옹호와 복지증진에 이바지함을 목적으로 함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2019.",
    name: "입양가족상담교육협회",
    purpose: "○ 입양사전·사후 전문 서비스 기관으로써 입양특성화 상담, 치료 및 교육을 제공하여 아동학대 예방, 입양가족건강 증진 및 입양문화 개선에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2019.",
    name: "행동하는 의사회",
    purpose: "○ 의료계 내 나눔문화를 확산하고, 국민에게 봉사하는 의사상을 확립함으로써 노블리스 오블리주를 실천하고 한국의료발전과 인류의 보편적 건강증진에 이바지함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2021.",
    name: "사단법인 한국산후조리원협회",
    purpose: "○ 산후조리관련 학술연구, 조사, 활동 등을 통한 산모와 신생아 건강관리 및 산후조리 문화의 전문성 확보○ 산후조리원 서비스개선 향상을 위만 컨설팅 지원, 종사자 교육 및 전문가 양성 프로그램 운영을 통한 산후조리업의 품질 유지·발전",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2021.",
    name: "한우리복지회",
    purpose: "○ 어르신복지를 수행하여 지역주민의 참여를 촉진시킴으로서 지역사회의 복지증진과 발전에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2021.",
    name: "한국자활기업협회",
    purpose: "○ 자활기업간 정보, 기술 경영노하우 교류를 통해 기업 경영 활성화 촉진○ 자활기업간 협업 및 공동사업을 통해 자활기업 규모화 및 경쟁력 향상○ 자활기업 사회적가치 정립을 통해 윤리경영 실천과 대국민 인식개선",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2021.",
    name: "(사)글로벌행복한사람들",
    purpose: "○ 인간의 존엄성과 인간다운 생활을 할 권리를 보장하고, 지역의 필요한 대상에 대한 복지 및 돌봄 관련 서비스 등의 사업 및 시설 운영과 이를 위해 민간복지자원을 개발하며, 아동에서 노인까지 종합적인 돌봄 및 사회복지서비스 등을 통해 지역사회의 어려운 이웃들을 돕고, 현재와 미래 세대의 건강하고 행복한 사회, 환경을 위한 민간복지자원 육성을 위해 노력한다. 특히 보호(안전, 생활, 급식 등), 교육(학습, 특기적성, 독서 등), 문화(문화, 예술, 축제, 공연, 캠프, 도서출판 등), 정서지원(상담, 가족지원, 정서지원특화 서비스 등), 지역사회연계(인적연계, 기관연계, 직능단체 연계 등)의 5대 영역 서비스를 개발 및 연구를 통해 전문적인 서비스 제공 등의 사업을 제공한다. 또한 글로벌 시대에 맞게 북한이탈주민 및 외국인을 포함한 이주배경(다문화)의 대상들에게 맞는 서비스를 연구및 개발 하고 서비스를 제공한다.",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2022.",
    name: "(사)한국장애인보건의료협의회",
    purpose: "○ 장애인들의 효율적인 건강증진을 위한 정책연구, 실천사업○ 관련 장애인단체와 협력사업",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2021.",
    name: "사단법인 징검다리",
    purpose: "○ 나눔과 섬김을 통한 사회복지사업 - 아동,청소년, 여성, 노인, 장애인 등 사회취약계층지원을 위한 복지프로그램 개발을 통한 모금활동 및 직접지원사업 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2022.",
    name: "사단법인 굿웍스",
    purpose: "○ 행복한 삶을 위해 사랑으로 인한 안전한 보육과 양육, 자아가 보장된 행복한 미래가 있는 프로그램을 개발, 보급, 운영함을 목적으로 한다.",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2022.",
    name: "사단법인 첨단재생의료산업협회",
    purpose: "○ 첨단재생의료산업 협의체 구축○ 첨단재생의료 R&D 활성화○ 첨단재생의료기술 상용화 촉진",
    law: "②공익법인법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2022.",
    name: "사단법인 더함 위드",
    purpose: "○ 사회적 돌봄이 필요한 아동〮청소년들에게 프로그램 및 다양한 복지 서비스를 제공하고 나아가 보호자 및 지역사회 자원연계를 통해 건겅하고 안전한 돌봄 및 성장 지원을 목적으로 한다.",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2024.",
    name: "사단법인 선한영향력가게",
    purpose: "○  결식·결손 아동의 삶의 질을 향상시키고, 건강한 삶을 영위할 수 있도록 체계적이고, 다양한 활동을 전개하여 사회 전반적으로 선한 영향력을 나눔",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2024.",
    name: "사단법인 한국근육장애인협회",
    purpose: "○ 진행성 신경〮근육계 질환으로 장애가 발생된 근육 장애인의 사회생활 및 자립생활 지원",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2024.02.08.",
    name: "사단법인 이태복기념사업회",
    purpose: "○ 사회적 약자의 사회복지증진 - 저소득계층을 위한 후원, 결연사업 - 사회복지관련 조사연구사업 - 해외동포에 대한 후원사업 - 이태복 추모,연구,홍보사업 등",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2024.",
    name: "(사)글로컬건강도시연구원",
    purpose: "○ 건강도시 구현을 위한 학술연구, 교육 등을 통해 건강도시 문화 정착 및 제도 발전 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2024.12.26.",
    name: "(사)중독포럼",
    purpose: "○ 대한민국 중독문제 해결을 위한 사회문화적 환경조성과 합리적인 정책 마련을 통해 중독 없는 환경을 만드는 것을 목적으로 함",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2025.04.16",
    name: "(사)병원시설관리협회",
    purpose: "○ 병원시설과 시설관리 운영에 관한 연구, 전문교육 등을 통해 병원시설 표준화등을 제시하여 환자 안전과 국민 보건 향상",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2025.6.26",
    name: "사단법인 한국카리타스협회",
    purpose: "○ 카리타스 정신과 가치를 기반으로 사회복지사업의 발전과 사회복지 현장의 활성화",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
  ExcelRowData(
    permitDate: "2025.9.9.",
    name: "(사)국민의료복지네트워크",
    purpose: "○ 정부와 학계, 민간의 협력 네트워크를 구축하여 보건의료복지 정책의 혁신과 발전에 기여",
    law: "①민법",
    type: "-",
    remit: "보건복지부",
  ),
];
