import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> mofeRawData = [
  ExcelRowData(
    permitDate: "1965-03-22",
    name: "한국담배판매인회",
    purpose: "회원권익보호, 회원간의 상부상조 및 복지증진",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1965-04-07",
    name: "인구문제연구소",
    purpose: "인구이동, 인구통계, 인구정책에 대한 연구와 홍보",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1967-07-08",
    name: "한국경제연구원",
    purpose: "국내외 경제문제 조사연구, 건전한 시장경제체제와 자유기업의 성장발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1972-09-20",
    name: "담배인삼공제회",
    purpose: "회원의 복리 및 지위향상을 기하고 퇴직후 생활안정 및 친목도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1973-05-16",
    name: "한국물가협회",
    purpose: "물가조사자료발간 등을 통해 국민편익 증진",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1973-06-16",
    name: "한국산업정책연구소",
    purpose: "한국산업정책연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1974-12-12",
    name: "한국경영연구원",
    purpose: "국민경제의 발전을 도모하기 위해 공사기업의 경영합리화 방안을 연구 분석",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1977-01-15",
    name: "재일한국인본국투자협회",
    purpose: "재일동포투자 유치사업,, 본국투자회원사간의 친목도모본국투자기업 등 재일동포의 국내창구역할",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1977-04-20",
    name: "한국능률협회",
    purpose: "국내외의 경제ㆍ경영ㆍ기술문제의 조사연구, 산업경제정보의 교류, 경제합리화와 산업능률 극대화를 도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1978-06-12",
    name: "한국산업경제연구원",
    purpose: "경제의 국제화 과정에서 당면하고 있는 제반문제 조사분석, 기업의 경영 및 과학적 관리기법 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1981-02-12",
    name: "한일경제협회",
    purpose: "한일양국 경제계의 상호이해와 친선증진 및양국의 경제제휴 도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1983-11-10",
    name: "한국국제조세협회",
    purpose: "재정에 관한 국제법 및 비교법과 조세의 재정적, 경제적 측면에 대한 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1985-06-29",
    name: "KT&G동우회(前한국전우회)",
    purpose: "회원상호간의 친목도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1985-07-23",
    name: "녹색삶지식경제연구원",
    purpose: "국가경제 장기개발계획을 주축으로 산업경제정책을 연구 분석하여 국가경제정책 수립에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1986-05-26",
    name: "한국기업정책연구소",
    purpose: "중소기업의 경제운영 계획 및 국가의 경제사회발번 계획을 수집",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1986-10-06",
    name: "한국산업경영연구소",
    purpose: "기간산업의 경영실태 조사연구, 경제정책방향 설정을 위한 학술적 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1987-10-31",
    name: "한국경제예측연구원",
    purpose: "한국경제예측연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1987-10-31",
    name: "발전시스템연구소",
    purpose: "국가발전시스템연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1988-06-10",
    name: "한국지역사회연구소",
    purpose: "지역사회 제반문제를 연구하여 정책대안 제시학술세미나ㆍ시사간담회ㆍ장학사업 등을 통하여 사회발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1988-10-17",
    name: "한국산업경제연구소",
    purpose: "학술연구 및 원가계산",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1988-12-30",
    name: "한국물가정보",
    purpose: "물가조사자료발간 등을 통해 국민편의 증진",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1989-01-14",
    name: "한국경제과학연구원",
    purpose: "한국경제과학 분야의 선진화와 장단기 대응전략을 모색하기 위한 연구사업을 수행",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1989-03-23",
    name: "한국경제기술연구원",
    purpose: "국내외 경제현황 및 산업에 관한 제반조사 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1990-05-15",
    name: "경제정의연구소",
    purpose: "우리 사회의 경제적 균형발전, 공정분배를 위한 경제정책에 조사 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1990-05-17",
    name: "미래경제연구원",
    purpose: "미래경제연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1990-09-25",
    name: "21세기정책연구원",
    purpose: "21세기를 향한 국민경제의 성장발전과 중장기적 국가정책 방향 및 주요 현안문제에 대한 정책대안을 제시",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1991-01-01",
    name: "아세아,태평양경제연구소",
    purpose: "세계정치ㆍ경제구조변화와 아세아ㆍ태평양권의 자료수집등 세계속에서 한국의 진로를 모색",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1991-01-25",
    name: "한국태평양경제협력위원회",
    purpose: "1980년 설립된 태평양경제협력위원회(PECC)의 한국위원회대외적으로 PECC의 각종 국제회의에서 우리나라를 대표, 대내적으로 정부와 민간의 아ㆍ태 경제협력사업 추진을 지원",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1991-02-05",
    name: "한국경제종합연구원",
    purpose: "한국경제종합연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1991-03-05",
    name: "서울경제연구원",
    purpose: "대내외 환경여건의 급격한 변화에 적응할 수 있는 정책개발, 제반 경제활동의 효율을 높임으로서 국민복지향상 도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1991-09-09",
    name: "양지경제연구회",
    purpose: "경제현안에 대한 올바른 분석과 이해를 도모하고 촉진함으로써 국가경제의 발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1992-07030",
    name: "대한발전전략연구원",
    purpose: "우리나라 성장발전과 중장기적 국가정책방향 및 현안문제에 대한 대안제시(학술연구 및 연구자료 발간사업)",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1992-12-01",
    name: "한국정책학회",
    purpose: "정책학 및 분야별 정책에 관한 학술활동 촉진",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1993-01-21",
    name: "한국경제학회",
    purpose: "경제 이론, 정책, 역사 및 실정등에 관한 연구 및 보급",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1993-03-09",
    name: "서울사회경제연구소",
    purpose: "한국에 적합한 경제이론을 개발하고 경제현실을 체계적으로 조사ㆍ연구하여 올바른 정책방향을 제시",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1993-04-09",
    name: "국민경제한림원",
    purpose: "국민경제연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1993-11-13",
    name: "21세기경제사회연구원",
    purpose: "정치, 경제, 사회연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1994-03-10",
    name: "낙성대경제연구소",
    purpose: "한국경제의 역사적 발전과정과 구조적 특질에 대해 체계적으로 조사ㆍ연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1994-12-07",
    name: "한국경제전략연구원",
    purpose: "한국경제의 세계화를 위해 경제정책과 기업의 국제경쟁력의 강화방안 등을 새로운 각도에서 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1994-12-16",
    name: "아시아개발연구원",
    purpose: "동남아시아 지역의 정치ㆍ경제ㆍ사회의 거시적동향, 미시적 정보를 수집ㆍ분석하여 한국기업의 대아시아지역 진출에 도움",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1994-12-19",
    name: "지에스아이",
    purpose: "21세기를 대비한 국가경제의 합리적 발전 모델의 제시를 위하여 경제,,사회 및 정치 등 제반분야와의 관련 문제를 종합적으로 조사, 연구하여 국가경제발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1994-12-30",
    name: "한국경제경영연구원",
    purpose: "한국경제연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1995-02-18",
    name: "바른경제동인회",
    purpose: "기업윤리경영 실행",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1995-03-06",
    name: "한국경제정책연구소",
    purpose: "원가계산 용역기관",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1995-04-04",
    name: "APEX경영연구소",
    purpose: "마케팅연구,경제,경영서적발간",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1995-04-10",
    name: "한양경제연구원",
    purpose: "경제예측 등의 학술적연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1995-05-25",
    name: "한국사회경제연구소",
    purpose: "사회과학 전분야에 대한 문제를 종합적으로 조사분석연구하여 효율적인 국가정책방향 수립",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1995-07-20",
    name: "한국경제개발연구원",
    purpose: "종합학술연구, 정부회계원가계산 용역기관",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1995-08-24",
    name: "북한경제포럼",
    purpose: "북한경제연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1995-09-07",
    name: "재경회",
    purpose: "회원간의 친목도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1996-01-18",
    name: "국가경쟁력연구원",
    purpose: "국가경쟁력연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1996-02-07",
    name: "매일경제연구소",
    purpose: "국내의 경제, 사회, 산업, 경영에 대한 문제를 집중적으로 연구하여 효율적인 국가정책방향의 수립과 기업경영관리의 선진화에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1996-02-29",
    name: "지역산업사회연구원",
    purpose: "지역산업사회연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1996-07-10",
    name: "한국미래경영연구소",
    purpose: "한국미래경영연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1996-07-11",
    name: "개발연구협의체",
    purpose: "국제경제질서의 재편과 사회구조의 다변화등 인류가 당면한 문제들을 포괄적으로 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1996-09-19",
    name: "중앙경제연구원",
    purpose: "장단기 경제예측 등의 학술적 연구, 경영관리제도의 체계화, 국제경쟁력 제고를 통하여 국가경제발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1996-09-25",
    name: "대한경제연구원",
    purpose: "국내 및 국제산업사회에 대응하기 위한 기업의 효율적 경영을 위한 제분야의 연구ㆍ조사 수행",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1996-10-17",
    name: "한국EU학회",
    purpose: "유럽연합의 대외통상정책, 투자여건 연구 및 한국과 EU간의 경제교류를 활성화하고 양국간의 협력증진",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1996-11-09",
    name: "한국담배소비자보호협회",
    purpose: "담배소비자의 권리제창 및 권익보호",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1996-12-03",
    name: "안민정책포럼",
    purpose: "정책대안을 제시하는 학술단체",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1997-06-16",
    name: "아태경제협력교육재단",
    purpose: "APEC 회원국의 역내 교육/인력개발 및 교류사업에 대한 재정지원을 통해 APEC 발전에 기여함",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1997-08-13",
    name: "경영정보연구원",
    purpose: "학술연구용역 및 원가계산관리",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1997-09-06",
    name: "한국경제정보연구원",
    purpose: "국가경제의 균형적발전과 한국경제의 국가경쟁력제고 등의 실질적 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1997-09-06",
    name: "경제자유찾기모임",
    purpose: "경제자유찾기",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1997-09-06",
    name: "APEC산업전략연구원",
    purpose: "한국경제에 관한 학문적 연구 및 교육, 한국산업의 국제경쟁력 향상과 국민경제의 성장발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1997-09-18",
    name: "한국사회경제학회",
    purpose: "한국경제에 관한 연구를 촉진하고 국민경제의 성장ㆍ발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1997-11-21",
    name: "동양경제정보연구소",
    purpose: "우리나라의 국제경쟁력 제고를 위한 경제정책방향 설정 및 제도연구, 경영관리기법 연구, 국제유통경제의 학술적 조사연구 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1997-12-11",
    name: "경제문화연구소",
    purpose: "지역경제발전을 위한 경제세미나ㆍ교육 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1997-12-29",
    name: "한국경영평가연구원",
    purpose: "한국경제의 국제경쟁력 함양",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1998-02-20",
    name: "한국담배협회",
    purpose: "담배산업의 건전한 발전도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1998-03-30",
    name: "나라발전연구회",
    purpose: "21C 선진경제의 구축 및 남북통일시대에 대비한 중장기 국가발전전략 연구개발",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1998-04-10",
    name: "한국경영분석연구원",
    purpose: "경영분야에 대한 연구와 선진경영교육기관과의 교류를 통해 경영정보와 경영기법을 기업에게 보급ㆍ전파",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1998-12-19",
    name: "금융경제시스템연구소",
    purpose: "금융경제연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1998-12-19",
    name: "21세기경제경영전략연구소",
    purpose: "경제경영연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1998-12-28",
    name: "국제경제전략연구원",
    purpose: "중국진출업체 및 개인에게 정보제공, 교육 등을 통해 협조",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1998-12-28",
    name: "전경련 국제경영원",
    purpose: "경영분야에 대한 연구와 선진경영교육기관과의 교류를 통해 경영정보와 경영기법을 기업에게 보급ㆍ전파",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1999-03-03",
    name: "한국경제평론가회",
    purpose: "한국경제평론에 대한 시민단체 등 여러 단체에 대해 객관적인 의견을 모으고 알림",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1987-11-01",
    name: "한국공기업학회",
    purpose: "공기업의 제반과제에 관한 연구조사 및 한국공기업의 발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1999-06-30",
    name: "제주경제개발연구소",
    purpose: "제주경제의 지속적인 개발을 위한 연구ㆍ조사분석을 통해 제주경제의 발전방향을 제시",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1999-07-05",
    name: "서강경제인포럼",
    purpose: "서강대학교 경제학과 동문 구성 및 국내외 경제 동향분석 등 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1999-09-07",
    name: "동남발전연구원",
    purpose: "지역경제발전과 연구를 통한 정책적 대안 제시",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1999-09-10",
    name: "한국세무회계학회",
    purpose: "세무ㆍ회계학 및 관련 학술연구의 진흥",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1999-10-19",
    name: "조세정의를 위한 한국납세자연합회",
    purpose: "납세자의 정당한 권익옹호 및 건전한 납세풍토조성",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1999-12-23",
    name: "한국원가관리협회",
    purpose: "원가계산제도 관련 학술적 연구와 회원상호간의 친목도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2000-02-11",
    name: "한국경영사학회",
    purpose: "경영사에 관련된 핚술연구와 회원상호간의 친목도모 목적",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2000-02-29",
    name: "21세기 경제사회연구소",
    purpose: "주변국이나 국내 경제에 미치는 영향을 과학적이고 실용성있게 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "1991-01-15",
    name: "한국정책분석평가학회",
    purpose: "공공정책분야의 과학적 분석 및 평가에 관한 이론, 모형과 활용방법 등의 연구ㆍ개발 및 관련사업을 추진하여 한국정책과학의 학문적 발전과 실용화에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2000-04-06",
    name: "한국계량경제학회",
    purpose: "계량 및 수리적 방법을 써서 한국의 경제적 발전에 기여하고자 하는 일체의 활동을 고무•지원함으로써 이론•실증 양면에서 그 발전을 촉진",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2000-04-06",
    name: "전북산업경영연구소",
    purpose: "국가의 경제발전과 지역의 산업발전 등을 위한 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2000-04-21",
    name: "디지털경제연구소",
    purpose: "새로운 패러다임의 디지털경제와 경영전략 및 경제정책을 조사ㆍ연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2000-04-24",
    name: "정부정책연구원",
    purpose: "경제, 공공기관 정책 등정부정책 일반 및 지방자치단체의 지역계획, 교통계획, 물류, 도로, 주택, 대기, 환경정책 등에 대한 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2000-05-17",
    name: "한중경제포럼",
    purpose: "한중경제교류 증진",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2000-06-17",
    name: "한국국제경제학회",
    purpose: "국제경제학의 학술연구 활동증진 및 학문발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2000-07-03",
    name: "글로벌전략연구원",
    purpose: "21세기 경제성장을 선도할 신산업 및 신기술과 관련된 전략을 연구함",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2000-11-16",
    name: "코리아경제개발연구원",
    purpose: "산업경제 학술연구, 연구자료집 단행본 발간등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2000-12-28",
    name: "새시대전략연구소",
    purpose: "정책개발 등 새로운 정치문화를 이룩하기 위한 출판, 교육, 협력 지원사업",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2001-01-03",
    name: "한국재경연구원",
    purpose: "지역과 국가의 경제사회 발전을 위하여 기업경영의 효율적인 운영을 위한 종합경제정책방향연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2001-01-19",
    name: "한국개발전략연구소",
    purpose: "개도국 및 후진국에 개발전략 전수",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2001-07-28",
    name: "한국경제사회발전연구원",
    purpose: "국가 및 지방자치단체 공기업 연구용역, 기업경영분석 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2001-10-18",
    name: "동남경제연구원",
    purpose: "부산, 경남 및 울산을 포함한 동남아 경제권 경제산업, 도시경영, 해양수산분야 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2001-10-23",
    name: "한국원가공학회",
    purpose: "원가계산제도 관련 학술적 연구와 회원상호간의 친목도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2001-12-26",
    name: "한국국제경영학회",
    purpose: "국제경영학 발전을 위한 학술교류와 친목도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2002-01-16",
    name: "엽연초생산안정화재단",
    purpose: "연초경작자의 영농기술 개발사업",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2002-01-31",
    name: "국제경쟁력 연구원",
    purpose: "세계 각국의 기업산업 국가차원에 국제경쟁력에 관한 조사ㆍ연구사업",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2002-03-19",
    name: "서울파이낸셜포럼",
    purpose: "한국을 동북아 금융중심으로 만들기 위한 정책개발 및 제안, 한국금융산업의 국제경쟁력 강화방안연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2002-04-24",
    name: "한국발전연구원",
    purpose: "한국지역사회 경제발전에 관련된 제 문제를 종합적이고 체계적으로 조사 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2002-05-06",
    name: "한국재정학회",
    purpose: "재정학, 공공경제학과 이와 관련되는 연구발표, 계몽 및 회원상호간의 친목과 학문 발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2002-05-13",
    name: "21c국민경제연구소",
    purpose: "21세기 급변하는 경제산업 사회에 효과적으로 대체하기 위한 정부지방자체단체의 올바른 정책방향을 제시",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2002-07-02",
    name: "한국세법학회",
    purpose: "조세법 분야 연구를 통해 우리나라 조세법ㆍ조세제도 및 행정의 발전 도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2002-09-02",
    name: "국제자유도시포럼",
    purpose: "국가의 미래전략사업인 국제자유도시의 성공적인 실행을 위하여 민간차원에서 지원",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2002-09-02",
    name: "지역발전포럼",
    purpose: "지역경제 및 지역발전에 관한 현안문제에 대한 학제간 연구와 정책개발을 목적으로 함",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2002-12-27",
    name: "한국제도경제학회",
    purpose: "거시적 경제·제도 발전과 정책개발을 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2003-01-10",
    name: "한국공공자치연구원",
    purpose: "격변하는 시대에 새로운 패러다임의 창출 및 국가와 공공기관, 지방자치단체와 주민들에게 국민복리의 실현을 위한 연구수행",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2003-01-17",
    name: "경제문화포럼",
    purpose: "우리 경제의 성장잠재력을 정확히 분석하고, 이에 바탕을 둔 성장모델 등을 정부, 업계 및 국민에게 제시코자 함",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2003-02-06",
    name: "한국평가연구원",
    purpose: "평가 관련 연구에 대한 체계화 및 이론적인 틀을 마련 및 보급하여 평가에 대한 인식 수준 및 대외적인 신용도를 높이고 궁극적으로는 국가 경제 전반의 긍정적 파급효과를 도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2003-04-07",
    name: "한국하이에크소사이어티",
    purpose: "자유시장경제의 창달과 함께 정치, 교육, 언론, 복지 등 한국사회의 모든 부문에서 자유주의의 풍토를 조성",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2003-04-28",
    name: "예우회",
    purpose: "기획예산처 친목도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2003-05-09",
    name: "미래정경연구소",
    purpose: "자본주의 세계경제와 국제정세의 역학관계에 대한 거시경제적 연구분석을 통해 발전적 경제정책 수립과 대외경쟁력 강화에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2003-05-09",
    name: "동북아전략연구원",
    purpose: "국가역량강화를 바탕으로 동북아 중심국가로 발돋음하기 위한 정치ㆍ경제적, 사회ㆍ문화적 전략을 수립하고 이에 필요한 개혁과제를 도출ㆍ실현을 위한 정책대안 개발",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2003-08-06",
    name: "21세기 여성연합CEO연합",
    purpose: "바람직한 여성경영인 체제의 발전을 도모하며, 선진적 자유경제활동 추구를 지원함으로써 국가의 동북아경제중심으로 도약에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2003-08-18",
    name: "21세기나라비전연구소",
    purpose: "국가경쟁력, 산업 및 기업경쟁력 제고방안, 신성장산업 등에 대한 연구 및 새로운 국제질서에 조응하는 법ㆍ제도ㆍ문화적 체제연구 등 21세기 일류국가건설에 이바지",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2003-09-01",
    name: "동아시아금융통화협력연구회",
    purpose: "동아시아 국가의 통화협력관계  및 발전방향 모색",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2003-10-31",
    name: "아시아경제연구원",
    purpose: "21세기 지식경영시대를 대비하여 한국경제의 발전을 위한 자료수집과 학술연구, 각종 학술회의 등의 활동",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2004-02-11",
    name: "국가비전연구소",
    purpose: "21세기 새롱운 국제질서에 부응하는 국가비전과 전략을 제시하고 국가경영을 효율적으로 지원",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2004-04-16",
    name: "한국조세연구포럼",
    purpose: "사회ㆍ경제환경 변화에 맞는 적절한 조세제도 발전방향연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2004-06-18",
    name: "한국경영경제개발원",
    purpose: "국가거시경제지역발전과 기업 및 공기업 등의 경영문제 극복을 위한 이론개발과 장기발전방향 제시 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2004-07-23",
    name: "경제사학회",
    purpose: "경제사 및 그와 관련된 경제이론과 정책, 제도 등을 연구발표",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2004-10-01",
    name: "한국경제연구학회",
    purpose: "한국경제와 관련된 경제이론과 정책, 제도 등을 연구발표",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2004-10-06",
    name: "JA Korea",
    purpose: "청소년들이 시장경제에 대한 기초적인 지식을 습득하고, 다양한 직업교육과 기업경영에 대한 올바른 이해 함양",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2004-12-31",
    name: "한국경제법학회",
    purpose: "경제법에 관한 조사, 연구와 회원상호간 친목도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2005-03-10",
    name: "오피니언 리더스클럽",
    purpose: "시장경제의 제기능에 대한 올바른 이해 및 경제 현안문제에 대한 해결방안 모색",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2005-04-25",
    name: "한국미래경영연구원",
    purpose: "국가경제정책 및 기업경영에 대한 다각적인 분야를 조사하여 고도로 변화된 국제회에 신속한 대응",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2005-05-13",
    name: "한국소비자안전학회",
    purpose: "PL이론 및 실무에 대한 연구 및 학술발표회, 학회지 발간 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2005-06-07",
    name: "유엔미래포럼",
    purpose: "한국경제 미래산업 파악, 국가미래 성장동력산업 발굴과 활성화를 위한 조사 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2005-06-10",
    name: "시장경제제도연구소",
    purpose: "경제제도 연구를 통해 시장경제를 활성화",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2005-06-14",
    name: "세계경제사회연구원",
    purpose: "국내외 경제정책연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2005-08-31",
    name: "한국정부조달연구원",
    purpose: "선진미래경제진입에 있어서 정부조달의 역할 고찰 및 각종연구사업진행",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2005-11-09",
    name: "공공기관경영연구원",
    purpose: "국가, 지자체, 공공기관의 거버넌스 체계, 경영기법, 관련 제도 등에 대한 연구를 통해 공공기관의 경영체계 효율화에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2005-11-23",
    name: "KCEE(한국청소년경제교육원)",
    purpose: "청소년 및 국민들의 신용교육을 통한 신용경제생활 영위",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2005-12-26",
    name: "한국 EVM학회",
    purpose: "국방 부문 사업성과관리 연구 단체",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2005-12-29",
    name: "한강서사이어티",
    purpose: "한국의 경제성장,국제협력 증진 및 통일과 경제공동체건설등 국가적과제 실현",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2006-01-19",
    name: "한국여성경제학회",
    purpose: "경제학 이론ㆍ실증연구를 성별경제학적 시각으로 조명하여 경제학 발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2006-03-17",
    name: "한국경제통상학회",
    purpose: "경제통상 분야의 연구활동을 통하여 국가 및 지역 경제발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2006-04-05",
    name: "한국세무학회",
    purpose: "세무학의 발전 이바지를 목적",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2006-04-18",
    name: "한국정책기획평가원",
    purpose: "재정경제정책등 전문지식개발 보급과 교육훈련",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2006-06-26",
    name: "한국경제교육학회",
    purpose: "경제교육 관련 연구 및 발표, 교육자료, 연구보고서,학회지등 출판물 간행 및 보고",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2006-07-27",
    name: "한독경상학회",
    purpose: "독일어권 교류 통한 한국에서의 경제발전",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2006-10-09",
    name: "좋은정책포럼",
    purpose: "지속가능한 진보를 지향하는 한국사회 선진화의 이념적 방향제세",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2006-12-15",
    name: "21세기산업연구소",
    purpose: "국가경제 균형발전과 기업의 국제경쟁력을 제고시켜 국민경제발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2006-12-15",
    name: "The NEAR Faundation",
    purpose: "동북아의 현안에 대한 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2006-12-27",
    name: "전남경제발전연구원",
    purpose: "종합경제대책등의 연구를 통해 지역 경제발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2007-01-11",
    name: "국제무역투자연구원",
    purpose: "국제무역 투자연구개발 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2007-02-15",
    name: "한국평가감사연구원",
    purpose: "국내외 공공및 민간부분의 평가및 감사관련 사례연구를 통한 이론화 작업 등 재반연구와 컨설팅 그리고 평가활동 수행",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2007-03-06",
    name: "한중조세실무연구원",
    purpose: "한중 조세실무자의 교류를 통한 양국의 경제발전",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2007-03-16",
    name: "한국조세연구회",
    purpose: "조세제도제정과 집행상 문제해결을 위한 학술연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2007-04-18",
    name: "서비스사이언스전국포럼",
    purpose: "서비스사이언스 관련 연구 및 서비스산업발전을 촉진하기 위한 산학협동",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2007-05-25",
    name: "서민경제연구소 정의와땀",
    purpose: "국민경제의 민주화를 통한 서민경제발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2007-06-19",
    name: "국가미래정책포럼",
    purpose: "정책적 시사점과 파급효과가 큰 국내외 미래예측 관련 연구, 동향 및 이슈분석",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2007-09-21",
    name: "한국경영경제문제연구원",
    purpose: "국내외 산업활동 및 경영경제환경을 조사하고 중장기 경제  및 변화 예측분석하여 그 결과를 제공",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2007-10-09",
    name: "한국경제발전학회",
    purpose: "한국경제 연구발표, 학회지 및 기타 간행물 발간",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2007-10-19",
    name: "국제한인경제총연합",
    purpose: "국내 지방자치단체 및 기업과 해외교포 기업 및 교포 실업인들간의 투자 등 경제교류 증진위해 글로벌 비즈니스 데이터베이스 구축 및 각 국가별 교포기업 동향 분석, 국내외 비즈니스 교류, 세계 경제인대회 개최를 목적으로 설립",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2007-11-19",
    name: "국제금융센터",
    purpose: "국제금융시장과 세계경제의 흐름을 밀착 감시하여 외환위기 사전예방",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2008-02-18",
    name: "통섭정경연구원",
    purpose: "국민경제 진흥을 위하여 경제정책, 금융정책 등을 개발하기 위한 연구활동",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2008-04-21",
    name: "선진국민정책연구원",
    purpose: "국가 선진화와 관련 제분야의 자료수집,조사,연구, 홍보 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2008-05-30",
    name: "경제추격연구소",
    purpose: "국민경제 및 기업성장에 관한 연구로 인류복지 증대 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2008-09-11",
    name: "한국재정정책학회",
    purpose: "재정정책과 관련된 연구, 조사와 발표 및 보급으로 학술 및 사회발전에 기여하고 회원 상호간의 유대 도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2008-09-19",
    name: "기후변화ㆍ에너지대책포럼",
    purpose: "ㅇ 지구온난화 방지를 위한 온실가스 의무감축에 직면한 대한민국이 향후 지속가능한 경제성장을 이룩하는데 필요한 정책개발 및 연구 수행ㅇ 정책대안 제시를 통해 저탄소 녹색성장 국가건설에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2008-09-19",
    name: "노회찬마들경제연구소",
    purpose: "지역경제발전 이론과 정책 등을 연구하여 국민경제발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2008-11-18",
    name: "국민통합포럼",
    purpose: "국민대통합을 통한 국가경제발전과 선진한국건설에 이바지",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2008-11-25",
    name: "한국선진화정책학회",
    purpose: "한국사회의 선진화를 위한 비전과 정책 연구 보급",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2009-04-27",
    name: "세계미래포럼",
    purpose: "미래선진사회를 구현하기 위한 미래지향적 사회를 조성하고 이를 통해 변화와 개혁의 토양을 배양함",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2009-06-09",
    name: "바른아카데미",
    purpose: "시장경제교육",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2009-07-24",
    name: "한국납세연맹",
    purpose: "국가 또는 지방자체단체 및 공공기관에서 부과하는 불합리한 조세로부터 상대적 약자인 납세자의 권익을 보호",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2009-08-03",
    name: "한국국제금융학회",
    purpose: "국제금융동향 파악",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2009-08-21",
    name: "한국한미경제학회",
    purpose: "한미경제학회의 소속학회, 국내의 학회, 연구기관과의 경제학 학문교류",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2009-10-20",
    name: "국제경제연구소",
    purpose: "국제경제 주요현안 및 통상의제에 관한 연구와 그 보급을 통해 국가경제 발전에 기여함을 목적으로 함",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2009-11-13",
    name: "선진사회만들기연대",
    purpose: "우리사회의 경제사회관련 과제와 제도에 대한 정책대안과 비전 제시하고 제도개선 및 자유시장경제질서확립 복지사회구현에 이바지",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2010-01-14",
    name: "글로벌경영전략연구원",
    purpose: "글로벌 경제 경영에 관한 연구와 그 보급을 통해 기업의 성장과 국가경제의 발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2010-03-09",
    name: "한국정책개발연구원",
    purpose: "국내외 경제동향분석 및 심층경제분석을 통한 장단기발전전략 및 정책수립",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2010-03-17",
    name: "다산경제연구원",
    purpose: "경제 관련 이론과 정책의 연구 및 개발각종 사업 및 투자에 대한 평가와 경제예측각종 제도 및 여건의 개선 등에 관한 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2010-03-17",
    name: "세종연구원",
    purpose: "녹색성장, 일자리 창출, 물가 및 부동산 시장 안정 등 국가경제발전을 위한 각종 경제정책의 분석 및 평가",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2010-05-01",
    name: "한국금융소비자학회",
    purpose: "금융소비자에 대한 학제적 연구를 통하여 금융소비자연구,보호,투명하고 공정한 금융시장과 금융행정의 발전을 도모",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2010-06-01",
    name: "한국비용편익분석연구원",
    purpose: "공공 및 민간투자사업의 경제성 분석과 관련된 국내외 비용편익 분석이론과 그 적용방법등을 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2010-07-29",
    name: "경영사연구소",
    purpose: "ㅇ 경영사, 기업사, 기업가사 연구 맟 경영 및 기업발전에 필요한 각종 조사 연구 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2010-11-01",
    name: "홍익경제연구소",
    purpose: "ㅇ국내외 경제동향분석 및 경제분석을 통한  장단기발전전략 및 정책수립.ㅇ최근 경제관련 분석 및 정보, 자료집,   연구 보고서 발간ㅇ경제분야 학술회의 및 연구개발",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2010-11-26",
    name: "한국재정법학회",
    purpose: "ㅇ국내외 재정법학 및 관련 법제의 학술적 연구와 조사 및 교육ㅇ국내외 연구발표회 및 강연회의 개최 및 참여ㅇ학회지 기타 간행물의 발간ㅇ학회의 목적을 같이 하는 국내외 여러 단체와의 교류ㅇ기타 학회의 목적달성에 필요한 사업",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2010-12-05",
    name: "한국서비스산업연구원",
    purpose: "ㅇ서비스산업 관련 연구용역, 전문적 자문,  교육훈련 및 이에 수반된 사업의 수행ㅇ산학협동 및 국내외 제 연구원과의 학술교류",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2011-01-14",
    name: "국가미래연구원",
    purpose: "ㅇ 국가발전을 위한 제 분야의 조사연구, 개선방안, 정책대안 및 법과 제도개선 연구, 용역 수탁사업, 자문사업ㅇ 연구토론회, 심포지엄 및 국제학술대회 개최, 출판 및 홍보ㅇ 기타 설립목적에 부합되는 사업",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2011-04-26",
    name: "한국이란경제인협회",
    purpose: "ㅇ 한-이란간 경제인 교류를 통해 양국간 문화, 경제 등 제분야에서의 화합과 경제발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2011-08-09",
    name: "글로벌경제재정연구원(GEFRI)",
    purpose: "ㅇ실물경제정보를 수집, 조사하여 미래지향적인 경제경영전략 수립",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2012-01-17",
    name: "이태석사랑나눔",
    purpose: "ㅇ故 이태석 신부의 사랑과 섬김의 정신을   대한민국과 세계에 널리 확산",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2012-01-25",
    name: "한국지속성장연구원",
    purpose: "ㅇ시장경제의 발전 등 나라경제의 지속성장을 위한 경제전략 연구ㅇ중소기업 지원, 지역경제 활성화, 개발도상국 경제개발 지원 정책연구ㅇ상기 관련 학술회의ㆍ토론회 개최ㆍ경제교육 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2012-03-20",
    name: "한국개발정책학회",
    purpose: "ㅇ국제개발협력분야의 학술연구, 전략마련, 정책개발 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2012-06-08",
    name: "한국국유부동산연구원",
    purpose: "사회 일반의 이익 공여를 위해 국유 부동산과 관련된 제 분야의 현상을 조사,연구,분석",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2012-11-13",
    name: "서비스산업총연합회",
    purpose: "서비스산업 활성화와 서비스기업의 발전을 위한 제반 활동을 수행함으로써 선진서비스국가를 구현하는데 이바지함을 목적으로 한다.",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2013-01-04",
    name: "사회적책임경영품질원",
    purpose: "조직의 지속가능한 성장을 위하여 사회적책임, 지속가능경영, 경영품질 등을 연구ㆍ보급하고 그 실천방안의 제시를 통하여 국가ㆍ사회발전에 공헌함",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2013-01-10",
    name: "사단법인 청계경제정책연구소",
    purpose: "한국과 세계 각국의 경제정책에 대한 연구와 조사",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2013-01-29",
    name: "선진경제통상연구소",
    purpose: "국내외 경제발전, 기업경영 및 자유무역협정(FTA) 관련 통상 문제를 공동으로 연구ㆍ발표함으로써 관련 학문 발전과 국가경제 발전에 기여함을 목적으로 함",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2013-04-19",
    name: "포럼 메가체인지",
    purpose: "○ 미래예측 전문가들간 상호교류와 공동연구○ 전문가 초청 강연, 국내외 민ㆍ관 세미나, 토론회 개최○ 미래대응 준비를 위한 정책건의 및 각종 교육프로그램 운용○ 설립목적 수행을 위한 용역활동과 각종 자문활동○ 미래예측에 대한 연구내용의 발간ㆍ배포 및 판매",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2013-07-18",
    name: "한국납세자권익연대",
    purpose: "ㅇ 조세 관련 권리구제절차 등 안내 상담ㆍ교육 실시ㅇ 납세자 권익보호를 위한 권리구제 지원 활동ㅇ 조세제도에 관한 토론회 개최ㅇ 조세제도 개선의견 제시 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2013-08-19",
    name: "국제개발협력실행연구원",
    purpose: "공적개발원조 및 북한지원 분야의 학술연구, 포럼활동, 정책제안",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2013-08-30",
    name: "포럼 오래",
    purpose: "경제∙재정전략 수립에 관한 학술연구, 교육훈련 및 정책개발 활동을 통하여 사회에 이바지함과 동시에 국가의 미래를 위한 정책 아젠다를 설정하고 개방적 네트워킹의 확산을 통한 집단지성을 구성하여 차세대 지도자의 양성과 한국과 국제사회의 공동번영을 촉진하는 데 이바지",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2013-09-03",
    name: "한반도개발협력연구소",
    purpose: "ㅇ (설립목적) 남북한간 산업, 금융, SOC, 경제특구 등을 중심으로 경제협력 및 통합방안 연구 ㅇ (주요사업) 남북경협 및 경제통합 관련 조사연구 및 정책개발, 교육ㆍ간행물 발간ㆍ학술교류 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2013-10-25",
    name: "한·미얀마 연구회",
    purpose: "미얀마 경제·사회·문화와 관련된 학술연구, 국내외 정부·산업·학계·연구기관과의 협력사업 등을 통한 한-미얀마 협력관계 증진",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2013-11-",
    name: "바른협동조합",
    purpose: "ㅇ 협동조합에 대한 올바른 이해와 실천을 위한 기본지식전파 및 지속가능한 바른 협동조합을 위한 설립 지원ㅇ 협동조합 발전을 위한 지도자 양성 및 협동조합간 네트워크 구축으로 통하여 지역, 사회, 경제 발전에 밑거름이 되는 협동조합 육성",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2013-12-16",
    name: "경제사회포럼",
    purpose: "국내외 경제사회 분야를 종합적으로 조사․연구하며, 전문가포럼을 통하여 국가 경제사회 발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2014-04-09",
    name: "글로벌공공개발연구원",
    purpose: "경제발전경험 공유사업 분야의 조사, 연구, 사업수행 등-한국경제개발 경험과 지식의 개도국 공유, 개도국 공무원 초청 연수, 특정분야에 대한 리서치 용역, OECD/DAC 수원국 현황 연구 등 공공자료의 발간",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2014-05-07",
    name: "국가경영연구원",
    purpose: "○ 재정사업의 일반평가, 심층평가 및 예비타당성 등 평가 연구 ○ 공공부문과 사회적 부문 예산의 효율성 관리와 성과제고를 위한 지표개발 및 발전방향 연구○ 정부, 지방자치단체 등 공공부문의 혁신과 생산성 향상을 위한 연구○ 국내외 주요 지역과 산업ㆍ정책 등의 동향정보를 조사ㆍ수집 및 분석ㆍ보급 활동 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2014-07-14",
    name: "우리들의 미래",
    purpose: "기후변화, 인구변동, 남북통일 분야의 학술 및 사회활동",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2014-09-02",
    name: "한국미래전략학회",
    purpose: "미래예측, 미래준비, 미래전략",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2014-10-21",
    name: "한국원가분석사회",
    purpose: "원가분석사 회원관리 및 원가검토분야 학술연구등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2014-10-27",
    name: "핵심기업 경제인 연합회",
    purpose: "핵심기업의 신성장 전략연구 및 기업 간 협업과 소통으로 새로운 협력문화를 제시, 포럼운영 및  간행물 사업, 심포지엄 운영 등 실시",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2014-12-26",
    name: "북한개발연구소",
    purpose: "북한 미시지역에 대한 공간정보자료 수집 및 작성,북한지역별 투자전략 수립 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2015-01-02",
    name: "경제사회공유가치창출연구원",
    purpose: "공유가치창출을 통한 따뜻한 경제사회를 만드는데 일조하며, 국가 및 기업의 경쟁력 향상을 위한 혁신과 성장의 발판을 마련하여 국가경제발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2015-01-07",
    name: "한국사업타당성분석협회",
    purpose: "국가재원 및 거시경제관련 사업타당성을 분석·연구하는 기관 및 개인회원의 협의체",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2015-04-16",
    name: "(사)대한민국지혜자산화재단",
    purpose: "인적자원 개발을 위한 지혜스토리 채집 및 가공, 교육전수와 관련되는 연구개발활동",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2002-05-06",
    name: "한국재정학회",
    purpose: "재정학, 공공경제학과 이와 관련되는 연구발표, 계몽 및 회원상호간의 친목과 학문 발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2015-05-27",
    name: "한국민간투자학회",
    purpose: "한국 민간투자사업과 관련한 학문과 민간투자제도 발전에 기여함을 목적으로 함",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2015-05-29",
    name: "아시아금융학회(Asia Finance Society)",
    purpose: "아시아 역내 금융질서, 통화정책, 금융시장구조에 대한 연구, 역내 금융전문가들간 네트워크 형성",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2015-06-02",
    name: "한국조세사학회",
    purpose: "조세관련 연구발표, 학회지(조세사학 연구) 및 기타 출판물의 간행, 국내외 학술단체와의 교류",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2015-06-08",
    name: "(사)지역사회적경제허브센터",
    purpose: "세미나개최, 협동조합 전문가 포럼, 사회적경제조직의 컨설팅 업무 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2015-09-18",
    name: "에이스텝연구소(A-Step Institute)",
    purpose: "경제정책, ODA사업 관련 연구자문 및 제안",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2016-03-17",
    name: "한국전자세제협회",
    purpose: "전자상거래와 관련된 조세제도 연구를 통한 조세발전 모도",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2016-05-18",
    name: "지평인문사회연구소",
    purpose: "거시경제, 금융 등 경제분야 및 이에 수반되는인문분야의 연구, 출판 사업 지원을 통해우리 경제사회의 미래를 설계",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2016-05-26",
    name: "경제위기관리연구소",
    purpose: "세계경제위기 및 한국경제위기에 대응할 정책을 연구하며,과거의 경제위기 사례와 위기극복 정책의 수집․정리 및 산․학․연․관간의 경제위기 극복정책에 관한 통합적인 정책 연구, 개발, 교육, 컨설팅 등을 통해 우리 경제와 산업, 기업의 국제경쟁력 제고에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2016-06-03",
    name: "미래경제교육네트워크",
    purpose: "KB국민은행 출신 퇴직자를 활용하여 경제교육사업을 수행",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2016-06-14",
    name: "미래학회",
    purpose: "미래변화 및 미래전략 등에 관한 학술 및 연구활동",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2017-04-18",
    name: "한국건설관리연구원",
    purpose: "국가계약제도 연구 등을 통해 국가의 재정건전성 도모와 공공분야 조달제도 선진화에 이바지",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2017-08-22",
    name: "공공기관사회책임연구원",
    purpose: "공공기관의 사회책임 활동 및 지역밀착형 공헌활동 활성화",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2018.1.26",
    name: "한국공유경제진흥원",
    purpose: "연구개발 및 유관단체와의 교류, 민간의 공유 인프라 구축지원, 학술세미나 개최 및 전문서적 발간, 전문인력 양성 지원등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2018.03.06",
    name: "경제금융협력연구위원회",
    purpose: "한국 경제의 주요 현안 및 산업분석, 세계경제동향을 통해 제도 및 법령 개선,발전을 위한 연구 및 논의",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2018.03.30",
    name: "한국조세정책학회",
    purpose: "조세정책, 조세법, 세무회계 등 이론과 실무에 관련한 조사, 연구발표회, 강연회 및 학술 관련회의 개최, 회보, 논문집 및 연구서적의 간행 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2018.10.11",
    name: "미제스와이어",
    purpose: "미국 미제스연구소의 글들의 한글 번역 등을 통해 자유의 정신을 고취시켜 대한민국의 평화에 이바지",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2018.12.16",
    name: "한국환급창구운영사업자협회",
    purpose: "내국세 환급 관련 산업의 활성화를 위한 의견수렴 및 정부건의, 환급창구운영사업자 간 공정경쟁 환경조성 및 자율규제, 회원사간 협력증진을 위한 기금조정 및 운영, 내국세 환급 및 산업 관련 국내,외 학술행사 및 홍보활동",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2019.01.22",
    name: "한국공유경제협회",
    purpose: "공유경제의 의미･중요성에 대한 사회적 이해와 공감대 확산, 공유경제 활성화 생태계 조성 기여 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2019.01.24",
    name: "아프리카-한국경제개발협회",
    purpose: "아프리카 각국의 지역개발을 위한 정보 수집 및 공유, 아프리카 각국의 사회 인프라사업에 대한 세미나 개최, 아프리카 회원국과 국내일반 회원의 친목 모임 주선",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2019.04.09",
    name: "한국융합복지연구원",
    purpose: "생애주기별 사회복지, 경제정책의 연구 및 관련 교육, 세미나 개최, 수면 가계자산의 유동화, 유휴노동력의 사회가치적 활용 등 지속가능한 시장 친화적 복지시스템 개발연구 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2019.08.09",
    name: "한국협동조합학회",
    purpose: "협동조합에 관한 이론과 실제를 연구하고, 서로의 경험과 지식을 교류함으로서, 협동조합의 발전에 기여하고 회원 상호간의 협력을 도모함",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2019.10.22",
    name: "임팩트얼라이언스",
    purpose: "󰋻법인의 목적 및 사업이 소셜 임팩트 창출 생태계 조성, 임팩트 지향조직 지원 등에 관한 것으로 구체적으로 제시󰋻사업계획상 사업내용 및 방법, 사업추진기간 등이 명확하고 실현가능",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2019.12.03",
    name: "유쾌한반란",
    purpose: "학술·연구 활동 등을 통한 회원 상호간의 협력증진과 소외계층 지원, 봉사 등을 통한 사회적 자본 축적에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2019.12.05",
    name: "경제교육단체협의회",
    purpose: "경제교육기관 간 네트워크 구축과 경제교육 협력 및 지원사업",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2020.5.27",
    name: "포용사회연구소",
    purpose: "포용성장을 위한 사회 안전망 개선 방안 논의, 복지 사각지대 개선 및 불평등, 양극화 해소가 경제성장에 미치는 영향 연구",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2020.6.29",
    name: "사회적가치경영연구원",
    purpose: "국내 사회적경제 및 비영리 조직의 경영역량평가 및 역량강화 사업, 전문가 양성사업, 출파나 및 정책개발 사업",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2020.8.24",
    name: "연구그룹미래세상",
    purpose: "사회,경제,문화,생태,기술 등 환경변화에 대응하여 국가 미래상을 예측하고 발전 전략을 제시, 사회의 상생과 발전에 기여",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2020.9.2",
    name: "한국사회적경제연대회의",
    purpose: "사회적 경제 조직간 협동과 연대를 통해 사회적 경제 영역을 확대하고, 업종, 지역 간 네트워크 구축 및 활성화 지원",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
  ExcelRowData(
    permitDate: "2020.12.28",
    name: "지속경제사회개발원",
    purpose: "지속가능한 경제, 사회의 발전 전략연구, UN 지속가능한 발전 목표관련 글로벌 정보 분석, 사회적 경제 활성화를 위한 과제 발굴, 책임 투자 및 ESG확산을 위한 사회활동, 퍼용 사회 실현을 위한 사회 활동 등",
    law: "-",
    type: "-",
    remit: "재정경제부",
  ),
];
