import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> mowRawData = [
  ExcelRowData(
    permitDate: "-",
    name: "민족통일협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민족문화통일회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "일천만이산가족위원회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화문제연구소",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민주통일촉진회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한연구소",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족세계선교원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민족통일복음화운동본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한우리문화원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족통일여성협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "세계한민족평화통일협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "미래정책연구소(구, 통일시대연구소)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "다물민족연구소",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "아시아사회과학연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국청년정책연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북문화교류협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민족통일문화재단(구, 민족통일선교협회(구,민족통일희년운동협회))",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북민간교류협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민족통일불교협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북나눔",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일경제연구협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국사회문화연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "글로벌블레싱(구, 민족통일에스라운동협의회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족통일촉진협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국사회통일연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국통일진흥원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한겨레통일문화재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "미래약속포럼(舊 21세기통일경제연구원)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한인권시민연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "선진통일건국연합(구, 통일건국민족회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "우리민족서로돕기운동",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북코리아 미술교류협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "21세기국가발전연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한백정신중흥회(구, 국민정신중흥회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "온갓네트워크(구, 대한기독교자유연맹)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대한민국팔각회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족통일운동지도자연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국불교자유총연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "어린이어깨동무",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국미래연구학회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국청년지도자연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민족화해협력범국민협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화와 통일을 위한 복지기금재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화를만드는여성회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민족화합운동연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "코리아하나재단(구, 민족문화교류재단, 남북강원도문화교류재단)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북방문제연구소",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "세계평화여성연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "탈북자동지회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일맞이",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화통일복지협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북경제협력발전협의회(구, 남북농업발전협력민간연대)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "좋은벗들",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북체육연구학회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민족통일연합중앙회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "세계평화청년학생연합(구, 세계평화청년연합)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민족통일촉진회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국통일교육연구회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화통일불교협회(구, 조국평화통일불교협회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "21세기남북문화연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한민주화네트워크",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "범민족화합통일운동본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북사랑나누기협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "겨레하나되기운동연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북강원도협력협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족한마음운동본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북통일운동국민연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북청소년중앙연맹",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북협력제주도민운동",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일교육협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "미래전략연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민족통일체육연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "새롭고하나된조국을위한 모임",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화운동연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일문화연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "6.25전쟁납북인사가족협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "어린이의약품지원본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "피스코리아 국민통합비전(구, 백범정신실천겨레연합, 피스코리아)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북통일운동본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "서울평양학회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "범민족동질성회복촉진회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화통일시민연대",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "동북아한민족협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화통일탈북인연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "코리아통합연구원(구, 통일미래사회연구소)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화디딤돌(구, 남북문화통합교육원)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "좋은씨앗(하늘꿈학교)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민주주의정치철학연구소",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일농수산정책연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "두리하나",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "엔케이워치(구, 북한민주화운동본부)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북청소년통일교육진흥원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민간남북경제교류협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "전남남북교류평화센터(구, 전남남북교류협의회(구구, 전남도민남북교류협의회))",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한인권정보센터",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "겨레하나(구, 우리겨레하나되기운동본부)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한사회문화학회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "등대복지회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화통일단체총연합(구, 남북청소년교류평화연대)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한마음재단(舊 한마음평화연구재단)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "나눔인터내셔날",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화삼천",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일문화예술인협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북역사학자협의회(구, 남북학술교류협회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "엔케이인포메이션센타",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "구손평화봉사단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북경제문화협력재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화협력원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한백정보문화연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "국제사랑재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일교육문화원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도평화를추구하는모임",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "겨레사랑복지협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북함께살기운동",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일농수산사업단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "동학민족통일회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "여명",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "새로운코리아구상을위한연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "아리랑공동체",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "연구소2020통일한국",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국통일여성협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화예술재단(구, 평화미술협회(구구, 평화통일미술협회))",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북경제연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "기쁜소식",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국정신문화복지재단(구, 한국불교청년복지재단)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민족사랑나눔",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "늦봄 평화교육사업회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족평화재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "위드아시아(구, 참여불교운동본부)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일을준비하는탈북자협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일시대청소년연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국통일협회(구, 통일동우회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "월드브레드(구, 북녘어린이사랑)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "겨레말큰사전남북공동편찬사업회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "하나를위한음악재단(구, 남북음악교류재단)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북물류포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일준비네트워크",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북환경교류연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "나라사랑",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "개성공단기업협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "코리아평화봉사회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "조국평화통일협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민족과겨레",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북의료협력재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북체육교류협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화문화재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "숭의동지회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "새로운사회를여는연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "광주광역시남북교류협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족통일포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "우리나라사랑",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "먹고사는문제연구소(구, 동서남북포럼)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "영통포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "하나로민족협력",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "하나누리",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "겨레의숲",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북교류협력지원협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북생명살림협력단(구, 남북환경농업협력단)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사랑담는사람들",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일아카데미(구, 열린북한)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북기술교육협력본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북경협국민운동본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일교육개발연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "하나됨을 위한 늘푸른삼천",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북평화재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일연합종교포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "금수강산가꾸기협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "나눔과평화재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "코리아컨센서스연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "세계결핵제로운동본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "동북아공동체문화재단(구, 동북아공동체연구재단(구구, 동북아공동체연구회))",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "해피투게더",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화통일화해연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도평화연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "개성공업지구지원재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북지역균형발전협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "우리누리평화운동(구, 새우리누리평화운동)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "겨레살림공동체(구, 한민족평화모임선교원)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "참된평화를만드는사람들",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화민족문화연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한전략센터",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북농림수산물사업협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "세계평화교류연구소",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도평화경제연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북누리나눔",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "부산YWCA 새터민지원센터",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "에이스경암",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북통일미래세대교류협의회(구, 북한어린이돕기국민운동협의회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "NK지식인연대",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국기독교탈북민정착지원협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화한국",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "새터민회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족사랑네트워크",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북장애인교류협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "선한의료인들",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "우리탈북민정착기구",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일미디어(구, 남북언론연구회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "동북아평화경제연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "자유통일문화원(구, 북한전통음식문화연구원)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "미래나눔(구, 미래나눔재단)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "코리아미래재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국자유연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "기독교북한선교회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도미래재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한꿈",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한자원연구소",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "홍익(구, 통일녹색재단)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화교류협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "길동무(구, 남북장애인협력사업단)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "코리아정책연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "성공적인통일을만들어가는사람들",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "나이스피플(구, 새누리좋은사람들)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도통일연합회(구, 하나여성회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북교육개발원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한민주화위원회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "우리민족",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화통일국민포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대한불교조계종 민족공동체추진본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "새문화복지연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "세이브엔케이",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족문화복지진흥원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "세계북한연구센터",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민족사랑협회(구, 코리아DMZ협의회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "전시납북국회의원유족회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "전국대학통일문제연구소협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "행복한통일로",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "탈북동포사회복지센터",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일전략연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한전략정보서비스센터",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국평화연구학회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북사회통합연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "유니코문화교류협회(구, 북한이탈주민비전네트워크)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "임진강",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대한민국 ROTC통일정신문화원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "GK전략연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "아시아태평양공동체",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한이탈주민사랑협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화통일무지개운동협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한우리",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한발전연구원(구, 북한개혁연구원)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도체육협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "자유북한운동연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한이탈주민자립지원협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "함께일하는사람들",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "탈북여성지원 지에프에스 우물가",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "드림",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화를일구는사람들",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "우리들의성장이야기",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족밀알공동체",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한마음통일사업회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "국제푸른나무(구, 푸른나무)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "겨레얼통일연대",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "느헤미야코리아",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화누리(구, 고양평화누리)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일사랑교육협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "조각보",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "온누리사랑나눔",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도비전과통일",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북이산가족협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "늘푸른",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한연구학회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "물망초",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "겨레사랑",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국글로벌피스재단(구, 한국GPF재단)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "NK체육단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일을생각하는사람들의모임",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국DMZ학회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "모두함께",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북교역연구협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "전후납북자피해가족연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한마음나눔회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "선양하나",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "꿈의통일을현실의통일로의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도발전전략연구원(구, 한우리통일연구원(구구, 한우리통일국가복지연구원))",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도선진화연대",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "모두하나교육회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한인권과민주화실천운동연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "나누며하나되기",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "김상철기념사업회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화열차타고평양가자재단(구, 한민족통일연합회(구구, 탈북동포지원연합))",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한생명살리기운동본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "전북겨레하나",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)북한체제트라우마치유상담센터",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "세계와동북아평화포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "해솔직업사관학교",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도통일연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북문화예술원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "동서남북",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "큰샘",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한이탈주민연합(구, 대경한마음연합)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "하나로복지회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북경제협력포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족예술문화진흥협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "세계태권도평화통일지원재단(구, 민주평화통일지원재단)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "새일",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도평화화해협력포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "세종평화통일포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북경협경제인연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일문화네트워크",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "크로싱",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "선진한국비전연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화코러스재단(구, 통일아동키크기재단(구구, 북한아동키크기재단))",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "시호나눔재단(구, 시호희망나눔, 통일희망나눔재단)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국통일문인협회(구, 한민족평화통일촉진문인협회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족고구마나눔운동본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "새삶",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일안보선진화포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "하나반도의료연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "더함께새희망",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "리멤버위원회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일길벗협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북협력",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일미래연대",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "세계평화공원추진국민연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족평화나눔재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일경모회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "뉴코리아",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "하늘우산",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "비전코리아",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일을위한북한인권운동본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일문화(구, 남북경영경제포럼)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도평화통일재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일나무",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대한민국통일문화창작진흥회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "손과마음(구, 하나울림)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화물연구회(구, 북한물문제연구회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북사랑네트워크",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일과나눔",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일한국세움재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일코리아 건사모(구, 통일코리아)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북보건의료교육재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "우니타스",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "OGKM(one green korea movement 조국을푸르게)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일정책개발연구원(구, 한민족통일문화센터)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "투게더인터네셔널(구, 원코리아선린회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "하나사랑협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "두라인터내셔널",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북방연구회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사랑광주리",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북경제협력협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "더메신저(구, 통일전략연구소)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화통일범국민운동본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국사회교육진흥원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일경제사회연구회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "하나의코리아",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "반석",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "새한누리",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북장애인복지연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국지정학연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북경제협력연구소",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일시대준비위원회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "글로벌만나재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화의 씨앗들",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일법정책연구회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화통일예술인연합회(구, 탈북예술인연합회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "탈북민사랑나눔운동본부(구, 특수임무수행자와 함께하는 탈북민 사랑나눔 운동본부)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화와통일을위한연대",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일미래포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일한국 재정정책 연구소",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화와 함께",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일간호포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "금강산투자기업협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "우리들학교",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "청소년통일문화",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북통합복지협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한겨레평화통일포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "금강산기업협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "민족문화체육연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도평화네트워크",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "생명그루",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도평화만들기",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북교류공동운동본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "늘푸른상담협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "샌드연구소",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도통일역사문화연구소",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "예평글로벌비젼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일문화교류협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "미래를위한사랑나눔협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한길남북교류사업단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "미안해 정말 미안해",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일한국복지협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일의길",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "그린코리아 네트워크",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북역사문화교류협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일대박실천연대",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일지향협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일문제연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북보건협력",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "미래사랑",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화의길",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "우리경제협력기업협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도경제협력원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일과미디어",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사람과사람그리고공유와동행",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "솔샘",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국평화협력연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도개발연합(舊 남북하나개발원)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "유나이티드꼬레아연구소",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도평화관광협회(舊 남북평화관광협의회)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "발휘재",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일한국연구소(구, 동화연구소)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "비욘드더바운더리",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일의 징검다리 우리온",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도평화경제포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도 평화와 번영을 위한 협력",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "다물통일문화재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "우리아이재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도김치발전협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일을이루는사람들",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북생명농업협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "피스브릿지",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "UN한반도평화번영재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "겨레통일문화",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "그날까지동족사랑연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "think",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "미래희망나눔",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한민족평화통일전국연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한울타리통일모임",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한백평화통일재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "함께나누는세상",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북장애인치료지원협의체",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북차문화교류협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일을꿈꾸다",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "플랫폼2032",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "팍스보비스",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "하나되는길",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "세계한반도평화회의",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일시대보건의료포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북협력민간단체협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한백경제협력포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "코리아남북교류연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "공정평화통일국민연대",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "코리아-유라시아 로드 런",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일코리아지도자회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한백통일재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "광복소년소녀단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "코리아경제포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일메아리연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "427 한반도 평화번영 시민재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화콩 드림",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "동북아 평화협력 네트워크",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북 사회기반시설 협력 네트워크",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북상생 통일연대",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "유니시드",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "하나행복나눔봉사회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "아시아평화대안",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "이글스네스트파운데이션",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "새한반도야구회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "화해평화연대",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화드림포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "비바코리아",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "금강평화지역발전포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "위로",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "부산평화통일센터 하나",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "DMZ평화네트워크",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "뉴코리아피스파운데이션",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "서울평양연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국통일외교협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북방경제문화원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "이산가족소망회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일준비학교총연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일을실천하는사람들",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도평화경제회의",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "시각장애겨레손",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화통일교육문화센터",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도교역투자연합회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도미래행복연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국새생명복지재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "윤산평화법제포럼",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일협력연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "동행연구소",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "하모니골드협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "네번째강문화연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "너와락나눔재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "평화어머니회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "자유통일국민연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한회복국민운동",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한인권",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "광주한백통일재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "프리덤스피커즈인터내셔널",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "해마루",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북스포츠문화연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "원하다",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일시민학교",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "신창읍민회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일을위한환경과인권",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "글로벌컨센서스연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "백두한라협회(구, 백두한라봉사단)",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일호국유공자회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "통일걷기",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "새삶인협회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한자유화추진총연맹",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북공동체협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "모자이크코리아",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "탈북민공익활동지원연합",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "남북통일애국본부",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "대한민국미래희망재단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)비전유니피게이션",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)하나로드림",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)평양민족통일예술단",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)에스엔케이글로벌센터",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)북한인권민간단체협의회",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)빛 가운데",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)통일융합전략연구원",
    purpose: "-",
    law: "-",
    type: "-",
    remit: "통일부",
  ),
];
