import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> mofRawData = [
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해운협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국국제해운대리점협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)한국해사문제연구소",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해운물류학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해법학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해운대리점협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해운중개업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)한국해사재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양산업총연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한중카페리협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)국제해운거래제도연구소",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해운세제학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)신북방 해양경제 포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국해운항만학술단체협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국해사포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)송언해양연구센타",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양환경에너지학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양문화발전연구소",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수중과학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)연안보전네트워크",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)제주도바다환경보전협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양보호국민연대",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수중환경안전협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)연안환경보전연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)초록생활",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)환경재단 바다와미래",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양환경안전협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)서남해양개발연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)바다살리기국민운동본부",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국물사랑연합",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해병이바다살리기운동본부",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)지구환경해양보호연대",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수중사진영상협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)블루환경교육센터",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)바다사랑실천운동시민연합",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양환경보전국민연합",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)대한민국해양연맹",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)삼각해양과학진흥회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양탐험문화진흥회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)수산해양포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양비즈니스학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)특수임무UDU동지회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)이순신리더쉽연구회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양문학가협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양산업연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)이사부기념사업회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양사진영상협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해룡",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양디자인협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)녹색성장해양포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)미래해양수산포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)한국해양재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양정책학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)아시아퍼시픽해양문화연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)동북아연안네트워크",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국심해기술협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양교육연구회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)장보고글로벌재단",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양수산발전포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)경기만 포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "울산해양포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국해양정책연합",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)적도해양포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양디자인기술연구소",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양문화연맹",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)한국해양전략연구소",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)환동해미래포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)이어도연구회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)독도지킴이봉사단",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)국제해양법학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수로학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)독도사랑회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)독도사랑운동본부",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)독도해양·수산연구회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)독도연구보전협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양영토협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)동해학술원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양정책연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)독도수호연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)동해병기",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)독도청년총연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)대한민국 독도협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)독도지킴이 그린연합",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양바이오학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양생명과학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국키틴키토산학회→ (사) 한국천연고분자학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양수산기업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국생태계모델링연구회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양환경생태계보전협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)갯벌·연안보전포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수족관협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양생태보존연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)가로림만 생태관광협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)동아시아바다공동체오션",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국퇴적환경준설학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양배출협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양이용영향평가협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양수산환경협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국보존문화협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)남해군해양환경보전협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)세이브 제주바다",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국크루즈연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국마리나선주협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)대한마리나산업진흥회",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국산업잠수협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국범선협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국청소년스킨스쿠버협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양레저보트협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국바다수영협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양관광학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국레포츠연맹",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양소년단연맹",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양레저네트워크",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국잠수산업연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양디자인학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국요트세계일주협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "아태마리나학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국국제크루즈연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수중레저협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국생존수영지도자협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국크루즈포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국해양레저스포츠연맹",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국제트스키협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)대한잠수협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양레저관광 진흥회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국연안협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)워터프런트연구협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양심층수산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양과학기술협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)극지해양미래포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양심층수이용학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국항해항만학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)한국해사협력센터",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양안전진흥협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)한국해사위험물검사원",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국마린엔지니어링학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국외양요트협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국선급",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국선박평형수협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국항만경제학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)동북아항만포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수상교통시설협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)한국항만해안기술원",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국검수검정협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국항만물류협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)다보스해양경제연구소",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국도선사협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)여수·광양권해양협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)인천항발전협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)부산항만산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국급유선선주협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)환동해북방사업연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해운항만물류정보협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국도선안전교육연구센터",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)인천항만산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국선용품산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)군산통선협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)부산항만산업총연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)거제항만발전협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국연안방재학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)포트아카데미연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)부산항신항배후단지물류협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국종합물류연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)풍양연구장학재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)평택·당진항 자유무역지역 협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)울산항발전협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)부산항시설관리센터",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)인천항시설관리센터",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)평택항활성화촉진협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)광양항배후단지입주기업협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)북방물류산업진흥원",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)평택당진항발전협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)부산항신항시설관리센터",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)여수광양항발전협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)에코포트포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양통상무역연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)국제이네비해양경제학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국스마트해양학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국공공안전통신협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양안전심판변론인협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)내륙지수산물중도매인연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)바다먹거리사랑협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국수산물도매시장법인협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국수산물유통인모임",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국수산물중도매인협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산물용기협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국건해산물 생산자 및 유통인협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국천일염수출협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수입낙지유통협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해항회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)부산예부선협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)인천예부선협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)인천예인선선주협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)부산예부선선주협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)여객선안전진흥재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해조회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국연안여객카훼리 및 쾌속선사업자 협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국중량물해상운송선주협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)인천예부선화물운송협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사) 전라북도 예·부선협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)군산예・부선협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)목포예・부선협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)연안해운발전연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국어촌체험마을연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국어촌사랑협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국바다해설사협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 멋진바다",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)대한수산질병관리사회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)바다셰프",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사) 전라남도멸치권현망협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)수진회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국근해오징어채낚기연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국실뱀장어어민·유통연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산과학총연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국어업포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국생분해어망협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산해양기술학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국어류학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국오징어채낚기선주실무자연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산법제연구소",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국붉은대게근해통발협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국새우조망총연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국갈치생산자협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국꽃게생산자연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국연안어업인연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국대하생산자협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국문어생산자협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국키조개생산자협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)서해중부 연안개량안강망협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사) 충남·경기·인천 근해형망협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "근해소형선망협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국근해바다장어통발생산자협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)제주참조기근해자망생산자협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국어선통신사협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국어선중개업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산증양식기술사협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수조양식기자재연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국진주양식협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)패류인공종묘협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국축제식양식협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국유해조류연구회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해삼협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국관상어협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국송어양식협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국향어양식협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국자라생산자협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국메기양식중앙연협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국내수면양식단체연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국광어양식연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국민물장어생산자협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국김생산어민연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국새우양식총연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산종자산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국전복협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국전복산업연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국김산업연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국조류(藻類)학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국전복유통협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국다슬기양식유통생산자협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국농수산환경안전협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국토속어양식협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국마른김생산자연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국동자개양식생산자협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해조류산업발전협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국김종자생산자연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국패류학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사) 전국내수면어로어업인협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사) 전국내수면미꾸라지양식생산자 협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국전복종자협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국양어사료협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국양식기자재 생산자협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해조류활성처리제연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)수산양식자원진흥회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한반도양식기술보급협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국우렁이연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국미역다시마종자업연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양산업통합클러스터",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산무역협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국굴가공협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국미역가공협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산물유통가공협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산물건조가공협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산물품질인증가공협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국싱싱회가공업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)대한냉동수산식품안전관리원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)간고등어생산자협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국생선회협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국오징어생산자단체연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국친환경수산협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국전복수출협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산물품질관리사협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국김수출협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)수우회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한반도수산포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국미래바다포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)수협재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산산업총연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산어촌연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)서해안연합회",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)인천수산인협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산정보콘텐츠기술협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국낚시어선협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국낚시업중앙회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국자율관리어업연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국인공어초협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국기조연맹",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국프로낚시연맹",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산자원생태연구협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국낚시연합",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국낚시단체총연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국낚시협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)바다녹화운동본부",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)낚시산업무역협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)대한프로낚시협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)로얄경기연맹",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국선상낚시어선협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산경영기술연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국영어조합법인중앙회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양수산신지식인중앙연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)수산연안개발연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산업경영인중앙연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산경영학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산기자재협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국여성어업인연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한수대수산전문경영인협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국선박통신사협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해기사협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)선우회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국해운노동조합협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국선원장애인복지협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국해상전직선원노인복지협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국연근해어선외국인선원관리협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해외어업협력센터",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국옵서버협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)제주바당",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국수산업생산자단체연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국유조선사협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해외이주화물협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국근해자망연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)군산항발전시민협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국연안어업인중앙연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산중도매인조합연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)해양심층수산업 고성진흥원",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양한림원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양생태보존회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국굴수하식연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)군산항발전협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)서해근해안강망연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한국해운항만물류연구원",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)대한패들서프(SUP) 프로협회(KAPP)",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 국제비행선박협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 스마트수산어촌포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 바다드림",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국해양기자협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 오션케어",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 한국해양디자인진흥원",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국수산부산물자원화협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 유명인해양청소봉사단",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 선박항해융합협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 여수선언실천위원회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국선장포럼",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 환경통합감시센터",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 바다의품",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국비어업인수산자원보호협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국항만물류전략연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국운반선협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 해양환경보존전국감시연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 해양생태보전복원협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국해양바이오산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 제주해양힐링협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 플랜오션",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 전북해양환경협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 여수해양환경보전협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 전국낚시어선연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국바다낚시업연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 해양환경구조협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국해양환경감시단",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국어선중개사협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 대한극지의학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국루어낚시협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국여성해사인협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 청해",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 전국해양학교수협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 섬즈업",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 대형선망고등어생산자협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 전국어촌계장협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 제주해양사랑협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 한국해양환경연맹",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 묵암재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양시민과학센터 파란",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)여수광양 예·부선 협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국항만장비산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)대한민국 참다랑어양식협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국스마트수산생물자원조사연구협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국낚시교육원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양레저산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)부산항국제여객선협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국청정메탄올산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)바다살리기네트워크",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)친환경수상레저협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국항만건설작업선협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양수상레저스포츠회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 선원기금재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양시민과학조사단",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)기후해양정책연구소 코리",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)굿웨이브",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국낚시진흥협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(재)마린유겐트 코리아",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해안해양공학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)세이브오션",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)우리바다클린운동본부",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)인천연안항발전협의체",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양플랜트서비스산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)어업기자재협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사) 전국해녀협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)격렬비열도사랑운동본부",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국양식수산물재해손해사정사협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)제주해양치유산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국해양수산 드론모빌리티 산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)제주해양수산바이오기업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)수중환경과학협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "재단법인 신안교통재단",
    purpose: "-",
    law: "-",
    type: "재단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)이어도지키기국민운동",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)선박건조금융법정책학회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산물안전정책연구원",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국전기선박협의회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)해양복원환경단체 블루사이렌",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "사단법인 바다숲",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국미역자조회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국선상낚시인협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국수산식품산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)한국북극항로협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)전국근해어선 선주 총연합회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)수산물유통협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)부산크루즈산업협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "(사)서해참홍어연승생산자협회",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "해양레저관광협회",
    purpose: "-",
    law: "-",
    type: "특수",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "바다저자와의대화",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "해양수도권연합",
    purpose: "-",
    law: "-",
    type: "사단",
    remit: "해양수산부",
  ),
];
