import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> modsRawData = [
  ExcelRowData(
    permitDate: "1971",
    name: "한국통계학회",
    purpose: "사회 일반의 이익에 공여하기 위하여 통계학 및 통계의 발전과 이에 관련된 분야의 연구 및 연구조성",
    law: "-",
    type: "사단법인",
    remit: "국가데이터처",
  ),
  ExcelRowData(
    permitDate: "1995",
    name: "한국인구학회",
    purpose: "인구학 및 인구통계의 발전과 이에 관련된 분야의 연구 및 연구조성",
    law: "-",
    type: "사단법인",
    remit: "국가데이터처",
  ),
  ExcelRowData(
    permitDate: "1999",
    name: "한국조사연구학회",
    purpose: "조사연구와 관련이 있는 학계 및 실무 분야 전문가들이 조사연구를 활용하고 연구하는 학문간 및 이론과 실무간 연구",
    law: "-",
    type: "사단법인",
    remit: "국가데이터처",
  ),
  ExcelRowData(
    permitDate: "1990",
    name: "한국통계조사연구소",
    purpose: "정부의 시책에 적극  부응하여 정치, 경제, 경영 등 사회과학 전 분야에 대한 학술적 연구와 실증적 분석을 통해 국가경제발전 시책에 기여하고, 통계 수요에 대비하여 과학적이고 합리적인 통계연구 기법을 개발 보급",
    law: "-",
    type: "사단법인",
    remit: "국가데이터처",
  ),
  ExcelRowData(
    permitDate: "2016",
    name: "한국삶의질학회",
    purpose: "삶의 질에 대한 학술연구 및 회원 상호간 전문적 지식 교환",
    law: "-",
    type: "사단법인",
    remit: "국가데이터처",
  ),
  ExcelRowData(
    permitDate: "2018",
    name: "한국빅데이터협회",
    purpose: "정형 및 비정형 빅데이터의 활용과 관련 제반 활동 수행빅데이터 조사, 연구, 교육, 국제협력, 학술활동 지원 및 창달",
    law: "-",
    type: "사단법인",
    remit: "국가데이터처",
  ),
  ExcelRowData(
    permitDate: "1996",
    name: "한국조사협회",
    purpose: "마케팅, 여론 조사활동의 질적 향상 및 합리화를 통해 조사산업의 발전을 도모하며, 국가통계산업의 발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "국가데이터처",
  ),
  ExcelRowData(
    permitDate: "2019",
    name: "한국행정개혁학회",
    purpose: "통계 자료의 수집 및 분석과 관련된 제반활동을 수행함으로써 통계적 근거에 기반을 둔 과학적 연구기법을 통해 국가 행정개혁의 발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "국가데이터처",
  ),
  ExcelRowData(
    permitDate: "1993",
    name: "한국사회조사연구소",
    purpose: "우리사회와 국가의   발전을 위한 각종   자료의 수집과 축적 및 분석을 통해 국가 발전에 이바지",
    law: "-",
    type: "사단법인",
    remit: "국가데이터처",
  ),
  ExcelRowData(
    permitDate: "1970",
    name: "한국응용통계연구원",
    purpose: "우리나라의 정치․경제와 기업경영에 관한 조사 연구개발 및 사회발전에  부응한 새로운 통계에 대한 일반적인 인식을    고취시키기 위하여 일반  국민에 대한 통계인식 확대와 과학적인 통계 이론 및 기법 보급",
    law: "-",
    type: "사단법인",
    remit: "국가데이터처",
  ),
  ExcelRowData(
    permitDate: "1987",
    name: "통계동우회",
    purpose: "회원 상호간의 친목과  상부상조로서 회원의 복리 증진을 도모하며, 전문적이고 풍부한 경험으로  통계업무 수행에 관한 건의 및 자문에  응하여  통계행정 발전에 기여",
    law: "-",
    type: "사단법인",
    remit: "국가데이터처",
  ),
  ExcelRowData(
    permitDate: "1973",
    name: "한국보건정보통계학회",
    purpose: "보건의료 정보·통계에 관한 연구와 응용을 도모함으로써 보건의료 분야의 발전향상에 기여",
    law: "-",
    type: "사단법인",
    remit: "국가데이터처",
  ),
  ExcelRowData(
    permitDate: "2020",
    name: "아시아여론조사학회",
    purpose: "아시아 여론조사에 관한 학문연구와 발전",
    law: "-",
    type: "사단법인",
    remit: "국가데이터처",
  ),
  ExcelRowData(
    permitDate: "1963",
    name: "한국통계진흥원",
    purpose: "국민의 통계인식을 제고하고 각종 통계의 개발, 개선과 기술향상을 통하여 통계산업의 발전과 통계인프라 강화를 증진함을 목적으로 함",
    law: "-",
    type: "재단법인",
    remit: "국가데이터처",
  ),
  ExcelRowData(
    permitDate: "2011",
    name: "한국통계정보원",
    purpose: "통계의 개발, 진흥을 위하여 통계정보 이용의 활성화 및 효율적 관리와 통계정보시스템의 구축, 운영",
    law: "-",
    type: "재단법인",
    remit: "국가데이터처",
  ),
];
