import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> molegRawData = [
  ExcelRowData(
    permitDate: "2007년",
    name: "(사) 한국비교공법학회",
    purpose: "비교공법학 및 관련된 법제의 학술적 조사ㆍ연구발표를 통한 공법학의 보급과 회원 상호간의 협력을 도모",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2009년",
    name: "(사) 한국토지보상법연구회",
    purpose: "재산권보상 법제 연구로 합리적인 보상법제 마련",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2009년",
    name: "(사) 한국입법정책학회",
    purpose: "입법학 및 관련 학술 조사·연구·발표 및 보급과 한국의 법제발전 도모",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2010년",
    name: "(사) 법과 역사 학회",
    purpose: "법과 역사에 관한 학문 연구와 학술 교류 등을 통한 법학 발전 기여",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2010년",
    name: "(사) 한국조세법학회",
    purpose: "조세법학과 조세정책학 등의 학제간 교류 종합적 조사 연구를 통하여 조세법의 학문적 발전 및 실정법 제도 발전에 기여",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2011년",
    name: "(사) 한국국가법학회",
    purpose: "공법학의 연구 및 회원 상호간의 협력과 친목 도모",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2011년",
    name: "(사) 입법이론실무학회",
    purpose: "입법이론과 입법실무의 통합적 연구를 통하여 입법에 관한 학문적 발전을 촉진하고 실정법제도 및 입법실무의 발전에 기여",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2011년",
    name: "(재) 한국법령정보원",
    purpose: "법령정보의 체계적 수집․관리 법령정보의 신속․정확한 제공 및 법제정책의 교육ㆍ홍보 지원으로 법률문화의 향상에 이바지",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2012년",
    name: "(사) 한국사이버안보법정책학회",
    purpose: "사이버안보법학 및 관련 학문의 연구ㆍ발표ㆍ응용활동 지원을 통한 사이버안보법학의 발전과 법치주의 진작에 기여",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2012년",
    name: "(사) 한국기업ㆍ노동ㆍ복지법학회",
    purpose: "기업노동 및 사회복지 관련 법제의 사상과 이론 및 정책 그리고 실무의 심층적 탐구와 아울러 이들 법제와 관련된 주변 학문과의 학제적인 연구를 통한 기업법",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2013년",
    name: "(사)대한법학교수회",
    purpose: "법학교육 발전방안의 연구 및 건의 법학교육의 표준화 및 인증사업",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2013년",
    name: "(사)한국생명존중법연구회",
    purpose: "삶과 죽음 자살에 관한 조사ㆍ연구를 하고 생명존중과 관련되거나 약자ㆍ소수자를 보호하기 위한 법ㆍ제도를 연구ㆍ개선하며 생명존중을 달성하기 위한 교육ㆍ컨설팅ㆍ문화ㆍ홍보사업을 추진함으로써 국민 행복과 새시대를 여는 것을 목적으로 함",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2014년",
    name: "(사) 한국의료법학회",
    purpose: "의료를 비롯하여 약과 보건 등에 관련된 법제에 관하여 관련된 학문 상호간의 학제적 연구를 통하여 상호간의 이해와 심층적 연구를 촉진하며 외국의 법제에 관한 연구를 가미하여 고유의 법제의 독창성을 탐구하며 관련 법제의 개선을 위하여 노력함으로써 전문적인 법률문화의 창달에 기여",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2015년",
    name: "(사) 한국문화예술법학회",
    purpose: "문화와 예술분야에 관한 법학 발전을 위한 국내외 법제의 조사․연구 각종 학술활동 및 회원 상호간의 협력 도모",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2016년",
    name: "(사) 글로벌기업지배구조연구소",
    purpose: "기업지배구조 관련 법제 연구 및 국내 법적ㆍ제도적 규제 평가를 통한 자본시장의 건전한 발전 도모",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2017년",
    name: "(사) 한양법학회",
    purpose: "한국법학의 발전을 위한 국내외 법제의 조사․연구 각종 학술 활동 및 회원 상호간의 협력도모",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2017년",
    name: "(사) 행정법과 법치주의학회",
    purpose: "국가입법정책 및 이에 관련된 학술의 조사․연구․발표 및 보급",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2018년",
    name: "(사) 디지털규제혁신포럼",
    purpose: "일상생활 속 불필요하고 부조리한 규제 법령 발굴 및 개선 방안 제시",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2018년",
    name: "(사) 한국과학기술법학회",
    purpose: "과학기술법 분야의 체계적인 연구와 연구자 상호간의 교류 및 공동연구를 촉진 등 과학기술의 창달과 지속가능한 사회의 구현에 이바지",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2020년",
    name: "(사) 한국법제학회",
    purpose: "법제 관련 연구 발표 및 국제적인 학술교류에 기여 회원들의 연구증진과 친목도모",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2022년",
    name: "(사) 교통법정책학회",
    purpose: "법과 정책에 관한 학술적 연구와 국회 행정기관 산업체 대학과 공동연구를 통해 국가 법과 정책 발전에 기여함",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2024년",
    name: "(사)한국법령정책연구원",
    purpose: "입법정책의 연구와 평가 등 법령정책 활동을 통하여 국가 법령정책 발전에 기여",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2024년",
    name: "(사)한국공공계약법학회",
    purpose: "공공조달법 민간투자법 등 공공계약법에 대한 다양한 논의의 장을 마련하여 공공계약법 분야의 학문적ㆍ실무적 발전에 기여",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
  ExcelRowData(
    permitDate: "2024년",
    name: "(사)재정헌법제도연구회",
    purpose: "재정에 관한 헌법 및 법령 등 제도 전반과 입법 및 행정정책에 대하여 학제 간의 학술적 연구와 국회 행정기관 등과의 공동연구를 통해 재정에 관한 헌법과 법제도 및 정책 발전에 기여",
    law: "-",
    type: "-",
    remit: "법제처",
  ),
];
