import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> mfdsRawData = [
  ExcelRowData(
    permitDate: "1999-07-08",
    name: "(사)한국의료기기산업협회",
    purpose: "의료기기의 국내외 공급질서 확립 및 양질의 의료기기공급을 통한 국민보건 향상 및 의료기기산업발전에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2000-11-27",
    name: "(사)한국의료방사선안전관리협회",
    purpose: "의료방사선 종사자와 환자의 방사선 안전관리",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2001-01-11",
    name: "(재)약학정보원",
    purpose: "국내생산 의약품 및 수입의약품에 관한 제반 정보를 수집, 데이터베이스화하여 이를 보건의료 관련 종사자 및 필요로 하는 자에게 제공함으로써 약학 및 보건의료제도 발전과 국민의 건강 증진에 기여",
    law: "-",
    type: "재단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2001-10-10",
    name: "(사)한국카카오연구회",
    purpose: "카카오.초콜릿에 관한 제도개선 방안 연구 및 정책건의",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2002-11-06",
    name: "(사)한일외식문화교류협회",
    purpose: "한일외식문화교류로 식문화발전 및 외식산업 기술교류",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2003-02-27",
    name: "(사)한국독성학회",
    purpose: "독성학의 교육 및 연구개발",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2003-06-26",
    name: "(재)의약품품질연구재단",
    purpose: "의약품 등(의약품, 의약외품, 식품, 화장품, 의료기기 등)의 품질기준 및 시험법과 관련 정보 등을 전문적이고 체계적으로 조사 연구하고 대한민국약전 등 관련 자료의 간행,보급 및 교육을 실시하여 보건산업의 국제경쟁력을 제고하고 국민보건 상향에 이바지",
    law: "-",
    type: "재단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2003-07-18",
    name: "(사)한국식품안전협회",
    purpose: "식품, 수입식품 등의 안전 확보와 위생 향상을 도모함으로써 식품산업의 발전과 국민보건 향상에 기여함을 목적",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2003-08-06",
    name: "(사)한국약제학회",
    purpose: "약제학의 진보 발전과 산,학, 관, 연 분야의 학술 연구 및 제약산업 발전에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2004-06-12",
    name: "(사)한국응용약물학회",
    purpose: "약물학 및 생리활성 물질에 관련된 연구와 지식의 향상 및 학술발전에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2005-01-21",
    name: "(사)한국에프디시규제과학회",
    purpose: "의약품, 의약외품, 의료기기, 화장품 및 건강기능식품 등과 관련된 국내·외의 각종 법제와 규제에 대한 연구와 교육 등을 통하여 합리적이고 투명한 법령과 규정의 제·개정 및 정책개발에 기여함으로써 관련 산업의 발전 및 국민의 건강증진에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2005-07-27",
    name: "(사)대한의공협회",
    purpose: "의공학기술 발전 및 의료기기 안전관리",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2005-09-29",
    name: "(사)한국의료기기유통협회",
    purpose: "올바른 의료기기의 선택 및 사용방법 교육․홍보, 의료기기 품질향상 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2005-09-29",
    name: "(사)한국식품위생안전성학회",
    purpose: "식품위생향상을 위한 학술연구와 정보교류",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2005-11-01",
    name: "(사)한국생약학회",
    purpose: "사회일반의 이익에 공여하기 위한 학문적 유대를 원활히 하여 국내․외적으로 생약학 및 천연물과학 등의 발전과 관련 정책 개발에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2006-01-13",
    name: "(사)한국향료산업협회",
    purpose: "식품향료 등에 대한 위생 및 안전성을 확보하여 국민보건 향상에 기여하고 향료산업의 건전한 발전을 도모",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2006-03-14",
    name: "(사)한국급식식자재위생관리협회",
    purpose: "단체급식 식자재에 대한 위생 및 품질 안정성을 확보, 단체급식 식자재업 발전도모",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2008-01-11",
    name: "(사)한국식품안전연구원",
    purpose: "국내외 식품안전관련 이슈에 대한 과학자 네트워크를 구축하여 과학적 사실에 근거한 식품안전기반 확립",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2009-05-25",
    name: "(재)한국의료기기기술원",
    purpose: "진단용방사선 발생장치의 성능 및 안전관리검사와 평가 등",
    law: "-",
    type: "재단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2009-05-25",
    name: "(재)한국의료기기평가원",
    purpose: "진단용방사선 발생장치의 검사와 의료기기 분야의 성능평가 및 기술개발연구사업을 통한 국민 보건 향상",
    law: "-",
    type: "재단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2009-08-06",
    name: "(사)한국급식∙외식위생학회",
    purpose: "급식∙외식산업의 위생관리에 관한 학술적 연구와 활동 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2010-09-29",
    name: "(사)한국실험동물협회",
    purpose: "동물실험시설의 설치자 및 관리자. 실험동물공급자, 취급자의 교육 훈련, 실험동물의 생산·사용·관리등에 관한 정보의 수집·관리·제공 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2011-01-12",
    name: "(재)병원약학교육연구원",
    purpose: "병원약학 관련 교육 및 연구를 지원하여 병원약학 교육 발전 및 첨단 병원약학 연구에 기여",
    law: "-",
    type: "재단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2011-07-01",
    name: "(사)한국바이오의약품협회",
    purpose: "바이오의약품 관련 연구개발, 제도개선 및 제품의 글로벌화를 지원하고 바이오의약품산업을 발전시킴으로써 국가경제와 국민보건 향상에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2012-08-08",
    name: "(사)싱겁게 먹기 실천연구회",
    purpose: "소금 과잉섭취와 만성질환과의 관계에 대한 임상 역학 조사, 실험연구, 결과 홍보 사업 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2012-12-11",
    name: "(사)한국식품등시험검사기관협회",
    purpose: "식품 등의 시험·검사 기술·방법 및 시험·검사 산업 전반에 대한 조사·연구 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2013-12-16",
    name: "(재)식품안전상생재단",
    purpose: "식품 품질안전 분야에 대한 중소기업 기술 지원사업 등",
    law: "-",
    type: "재단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1966-01-07",
    name: "(사)한국외식업중앙회",
    purpose: "일반음식점의 건전한 발전과 회원간의 권익보호",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1966-03-26",
    name: "(사)대한제과협회",
    purpose: "휴게음식점 중 제과점 영업의 건전한 발전과 회원간의 권익보호",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1969-10-07",
    name: "(사)한국식품산업협회",
    purpose: "식품산업의 발전과 식품위생수준 향상 도모",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1973-06-26",
    name: "(사)한국인삼제품협회",
    purpose: "인삼제품 제조·가공영업의 건전한 발전과 회원간의 권익보호",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1985-01-11",
    name: "(사)한국휴게음식업중앙회",
    purpose: "휴게음식점 중 다방영업의 건전한 발전과 회원간의 권익보호",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1985-09-02",
    name: "(사)한국조리사협회중앙회",
    purpose: "조리기술 향상과 조리사면허자의 권익보호",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1985-12-27",
    name: "(사)한국치과의료기기산업협회",
    purpose: "치과기자재의 품질 향상과 건전한 유통질서를 위한 조사, 연구사업치과기자재 제조, 수입업무에 관한 사업치과기자재 공급에 종사하는 자의 자질향상을 위한 교육",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1987-05-25",
    name: "(사)한국유흥음식업중앙회",
    purpose: "유흥주점의 건전한 발전과 회원간의 권익보호",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2013-12-30",
    name: "(사)한국건강기능식품협회",
    purpose: "건강기능식품업계의 건전한 발전과 국민보건 향상도모",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1990-04-10",
    name: "(사)한국식용유지고추가공업협회",
    purpose: "즉석 판매제조·가공업중 참기름등을 제조·가공하는 영업자의 권익보호",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1990-04-10",
    name: "(사)한국떡류식품가공협회",
    purpose: "즉석 판매제조·가공업중 떡류를 제조·가공하는 영업자의 권익보호",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2013-12-30",
    name: "한국축산부산물업중앙회",
    purpose: "식용을 목적으로 생산된 식육 중 부산물의 위생처리, 시설 개선을 위한 자체 지도 점검 및 기술향상 도모 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1991-10-21",
    name: "(사)한국추출가공식품업중앙회",
    purpose: "즉석 판매제조·가공업중 염소중탕 등 추출가공식품 영업의 건전한 발전과 회원간의 권익보호",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1994-02-26",
    name: "(사)한국단란주점업중앙회",
    purpose: "단란주점영업의 건전한 발전과 회원간의 권익보호",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1996-08-13",
    name: "(사)전북음식문화연구회",
    purpose: "향토 전통음식 및 식문화의 발전도모",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1996-08-28",
    name: "(사)한국식품영양과학회",
    purpose: "식품영양에 관한 연구 및 식생활개선으로 국민보건 향상도모",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "1999-07-07",
    name: "(사)한국베버리지마스터협회",
    purpose: "조주에 관한 조사·연구와 국제교류 등을 통하여 칵테일 문화 보급·발전",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2002-08-08",
    name: "(사)한국식품기술사협회",
    purpose: "식품기술사의 권익보호 및 교육을 통한 국가식품산업의  기술발전 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2006-10-04",
    name: "(사)한국급식협회",
    purpose: "위탁급식산업의 필요사항에 대한 조사.연구.지도 등을 통한 식품위생수준의 향상",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2013-12-30",
    name: "(사)한국수입육협회",
    purpose: "수입육 유통 개선에 관한 사업수입육 유통질서 확립을 위한 홍보, 지도 사업수입육 관련 국내외 조사, 연구 사업",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2013-12-30",
    name: "(사)한국임상개발협회",
    purpose: "의약품에 대한 임삼시험 지식 배양, 신약개발의 임상시험 수준 향상 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2014-01-29",
    name: "(사)한국식육운송협회",
    purpose: "축산물 식육운송과 관련되는 정책개발 및 표준화사업과 식육운송기술의 상호교류 및 조사연구사업",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2014-05-23",
    name: "(사)한국식품커뮤니케이션포럼",
    purpose: "식품관련 정보 교류를 위한 전문가 포럼, 교육 및 연구 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2014-08-13",
    name: "(사)축산기업중앙회",
    purpose: "식육산업 위생시설의 개선과 기술향상을 도모하여 국민보건 및 식육유통발전에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2014-08-13",
    name: "(사)한국계란선별포장유통협회",
    purpose: "계란유통 체계를 선진화하여 위생적이고 고품질의 계란을 소비자에게 공급함으로써 국민건강 향상에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2014-08-13",
    name: "(사)한국육계협회",
    purpose: "위생계육생산  공급으로 국민건강 향상 ·계육산업의 국제경쟁력 향상을 기함",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2014-08-13",
    name: "(사)한국축산물처리협회",
    purpose: "축산물작업장의 시설 및 도축방법 등의 개선을 통하여 축산물을 위생적으로 처리함으로써 국민보건 향상과 축산업 발전에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2014-08-13",
    name: "(사)한국육가공협회",
    purpose: "위생적이고 안전한 식육 및 식육가공품과 포장육을 공급하여 소비자 보호에 기여 및 축산물의 품질향상 도모",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2014-08-13",
    name: "(사)한국난가공협회",
    purpose: "난가공업을 영위하고 있는 가공업체들의  대내외적인 창구로서 회원의 경제적, 사회적 지위향상과 복리증진에 기여 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2014-08-13",
    name: "(사)한국의약품수출입협회",
    purpose: "의약품, 의약외품, 인체조직, 화장품 등의 무역진흥과 품질관리 및 유통질서 확립으로 회원의 권익을 보호하고, 국민보건 향상과 경제발전에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2014-08-13",
    name: "(사)한국글로벌의약산업협회",
    purpose: "새로운 의약품의 개발 촉진, 제약산업의 윤리기준 제고, 국민보건 향상에 대한 제약산업의 기여도 강화, 의약품 관련 정보의 효율적 확대보급",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2014-08-13",
    name: "(사)한국제약바이오협회",
    purpose: "제약바이오산업의 건전한 발전을 기함으로써 국민 보건향상에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2014-08-13",
    name: "(사)대한화장품협회",
    purpose: "화장품산업의 건전한 발전을 도모함으로써 공동복리 증진과 국민보건향상에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2014-10-27",
    name: "(사)전국식육부산물전문상인회",
    purpose: "식육부산물의 위생적 처리 및 시설 개선, 식육부산물의 고급화를 위한 연구·개발, 식육부산물 판매업 영업자에 대한 위생교육 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2014-12-15",
    name: "(사)식약동우회",
    purpose: "회원 상호 간의 친목과 상부상조로서 회원의 복리증진을 도모하며, 전문적 지식과 풍부한 경험으로 식의약 발전에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2016-03-17",
    name: "(사)코리아할랄센터",
    purpose: "할랄에 대한 정확한 정보제공을 통해 할랄식품에 대한 인식제고 및 안전성을 담보하고, 이슬람권 국가에 대한 한국식품수출을 지원하여 식품산업발전에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2016-08-19",
    name: "(사)한국한약재GMP협회",
    purpose: "한의약 산업 발전을 도모하고 우수한 한약재를 제조 공급함으로써 국민보건 향상에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2016-12-14",
    name: "(사)대한항암요법연구회",
    purpose: "다기관 암 임상시험 수행 및 지원, 기술정보 교류, 전문인력 양성 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2017-01-03",
    name: "(사)한국식자재유통협회",
    purpose: "식자재 유통산업의 선진화 및 효율화와 식품위생 안전성 제고",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2017-04-06",
    name: "(사)대한아이스크림협회",
    purpose: "아이스크림 산업의 균형있는 발전과 국민 식생활 향상에 기여함으로써 국민의 건강증진에 이바지",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2017-12-01",
    name: "(사)집단급식조리협회",
    purpose: "조리종사자의 보건위생관리 등 조리 관리 수준향상 및 조리 안전에 관한 교육 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2018-05-24",
    name: "(사)한국위생물수건처리업중앙회",
    purpose: "회원의 영업상 필요한 원부자재의 공동구입, 생산가공 및 분배에 관한 사업, 영업의 위생자율지도 사업 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2018-07-19",
    name: "(사)한국커피과학회",
    purpose: "커피에 관한 학술연구발표회, 강연회 등의 개최 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2018-10-05",
    name: "(사)한국의료용고압가스협회",
    purpose: "의료용고압가스 GMP기준의 조기 정착을 통한 품질관리 향상 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2018-12-07",
    name: "(사)한국외식업중앙회 외식가족공제회",
    purpose: "외식가족공제회원의 생활안정과 복리증진을 위한 공제급여 사업 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2019-02-13",
    name: "(사)한국향미유협회",
    purpose: "향미유 관련 기술정보 교류를 위한 포럼 개최, 향미유 기술 발전을 위한 교육사업 및 정책연구사업 추진 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2019-02-28",
    name: "(재)제약기술재단",
    purpose: "제약바이오 GMP 현황 조사, 기술지원(세미나, 교육) 및 전문인력 육성 등",
    law: "-",
    type: "재단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2019-04-18",
    name: "(사)한국체외진단의료기기협회",
    purpose: "체외진단의료기기 기업 성장지원, 특허 및 법률자문, 해외진출 지원, 정부정책 개발 수립 지원 및 교육 지원 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2019-09-05",
    name: "(사)기저귀위생용품산업협회",
    purpose: "기저귀 품질향상과 관련한 제조기술, 해외정보 등을 제공하고 원부자재 사전안전관리를 통한 서비스 품질향상 및 국민건강권 수호",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2020-02-18",
    name: "(사)한국유산균·프로바이오틱스학회",
    purpose: "유산균 및 프로바이오틱스에 관한 기초 및 응용연구를 촉진하고 관련된 이론과 기술을 보급함으로써 이 분야 학문과 산업기술의 발전에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2020-03-06",
    name: "(재)범부처 전주기 의료기기 연구개발 사업단",
    purpose: "의료기기 연구개발의 전주기 지원체계 구축을 통한 국내외 의료기기 시장점유율 확대",
    law: "-",
    type: "재단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2020-03-26",
    name: "(사)식용란선별포장업협회",
    purpose: "식용란선별포장업 관련 종사자들이 참여하여 식용란을 선별·포장하여 위생적이고 안전한 식용란을 유통하여 소비자 보호 및 식용란선별포장업의 건전한 발전에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2020-10-29",
    name: "(사)대한부인종양연구회",
    purpose: "부인암에 대한 다기관 공동 임상연구 개발, 시행 및 상호 정보교환, 부인암 연구와 관련된 국제교류, 전문 인력의 교육 및 훈련, 부인암 연구에 관한 홍보 및 계몽",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2021-02-16",
    name: "(사)대한화장품학회",
    purpose: "화장품 연구논문발표회 및 학술강연회의 개최 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2021-02-23",
    name: "(사)한국주류안전협회",
    purpose: "주류HACCP 보급 및 위해예방관리 보급에 관한 사업 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2021-03-05",
    name: "(사)한국산업약사회",
    purpose: "의약품, 의약외품 등 관련산업(이하 ‘의약품등 관련산업’이라 한다)에 종사하는 약사의 직무능력 및 윤리의식을 향상시켜 보다 안전하고 효과 높은 제품을 개발, 제조, 공급함으로써 국민의 안전과 건강증진에 이바지",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2021-03-18",
    name: "(사)한국스마트헬스케어협회",
    purpose: "스마트헬스케어 관련 법·제도 연구 및 정책개발 대정부 건의사업, 기술동향 조사 및 표준 규격 연구·개발 사업, 산업 활성화와 이용촉진을 위한 전시·홍보 사업 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2021-11-12",
    name: "(사)한국외식산업협회",
    purpose: "국내외 외식산업의 경쟁력 향상을 통한 양적, 질적 성장 기여 및 외식산업 발전과 국민의 위생안전 및 건강 증진 기여 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2021-11-18",
    name: "(사)전국족발유통판매협회",
    purpose: "족발의 위생적인 유통과 판매시스템 및 품질향상을 통한 국민보건 및 축산물 위생 수준 제고",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2022-03-22",
    name: "(재)한국규제과학센터",
    purpose: "바이오헬스 산업 발전을 위한 정책의 개발 및 지원, 규제과학 인재양성대학 지원 및 교육 프로그램 개발·운영 등",
    law: "-",
    type: "재단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2023-01-25",
    name: "(사)정밀영양협회",
    purpose: "정밀영양산업의 기반조성과 연구개발 촉진 등을 통한 보건산업 및 국민건강 증진 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2023-08-10",
    name: "(사)HACCP경영교육원",
    purpose: "축산물 및 식품의 안전 확보 및 위생 향상을 도모함으로써 축산 및 식품산업의 발전과 국민 건강 및 보건 향상에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2024-06-12",
    name: "(사)한국의약화학회",
    purpose: "산학연 의약화학 관련 분야의 학술연구, 교육, 정책 협력의 장을 마련함으로써, 신약의 연구개발 지원 및 진흥을 도모하고 신약개발 역량 강화에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2024-07-05",
    name: "(사)대한임상약리학회",
    purpose: "국민이 의약품을 안전하게 사용하는 것에 기여하기 위해 임상약리학의 학문적 발전과 유관 산,학,연 분야의 발전에 기여",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2025-06-12",
    name: "(사)대한마약학회",
    purpose: "마약류 및 약물 남용에 대한 학술 연구 및 교류, 출판사업, 교육 프로그램 운영, 국내·외 네트워크 및 협력체계 구축, 정책지원 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
  ExcelRowData(
    permitDate: "2025-07-18",
    name: "(사)한국카페산업위생안전협회",
    purpose: "커피머신, 제빙기 등 카페장비에 대한 위생안전 및 청결유지에 대한 교육, 이력관리 인증프로그램 구축 등의 사업 등",
    law: "-",
    type: "사단",
    remit: "식품의약품안전처",
  ),
];
