import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> mpmRawData = [
  ExcelRowData(
    permitDate: "1982.02.01.",
    name: "공무원연금공단",
    purpose: "ㅇ공무원의 퇴직 또는 사망과 공무로 인한 부상",
    law: "-",
    type: "-",
    remit: "인사처",
  ),
  ExcelRowData(
    permitDate: "2002.08.09.",
    name: "한국인사행정학회",
    purpose: "정부를 비롯한 공공부문과 민간부문의 인력관리의 이론과 실제를 연구하고 그 발전에 기여",
    law: "-",
    type: "-",
    remit: "인사처",
  ),
  ExcelRowData(
    permitDate: "2006.06.08",
    name: "국가시험문제연구회",
    purpose: "ㅇ공무원채용시험의 내용과 방법등에 관한 이론과 실제를 연구하고 그 발전에 기여하고자 함",
    law: "-",
    type: "-",
    remit: "인사처",
  ),
  ExcelRowData(
    permitDate: "2007.05.31",
    name: "한국윤리연구원",
    purpose: "부패관련 연구‧조사‧교육훈련 및 컨설팅 등을 통해 중앙‧지방자치단체‧공직유관단체‧민간기업 경쟁력강화",
    law: "-",
    type: "-",
    remit: "인사처",
  ),
  ExcelRowData(
    permitDate: "2008.05.29",
    name: "한국리더십개발원",
    purpose: "ㅇ공무원 교육훈련 프로그램 개발",
    law: "-",
    type: "-",
    remit: "인사처",
  ),
  ExcelRowData(
    permitDate: "2008.08.26",
    name: "전국공무원연금수급권자총연합회",
    purpose: "ㅇ공무원연금 수급권자의 권익보호에 관한 사업",
    law: "-",
    type: "-",
    remit: "인사처",
  ),
  ExcelRowData(
    permitDate: "2013.05.23",
    name: "대한민국 공무원 공상유공자회",
    purpose: "ㅇ공무원의 경험을 소외계층에 환원하고 공상공무원의 사회 경제적 어려움 해소를 통한 복리향상 등",
    law: "-",
    type: "-",
    remit: "인사처",
  ),
  ExcelRowData(
    permitDate: "2007.08.02",
    name: "경찰소방안전 후원연합회",
    purpose: "ㅇ경찰·소방공무원 공상자들의 처우 개선 및 지원",
    law: "-",
    type: "-",
    remit: "인사처",
  ),
  ExcelRowData(
    permitDate: "2020.5.14",
    name: "(사)한국공공복지학회",
    purpose: "ㅇ공무원연금 및 공적연금 관련 연구발표 및 강연회 개최",
    law: "-",
    type: "-",
    remit: "인사처",
  ),
  ExcelRowData(
    permitDate: "2020.9.3.",
    name: "(사)한국역량진단평가학회",
    purpose: "ㅇ공사부문 조직들의 역량진단 및 평가에 관한 이론과 실제를 연구하고 그 발전에 기여",
    law: "-",
    type: "-",
    remit: "인사처",
  ),
  ExcelRowData(
    permitDate: "2015.5.22.",
    name: "한국공무원 문학협회",
    purpose: "ㅇ한국공무원문학협회 회지 및 회보 발간",
    law: "-",
    type: "-",
    remit: "인사처",
  ),
  ExcelRowData(
    permitDate: "2009.2.27.",
    name: "경찰소방안전 후원연합회",
    purpose: "ㅇ경찰·소방공무원 공상자들의 처우 개선 및 지원",
    law: "-",
    type: "-",
    remit: "인사처",
  ),
];
