import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> mipRawData = [
  ExcelRowData(
    permitDate: "1962",
    name: "대한변리사회",
    purpose: "산업재산권제도의 발전 등",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "1969",
    name: "아시아변리사회한국협회",
    purpose: "아시아 지역내의 변리사간 협력 등으로 지식재산권제도 발전 기여",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "1992",
    name: "한국학교발명협회",
    purpose: "발명교육 활성화 여건 조성 및 지도교원의 전문성과 자질향상",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "1994",
    name: "한국발명진흥회",
    purpose: "발명장려 사업 및 발명인재 양성",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "1995",
    name: "한국지식재산학회",
    purpose: "지식재산 제도에 관한 국내외 이론 및 실무 연구, 지식재산에 관한 지식보급 및 인적 네트워크 구축",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "1996",
    name: "한국국제지식재산보호협회",
    purpose: "국제회의개최, 입법활동보조, 위원회활동, 간행물발간",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "1999",
    name: "한국여성발명협회",
    purpose: "여성발명 저변확대, 여성발명가 양성 및 활용",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "1999",
    name: "한국특허학회",
    purpose: "특허학연구 학술지 발간, 발명가 자격특강 및 시험실기, 연구 발표회 및 강연 강습회 개최 등",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2000",
    name: "한국지식경영학회",
    purpose: "지식경영 및 지식기반경제에 관련된 학술연구 등",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2001",
    name: "특우회",
    purpose: "특허행정에 관한 건의 및 자문 등",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2001",
    name: "한국특허정보원",
    purpose: "특허정보 보급 및 DB구축, 특허행정정보시스템 운영",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2002",
    name: "한국청소년발명영재단",
    purpose: "과학발명영재 발굴 및 인재 육성",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2003",
    name: "국제변리사연맹한국협회",
    purpose: "지식재산권에 관한 국내 및 국제적 제도의 합리적인 정립 및 국내·외 단체 협력",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2004",
    name: "한국대학발명협회",
    purpose: "대학발명활동 활성화, 대학발명분야 발전 및 우수발명인력 발굴",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2005",
    name: "한국특허창작지원협회",
    purpose: "산업재산권 정보 소외계층을 대상으로 산업재산권에 대한 이해와 관심 및 중요성 홍보",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2005",
    name: "한국지식재산연구원",
    purpose: "국내·외 지식재산권 및 신지식재산권의 동향에 관한 조사 연구 등",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2008",
    name: "한러산업과학기술위원회",
    purpose: "발명의 사업화 등",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2008",
    name: "한국지식재산서비스협회",
    purpose: "지식재산서비스업 활성화 등",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2009",
    name: "한국특허법학회",
    purpose: "지식재산권 관련 법 및 관련 분야의 연구, 발표, 연구실적 보급",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2011",
    name: "한국상표디자인협회",
    purpose: "국내·외 IP관련 중요한 현안이슈, 동향 및 쟁점 등 관련 국내외포럼, 세미나 개최",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2011",
    name: "한국발명교육학회",
    purpose: "발명분야에 종사하는 회원들의 친목·상호 교류 촉진 및 발명교육 활동",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2011",
    name: "한국지식재산협회",
    purpose: "지식재산 분야에 대한 경영 노하우 공유 및 상호 협력 방안 논의",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2012",
    name: "한국라이센싱협회",
    purpose: "지재권 라이센싱 활동 관련 교류 및 교육",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2012",
    name: "한국지식재산교육연구학회",
    purpose: "지식재산 교육 및 교수방법의 연구 등",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2012",
    name: "한국특허전략개발원",
    purpose: "R&D 지식재산 연계전략 지원",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2014",
    name: "아이팩조정중재센터",
    purpose: "지식재산 관련 분쟁을 조정·중재",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2015",
    name: "한국지식재산보호원",
    purpose: "국내·외 지식재산권 보호를 위한 정책 제안 및 국내 위조상품 단속활동 지원 등",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2015",
    name: "IPLI(지식재산법제연구원)",
    purpose: "지식재산권에 관한 학술진흥 도모",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2017",
    name: "디자인지식재산권협회",
    purpose: "디자인을 기반으로 전개되는 비즈니스의 지식재산 활용방안 등 연구",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
  ExcelRowData(
    permitDate: "2018",
    name: "디랩사회적협동조합",
    purpose: "대전지역 내 문화산업진흥 지원, 특허 유무상 매입 등",
    law: "-",
    type: "-",
    remit: "지식재산처",
  ),
];
