import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> nhrckRawData = [
  ExcelRowData(
    permitDate: "-",
    name: "인권재단 사람",
    purpose: "인권에 관한 연구와 교육, 실천하는 개인 및 단체의 활동을 지원함으로써 인권향상, 국제인권교류 촉진에 기여",
    law: "-",
    type: "재단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "국제엠네스티 한국지부",
    purpose: "국제엠네스티 규약의 이념과 가치에 따라 세계인권선언을 비롯한 국제인권기준들이 모든 사람에게 보편적으로 보장되는 세계이룩",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "천주교인권위원회",
    purpose: "그리스도정신에 근거하여 인간이 지녀야 할 보편적 권리 옹호, 공동선 추구",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "울산인권운동연대",
    purpose: "인간의 존엄성과 사람으로서 누려야 할 보편적 권리를 보장받을 수 있는 사회 건설",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "정의·평화·인권을 위한 양심수후원회",
    purpose: "반전·평화운동을 하다가 구속된 양심수의 석방 및 후원사업, 출소 양심수 지원, 정의·평화·인권의 개선",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "여성문화이론연구소",
    purpose: "여성문화이론 및 여성문화 정책발전과 실천에 이바지, 여성인권 향상을 목표로 한 정책제안을 통해 여성의 행복한 삶 구현",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "장애인인권센터",
    purpose: "장애인의 인권향상을 통한 완전한 통합사회 구현",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "4.9통일 평화재단",
    purpose: "인혁당 사건으로 사형당한 8인을 비롯한 관련자들의 뜻을 계승·실천하고 우리사회의 민주주의와 민족통일, 자주, 평화, 인권운동에 기여",
    law: "-",
    type: "재단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "열린네트워크",
    purpose: "장애인 및 사회적 약자의 권리보장과 인권증진을 통해 '내가 주인되고 우리가 하나되는 세상'을 만드는 것을 목적으로 함",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "진실의 힘",
    purpose: "정치·경제·사회적으로 중대한 인권침해의 진상 규명, 피해자의 치유와 재활 지원, 법과 제도를 개선하여 인간의 존엄성을 지키는데 기여",
    law: "-",
    type: "재단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "참누리",
    purpose: "조사연구, 전문교육 및 사회운동, 인권증진 및 복지사업을 통해 국민의 인권개선 및 적정한 기초생활 보장 달성",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "인권의학연구소",
    purpose: "보건의료인의 인권의식함양, 폭력피해자 치유 프로그램 운영 및 지원, 사회적 약자 및 소수자의 건강권 보호와 증진에 기여",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "북한인권보호연합회",
    purpose: "북한인권상황을 대한민국 국민과 국제사회에 바로 알리고 북한이탈주민의 인권보호 및 정착지원 도모, 북한인권상황 개선",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "호루라기",
    purpose: "우리사회의 민주적 발전 및 올바른 인권의식 성장, 공동체 발전에 기여하는 개인 및 단체의 인권활동 지원",
    law: "-",
    type: "재단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "공익인권법재단 공감",
    purpose: "소수자 및 사회적 약자의 인권 보장을 통해 우리사회 인권의 경계 확장, 공익법 활동의 활성화",
    law: "-",
    type: "재단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "공익법센터 어필",
    purpose: "이주민들의 인권 보호·증진, 해외 한국기업의 인권 침해 감시·방지 등 국내외 사회적 약자들의 인권 옹호",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한반도 인권과 통일을 위한 변호사 모임",
    purpose: "자유민주주의와 시장경제질서에 토대를 둔 공동체의 시민적 가치 실현, 실질적 법치주의 확립 및 한반도 인권문제 개선, 평화적 통일 기반 마련",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "일본군성노예제 문제해결을 위한 정의기억연대",
    purpose: "일본군성노예제 문제의 정의로운 해결을 통해 피해자들의 명예 및 인권 회복에 기여, 무력갈등 및 전시성폭력 재발방지 및 전시성폭력 피해자의 인권회복에 기여",
    law: "-",
    type: "재단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "한베평화재단",
    purpose: "한국과 베트남, 세계의 인권증진 및 평화와 상생의 미래를 여는데 기여함",
    law: "-",
    type: "재단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "정신장애인권연대 카미",
    purpose: "정신장애인의 통합을 위한 각종 지원 사업, 정신장애에 대한 우리사회의 차별과 편견 해소, 정신장애인의 인권증진 도모",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "인권도시연구소",
    purpose: "민간 연구기관으로서 사람들의 일상적 삶의 공간인 도시에서의 인권증진을 통한 행복한 인권도시 공동체를 만드는데 기여",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "아셈노인인권정책센터",
    purpose: "노인인권에 대한 전문적이고 체계화된 정책연구, 교류협력을 통해 아셈회원국이 직면한 노인 문제 해소, 인권보호 및 증진에 기여",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "들꽃",
    purpose: "우리나라 근현대사에서 발생한 중대한 인권침해 사건의 진실 규명, 인권 존중사회와 사회정의 실현에 기여",
    law: "-",
    type: "재단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "정보인권연구소",
    purpose: "정보 사회에서 기본적 인권이 보장될 수 있도록 정보사회 분석·연구 및 올바른 정책 대안 제시",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "장애인차별금지추진연대",
    purpose: "장애인차별금지법이 그 역할을 다하기 위해 이루어지는 모든 활동에 적극 대응, 장애와 비장애가 구분되지 않고 평등권이 보장되는 사회건설",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
  ExcelRowData(
    permitDate: "-",
    name: "장애의 벽을 허무는 사람들",
    purpose: "장애인 및 사회적 약자의 권리확보와 차별 환경 개선을 통해 평등한 세상 구현",
    law: "-",
    type: "사단",
    remit: "국가인권위원회",
  ),
];
