import 'package:mois_smart_ledger/models/raw_data.dart';

const List<ExcelRowData> fscRawData = [
  ExcelRowData(
    permitDate: "2020.08.28",
    name: "한국재무관리학회",
    purpose: "-",
    law: "민법 제32조",
    type: "사단법인",
    remit: "금융위원회",
  ),
  ExcelRowData(
    permitDate: "2008.2.4",
    name: "은행법학회",
    purpose: "-",
    law: "민법 제32조",
    type: "사단법인",
    remit: "금융위원회",
  ),
  ExcelRowData(
    permitDate: "2009.3.12",
    name: "한국금융연구센터",
    purpose: "-",
    law: "민법 제32조",
    type: "사단법인",
    remit: "금융위원회",
  ),
  ExcelRowData(
    permitDate: "2021.9.14.",
    name: "금융부동산경제연구원",
    purpose: "-",
    law: "민법 제32조",
    type: "사단법인",
    remit: "금융위원회",
  ),
  ExcelRowData(
    permitDate: "2021.12.10",
    name: "서현학술재단",
    purpose: "-",
    law: "민법 제32조",
    type: "사단법인",
    remit: "금융위원회",
  ),
  ExcelRowData(
    permitDate: "2022.2.18.",
    name: "국민나눔교육",
    purpose: "-",
    law: "민법 제32조",
    type: "사단법인",
    remit: "금융위원회",
  ),
  ExcelRowData(
    permitDate: "2022.5.27.",
    name: "온라인투자연계금융협회",
    purpose: "-",
    law: "민법 제32조",
    type: "사단법인",
    remit: "금융위원회",
  ),
  ExcelRowData(
    permitDate: "2024.3.22.",
    name: "금융연구포럼",
    purpose: "-",
    law: "민법 제32조",
    type: "사단법인",
    remit: "금융위원회",
  ),
  ExcelRowData(
    permitDate: "2024.5.9",
    name: "케이아이씨피에이 회계정책연구원",
    purpose: "-",
    law: "민법 제32조",
    type: "사단법인",
    remit: "금융위원회",
  ),
  ExcelRowData(
    permitDate: "2024.9.26.",
    name: "디지털자산보호재단",
    purpose: "-",
    law: "민법 제32조",
    type: "재단법인",
    remit: "금융위원회",
  ),
  ExcelRowData(
    permitDate: "2024.11.14",
    name: "사단법인 한국지속가능성인증포럼",
    purpose: "-",
    law: "민법 제32조",
    type: "사단법인",
    remit: "금융위원회",
  ),
  ExcelRowData(
    permitDate: "2024.11.26.",
    name: "사단법인 한국투자자포럼",
    purpose: "-",
    law: "민법 제32조",
    type: "사단법인",
    remit: "금융위원회",
  ),
  ExcelRowData(
    permitDate: "54.12.11",
    name: "한국공인회계사회",
    purpose: "-",
    law: "공인회계사법 제41조",
    type: "공인회계사법에 따라 설립된 특수법인",
    remit: "금융위원회",
  ),
];
